{
  "hash": "d163b4f1499520f541b7639808f3f1c1",
  "result": {
    "engine": "knitr",
    "markdown": "# Matching Estimators\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(MatchIt)\nlibrary(cobalt)\nlibrary(WeightIt)\nlibrary(marginaleffects)\n```\n:::\n\n\nMatching is a way to make treated and control observations more comparable.\nFor each treated observation, we look for controls with similar covariates.\nThen we compare outcomes in this matched sample.\n\nThis does not solve endogeneity. Matching only helps with selection on\nobservables. If the treatment is selected on unobserved variables, matching\nwill not fix the problem. The value of matching is that it makes the overlap\nproblem visible. A regression can extrapolate quietly; matching often shows\nthat there are no good controls for part of the treated sample.\n\nIn R, the main workflow is `MatchIt` for matching and `cobalt` for balance\nchecking.\n\n> **Related reading**: A longer treatment is in\n> [Matching and Weighting Part 1](https://xiangao.github.io/blog_book/matching-part1.html)\n> of *Topics on Econometrics and Causal Inference*, which credits Noah\n> Greifer and coauthors (the `MatchIt`/`WeightIt` package authors).\n\n## Assumptions\n\nMatching needs the same assumptions as other selection-on-observables\nmethods:\n\n1. **SUTVA** — no interference, no hidden treatment versions.\n2. **Ignorability** (unconfoundedness) — conditional on $X$, the\n   treatment $D$ is independent of the potential outcomes $(Y(0), Y(1))$.\n3. **Overlap** (positivity) — every value of $X$ has positive probability\n   of being both treated and untreated.\n\nEven if ignorability is true, the covariate distribution can be very\ndifferent in the treated and control groups. Matching tries to repair that\nbefore estimating the effect. If there is no overlap, it should not pretend\nthere is overlap.\n\n## The Lalonde example\n\nI use the Lalonde job-training data because it is the standard example for\nmatching. The treatment is job training. The outcome is 1978 earnings. The\ndata set in `MatchIt` is the observational version, so the treated and\ncontrol groups are not balanced at the start.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"lalonde\", package = \"MatchIt\")\nglimpse(lalonde)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 614\nColumns: 9\n$ treat    <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~\n$ age      <int> 37, 22, 30, 27, 33, 22, 23, 32, 22, 33, 19, 21, 18, 27, 17, 1~\n$ educ     <int> 11, 9, 12, 11, 8, 9, 12, 11, 16, 12, 9, 13, 8, 10, 7, 10, 13,~\n$ race     <fct> black, hispan, black, black, black, black, black, black, blac~\n$ married  <int> 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0~\n$ nodegree <int> 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1~\n$ re74     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~\n$ re75     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~\n$ re78     <dbl> 9930.0460, 3595.8940, 24909.4500, 7506.1460, 289.7899, 4056.4~\n```\n\n\n:::\n:::\n\n\nThere are 614 observations, 185 treated and 429 control. The treatment is\n`treat`; the outcome is `re78`, 1978 earnings in dollars; the covariates are\n`age`, `educ` (years of schooling), `race` (black, hispanic, white), `married`,\n`nodegree` (no high-school degree), and `re74` and `re75`, earnings in 1974 and\n1975. The earnings variables matter most here, because they pile up at zero and\ndiffer sharply between the groups.\n\nBefore matching anything we check balance. `bal.tab` reports the standardized\nmean difference for each covariate and flags any above 0.1:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Construct a pre-match MatchIt object for balance reporting\nm.pre <- matchit(treat ~ age + educ + race + married + nodegree + re74 + re75,\n                 data = lalonde, method = NULL,\n                 distance = \"glm\")\nbal.tab(m.pre, thresholds = c(m = 0.1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBalance Measures\n                Type Diff.Un     M.Threshold.Un\ndistance    Distance  1.7941                   \nage          Contin. -0.3094 Not Balanced, >0.1\neduc         Contin.  0.0550     Balanced, <0.1\nrace_black    Binary  0.6404 Not Balanced, >0.1\nrace_hispan   Binary -0.0827     Balanced, <0.1\nrace_white    Binary -0.5577 Not Balanced, >0.1\nmarried       Binary -0.3236 Not Balanced, >0.1\nnodegree      Binary  0.1114 Not Balanced, >0.1\nre74         Contin. -0.7211 Not Balanced, >0.1\nre75         Contin. -0.2903 Not Balanced, >0.1\n\nBalance tally for mean differences\n                   count\nBalanced, <0.1         2\nNot Balanced, >0.1     7\n\nVariable with the greatest mean difference\n Variable Diff.Un     M.Threshold.Un\n     re74 -0.7211 Not Balanced, >0.1\n\nSample sizes\n    Control Treated\nAll     429     185\n```\n\n\n:::\n:::\n\n\nSeven of the nine contrasts exceed 0.1. Earnings in 1974 differ by $-0.72$\nstandard deviations, the black indicator by 0.64, the white indicator by\n$-0.56$, marital status by $-0.32$, age by $-0.31$, earnings in 1975 by\n$-0.29$. Only `educ` (0.055) and the hispanic indicator ($-0.083$) pass. The\npropensity score itself differs by 1.79 standard deviations. This sample is\nnowhere near balanced.\n\n## Distance measures\n\nMatching needs a distance metric. The usual choices are:\n\n1. **Propensity score**: estimate $\\hat e(x)=P(D=1 \\mid X=x)$ and match on\n   the fitted probability. This turns many covariates into one score.\n2. **Mahalanobis distance**: match on the raw covariates using the squared\n   distance $(x_i-x_j)'\\Sigma^{-1}(x_i-x_j)$ (rankings are unchanged by the\n   square root). This works better in low dimension.\n3. **Hybrid**: impose a propensity-score caliper, then use Mahalanobis\n   distance inside the caliper.\n\n## Matching methods\n\n### Nearest-neighbour matching on a propensity score\n\nWe fit the propensity score by logistic regression, take its linear index, and\nmatch each treated unit to the single closest control, without replacement.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm.nn <- matchit(treat ~ age + educ + race + married + nodegree + re74 + re75,\n                data = lalonde,\n                method = \"nearest\",\n                distance = \"glm\",\n                link = \"linear.logit\",\n                ratio = 1)\n\nm.nn\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nA `matchit` object\n - method: 1:1 nearest neighbor matching without replacement\n - distance: Propensity score\n             - estimated with logistic regression and linearized\n - number of obs.: 614 (original), 370 (matched)\n - target estimand: ATT\n - covariates: age, educ, race, married, nodegree, re74, re75\n```\n\n\n:::\n:::\n\n\nAll 185 treated units are matched, so 370 of the 614 observations are used and\n244 controls are discarded. The target estimand is the ATT.\n\nNow check balance again:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbal.tab(m.nn, thresholds = c(m = 0.1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBalance Measures\n                Type Diff.Adj        M.Threshold\ndistance    Distance   0.9192                   \nage          Contin.   0.0718     Balanced, <0.1\neduc         Contin.  -0.1290 Not Balanced, >0.1\nrace_black    Binary   0.3730 Not Balanced, >0.1\nrace_hispan   Binary  -0.1568 Not Balanced, >0.1\nrace_white    Binary  -0.2162 Not Balanced, >0.1\nmarried       Binary  -0.0216     Balanced, <0.1\nnodegree      Binary   0.0703     Balanced, <0.1\nre74         Contin.  -0.0505     Balanced, <0.1\nre75         Contin.  -0.0257     Balanced, <0.1\n\nBalance tally for mean differences\n                   count\nBalanced, <0.1         5\nNot Balanced, >0.1     4\n\nVariable with the greatest mean difference\n   Variable Diff.Adj        M.Threshold\n race_black    0.373 Not Balanced, >0.1\n\nSample sizes\n          Control Treated\nAll           429     185\nMatched       185     185\nUnmatched     244       0\n```\n\n\n:::\n:::\n\n\nFive of nine now pass, up from two. The earnings histories are repaired: `re74`\ngoes from $-0.72$ to $-0.05$ and `re75` from $-0.29$ to $-0.03$. Race is not:\nthe black indicator is still 0.373 and the white indicator $-0.216$. And `educ`\nhas got worse, from 0.055 to $-0.129$. This is what matching on a scalar score\ndoes: it balances the score, not the covariates. Two units with the same score\ncan differ on individual covariates in offsetting ways, and nothing in the\nprocedure prevents that.\n\n### Full matching\n\nFull matching forms subclasses with treated and control observations inside\neach subclass. It can put one treated unit with several controls, or one\ncontrol with several treated units. It uses all observations and then assigns\nweights.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm.full <- matchit(treat ~ age + educ + race + married + nodegree + re74 + re75,\n                  data = lalonde,\n                  method = \"full\",\n                  distance = \"glm\",\n                  link = \"probit\")\n\nbal.tab(m.full, thresholds = c(m = 0.1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBalance Measures\n                Type Diff.Adj    M.Threshold\ndistance    Distance   0.0045 Balanced, <0.1\nage          Contin.   0.0393 Balanced, <0.1\neduc         Contin.  -0.0956 Balanced, <0.1\nrace_black    Binary   0.0043 Balanced, <0.1\nrace_hispan   Binary   0.0103 Balanced, <0.1\nrace_white    Binary  -0.0146 Balanced, <0.1\nmarried       Binary   0.0259 Balanced, <0.1\nnodegree      Binary   0.0504 Balanced, <0.1\nre74         Contin.  -0.0009 Balanced, <0.1\nre75         Contin.  -0.0091 Balanced, <0.1\n\nBalance tally for mean differences\n                   count\nBalanced, <0.1        10\nNot Balanced, >0.1     0\n\nVariable with the greatest mean difference\n Variable Diff.Adj    M.Threshold\n     educ  -0.0956 Balanced, <0.1\n\nSample sizes\n                     Control Treated\nAll                   429.       185\nMatched (ESS)          50.76     185\nMatched (Unweighted)  429.       185\n```\n\n\n:::\n:::\n\n\nAll ten contrasts now pass, the largest being `educ` at $-0.096$, and no\nobservation is discarded. The cost is in the weights: the control effective\nsample size falls from 429 to 50.8, because full matching concentrates weight\non the controls that resemble treated units.\n\nThe effective sample size is the number of equally weighted observations that\nwould carry the same precision. An unweighted mean of $m$ observations has\nvariance $\\sigma^2/m$; a weighted mean with weights summing to one has variance\n$\\sigma^2 \\sum_i w_i^2$. Setting the two equal gives $m = 1/\\sum_i w_i^2$. So\n50.8 means these 429 controls carry about as much information as 51 equally\nweighted ones. Balance improved and precision did not.\n\n### Mahalanobis matching\n\nWhen the number of covariates is small, it is reasonable to match directly\non the covariates with Mahalanobis distance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm.maha <- matchit(treat ~ age + educ + race + married + nodegree + re74 + re75,\n                  data = lalonde,\n                  distance = \"mahalanobis\")\nbal.tab(m.maha, thresholds = c(m = 0.1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBalance Measures\n               Type Diff.Adj        M.Threshold\nage         Contin.   0.1269 Not Balanced, >0.1\neduc        Contin.  -0.0430     Balanced, <0.1\nrace_black   Binary   0.3784 Not Balanced, >0.1\nrace_hispan  Binary   0.0000     Balanced, <0.1\nrace_white   Binary  -0.3784 Not Balanced, >0.1\nmarried      Binary  -0.0595     Balanced, <0.1\nnodegree     Binary   0.0486     Balanced, <0.1\nre74        Contin.  -0.2476 Not Balanced, >0.1\nre75        Contin.  -0.1322 Not Balanced, >0.1\n\nBalance tally for mean differences\n                   count\nBalanced, <0.1         4\nNot Balanced, >0.1     5\n\nVariable with the greatest mean difference\n   Variable Diff.Adj        M.Threshold\n race_black   0.3784 Not Balanced, >0.1\n\nSample sizes\n          Control Treated\nAll           429     185\nMatched       185     185\nUnmatched     244       0\n```\n\n\n:::\n:::\n\n\nMahalanobis matching balances only four of nine. The black and white indicators\nsit at $\\pm 0.378$, `re74` at $-0.248$, `re75` at $-0.132$, and `age` at 0.127.\nIt does worse than the propensity score did on earnings. With a three-level\nrace factor and two earnings variables that pile up at zero, the covariance\nmatrix is a poor description of the covariate space, and the metric it defines\nis a poor guide to who resembles whom.\n\n### Coarsened Exact Matching (CEM)\n\nCEM coarsens covariates into bins and then exact-matches on the binned\nvalues. This is very transparent: if a treated observation has no comparable\ncontrol in the binned covariate space, it is dropped.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm.cem <- matchit(treat ~ age + educ + race + married + nodegree + re74 + re75,\n                 data = lalonde,\n                 method = \"cem\")\nbal.tab(m.cem, thresholds = c(m = 0.1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBalance Measures\n               Type Diff.Adj    M.Threshold\nage         Contin.   0.0493 Balanced, <0.1\neduc        Contin.   0.0446 Balanced, <0.1\nrace_black   Binary   0.0000 Balanced, <0.1\nrace_hispan  Binary   0.0000 Balanced, <0.1\nrace_white   Binary   0.0000 Balanced, <0.1\nmarried      Binary   0.0000 Balanced, <0.1\nnodegree     Binary   0.0000 Balanced, <0.1\nre74        Contin.  -0.0427 Balanced, <0.1\nre75        Contin.  -0.0492 Balanced, <0.1\n\nBalance tally for mean differences\n                   count\nBalanced, <0.1         9\nNot Balanced, >0.1     0\n\nVariable with the greatest mean difference\n Variable Diff.Adj    M.Threshold\n      age   0.0493 Balanced, <0.1\n\nSample sizes\n                     Control Treated\nAll                   429.       185\nMatched (ESS)          41.29      65\nMatched (Unweighted)   75.        65\nUnmatched             354.       120\n```\n\n\n:::\n:::\n\n\nAll nine contrasts pass, and the largest is `age` at 0.049. Read the sample\nsizes before celebrating: only 65 of the 185 treated units are matched, and 120\nare dropped, along with 354 of the 429 controls. The control effective sample\nsize is 41.3.\n\nCEM can drop many observations. That is not necessarily a problem. It is\noften telling us that the original sample does not support the target\ncomparison. But it does change the question. The estimand is now the average\neffect for the 65 treated units that had a comparable control, not the ATT for\nall 185, and those two need not be the same number.\n\n## Estimation after matching\n\nAfter matching, we estimate the effect on the matched data. The matching\nweights come from `MatchIt`. With subclass matching, standard errors should\nbe clustered by subclass: units within the same matched subclass are not\nindependent draws -- they were selected together specifically because they\nresemble each other on the matching covariates, and (for many-to-one or\nfull matching) a single unit's outcome can appear, re-weighted, in the\n\"observation\" for more than one comparison. Treating them as independent\n(ordinary or heteroskedasticity-robust SEs) understates the true sampling\nvariability; clustering by subclass accounts for that within-subclass\ncorrelation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm.data <- match_data(m.full)\n\nfit <- lm(re78 ~ treat * (age + educ + race + married + nodegree + re74 + re75),\n          data    = m.data,\n          weights = weights)\n\n# Use marginaleffects for the average treatment effect with cluster-by-subclass SEs\navg_comparisons(fit,\n                variables = \"treat\",\n                vcov = ~subclass,\n                newdata = subset(m.data, treat == 1))   # ATT\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate Std. Error    z Pr(>|z|)   S 2.5 % 97.5 %\n     1977        704 2.81  0.00501 7.6   596   3357\n\nTerm: treat\nType: response\nComparison: 1 - 0\n```\n\n\n:::\n:::\n\n\nThe full-matching ATT is \\$1,977 with a subclass-clustered standard error of\n\\$704, a 95% interval of $[596, 3357]$, and $p = 0.005$. Training raised 1978\nearnings for the trained.\n\nThe point is not that matching mechanically produces the \"right\" answer.\nThe point is that after improving balance, the estimate is much less driven\nby obvious covariate differences.\n\n## Balance plots\n\n`cobalt::love.plot` is the easiest way to see the balance change. It plots\nstandardized mean differences before and after matching.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlove.plot(m.full,\n          stats = \"mean.diffs\",\n          thresholds = c(m = 0.1),\n          abs = TRUE,\n          var.order = \"unadjusted\",\n          title = \"Balance plot — Full matching\")\n```\n\n::: {.cell-output-display}\n![Balance before and after full matching, as absolute standardized mean differences.](matching_files/figure-pdf/love-plot-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nEach variable appears twice, unadjusted and adjusted, with the variables\nordered by their unadjusted difference and differences plotted in absolute\nvalue. Every point moves toward zero except `educ`, which starts at 0.055 and\nends at 0.096 --- it was already balanced, and full matching traded a little of\nit for the rest. `re74`, the worst offender before matching at $-0.72$, moves\nfurthest, ending at $-0.0009$.\n\nA useful rule is that standardized mean differences should be below 0.1,\nor below 0.05 if we want to be stricter.\n\n## Matching with replacement vs without\n\nBy default a control observation can be used only once. With replacement,\nthe same good control can be used several times. This often improves balance\nwhen overlap is weak, but the effective sample size becomes smaller.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm.repl <- matchit(treat ~ age + educ + race + married + nodegree + re74 + re75,\n                  data = lalonde,\n                  method = \"nearest\",\n                  distance = \"glm\",\n                  replace = TRUE)\nbal.tab(m.repl, thresholds = c(m = 0.1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBalance Measures\n                Type Diff.Adj        M.Threshold\ndistance    Distance   0.0044     Balanced, <0.1\nage          Contin.   0.2395 Not Balanced, >0.1\neduc         Contin.  -0.0161     Balanced, <0.1\nrace_black    Binary   0.0054     Balanced, <0.1\nrace_hispan   Binary  -0.0054     Balanced, <0.1\nrace_white    Binary   0.0000     Balanced, <0.1\nmarried       Binary   0.0595     Balanced, <0.1\nnodegree      Binary   0.0054     Balanced, <0.1\nre74         Contin.  -0.0493     Balanced, <0.1\nre75         Contin.   0.0087     Balanced, <0.1\n\nBalance tally for mean differences\n                   count\nBalanced, <0.1         9\nNot Balanced, >0.1     1\n\nVariable with the greatest mean difference\n Variable Diff.Adj        M.Threshold\n      age   0.2395 Not Balanced, >0.1\n\nSample sizes\n                     Control Treated\nAll                   429.       185\nMatched (ESS)          46.31     185\nMatched (Unweighted)   82.       185\nUnmatched             347.         0\n```\n\n\n:::\n:::\n\n\nWith replacement, nine of ten contrasts pass, against five of nine without.\n`age` is the exception, at 0.240. Only 82 distinct controls are used, and their\neffective sample size is 46.3. Compared with the 1:1 match without replacement,\nwhich used 185 distinct controls, the same good controls are being reused.\n\nIf matching without replacement cannot balance the sample, matching with\nreplacement is a reasonable next step.\n\n## ATE, ATT, ATC — choose carefully\n\n`MatchIt` usually targets the ATT. That means we are asking what treatment\ndid for the treated units. For ATE, use `estimand = \"ATE\"` and a method\nthat keeps the whole sample, such as full matching or weighting. For ATC,\nuse `estimand = \"ATC\"`. These are not just software options; they are\ndifferent causal questions.\n\n## When matching fails\n\nMatching fails in predictable ways:\n\n- High-dimensional matching is hard. Propensity scores reduce dimension,\n  but they do not create overlap.\n- If some values of $X$ have no treated or no control units, no matching\n  method can recover the missing comparison.\n- Propensity-score matching depends on the propensity-score model. If that\n  model is bad, the matching can be bad too.\n- Matching does not address hidden confounding. Rosenbaum bounds, discussed\n  in the [Sensitivity Analysis chapter](sensitivity-analysis.qmd), ask how\n  strong hidden bias would have to be to change the conclusion.\n\n## Matching vs weighting\n\nMatching and weighting do similar jobs. Matching chooses comparable\nobservations. Weighting keeps observations but changes their contribution so\nthe treated and control covariate distributions become closer.\n\nWhen overlap is good, both approaches often give similar answers. When\noverlap is bad, both approaches become fragile. The honest choices then are to\nchange the target population, to report the lack of overlap plainly, to move to\noverlap weights or another explicitly chosen target, or to trim -- accepting\nthat trimming changes the estimand rather than rescuing the original one.\n\nDoubly-robust estimators do not belong on that list. [AIPW](estimation.qmd) and\n[TMLE](nonparametric.qmd) protect against misspecification of the nuisance\nmodels, and they still require the treatment probabilities to be bounded away\nfrom zero, and away from one for an ATE. Where support is genuinely missing the\ninverse weights are extreme, and a doubly-robust estimator is then less stable\nthan a simple one, not more. Robustness to a wrong model is not robustness to a\nmissing comparison.\n\n## Weighting Alternatives\n\n`WeightIt` implements several weighting methods. The companion\n[blog chapter on weighting](https://xiangao.github.io/blog_book/weighting-part2.html)\nhas more detail. Here I use the same Lalonde data so the comparison is easy.\n\n### Inverse probability of treatment weighting (IPW)\n\nThe baseline method is IPW. Estimate the propensity score, then weight by\nthe inverse probability of receiving the observed treatment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nw_ipw <- weightit(treat ~ age + educ + race + married + nodegree + re74 + re75,\n                  data = lalonde, estimand = \"ATT\", method = \"glm\")\nbal.tab(w_ipw, stats = c(\"m\"), thresholds = c(m = 0.05))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBalance Measures\n                Type Diff.Adj         M.Threshold\nprop.score  Distance  -0.0205     Balanced, <0.05\nage          Contin.   0.1188 Not Balanced, >0.05\neduc         Contin.  -0.0284     Balanced, <0.05\nrace_black    Binary  -0.0022     Balanced, <0.05\nrace_hispan   Binary   0.0002     Balanced, <0.05\nrace_white    Binary   0.0021     Balanced, <0.05\nmarried       Binary   0.0186     Balanced, <0.05\nnodegree      Binary   0.0184     Balanced, <0.05\nre74         Contin.  -0.0021     Balanced, <0.05\nre75         Contin.   0.0110     Balanced, <0.05\n\nBalance tally for mean differences\n                    count\nBalanced, <0.05         9\nNot Balanced, >0.05     1\n\nVariable with the greatest mean difference\n Variable Diff.Adj         M.Threshold\n      age   0.1188 Not Balanced, >0.05\n\nEffective sample sizes\n           Control Treated\nUnadjusted  429.       185\nAdjusted     99.82     185\n```\n\n\n:::\n:::\n\n\nNote the stricter 0.05 threshold from here on. IPW balances nine of ten;\n`age` fails at 0.119. The control effective sample size is 99.8 out of 429,\nbetter than any of the matching methods above.\n\n### Covariate balancing propensity score (CBPS)\n\nCBPS estimates the propensity score while also trying to balance covariate\nmeans. So the propensity-score model is not judged only by likelihood; it is\nalso judged by balance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nw_cbps <- weightit(treat ~ age + educ + race + married + nodegree + re74 + re75,\n                   data = lalonde, estimand = \"ATT\", method = \"cbps\")\nbal.tab(w_cbps, stats = c(\"m\"), thresholds = c(m = 0.05))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBalance Measures\n                Type Diff.Adj     M.Threshold\nprop.score  Distance   -0.018 Balanced, <0.05\nage          Contin.    0.000 Balanced, <0.05\neduc         Contin.   -0.000 Balanced, <0.05\nrace_black    Binary   -0.000 Balanced, <0.05\nrace_hispan   Binary   -0.000 Balanced, <0.05\nrace_white    Binary    0.000 Balanced, <0.05\nmarried       Binary   -0.000 Balanced, <0.05\nnodegree      Binary   -0.000 Balanced, <0.05\nre74         Contin.   -0.000 Balanced, <0.05\nre75         Contin.   -0.000 Balanced, <0.05\n\nBalance tally for mean differences\n                    count\nBalanced, <0.05        10\nNot Balanced, >0.05     0\n\nVariable with the greatest mean difference\n Variable Diff.Adj     M.Threshold\n     re74       -0 Balanced, <0.05\n\nEffective sample sizes\n           Control Treated\nUnadjusted  429.       185\nAdjusted     98.46     185\n```\n\n\n:::\n:::\n\n\nEvery covariate mean difference is zero to three decimals, and the control\neffective sample size is 98.5.\n\n### Entropy balancing\n\nEntropy balancing chooses weights so that the weighted control group matches\nthe treated group on covariate means. It is useful because the balance\nconstraint is explicit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nw_ebal <- weightit(treat ~ age + educ + race + married + nodegree + re74 + re75,\n                   data = lalonde, estimand = \"ATT\", method = \"ebal\")\nbal.tab(w_ebal, stats = c(\"m\"), thresholds = c(m = 0.05))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBalance Measures\n               Type Diff.Adj     M.Threshold\nage         Contin.       -0 Balanced, <0.05\neduc        Contin.       -0 Balanced, <0.05\nrace_black   Binary        0 Balanced, <0.05\nrace_hispan  Binary        0 Balanced, <0.05\nrace_white   Binary       -0 Balanced, <0.05\nmarried      Binary       -0 Balanced, <0.05\nnodegree     Binary        0 Balanced, <0.05\nre74        Contin.       -0 Balanced, <0.05\nre75        Contin.       -0 Balanced, <0.05\n\nBalance tally for mean differences\n                    count\nBalanced, <0.05         9\nNot Balanced, >0.05     0\n\nVariable with the greatest mean difference\n Variable Diff.Adj     M.Threshold\n     re74       -0 Balanced, <0.05\n\nEffective sample sizes\n           Control Treated\nUnadjusted  429.       185\nAdjusted     98.46     185\n```\n\n\n:::\n:::\n\n\nThe standardized mean differences are essentially zero because entropy\nbalancing imposes mean balance directly. The effective sample size is 98.5.\n\nThat is the same table CBPS produced, and it is not a coincidence: the two sets\nof control weights are numerically identical here, agreeing to twelve decimal\nplaces. Just-identified CBPS for the ATT solves the exact mean-balance moment\nconditions with a logistic link, which makes the control weights proportional\nto $\\exp(x'\\lambda)$. Entropy balancing minimises the Kullback-Leibler\ndivergence from uniform weights subject to the same exact mean-balance\nconstraints, and its solution has the same $\\exp(x'\\lambda)$ form. Same\nconstraints, same functional form, same weights. The two methods are motivated\ndifferently and arrive at one answer.\n\n### Energy balancing\n\nEnergy balancing targets the whole covariate distribution, not just means.\nIt is more ambitious than entropy balancing, and usually more computationally\nexpensive.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nw_energy <- weightit(treat ~ age + educ + race + married + nodegree + re74 + re75,\n                     data = lalonde, estimand = \"ATT\", method = \"energy\")\nbal.tab(w_energy, stats = c(\"m\"), thresholds = c(m = 0.05))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBalance Measures\n               Type Diff.Adj     M.Threshold\nage         Contin.  -0.0016 Balanced, <0.05\neduc        Contin.   0.0106 Balanced, <0.05\nrace_black   Binary   0.0060 Balanced, <0.05\nrace_hispan  Binary  -0.0008 Balanced, <0.05\nrace_white   Binary  -0.0053 Balanced, <0.05\nmarried      Binary  -0.0011 Balanced, <0.05\nnodegree     Binary   0.0050 Balanced, <0.05\nre74        Contin.  -0.0021 Balanced, <0.05\nre75        Contin.   0.0226 Balanced, <0.05\n\nBalance tally for mean differences\n                    count\nBalanced, <0.05         9\nNot Balanced, >0.05     0\n\nVariable with the greatest mean difference\n Variable Diff.Adj     M.Threshold\n     re75   0.0226 Balanced, <0.05\n\nEffective sample sizes\n           Control Treated\nUnadjusted  429.       185\nAdjusted     41.82     185\n```\n\n\n:::\n:::\n\n\nAll nine contrasts pass, the largest being `re75` at 0.023 --- close to zero\nbut not exactly zero, because energy balancing does not impose mean balance as\na constraint. The control effective sample size is 41.8, less than half of\nentropy balancing's 98.5. That is the price of targeting the whole covariate\ndistribution rather than its means.\n\n### Estimation with weighted-aware regression\n\nAfter computing weights, use `lm_weightit()` instead of plain `lm` if we\nwant standard errors that account for the estimated weights.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_ebal <- lm_weightit(\n  re78 ~ treat * (age + educ + race + married + nodegree + re74 + re75),\n  data     = lalonde,\n  weightit = w_ebal\n)\n\navg_comparisons(fit_ebal, variables = \"treat\",\n                newdata = subset(lalonde, treat == 1))   # ATT\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate Std. Error    z Pr(>|z|)   S 2.5 % 97.5 %\n     1273        770 1.65   0.0983 3.3  -236   2783\n\nTerm: treat\nType: probs\nComparison: 1 - 0\n```\n\n\n:::\n:::\n\n\nThe entropy-balanced ATT is \\$1,273 with a sandwich standard error of \\$770,\na 95% interval of $[-236, 2783]$, and $p = 0.098$. The interval includes zero.\n\n### When to use each weighting method\n\n| Method | Strengths | Weaknesses |\n|---|---|---|\n| **IPW** (glm) | Familiar; well-studied | Sensitive to PS misspecification; extreme weights |\n| **CBPS** | Balance-constrained PS; robust to model misspecification | Slower; can fail with many covariates |\n| **Entropy balancing** | Exact mean balance; doubly robust for ATT | Balances means only, not distributions |\n| **Energy balancing** | Balances entire distribution | Computationally heavier; less mature theory |\n\nFor applied work, entropy balancing is often a good default because it is\nsimple and the balance diagnostics are easy to explain. Energy balancing is\nuseful when matching the whole covariate distribution is important.\n\n### Comparing matching to weighting\n\nThe matching and weighting examples here target the same ATT, so put the two\nestimates next to each other rather than reporting whichever came last:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncmp <- rbind(\n  transform(as.data.frame(\n    avg_comparisons(fit, variables = \"treat\", vcov = ~subclass,\n                    newdata = subset(m.data, treat == 1))),\n    method = \"Full matching (subclass-clustered SE)\"),\n  transform(as.data.frame(\n    avg_comparisons(fit_ebal, variables = \"treat\",\n                    newdata = subset(lalonde, treat == 1))),\n    method = \"Entropy balancing (sandwich SE)\")\n)\n\ncmp[, c(\"method\", \"estimate\", \"std.error\", \"conf.low\", \"conf.high\", \"p.value\")] |>\n  knitr::kable(digits = c(0, 0, 0, 0, 0, 3),\n               caption = \"Two routes to the same ATT on the Lalonde data\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Two routes to the same ATT on the Lalonde data\n\n|method                                | estimate| std.error| conf.low| conf.high| p.value|\n|:-------------------------------------|--------:|---------:|--------:|---------:|-------:|\n|Full matching (subclass-clustered SE) |     1977|       704|      596|      3357|   0.005|\n|Entropy balancing (sandwich SE)       |     1273|       770|     -236|      2783|   0.098|\n\n\n:::\n:::\n\n\nThe gap is instructive. The two point estimates differ by roughly one standard\nerror, and one interval excludes zero while the other does not --- a reader who\nsees only one of these tables would draw a different conclusion about whether\nthe programme worked. Note also that the ranking on balance does not settle it:\nentropy balancing imposes *exact* mean balance (every standardized difference\nabove is at most 0.023), whereas full matching leaves `educ` at $-0.096$, yet it\nis entropy balancing that gives the smaller estimate and the wider interval.\nBetter mean balance is not the same thing as a more precise or more credible\nanswer.\n\nThis is model dependence, not a bug in either method. In an applied paper I would\nreport balance for each method, not just the final coefficient, and I would report\nboth estimates. If several reasonable methods give similar balance and similar\nestimates, the result is more credible. If they differ sharply, as here, the\nproblem is usually weak overlap or model dependence, and the honest summary says\nso instead of picking the number that crosses the significance line.\n\nFor more details on `MatchIt` and the Stata `teffects` commands, see the\n[matching blog chapter](https://xiangao.github.io/blog_book/matching-part1.html)\nand [treatment-effects in Stata](https://xiangao.github.io/blog_book/treatment-matching.html).\n\n## Matching, weighting, and direct estimation\n\nThe estimation chapter estimated a treatment effect by regression adjustment,\nIPW, AIPW and IPWRA. This chapter estimated one by matching and by four\nweighting methods. Those are not two families of estimators. They are one\nestimand and several ways of building it, and it is worth saying how they line\nup.\n\nThe ATT is\n\n$$\n\\tau_{ATT} = E[Y \\mid W = 1] - E_{X \\mid W = 1}\\bigl[\\, E[Y \\mid W = 0, X] \\,\\bigr].\n$$ {#eq-matching-att-routes}\n\nThe first term is observed. It is the mean outcome among the treated. The\nsecond term is not observed. It is the mean outcome the treated would have had\nuntreated, averaged over the covariate distribution of the treated. Every\nmethod in both chapters is a way of forming that second term, and every one of\nthem ends up as a weighted average of control outcomes,\n$\\sum_{i: W_i = 0} w_i Y_i$. What differs is where the weights come from.\n\n| Route | What is modelled | Weight on control $i$ |\n|---|---|---|\n| Regression adjustment | the outcome, $\\mu_0(x) = E[Y \\mid W=0, X=x]$ | implicit in the fitted values used to predict at treated $x$ |\n| IPW | the propensity score $\\pi(x)$ | the odds $\\pi(x_i)/(1-\\pi(x_i))$ |\n| Matching | neither; a distance rule | 0 if unmatched, else 1, the number of times reused, or the subclass ratio |\n| Entropy, CBPS, energy balancing | the weights themselves | whatever satisfies the balance constraints |\n| AIPW | both | the odds, applied to the residual $Y - \\hat\\mu_0(X)$ |\n\nWeighting is IPW. That is the second row, and `weightit` with\n`estimand = \"ATT\"` and `method = \"glm\"` returns exactly those odds. CBPS,\nentropy balancing and energy balancing do not change the estimator. They\nchange how the weights are found. IPW fits $\\pi$ by maximum likelihood and\nthen transforms it into weights; the balancing methods skip the likelihood and\nsolve for the weights directly. For entropy balancing the link is exact rather\nthan an analogy: the control weights are proportional to $\\exp(x'\\lambda)$, as\nthe CBPS comparison above showed, and that is the odds of a logistic\npropensity score. Entropy balancing is IPW for a logit model whose\ncoefficients are set by exact mean balance instead of by likelihood.\n\nMatching is weighting too, with the weights restricted to zero and small\nintegers and chosen by a distance rule rather than by a model. That is what\nlets `match_data` hand a weights column to `lm`. The restriction is where the\ntrade-off lives. Matching sets some weights to zero, so it discards\nobservations, and when it discards treated units --- as CEM did above, keeping\n65 of 185 --- the estimand becomes the ATT among the matched treated. Weighting\nkeeps everyone, so the estimand survives, and pays for it with extreme weights\nwhen overlap is poor, which is what the effective sample sizes in this chapter\nhave been reporting. Matching buys stability with the estimand. Weighting buys\nthe estimand with variance.\n\nAIPW uses both columns. Start from regression adjustment, then add the\nodds-weighted average of the control residuals $Y - \\hat\\mu_0(X)$. It is\nconsistent if either model is right. The section on estimation after matching\ndid an informal version of the same thing: match first, then run a regression\nwith treatment-covariate interactions on the matched sample. That is regression adjustment after\nmatching, and the regression plays the part of the augmentation term. It is a\nrelative of @abadie-imbens-2011 bias-corrected matching rather than the same\nestimator: their correction is applied unit by unit to matched outcomes and comes\nwith its own variance theory, neither of which a post-matching interacted\nregression reproduces.\n\nFive routes, one data set. Each row below is built by hand from the weight\nrepresentation so the arithmetic is visible.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovs <- c(\"age\", \"educ\", \"race\", \"married\", \"nodegree\", \"re74\", \"re75\")\ntrt  <- lalonde$treat == 1\ny    <- lalonde$re78\n\n# Outcome model, fitted on controls only, then predicted everywhere\nmu0_fit <- lm(reformulate(covs, response = \"re78\"),\n              data = subset(lalonde, treat == 0))\nmu0 <- predict(mu0_fit, newdata = lalonde)\n\n# Odds weights from a logistic propensity score\nps     <- predict(glm(reformulate(covs, response = \"treat\"),\n                      data = lalonde, family = binomial), type = \"response\")\nodds   <- ps / (1 - ps)\nwt_ipw <- ifelse(trt, 1, odds)\n\n# Weighted difference in means: the common shape of rows 2 to 4\nhajek <- function(w) {\n  weighted.mean(y[trt], w[trt]) - weighted.mean(y[!trt], w[!trt])\n}\n\natt_ra   <- mean(y[trt] - mu0[trt])\natt_ipw  <- hajek(wt_ipw)\natt_eb   <- hajek(w_ebal$weights)\natt_fm   <- hajek(m.full$weights)\natt_aipw <- att_ra - weighted.mean(y[!trt] - mu0[!trt], odds[!trt])\n\ndata.frame(\n  route = c(\"Regression adjustment (outcome model)\",\n            \"IPW (propensity model)\",\n            \"Entropy balancing (balance constraints)\",\n            \"Full matching (distance rule)\",\n            \"AIPW (both models)\"),\n  att = c(att_ra, att_ipw, att_eb, att_fm, att_aipw)\n) |>\n  knitr::kable(digits = 0, col.names = c(\"Route\", \"ATT\"),\n               caption = \"Five routes to the same ATT on the Lalonde data.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Five routes to the same ATT on the Lalonde data.\n\n|Route                                   |  ATT|\n|:---------------------------------------|----:|\n|Regression adjustment (outcome model)   | 1648|\n|IPW (propensity model)                  | 1214|\n|Entropy balancing (balance constraints) | 1273|\n|Full matching (distance rule)           | 1855|\n|AIPW (both models)                      | 1231|\n\n\n:::\n:::\n\n\nTwo of these numbers confirm the algebra directly. The hand-built odds weights\nagree with the `weightit` propensity-score weights from the IPW section above to\nmachine precision, so the claim that weighting is IPW is an identity here and not\na resemblance. And entropy balancing gives \\$1,273 --- the same figure that\n`lm_weightit` produced earlier with the full set of treatment-covariate\ninteractions, agreeing to nine decimal places. Exact mean balance leaves nothing for a linear\noutcome model to correct, so adding one changes the estimate not at all. That is\nthe double robustness of entropy balancing [@zhao-percival-2017] appearing as\narithmetic: the same weights deliver the IPW estimator for a logit propensity\nmodel and the regression-adjustment estimator for a linear outcome model.\n\nThe spread across routes is the part to read carefully. Regression adjustment\ngives \\$1,648 and IPW gives \\$1,214. AIPW starts from the regression-adjustment\nfigure and the augmentation term subtracts \\$417, landing at \\$1,231 --- next to\nIPW, not next to regression adjustment. The propensity side is doing the work\nhere, which is what we should expect when the treated and control covariate\ndistributions are as far apart as the balance tables in this chapter have shown.\nFull matching sits highest at \\$1,855. It fits a propensity score too --- a\nprobit, used as the distance for forming subclasses --- so the gap between it and\nIPW's \\$1,214 is not about whether a propensity model was estimated. It is about\nhow the score is turned into weights: coarse subclass weights that throw away the\nscore's fine gradations, against the odds transformation that keeps them.\n\nThese are point estimates. Standard errors are not comparable across the rows\nand are deliberately left out: matching is not a smooth functional of the data,\nso the bootstrap is invalid for it [@abadie-imbens-2008] and the subclass\nclustering used earlier is needed, while IPW and AIPW have influence-function\nvariances and AIPW attains the semiparametric efficiency bound that fixed-$M$\nmatching does not --- given positivity, enough regularity, nuisance estimators\nconverging fast enough (with cross-fitting when they are flexible), and both\nnuisance limits at the truth. The bound is a property of the estimator plus those\nconditions, not of the name. The lesson from the column of estimates is the same one the\nmatching-versus-weighting comparison gave: with overlap this weak, the choice\nof route moves the answer by more than one standard error, so report several\nroutes rather than the one that reads best.\n\n## Summary\n\n- Matching is for selection on observables. It does not fix unobserved\n  confounding.\n- The main diagnostic is covariate balance, not the treatment-effect\n  coefficient.\n- Propensity-score matching is simple, but full matching or weighting often\n  balances better.\n- If there is no overlap, change the estimand or restrict the sample. Do not\n  hide the support problem.\n- Matching, weighting, and the direct estimators of the previous chapter are\n  one estimand built several ways. Weighting with `method = \"glm\"` is IPW, and\n  matching is weighting with the weights restricted to zero and small integers.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}