{
  "hash": "e06489e63f4d54108271ccb60e786464",
  "result": {
    "engine": "knitr",
    "markdown": "# Bayesian Causal Inference\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(BART)\nlibrary(bcf)\n```\n:::\n\n\nThe earlier chapters mostly compute point estimates and standard errors.\nBayesian methods instead put priors on unknown quantities and return a\nposterior distribution. For causal inference this is useful when we want\nuncertainty about a function of the model, such as an individual treatment\neffect or a policy value, not just one coefficient.\n\nI use two models:\n\n1. **BART for causal inference** (Hill 2011), where BART is used as a\n   flexible outcome model.\n2. **Bayesian Causal Forests** (BCF; Hahn, Murray, & Carvalho 2020), which\n   separates the baseline outcome model from the treatment-effect model.\n\n> **Related reading**: The chapter [Using Numpyro](https://xiangao.github.io/blog_book/numpyro.html)\n> in *Topics on Econometrics and Causal Inference* demonstrates a\n> Bayesian hierarchical model with Numpyro. For an MCMC-from-scratch\n> perspective on causal inference, that companion piece is the natural\n> next step after this chapter.\n\n## Setup\n\nWe reuse the simulation from the [Heterogeneous Treatment Effects](heterogeneous-effects.qmd)\nchapter, at $n = 2000$ rather than 5000. Five covariates are drawn\nindependently from $U(0,1)$. Treatment is\n$D \\sim \\text{Bernoulli}(\\Lambda(-0.3 + 1.5X_2))$, the individual effect is\n$\\tau(x) = 1 + 2x_1$, and the potential outcomes are\n$Y(0) = 0.5X_2 + \\varepsilon$ with $\\varepsilon \\sim N(0,1)$ and\n$Y(1) = Y(0) + \\tau(X)$. Only $X_1$ modifies the effect, only $X_2$ confounds,\nand $X_2$ is observed, so both models below are identified.\n\nThe aim is to see what a posterior adds over a point estimate: an interval for\nthe ATE that requires no asymptotic argument, and an interval for every\nindividual effect.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\nn <- 2000\np <- 5\n\nX <- matrix(runif(n * p), n, p)\ncolnames(X) <- paste0(\"X\", 1:p)\n# Treatment depends only on observed covariates, so unconfoundedness given X\n# holds and the \"True ATE\" comparison measures estimator performance (not bias).\nps <- plogis(-0.3 + 1.5 * X[, 2])\nD  <- rbinom(n, 1, ps)\ntau <- 1 + 2 * X[, 1]\nY0  <- 0.5 * X[, 2] + rnorm(n)\nY1  <- Y0 + tau\nY   <- ifelse(D == 1, Y1, Y0)\n\ndf <- data.frame(Y = Y, D = D, X)\ncat(sprintf(\"True ATE = %.3f\\n\", mean(tau)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue ATE = 1.985\n```\n\n\n:::\n:::\n\n\nThe realized ATE in this draw is 1.985, against a population value of 2.\n\n## BART for causal inference (Hill 2011)\n\nBayesian additive regression trees are Chipman, George and McCulloch [-@chipman-george-mcculloch-2010-bart]; the use made of them for causal inference here follows Hill [-@hill-2011-bart].\n\nBART is a sum of many small regression trees. The prior keeps each tree\nweak, and the sum of trees gives flexibility.\n\nFor causal inference, the recipe is:\n\n1. Fit BART for $\\mu(d,x)=\\mathbb{E}[Y \\mid D=d,X=x]$.\n2. For each unit $i$, predict counterfactuals $\\mu(1, x_i)$ and $\\mu(0, x_i)$.\n3. The individual treatment effect (ITE) is $\\hat\\tau_i = \\mu(1, x_i) - \\mu(0, x_i)$.\n4. Average the posterior draws to get the posterior for ATE or ITEs.\n\nWe run 1000 posterior draws after 200 burn-in, with $D$ and the five covariates\nas the design matrix. Each draw gives an ATE, and the spread across draws is\nthe posterior uncertainty.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# BART::wbart fits a continuous-outcome BART model\n# Combine D and X as the design matrix\nX_train <- cbind(D = D, X)\nset.seed(42)\nbart_fit <- wbart(\n  x.train = X_train,\n  y.train = Y,\n  ndpost = 1000,    # posterior samples after burn-in\n  nskip  = 200,     # burn-in\n  printevery = 1000\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n*****Into main of wbart\n*****Data:\ndata:n,p,np: 2000, 6, 0\ny1,yn: 2.058453, -2.423620\nx1,x[n*p]: 1.000000, 0.647277\n*****Number of Trees: 200\n*****Number of Cut Points: 1 ... 100\n*****burn and ndpost: 200, 1000\n*****Prior:beta,alpha,tau,nu,lambda: 2.000000,0.950000,0.174777,3.000000,0.205658\n*****sigma: 1.027514\n*****w (weights): 1.000000 ... 1.000000\n*****Dirichlet:sparse,theta,omega,a,b,rho,augment: 0,0,1,0.5,1,6,0\n*****nkeeptrain,nkeeptest,nkeeptestme,nkeeptreedraws: 1000,1000,1000,1000\n*****printevery: 1000\n*****skiptr,skipte,skipteme,skiptreedraws: 1,1,1,1\n\nMCMC\ndone 0 (out of 1200)\ndone 1000 (out of 1200)\ntime: 17s\ncheck counts\ntrcnt,tecnt,temecnt,treedrawscnt: 1000,0,0,1000\n```\n\n\n:::\n\n```{.r .cell-code}\n# Counterfactual predictions\nX_treat   <- cbind(D = rep(1, n), X)\nX_control <- cbind(D = rep(0, n), X)\n\nmu1_post <- predict(bart_fit, newdata = X_treat)   # 1000 x n posterior draws\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n*****In main of C++ for bart prediction\ntc (threadcount): 1\nnumber of bart draws: 1000\nnumber of trees in bart sum: 200\nnumber of x columns: 6\nfrom x,np,p: 6, 2000\n***using serial code\n```\n\n\n:::\n\n```{.r .cell-code}\nmu0_post <- predict(bart_fit, newdata = X_control)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n*****In main of C++ for bart prediction\ntc (threadcount): 1\nnumber of bart draws: 1000\nnumber of trees in bart sum: 200\nnumber of x columns: 6\nfrom x,np,p: 6, 2000\n***using serial code\n```\n\n\n:::\n\n```{.r .cell-code}\n# Posterior of individual treatment effects\ntau_post <- mu1_post - mu0_post   # 1000 x n posterior draws of ITEs\n\n# Posterior summaries\ntau_mean <- rowMeans(tau_post)    # ATE in each draw\nate_post_mean   <- mean(tau_mean)\nate_post_sd     <- sd(tau_mean)\nate_post_ci     <- quantile(tau_mean, c(0.025, 0.975))\n\ncat(sprintf(\"BART ATE posterior:\\n\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBART ATE posterior:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"  Mean:    %.3f\\n\", ate_post_mean))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Mean:    1.977\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"  SD:      %.3f\\n\", ate_post_sd))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  SD:      0.048\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"  95%% CrI: [%.3f, %.3f]\\n\", ate_post_ci[1], ate_post_ci[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  95% CrI: [1.880, 2.071]\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"  True ATE: %.3f\\n\", mean(tau)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  True ATE: 1.985\n```\n\n\n:::\n:::\n\n\nThe posterior mean is 1.977 with a posterior standard deviation of 0.048 and a\n95% credible interval of $[1.880, 2.071]$, which covers the realized 1.985. The\nposterior draws give the uncertainty directly: no asymptotic variance formula\nand no bootstrap, just the spread of the 1000 draws.\n\n### Individual-level credible intervals\n\nBART also gives a posterior for each unit's treatment effect. Here I plot\nthe posterior mean and pointwise credible intervals against the true\n$\\tau_i$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nite_mean <- colMeans(tau_post)\nite_lo   <- apply(tau_post, 2, quantile, 0.025)\nite_hi   <- apply(tau_post, 2, quantile, 0.975)\n\ndf_ite <- tibble(\n  X1     = X[, 1],\n  true   = tau,\n  est    = ite_mean,\n  lo     = ite_lo,\n  hi     = ite_hi\n)\n\nggplot(df_ite, aes(x = X1)) +\n  geom_ribbon(aes(ymin = lo, ymax = hi), alpha = 0.2,\n              fill = \"steelblue\") +\n  geom_point(aes(y = est), size = 0.4, alpha = 0.3, colour = \"steelblue\") +\n  geom_abline(aes(intercept = 1, slope = 2), colour = \"firebrick\",\n              linetype = \"dashed\", linewidth = 1) +\n  labs(x = \"X1\", y = \"Individual treatment effect\",\n       caption = \"Red dashed = true τ(x). Blue band = pointwise 95% credible interval.\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![BART-estimated individual treatment effects (mean of posterior) vs true τ(x) = 1 + 2 X₁. Shaded band shows pointwise 95% credible intervals.](bayesian-causal_files/figure-pdf/bart-ite-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nThe blue points are posterior means, the blue ribbon is the pointwise 95%\ncredible interval, and the red dashed line is the true $\\tau(x) = 1+2x_1$. This\nis what a frequentist CATE estimator does not hand you for free: an interval\nfor each individual, not only for the average.\n\n## Bayesian Causal Forests (BCF)\n\nBCF is Hahn, Murray and Carvalho [-@hahn-murray-carvalho-2020-bcf]. The separate prior on the treatment-effect function is what addresses the regularization-induced confounding that Hahn et al. [-@hahn-carvalho-puelz-he-2018] identify in a single-surface fit.\n\nBART models $\\mathbb{E}[Y \\mid D,X]$ directly. That means the same trees\nhave to learn the baseline outcome and the treatment-effect heterogeneity.\nWhen strong predictors of $Y(0)$ are also related to treatment, this can\ncreate noisy treatment-effect estimates.\n\nBCF writes the conditional mean as\n\n$$\n\\mathbb{E}[Y \\mid D, X] = \\mu(X) + \\tau(X)\\, D,\n$$ {#eq-bayesian-causal-1}\n\nand puts separate priors on $\\mu(X)$ and $\\tau(X)$. The treatment-effect\npart is regularized more strongly, which helps avoid overfitting\nheterogeneity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# BCF requires a propensity score as an input (\"piHat\")\nps_fit <- glm(D ~ X1 + X2 + X3 + X4 + X5, data = df, family = binomial)\npiHat  <- predict(ps_fit, type = \"response\")\n\n# BCF prints MCMC progress in a way that conflicts with knitr's encoding.\n# Its `verbose=FALSE`/`no_output=TRUE` arguments do not fully suppress this\n# within the SAME R session (the progress output comes from C++ code, not\n# from R's own message()/cat() machinery that sink()/suppressMessages()\n# can intercept) -- so the only reliable fix is running bcf() in its own R\n# process and only reading back the saved result, never its console output.\n# Use SEPARATE input and output files so a failed subprocess can never leave\n# the input list sitting where we expect the result, and check the exit\n# status and object names before trusting it.\n#\n# The subprocess needs its OWN set.seed(): a seed set in this session does not\n# reach a separate R process, so without the seed below BCF's posterior draws\n# change every time the chunk actually executes. The knitr cache hides that --\n# the numbers look stable until someone clears the cache, and then every BCF\n# figure in this chapter moves. Seed the worker so the chapter is reproducible.\ntmp_in  <- tempfile(fileext = \".rds\")\ntmp_out <- tempfile(fileext = \".rds\")\ntmp_err <- tempfile(fileext = \".log\")\nsaveRDS(list(Y = df$Y, D = df$D, X = X, piHat = piHat), tmp_in)\nstatus <- system(paste0(\"Rscript -e '\",\n  \"set.seed(42); \",\n  \"args <- readRDS(\\\"\", tmp_in, \"\\\"); \",\n  \"suppressMessages(library(bcf)); \",\n  \"f <- bcf(y=args$Y, z=args$D, x_control=args$X, x_moderate=args$X, \",\n  \"pihat=args$piHat, nburn=200, nsim=1000, n_chains=1, no_output=TRUE, \",\n  \"verbose=FALSE); \",\n  \"saveRDS(list(tau=f$tau), \\\"\", tmp_out, \"\\\")'\"),\n  ignore.stdout = TRUE, ignore.stderr = FALSE)\n# Surface the real cause instead of failing far downstream on a missing field.\nif (status != 0L || !file.exists(tmp_out)) {\n  stop(\"BCF subprocess failed (exit status \", status, \"). \",\n       \"Check that the 'bcf' package is installed in the worker session.\")\n}\nbcf_fit <- readRDS(tmp_out)\nif (is.null(bcf_fit$tau)) {\n  stop(\"BCF subprocess produced no 'tau' draws; aborting.\")\n}\nunlink(c(tmp_in, tmp_out, tmp_err))\n```\n:::\n\n\nThe propensity score enters BCF as data, so we fit it first by logistic\nregression on all five covariates. BCF then runs 1000 draws after 200 burn-in\non one chain. We extract the posterior treatment effects and summarise them the\nsame way as for BART:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntau_post_bcf <- bcf_fit$tau    # nsim x n matrix of posterior ITEs\n\nbcf_ate_post <- rowMeans(tau_post_bcf)\nbcf_ite_mean <- colMeans(tau_post_bcf)\n\ncat(sprintf(\"BCF ATE posterior:\\n\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBCF ATE posterior:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"  Mean:    %.3f\\n\", mean(bcf_ate_post)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Mean:    1.983\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"  SD:      %.3f\\n\", sd(bcf_ate_post)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  SD:      0.045\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"  95%% CrI: [%.3f, %.3f]\\n\",\n            quantile(bcf_ate_post, 0.025),\n            quantile(bcf_ate_post, 0.975)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  95% CrI: [1.896, 2.073]\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"  True ATE: %.3f\\n\", mean(tau)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  True ATE: 1.985\n```\n\n\n:::\n:::\n\n\nBCF gives a posterior mean of 1.984 with a posterior standard deviation of\n0.044 and a 95% credible interval of $[1.903, 2.072]$. Against BART's 1.977 and\n0.048, and a realized truth of 1.985, the two are indistinguishable at the level\nof the ATE. That is expected: the separation prior is aimed at the\ntreatment-effect *function*, and averaging over units washes out most of what\nit does.\n\n### BART vs BCF: individual treatment effects\n\nThe difference, if there is one, should appear in the individual effects. Each\npanel plots the posterior-mean ITE against $X_1$, with a loess fit and the true\n$\\tau(x)$ as the dashed red line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_compare <- bind_rows(\n  tibble(X1 = X[, 1], est = bcf_ite_mean, true = tau, method = \"BCF\"),\n  tibble(X1 = X[, 1], est = ite_mean,     true = tau, method = \"BART\")\n)\n\nggplot(df_compare, aes(X1, est)) +\n  geom_point(alpha = 0.2, size = 0.3, colour = \"steelblue\") +\n  geom_smooth(method = \"loess\", se = FALSE, colour = \"darkblue\",\n              linewidth = 1) +\n  geom_abline(intercept = 1, slope = 2, linetype = \"dashed\",\n              colour = \"firebrick\") +\n  facet_wrap(~ method) +\n  labs(x = \"X1\", y = \"Estimated ITE\",\n       caption = \"Red dashed = truth = 1 + 2 X1\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![BCF (left) vs BART (right) posterior-mean individual treatment effects against the true τ(x) = 1 + 2 X₁.](bayesian-causal_files/figure-pdf/compare-ite-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nBoth clouds follow the true line. BCF is usually the smoother of the two,\nbecause separating the prognostic part $\\mu(X)$ from the effect part $\\tau(X)$\nlets the prior regularise the effect function harder without also flattening\nthe baseline. In this DGP the baseline is nearly flat --- $Y(0) = 0.5X_2 +\n\\varepsilon$ --- so there is little prognostic signal for BART to confuse with\nthe effect, and the two methods have less to separate them than they would with\na strong, treatment-correlated baseline.\n\nBoth sets of numbers here are reproducible. BART is seeded in this session, and\nthe BCF worker seeds itself --- a seed set in the parent session does not reach\na separate R process, so the `set.seed(42)` inside the `Rscript` call is what\nmakes the posterior stable across renders.\n\n## When to use Bayesian methods\n\n| Reason to use Bayesian | Reason to use Frequentist |\n|---|---|\n| Prior information matters | Asymptotic theory is well-understood |\n| Need full posterior (e.g. for downstream decisions) | Computational cost matters (BART is slow on large $n$) |\n| Hierarchical / multilevel data structure | Effects are simple averages |\n| Small sample, weak identification | Effects are well-identified |\n| Want individual-level credible intervals | Existing frequentist toolkit is sufficient |\n\nBayesian methods are most useful when the posterior itself will be used:\nfor individual treatment decisions, policy values, or hierarchical models.\nIf the target is just a well-identified ATE in a large sample, the\nfrequentist methods in earlier chapters are often simpler.\n\n## Practical guidance\n\n- Start with BCF if the goal is heterogeneous effects.\n- Check MCMC diagnostics. A bad chain makes the posterior summaries useless.\n  Note that the fit above cannot support them: it runs a single chain with a\n  200-iteration burn-in, short of the package's own recommendation, so BCF\n  emits a warning and no between-chain diagnostic is available. Treat it as a\n  deterministic rendering demonstration. Its posterior intervals show the shape\n  of the output, not the precision of a production analysis, which would use\n  the recommended burn-in and several chains.\n- For BCF, pay attention to `piHat`; it is part of the model input.\n- Report posterior mean, posterior SD, and credible intervals for ATE and\n  meaningful CATE summaries.\n\n## Connections\n\n- The [Heterogeneous Treatment Effects](heterogeneous-effects.qmd)\n  chapter covers frequentist meta-learners (S/T/X/R/DR) and causal\n  forests via `grf`. BCF can be viewed as the Bayesian counterpart to\n  causal forests: both use ensembles of trees, but BCF puts priors on\n  the trees while `grf` uses honest sample-splitting.\n- The [Sensitivity Analysis](sensitivity-analysis.qmd) chapter's\n  Cinelli-Hazlett bounds are frequentist; the Bayesian analog is a\n  prior on the unmeasured-confounder strength (cf. McCandless et al.\n  2007).\n- For Bayesian *Numpyro*-style hierarchical models, see the [companion\n  blog chapter](https://xiangao.github.io/blog_book/numpyro.html).\n\n## Summary\n\n- BART estimates counterfactual outcomes by fitting a flexible outcome model.\n- BCF separates baseline outcome prediction from treatment-effect\n  heterogeneity.\n- The main output is the posterior, especially for individual effects or\n  policy decisions.\n- Computation is the main cost. For very large data, frequentist HTE methods\n  are usually easier.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}