{
  "hash": "0b9d39346c24869cd501c0d60131fa54",
  "result": {
    "engine": "knitr",
    "markdown": "# Causal Discovery: Observed Variables\n\n\n\nEarlier chapters assumed the graph was known, or at least that we could draw\na defensible DAG from subject knowledge. Causal discovery asks what can be\nlearned about the graph from observational data.\n\n## The Problem\n\nGiven $n$ i.i.d. observations of $p$ variables $(X_1, \\ldots, X_p)$, we want to recover the directed acyclic graph (DAG) $G$ that generated the data.\n\nThere is an important limit: observational data alone cannot distinguish\nbetween DAGs with the same conditional independence structure. The set of\nobservationally equivalent DAGs is a **Markov equivalence class**. The data\ncan identify this class, represented by a CPDAG, not necessarily the one true\nDAG.\n\nA CPDAG has the same skeleton (undirected edges) as all DAGs in its MEC. Some edges can be oriented (they have the same direction in every member of the MEC); others remain undirected because both directions are consistent with the CI structure.\n\n### Why some edges cannot be oriented\n\nThree DAGs are observationally equivalent — they produce the same set of conditional independences — and therefore indistinguishable from data:\n\n$$X \\to Y \\to Z \\qquad X \\leftarrow Y \\leftarrow Z \\qquad X \\leftarrow Y \\to Z$$ {#eq-causal-discovery-1}\n\nAll three imply $X \\perp\\!\\!\\!\\perp Z \\mid Y$ and no other CI. Their CPDAG shows $X - Y - Z$ with no arrowheads.\n\nThe structure $X \\to Y \\leftarrow Z$ (a **collider** at $Y$) is *not* equivalent: here $X \\perp\\!\\!\\!\\perp Z$ but $X \\not\\perp\\!\\!\\!\\perp Z \\mid Y$. Because it has a unique CI signature, the $\\to Y \\leftarrow$ orientation is identifiable from data. Algorithms orient these colliders; non-collider edges often remain undirected.\n\n### What a CPDAG tells you\n\nA directed edge $X \\to Y$ in the CPDAG means: in *every* DAG consistent with the data, $X$ causes $Y$. An undirected edge $X - Y$ means some consistent DAGs have $X \\to Y$ and others have $X \\leftarrow Y$ — data alone cannot decide.\n\nFor causal estimation: once you have a CPDAG, you can use background knowledge (temporal ordering, experimental context) to orient the remaining undirected edges, and then apply identification strategies from earlier chapters.\n\n## Two Discovery Paradigms in R\n\nIn R, `pcalg` implements two useful algorithm families:\n\n| Paradigm | Algorithm | Decision rule |\n|---|---|---|\n| **Constraint-based** | PC (Spirtes & Glymour, 1991) | Remove an edge when a CI test reports independence |\n| **Score-based** | GES (Chickering, 2002) | Add/remove/reverse the edge that most improves a model score (BIC) |\n\nBoth target the same CPDAG, but they make different mistakes. PC depends on\nfinite-sample conditional independence tests. GES depends on the score. I\nwould usually compare both.\n\n## Simulation\n\nWe generate a random Gaussian linear DAG using `pcalg::randomDAG` with 8 nodes and edge probability 0.35. Each edge $j \\to i$ generates a structural equation\n$$X_i = \\sum_{j \\in \\text{pa}(i)} \\beta_{ji} X_j + \\varepsilon_i, \\quad \\varepsilon_i \\sim N(0,1),$$ {#eq-causal-discovery-2}\nwith $|\\beta_{ji}|$ drawn from $[0.25, 1]$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2025)\n\nn_vars    <- 8\nn_samples <- 2000\nedge_prob <- 0.35\nlabels    <- paste0(\"X\", 1:n_vars)\n\ntrue_dag  <- randomDAG(n_vars, prob = edge_prob, lB = 0.25, uB = 1)\ngraph::nodes(true_dag) <- labels          # rename from \"1\"..\"8\" to \"X1\"..\"X8\"\ndata_mat  <- rmvDAG(n_samples, true_dag, errDist = \"normal\")\ncolnames(data_mat) <- labels\n\n# Adjacency matrix from the true DAG, in the pcalg \"ends-at-i\" convention:\n# entry [i,j] = 1 means an edge ending at i, i.e. j -> i.\nadj_true  <- t(as(true_dag, \"matrix\") != 0) * 1\n\n# igraph representation + shared layout for all comparison panels\nig_true <- graphnel_to_ig(true_dag)\ndag_layout <- igraph::layout_with_sugiyama(ig_true)$layout\nsprintf(\"Variables: %d   Samples: %d   True edges: %d\",\n        n_vars, n_samples, sum(adj_true))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Variables: 8   Samples: 2000   True edges: 11\"\n```\n\n\n:::\n:::\n\n\nThe draw gives 11 edges among the 28 possible pairs of 8 nodes, a density of\n0.39, close to the 0.35 we asked for. Both algorithms below see only\n`data_mat`; `adj_true` is kept aside to score them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_ig(ig_true, layout = dag_layout)\n```\n\n::: {.cell-output-display}\n![True DAG used for simulation.](causal-discovery_files/figure-pdf/fig-true-dag-1.pdf){#fig-true-dag fig-pos='H'}\n:::\n:::\n\n\n## CI-Test and Score Infrastructure\n\nPC uses a **Fisher-Z conditional independence test** appropriate for Gaussian data. Given the partial correlation $\\hat\\rho_{XY \\mid Z}$, the test statistic is\n$$T = \\sqrt{n - |Z| - 3} \\cdot \\operatorname{atanh}(\\hat\\rho_{XY \\mid Z}) \\;\\sim\\; N(0,1) \\quad \\text{under } H_0: X \\perp\\!\\!\\!\\perp Y \\mid Z.$$ {#eq-causal-discovery-3}\n\n**Choosing the significance level** $\\alpha$ involves a bias–variance tradeoff on the skeleton:\n\nAn edge is *removed* whenever a CI test fails to reject independence\n($p \\ge \\alpha$), so $\\alpha$ controls how easily edges are deleted:\n\n- **Low $\\alpha$ (e.g., 0.001)**: independence is rarely rejected, so more\n  tests \"find\" independence and more edges are removed. Sparser skeleton;\n  risks discarding real but weak edges.\n- **High $\\alpha$ (e.g., 0.05)**: independence is rejected more often, so\n  fewer edges are removed. Denser skeleton; risks retaining spurious edges.\n\nWith $n = 2000$ and $p = 8$ we use $\\alpha = 0.01$, a common default.\n\nGES does not use a significance level. It selects the graph that *minimizes*\nthe **Gaussian BIC**\n$$\\text{BIC}(G) = -2 \\,\\ell(\\hat\\theta; G) + |G| \\log n$$ {#eq-causal-discovery-4}\n(equivalently, maximizes the penalized log-likelihood\n$\\ell - \\tfrac{|G|}{2}\\log n$), which penalizes graph complexity directly.\nImplemented in `pcalg` as `GaussL0penObsScore`.\n\nWe wrap `gaussCItest` in a counter to track exactly how many CI tests PC calls:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_counted_ci <- function(suff_stat) {\n  count <- 0L\n  ci <- function(x, y, S, suffStat) {\n    count <<- count + 1L\n    gaussCItest(x, y, S, suffStat)\n  }\n  list(ci = ci, count = function() count)\n}\n\nsuff_stat <- list(C = cor(data_mat), n = n_samples)\n```\n:::\n\n\n## PC Algorithm\n\nThe **PC algorithm** (Spirtes & Glymour, 1991) starts from a complete undirected graph and removes edges whenever a conditional independence is found. It searches for separating sets $Z$ of increasing size, conditioning on subsets of the current neighbors. After skeleton discovery, Meek's rules orient as many edges as possible.\n\n**How it works, step by step:**\n\n1. Start with a complete undirected graph (every pair connected).\n2. For each pair $(X, Y)$, test $X \\perp\\!\\!\\!\\perp Y \\mid Z$ for all $Z \\subseteq \\text{neighbors}(X) \\setminus \\{Y\\}$, starting with $|Z| = 0$. Remove the edge if any such test passes.\n3. Repeat with conditioning sets of increasing size until no new edges are removed.\n4. Identify colliders: if $X - Z - Y$ and $X, Y$ non-adjacent, orient as $X \\to Z \\leftarrow Y$ only if $Z$ was not in the separating set of $X$ and $Y$.\n5. Apply Meek's orientation rules to propagate orientations without creating new colliders or cycles.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsig_level <- 0.01\n\nci_pc  <- make_counted_ci(suff_stat)\npc_fit <- pc(suffStat = suff_stat,\n             indepTest = ci_pc$ci,\n             labels = labels,\n             alpha = sig_level,\n             verbose = FALSE)\n\ncpdag_pc <- pc_fit@graph\nci_tests_pc <- ci_pc$count()\n```\n:::\n\n\n::: {.callout-note}\n**Reading the output: F1 scores**\n\nThe **F1 score** is the harmonic mean of precision and recall, ranging from 0 (worst) to 1 (perfect).\n\n- **Skeleton F1** measures whether the algorithm found the right edges regardless of direction. An edge is a true positive if it exists in both the estimated skeleton and the true one.\n- **CPDAG F1** is stricter: a directed edge $X \\to Y$ is only a true positive if the true DAG also has $X \\to Y$; an undirected edge $X - Y$ counts as correct if the true DAG has *either* direction.\n\nA high skeleton F1 with lower CPDAG F1 means the algorithm found the right adjacencies but oriented some of them incorrectly. **Caveat:** this is an *orientation-error-only* score -- leaving a truly directed edge undirected is never penalized, only actively wrong directions are. It is therefore not a standard CPDAG accuracy metric (which would also penalize unresolved/uncompelled orientations), and it can flatter an algorithm that simply declines to orient edges. Read it as \"of the orientations made, how many are right,\" not \"how much of the true CPDAG was recovered.\"\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Helper: extract directed adjacency matrix from a graphNEL CPDAG.\n# pcalg convention: amat[i,j] = 1 means an edge that ENDS at i,\n# i.e. a directed edge j -> i (or one endpoint of an undirected edge).\namat_from_graph <- function(g) {\n  # as(g, \"matrix\")[i,j] = 1 means i -> j (from->to). Transpose so that\n  # [i,j] = 1 means an edge ending at i (j -> i), matching adj_true's\n  # convention; otherwise CPDAG-F1 compares opposite orientations.\n  m <- t(as(g, \"matrix\") != 0)\n  storage.mode(m) <- \"integer\"\n  m\n}\n\n# Skeleton: symmetrize (edge exists either way).\namat_to_skel <- function(amat) (amat | t(amat)) * 1L\n\n# F1 scores: skeleton F1 (ignore direction) and CPDAG F1\n# (directed edge in estimate must match a directed edge in the truth;\n#  undirected in estimate matches either direction in truth).\n# CAUTION if reusing this function elsewhere: the CPDAG-F1 component is\n# orientation-error-only -- it never penalizes leaving a truly directed edge\n# undirected, only actively wrong orientations. It is not a standard CPDAG\n# accuracy metric and can flatter an algorithm that declines to orient\n# edges. See the discussion above this function for what it does and does\n# not measure.\nf1_scores <- function(amat_true, amat_est) {\n  skel_t <- amat_to_skel(amat_true)\n  skel_e <- amat_to_skel(amat_est)\n  diag(skel_t) <- diag(skel_e) <- 0\n  tp <- sum(skel_t & skel_e) / 2\n  fp <- sum(!skel_t & skel_e) / 2\n  fn <- sum(skel_t & !skel_e) / 2\n  f1_skel <- if (tp == 0) 0 else 2 * tp / (2 * tp + fp + fn)\n\n  # CPDAG F1: walk ordered pairs (i,j) with i < j\n  tp <- fp <- fn <- 0\n  p <- nrow(amat_true)\n  for (i in seq_len(p - 1)) for (j in seq.int(i + 1, p)) {\n    t_ij <- amat_true[j, i] == 1   # truth has i -> j?\n    t_ji <- amat_true[i, j] == 1   # truth has j -> i?\n    e_ij <- amat_est[j, i] == 1\n    e_ji <- amat_est[i, j] == 1\n    if (!t_ij && !t_ji && !e_ij && !e_ji) next\n    truth_undirected <- t_ij && t_ji\n    est_undirected   <- e_ij && e_ji\n    has_t <- t_ij || t_ji\n    has_e <- e_ij || e_ji\n    if (has_t && has_e) {\n      if (est_undirected || truth_undirected ||\n          (t_ij == e_ij && t_ji == e_ji)) {\n        tp <- tp + 1\n      } else {\n        fp <- fp + 1; fn <- fn + 1\n      }\n    } else if (has_e) {\n      fp <- fp + 1\n    } else {\n      fn <- fn + 1\n    }\n  }\n  f1_cpdag <- if (tp == 0) 0 else 2 * tp / (2 * tp + fp + fn)\n\n  c(skeleton = f1_skel, cpdag = f1_cpdag)\n}\n\namat_pc  <- amat_from_graph(cpdag_pc)\nf1_pc    <- f1_scores(adj_true, amat_pc)\nig_cpdag_pc <- graphnel_to_ig(cpdag_pc)\n\nsprintf(\"PC:    skeleton F1 = %.3f   CPDAG F1 = %.3f   CI tests = %d\",\n        f1_pc[\"skeleton\"], f1_pc[\"cpdag\"], ci_tests_pc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"PC:    skeleton F1 = 0.952   CPDAG F1 = 0.857   CI tests = 293\"\n```\n\n\n:::\n:::\n\n\nPC recovers the skeleton almost perfectly, with an F1 of 0.952, and orients most\nof it correctly, with a CPDAG F1 of 0.857. It needed 293 conditional\nindependence tests to get there.\n\n**Computational complexity:** In the worst case PC tests all subsets of neighbors, giving exponential growth with the maximum degree. In sparse graphs this is manageable; in dense graphs it becomes prohibitive.\n\n## GES Algorithm\n\n**GES** (Greedy Equivalence Search; Chickering, 2002) uses a different strategy. Instead of testing independences and removing edges, it searches the space of CPDAGs by adding and then removing edges that improve a model score. Under faithfulness and a consistent score such as BIC, GES recovers the true CPDAG as $n \\to \\infty$.\n\n**How it works, step by step:**\n\n1. **Forward phase.** Start from the empty graph. At each step, add the single edge whose addition most increases the BIC score, restricted to additions that stay within a CPDAG. Stop when no addition improves the score.\n2. **Backward phase.** From the forward-phase output, remove the single edge whose removal most increases the score. Stop when no removal improves the score.\n\nThe whole search operates on CPDAGs (equivalence classes), not individual DAGs, so it explores a much smaller space than naïve DAG search.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscore_ges <- new(\"GaussL0penObsScore\", data_mat)\nges_fit   <- ges(score_ges, verbose = FALSE)\ncpdag_ges <- as(ges_fit$essgraph, \"graphNEL\")\n\namat_ges  <- amat_from_graph(cpdag_ges)\nf1_ges    <- f1_scores(adj_true, amat_ges)\nig_cpdag_ges <- graphnel_to_ig(cpdag_ges)\n\nsprintf(\"GES:   skeleton F1 = %.3f   CPDAG F1 = %.3f   (score-based, no CI tests)\",\n        f1_ges[\"skeleton\"], f1_ges[\"cpdag\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"GES:   skeleton F1 = 0.800   CPDAG F1 = 0.720   (score-based, no CI tests)\"\n```\n\n\n:::\n:::\n\n\nGES gets a skeleton F1 of 0.800 and a CPDAG F1 of 0.720 on this dataset, both\nbelow PC's 0.952 and 0.857. Do not read that as a general ranking; the Monte\nCarlo below shows what happens when we stop looking at one draw.\n\nPC and GES fail differently. In PC, one wrong CI decision can affect later\norientation decisions. In GES, a wrong score move is usually more local.\n\n## Comparison\n\n::: {.callout-note}\n**Reading the CPDAG figure**\n\nIn the side-by-side graph display:\n\n- A **directed edge** $X_i \\to X_j$ means this orientation is invariant across all equivalent DAGs.\n- An **undirected edge** $X_i - X_j$ in the CPDAG display represents an *unoriented* edge: both $X_i \\to X_j$ and $X_i \\leftarrow X_j$ are statistically equivalent. This is **not** a hidden common cause — it means the data cannot determine direction.\n- A **missing edge** means the algorithm found a conditional independence separating those two variables.\n\nCompare the estimated CPDAGs to the true DAG: extra edges are false positives; missing edges are false negatives.\n:::\n\n\n::: {#tbl-comparison .cell tbl-cap='Algorithm comparison on the simulated 8-node DAG (n = 2000, alpha = 0.01)'}\n\n```{.r .cell-code}\nkable(data.frame(\n  Algorithm   = c(\"PC\", \"GES\"),\n  Paradigm    = c(\"Constraint-based\", \"Score-based\"),\n  Skeleton_F1 = round(c(f1_pc[\"skeleton\"], f1_ges[\"skeleton\"]), 3),\n  CPDAG_F1    = round(c(f1_pc[\"cpdag\"],    f1_ges[\"cpdag\"]),    3),\n  CI_Tests    = c(ci_tests_pc, NA)\n), row.names = FALSE)\n```\n\n::: {.cell-output-display}\n\n\n|Algorithm |Paradigm         | Skeleton_F1| CPDAG_F1| CI_Tests|\n|:---------|:----------------|-----------:|--------:|--------:|\n|PC        |Constraint-based |       0.952|    0.857|      293|\n|GES       |Score-based      |       0.800|    0.720|       NA|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nop <- par(mfrow = c(1, 3), mar = c(1, 1, 3, 1))\nplot_ig(ig_true,     layout = dag_layout, main = \"True DAG\")\nplot_ig(ig_cpdag_pc, layout = dag_layout, main = \"PC — estimated CPDAG\")\nplot_ig(ig_cpdag_ges,layout = dag_layout, main = \"GES — estimated CPDAG\")\npar(op)\n```\n\n::: {.cell-output-display}\n![True DAG vs. estimated CPDAGs. Arrows denote oriented edges; lines without arrowheads are unoriented (both directions are CI-equivalent).](causal-discovery_files/figure-pdf/fig-cpdags-1.pdf){#fig-cpdags fig-pos='H'}\n:::\n:::\n\n\n::: {.callout-note}\n**Interpreting the comparison table**\n\n- **Skeleton F1** is the primary metric for comparing algorithms: it measures edge recovery independent of orientation, since orientation accuracy is bounded by the MEC.\n- **CPDAG F1** additionally rewards correctly oriented edges and penalizes wrongly oriented ones (leaving an edge undirected is not penalized under our scoring).\n- **CI tests** is reported only for PC — GES is score-based and does not perform CI tests.\n\nOn this dataset PC comes out ahead on both metrics: GES's backward phase prunes or merges a few true adjacencies, which costs it skeleton F1 and, through the lost edges, CPDAG F1 as well. There is no general ranking — both algorithms target the *same* CPDAG, and the BIC score carries no orientation information beyond the conditional-independence structure (all DAGs in one Markov equivalence class receive the same score). Which one gets closer in finite samples depends on the DGP, the sample size, and the tuning ($\\alpha$ vs. the BIC penalty).\n:::\n\n## Monte Carlo Evaluation\n\nA single dataset can be lucky. We average over 100 replications to get stable estimates.\n\n**What to look for in the MC results:**\n\n- The **mean skeleton F1** is the headline: how often does each algorithm recover the true adjacencies?\n- The distribution of **CI test counts** (shown in @fig-mc-ci) tracks PC's computational variability; GES has no analogous quantity, so we plot PC alone.\n- High variance in F1 across replications suggests the algorithms are sensitive to the particular random graph.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nevaluate_once <- function(seed, n_vars = 8, n_samples = 2000,\n                          edge_prob = 0.35, sig = 0.01) {\n  set.seed(seed)\n  dag      <- randomDAG(n_vars, prob = edge_prob, lB = 0.25, uB = 1)\n  labs     <- paste0(\"X\", 1:n_vars)\n  graph::nodes(dag) <- labs\n  d        <- rmvDAG(n_samples, dag, errDist = \"normal\")\n  colnames(d) <- labs\n  adj      <- t(as(dag, \"matrix\") != 0) * 1L\n  ss       <- list(C = cor(d), n = n_samples)\n\n  ci       <- make_counted_ci(ss)\n  pc_f     <- pc(ss, ci$ci, labels = labs, alpha = sig, verbose = FALSE)\n  amat_p   <- amat_from_graph(pc_f@graph)\n\n  ges_f    <- ges(new(\"GaussL0penObsScore\", d), verbose = FALSE)\n  amat_g   <- amat_from_graph(as(ges_f$essgraph, \"graphNEL\"))\n\n  f_p <- f1_scores(adj, amat_p); f_g <- f1_scores(adj, amat_g)\n  c(f1_skel_pc  = f_p[\"skeleton\"], f1_skel_ges = f_g[\"skeleton\"],\n    f1_cpdag_pc = f_p[\"cpdag\"],    f1_cpdag_ges = f_g[\"cpdag\"],\n    ci_pc       = ci$count())\n}\n\nmc <- as.data.frame(t(sapply(1:100, evaluate_once)))\nnames(mc) <- c(\"f1_skel_pc\",\"f1_skel_ges\",\"f1_cpdag_pc\",\"f1_cpdag_ges\",\"ci_pc\")\n\nmc_summary <- data.frame(\n  Method      = c(\"PC\", \"GES\"),\n  Skeleton_F1 = round(c(mean(mc$f1_skel_pc),  mean(mc$f1_skel_ges)),  3),\n  CPDAG_F1    = round(c(mean(mc$f1_cpdag_pc), mean(mc$f1_cpdag_ges)), 3),\n  CI_Tests    = c(round(mean(mc$ci_pc), 1), NA)\n)\nkable(mc_summary,\n      caption = \"Monte Carlo averages (100 replications, n = 2000, p = 8)\",\n      row.names = FALSE)\n```\n\n::: {.cell-output-display}\n\n\nTable: Monte Carlo averages (100 replications, n = 2000, p = 8)\n\n|Method | Skeleton_F1| CPDAG_F1| CI_Tests|\n|:------|-----------:|--------:|--------:|\n|PC     |       0.947|    0.903|    230.6|\n|GES    |       0.933|    0.825|       NA|\n\n\n:::\n:::\n\n\nThe averages change the picture. On skeleton recovery PC gets 0.947 and GES\n0.933 --- a gap of 0.014, against the 0.152 gap on the single dataset shown\nabove. That one draw was not representative, and it is the reason this section\nexists. The honest statement is that the two algorithms recover adjacencies\nabout equally well on this class of graphs.\n\nThe CPDAG gap is larger and does not close: 0.903 for PC against 0.825 for GES.\nBoth algorithms target the same CPDAG and the BIC score is score-equivalent, so\nthis is not GES orienting *worse* in principle. It follows from the skeleton:\nedges GES fails to recover cannot be oriented at all, and our CPDAG score\ncounts those as errors.\n\nPC's average cost is 230.6 CI tests, below the 293 it used on the single\ndataset above --- another sign that draw was on the dense side.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mc, aes(x = ci_pc)) +\n  geom_histogram(bins = 20, fill = \"steelblue\", alpha = 0.75, color = \"white\") +\n  labs(x = \"CI tests (PC)\", y = \"Frequency\",\n       title = \"PC CI-test counts across 100 replications\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Distribution of PC's CI-test counts across 100 replications. The spread reflects how PC's cost depends on the realized graph density and the order of CI decisions.](causal-discovery_files/figure-pdf/fig-mc-ci-1.pdf){#fig-mc-ci fig-pos='H'}\n:::\n:::\n\n\nThe distribution is right-skewed: the mean is 230.6 against a median of 212,\nand the counts run from 40 to 770 across the 100 replications. Nothing changes\nbetween replications except the random graph and the sample drawn from it, so\na nineteen-fold spread in cost comes entirely from graph density --- a denser\ndraw means larger neighbour sets and therefore more conditioning subsets to\ntest. This is the practical face of the exponential worst case noted earlier.\nAt 8 nodes it is a nuisance; at 50 it is the binding constraint.\n\n## Real Data: Student Performance in PISA\n\nThe simulation had a luxury real research never does: a known true DAG, so we\ncould score recovery with F1. On real data there is **no ground truth**, so the\nquestions change. Instead of \"how close is the estimate to the truth?\" we ask:\ndo PC and GES *agree*; what can *background knowledge* orient; and is the\nstructure *stable* under resampling?\n\nWe illustrate on the OECD's **PISA 2022** assessment, restricted to **United\nStates** students and six variables with a clear substantive ordering.\n\n| Node | Meaning | Role |\n|---|---|---|\n| `HISEI` | Highest parental occupational status (ISEI) | Family background |\n| `HOMEPOS` | Home possessions index | Family background |\n| `IMMIG` | Immigration status (1 native … 3 first-gen) | Demographic |\n| `GRADE` | Grade relative to modal grade for age | Schooling |\n| `GENDER` | 1 = female, 0 = male | Demographic |\n| `MATH` | Mean of the 10 mathematics plausible values | Outcome |\n\n\n::: {.cell}\n\n```{.r .cell-code}\npisa <- read.csv(\"data/pisa_usa2022.csv\")\nXp   <- as.matrix(pisa[, c(\"HISEI\",\"HOMEPOS\",\"IMMIG\",\"GRADE\",\"GENDER\",\"MATH\")])\nwp   <- pisa$W\nplabs <- colnames(Xp)\nsprintf(\"Students (complete cases): %d\", nrow(Xp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Students (complete cases): 3890\"\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n**Three honesty caveats**, kept explicit:\n\n- **Plausible values.** Each student's ability is reported as 10 plausible\n  values (posterior draws), not one score. We use their mean, understating the\n  measurement variance; a full treatment runs discovery on each PV and pools.\n- **Categorical-as-Gaussian.** `IMMIG`, `GRADE`, `GENDER` are discrete; Fisher-Z\n  assumes joint Gaussianity — a standard but imperfect approximation.\n- **One country, one wave.** Pooling would inject country/time structure that\n  appears as spurious edges unless modelled as extra nodes.\n:::\n\n### Respecting the survey design\n\nPISA is not a simple random sample — students carry final weights `W_FSTUWT`.\nThe CI tests and the score are functions of the **covariance matrix** and a\n**sample size**, so we supply design-consistent inputs: a **weighted\ncovariance/correlation** matrix, and **Kish's effective sample size**\n$n_{\\text{eff}} = (\\sum_i w_i)^2 / \\sum_i w_i^2$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncwp   <- cov.wt(Xp, wt = wp, cor = TRUE)   # design-weighted moments\nCwp   <- cwp$cor\nSigp  <- cwp$cov\nneff  <- sum(wp)^2 / sum(wp^2)\nsprintf(\"Raw n = %d   Kish effective n = %.0f\", nrow(Xp), neff)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Raw n = 3890   Kish effective n = 3481\"\n```\n\n\n:::\n:::\n\n\n\n::: {#tbl-pisa-cor .cell tbl-cap='Design-weighted correlation matrix (PISA 2022, USA).'}\n\n```{.r .cell-code}\nkable(round(Cwp, 2))\n```\n\n::: {.cell-output-display}\n\n\n|        | HISEI| HOMEPOS| IMMIG| GRADE| GENDER|  MATH|\n|:-------|-----:|-------:|-----:|-----:|------:|-----:|\n|HISEI   |  1.00|    0.42| -0.17|  0.05|  -0.02|  0.33|\n|HOMEPOS |  0.42|    1.00| -0.18|  0.05|   0.03|  0.40|\n|IMMIG   | -0.17|   -0.18|  1.00|  0.07|   0.01| -0.05|\n|GRADE   |  0.05|    0.05|  0.07|  1.00|   0.08|  0.17|\n|GENDER  | -0.02|    0.03|  0.01|  0.08|   1.00| -0.09|\n|MATH    |  0.33|    0.40| -0.05|  0.17|  -0.09|  1.00|\n\n\n:::\n:::\n\n\nThe weights cost us little information here: the raw sample of 3,890 students\ncarries an effective sample size of 3,481, about 89% of it.\n\nThe correlation matrix already shows what the graph will have to explain.\n`MATH` correlates 0.40 with `HOMEPOS` and 0.33 with `HISEI`, the two family\nbackground measures, which themselves correlate 0.42 with each other. `GRADE`\ncorrelates 0.17 with `MATH` and `GENDER` $-0.09$. `IMMIG` correlates $-0.17$\nand $-0.18$ with the two background measures but only $-0.05$ with `MATH` ---\nits association with achievement runs largely through family background, which\nis the kind of statement a discovery algorithm is meant to formalise.\n\n### Two algorithms on the weighted data\n\nPC consumes the weighted correlation and effective $n$ directly. GES is\nscore-based and needs a data matrix, so we build a synthetic sample of\n$n_{\\text{eff}}$ rows whose empirical covariance equals the design-weighted\n$\\Sigma_w$ exactly (a Cholesky recolour) — a device to feed the *same* second\nmoments into a score that expects raw data, adding no information beyond\n$\\Sigma_w$.\n\nThis is a **moment-based approximation to the PISA design, not\ndesign-exact causal discovery.** The weighted covariance plus Kish's\n$n_{\\text{eff}}$ captures the final weights but not the full\nstratification and clustering of the design, and it ignores\nplausible-value (imputation) uncertainty in the achievement scores.\nTreat the recovered graph as a weighted-moment exploration, and do not\nread the effective-$n$ CI tests as exact design-based inference.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Synthetic matrix with covariance == Sigp exactly, neff rows\nm_eff <- round(neff)\nset.seed(1)\nZp <- scale(matrix(rnorm(m_eff * ncol(Xp)), m_eff), center = TRUE, scale = FALSE)\nZp <- Zp %*% solve(chol(cov(Zp)))     # whiten\nXw <- Zp %*% chol(Sigp)               # recolour to weighted covariance\nXw <- sweep(Xw, 2, cwp$center, \"+\")\ncolnames(Xw) <- plabs\n\npc_pisa   <- pc(list(C = Cwp, n = neff), indepTest = gaussCItest,\n                labels = plabs, alpha = 0.01)\namat_pcp  <- amat_from_graph(pc_pisa@graph)\n\nges_pisa  <- ges(new(\"GaussL0penObsScore\", Xw))\ncpdag_gesp<- as(ges_pisa$essgraph, \"graphNEL\")\namat_gesp <- amat_from_graph(cpdag_gesp)\n\nskp <- amat_to_skel(amat_pcp); skg <- amat_to_skel(amat_gesp)\ndiag(skp) <- diag(skg) <- 0\nsprintf(\"Skeleton edges — PC: %d   GES: %d   in both: %d\",\n        sum(skp)/2, sum(skg)/2, sum(skp & skg)/2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Skeleton edges — PC: 9   GES: 9   in both: 9\"\n```\n\n\n:::\n:::\n\n\nThe two algorithms find 9 skeleton edges each, and all 9 are the same edges.\nThat is the strongest agreement we can ask for without a ground truth: two\nmethods with different failure modes, one testing conditional independences and\none maximising a penalised likelihood, select an identical adjacency structure.\nNine edges out of 15 possible pairs is also a genuinely sparse answer, not a\nnear-complete graph.\n\nAgreement on the skeleton does not extend to orientation, as the next figure\nshows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nig_pcp  <- graphnel_to_ig(pc_pisa@graph)\nig_gesp <- graphnel_to_ig(cpdag_gesp)\nlay_p   <- igraph::layout_with_sugiyama(ig_pcp)$layout\nop <- par(mfrow = c(1, 2), mar = c(1, 1, 3, 1))\nplot_ig(ig_pcp,  layout = lay_p, main = \"PC — estimated CPDAG\")\nplot_ig(ig_gesp, layout = lay_p, main = \"GES — estimated CPDAG\")\npar(op)\n```\n\n::: {.cell-output-display}\n![Estimated CPDAGs from PC and GES on PISA 2022 (USA). Arrows are oriented edges; plain lines are unoriented. There is no true-DAG panel — on real data we have no ground truth.](causal-discovery_files/figure-pdf/fig-pisa-cpdags-1.pdf){#fig-pisa-cpdags fig-pos='H'}\n:::\n:::\n\n\n::: {.callout-important}\n**Read the disagreement, not just the agreement.** A purely data-driven score\nmay orient an edge as `MATH → HISEI` — a child's test score causing their\nparent's occupational status (GES does exactly this in the right panel). That\nis causally backwards, and the data cannot protect us: which direction this\nedge takes is not identifiable from observational data alone, so the\norientation the algorithm prints reflects its (possibly mistaken) v-structure\nand score decisions under misspecification, not evidence about the true\ndirection. This is exactly why background knowledge is not optional.\n:::\n\n### Orienting with background knowledge\n\nSex and immigration background are fixed at birth; family socioeconomic status\nis established long before the test; grade precedes the assessment; the score is\nthe outcome. That gives a **tier ordering**\n\n$$\n\\{\\text{GENDER}, \\text{IMMIG}\\} \\prec \\{\\text{HISEI}, \\text{HOMEPOS}\\}\n\\prec \\text{GRADE} \\prec \\text{MATH}.\n$$ {#eq-causal-discovery-5}\n\nA cross-tier edge must point earlier→later; a within-tier edge the ordering\ncannot decide. We impose this on the discovered **skeleton**, because the\nordering is knowledge we hold independently of how the data oriented things.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntier_p <- c(HISEI = 1, HOMEPOS = 1, IMMIG = 0, GRADE = 2, GENDER = 0, MATH = 3)[plabs]\nskel_p <- amat_to_skel(amat_pcp)\n\nedges_df <- data.frame(); undir_flag <- logical(0)\npp <- length(plabs)\nfor (i in seq_len(pp-1)) for (j in seq.int(i+1, pp)) {\n  if (skel_p[i, j] == 0) next\n  a <- plabs[i]; b <- plabs[j]\n  if (tier_p[a] == tier_p[b]) {\n    edges_df <- rbind(edges_df, data.frame(from = a, to = b)); undir_flag <- c(undir_flag, TRUE)\n  } else {\n    lo <- if (tier_p[a] < tier_p[b]) a else b\n    hi <- if (tier_p[a] < tier_p[b]) b else a\n    edges_df <- rbind(edges_df, data.frame(from = lo, to = hi)); undir_flag <- c(undir_flag, FALSE)\n  }\n}\nig_orient <- igraph::graph_from_data_frame(edges_df, vertices = plabs)\nigraph::E(ig_orient)$undirected <- undir_flag\n```\n:::\n\n\n::: {.callout-warning}\n**Where data-driven orientation disagreed with us.** Left to itself, PC\noriented `HISEI → IMMIG` and `HOMEPOS → IMMIG` — parental status and home\npossessions causing immigration background, which our tier ordering puts the\nother way round. GES did something worse with a different edge: it oriented\n`GRADE → IMMIG`, schooling causing immigration status (PC got that one\nright). These mistakes come from v-structure and score decisions made under\nmisspecification; the data is not informative about these directions.\nImposing the tier order overrides them. The lesson: **never ship a\ndiscovered orientation you have prior reason to disbelieve**.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlay_or <- igraph::layout_with_sugiyama(ig_orient)$layout\nplot_ig(ig_orient, layout = lay_or, main = \"PC skeleton + tier ordering\")\n```\n\n::: {.cell-output-display}\n![PC skeleton oriented by the temporal/logical tiers. Cross-tier edges point earlier-to-later; HISEI–HOMEPOS stays undirected (same tier).](causal-discovery_files/figure-pdf/fig-pisa-oriented-1.pdf){#fig-pisa-oriented fig-pos='H'}\n:::\n:::\n\n\nEvery edge into `MATH` is now a candidate causal parent of achievement — the\nbridge from discovery to estimation (back-door adjustment, e.g. on the parents\nof the chosen treatment variable). The only edge the ordering leaves\nundirected, `HISEI – HOMEPOS`, is\ntwo same-tier measures of family background that temporal logic cannot separate.\n\n### Stability: does the skeleton survive resampling?\n\nA single fit can be lucky. We resample students with replacement, re-estimate\nthe **weighted** PC skeleton, and record how often each edge appears.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nB_pisa <- 200\nboot_once <- function(b) {\n  set.seed(1000 + b)\n  idx <- sample.int(nrow(Xp), replace = TRUE)\n  Xb  <- Xp[idx, ]; wb <- wp[idx]\n  cwb <- cov.wt(Xb, wt = wb, cor = TRUE)\n  neff_b <- sum(wb)^2 / sum(wb^2)\n  fit <- tryCatch(pc(list(C = cwb$cor, n = neff_b), indepTest = gaussCItest,\n                     labels = plabs, alpha = 0.01), error = function(e) NULL)\n  if (is.null(fit)) return(NULL)\n  amat_to_skel(amat_from_graph(fit@graph))\n}\nncores <- max(1, parallel::detectCores() - 1)\nskels  <- parallel::mclapply(seq_len(B_pisa), boot_once, mc.cores = ncores)\nskels  <- skels[!vapply(skels, is.null, logical(1))]\nedge_freq <- Reduce(`+`, skels) / length(skels)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs_df <- do.call(rbind, lapply(seq_len(pp-1), function(i)\n  do.call(rbind, lapply(seq.int(i+1, pp), function(j)\n    data.frame(Edge = paste(plabs[i], \"—\", plabs[j]),\n               Frequency = round(edge_freq[i, j], 2))))))\npairs_df <- pairs_df[pairs_df$Frequency > 0, ]\nggplot(pairs_df, aes(x = reorder(Edge, Frequency), y = Frequency)) +\n  geom_col(fill = \"steelblue\", alpha = 0.8) +\n  geom_hline(yintercept = 0.5, linetype = \"dashed\", colour = \"grey50\") +\n  coord_flip() + ylim(0, 1) +\n  labs(x = NULL, y = \"Selection frequency across bootstrap resamples\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Bootstrap edge-selection frequency (weighted PC, 200 resamples). Edges near 1.0 are robust; near 0.5 are sample-dependent.](causal-discovery_files/figure-pdf/fig-pisa-stability-1.pdf){#fig-pisa-stability fig-pos='H'}\n:::\n:::\n\n\nSix of the nine edges appear in every one of the 200 resamples:\n`HISEI–HOMEPOS`, `HISEI–IMMIG`, `HISEI–MATH`, `HOMEPOS–IMMIG`, `HOMEPOS–MATH`\nand `GRADE–MATH`. `GENDER–MATH` appears in 99.5% and `GRADE–GENDER` in 98.5%.\nThe weakest of the nine is `IMMIG–GRADE` at 86.5% --- still stable, but the one\nto hold most loosely. Two edges that the full sample rejected do appear\noccasionally, `HOMEPOS–GENDER` in 14% of resamples and `IMMIG–GENDER` in 0.5%;\nneither is close to the 50% line.\n\nSo the family-background-to-math edges are perfectly stable: the SES gradient\nin achievement is not an artefact of this sample. On real data,\ncausal discovery is best read as **hypothesis generation** — it proposes a\nskeleton and the orientations the data support, which you then reconcile with\nsubject-matter knowledge before estimating effects.\n\n## Summary\n\nPC and GES target the same Markov equivalence class. PC uses conditional\nindependence tests; GES uses model fit. If they agree on the skeleton, that\nis reassuring. If they disagree, check sample size, model assumptions, and\npossible faithfulness problems.\n\n**From CPDAG to causal estimation:** Once a CPDAG is in hand, the workflow continues as follows:\n\n1. **Use background knowledge to orient undirected edges.** Temporal ordering is the most common source: if $X$ is measured before $Y$, the edge must be $X \\to Y$. Domain expertise, experimental context, or exclusion restrictions can orient others.\n2. **Check identifiability.** With a fully oriented DAG, apply the backdoor, front-door, or ID algorithm to determine whether the effect of interest is identifiable.\n3. **Estimate.** Use the identified functional with the estimators from earlier chapters (RA, IPW, AIPW, TMLE).\n\nIf some edges remain undirected after exhausting background knowledge, the bound over the equivalence class is not automatic. Something has to enumerate what the class permits. For total effects under a linear Gaussian model, IDA (intervention calculus when the DAG is absent) does exactly that: `pcalg::ida()` takes the CPDAG and the covariance matrix, works through the DAGs consistent with the estimated structure, and returns the multiset of possible effects, whose range is the bound. `idaFast()` does the same for many outcomes at once. Outside that model, or for estimands IDA does not cover, enumerate the admissible DAGs explicitly and report the spread of the identified functionals. The alternative is to collect interventional data and break the remaining equivalences.\n\n::: {.callout-note}\n**What cannot be recovered from observational data alone**\n\nBoth algorithms identify the CPDAG, not necessarily the true DAG. Some edge\ndirections require extra assumptions, temporal ordering, or interventional\ndata.\n\nThe next chapter addresses a harder problem: recovering the causal skeleton when some variables are *unobserved*.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}