project:
  type: book

book:
  title: "Introduction to Causal Econometrics with Observational Data"
  author: "Xiang Ao, HBS"
  date: "last-modified"
  search: true
  page-navigation: true
  chapters:
    - index.qmd
    - part: "Foundations"
      chapters:
        - identification.qmd
        - estimation.qmd

    - part: "Methods"
      chapters:
        - machine-learning.qmd
        - nonparametric.qmd

    - part: "Designs"
      chapters:
        - did.qmd
        - iv-rdd.qmd

    - part: "Mediation"
      chapters:
        - mediation.qmd

format:
  html:
    theme:
      light: cosmo
    code-link: true
    callout-appearance: simple
    code-tools: true

execute:
  freeze: auto
