{
  "hash": "1baf6574d65e86159f375d37ee385600",
  "result": {
    "engine": "knitr",
    "markdown": "# Survival Analysis with Causal Inference\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(survival)\nlibrary(survminer)\nlibrary(riskRegression)\n```\n:::\n\n\nWhen the outcome is time-to-event, such as death, readmission, job exit, or\nmachine failure, ordinary regression is not enough. Some observations are\ncensored. We know the event had not happened by the end of follow-up, but we\ndo not know the event time. Dropping those observations or treating the\nobserved follow-up time as the event time creates bias.\n\nI cover:\n\n1. Cox proportional hazards models with covariate adjustment.\n2. Inverse probability of censoring weighting (IPCW).\n3. Restricted mean survival time (RMST) differences.\n4. Doubly robust survival estimators in `riskRegression`.\n\n## The challenge of censored outcomes\n\nCensoring means we observe $\\min(T_i, C_i)$ and $\\delta_i = \\mathbb{1}\\{T_i \\le C_i\\}$,\nwhere $T_i$ is the event time and $C_i$ is the censoring time. The\nmain quantity of interest is the survival function\n\n$$\nS(t) = P(T > t)\n$$ {#eq-survival-causal-1}\n\nthe probability of surviving past time $t$. Treatment effects are usually\nreported as:\n\n- **Hazard ratio (HR)**: $HR = h_1(t) / h_0(t)$ (the ratio of hazards\n  under treatment vs control). Easy to estimate but hard to interpret\n  causally [@hernan-2010-hazards].\n- **Restricted mean survival difference (RMST)**: $\\int_0^\\tau [S_1(t) - S_0(t)] dt$\n  — the difference in mean survival up to time $\\tau$. Causally\n  interpretable as a \"years gained\" quantity.\n- **Survival probability difference**: $S_1(t) - S_0(t)$ at a specified\n  time. Reports a direct probability difference.\n\n## Setup: simulated survival data\n\nThe data are simulated once and shared with the Julia companion, so both books\nreport the same numbers. The generator is `data/gen_survival.R`.\n\nWe draw $n = 1500$ people with $\\text{age} \\sim N(60, 10^2)$ and\n$\\text{sex} \\sim \\text{Bernoulli}(0.5)$. Treatment is\n$\\text{trt} \\sim \\text{Bernoulli}(\\Lambda(-1.0 + 0.03(\\text{age}-60) + 0.4\\,\\text{sex}))$,\nso older people and one sex are more likely to be treated. Event times follow a\nWeibull proportional-hazards model with shape $k = 1.4$ and scale\n$\\lambda_0 = 0.11$,\n\n$$\nS(t \\mid X) = \\exp\\!\\bigl(-(\\lambda_0 t)^k e^{\\eta}\\bigr), \\qquad\n\\eta = -0.4\\,\\text{trt} + 0.03(\\text{age}-60) + 0.3\\,\\text{sex},\n$$ {#eq-survival-causal-4}\n\nso the true log hazard ratio for treatment is $-0.4$ and the true hazard ratio\nis $e^{-0.4} = 0.670$. Censoring is exponential dropout with mean 40 years,\ncapped by administrative end of follow-up at 12 years, and we observe\n$\\min(T, C)$ with an event indicator.\n\nBecause the model is fully specified, the other estimands follow by\nintegration. Over the population distribution of age and sex, the true\nfive-year risk is 0.295 under treatment and 0.403 under control, a **risk\ndifference of $-0.108$**, and the true restricted mean survival to five years\nis 4.341 years under treatment against 4.070 under control, an **RMST\ndifference of 0.271 years**. Note that treatment is confounded in the direction\nthat hides its benefit: age raises both the chance of treatment and the hazard,\nso the treated are sicker at baseline.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- read_csv(\"data/survival_sim.csv\", show_col_types = FALSE)\nn <- nrow(df)\ncat(sprintf(\"n = %d, events = %d (%.1f%%), censored = %d\\n\",\n            n, sum(df$event), 100 * mean(df$event), sum(1 - df$event)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn = 1500, events = 1010 (67.3%), censored = 490\n```\n\n\n:::\n:::\n\n\nOf the 1,500 people, 1,010 have an observed event (67.3%) and 490 are censored.\n\n## Kaplan-Meier survival curves\n\nThe Kaplan-Meier estimator is the basic nonparametric estimate of $S(t)$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkm_fit <- survfit(Surv(time, event) ~ trt, data = df)\nggsurvplot(km_fit, data = df,\n           pval = TRUE,\n           risk.table = TRUE,\n           xlab = \"Time (years)\",\n           legend.labs = c(\"Control\", \"Treatment\"))\n```\n\n::: {.cell-output-display}\n![Kaplan-Meier survival curves by treatment arm. Treatment shifts the survival curve upward, but the gap reflects both the causal effect AND any baseline imbalance in age/sex.](survival-causal_files/figure-html/km-1.png){width=768}\n:::\n:::\n\n\nThe KM curve is descriptive. It is not enough for causal inference here\nbecause treatment is related to baseline covariates.\n\n## Cox proportional hazards with adjustment\n\nThe familiar regression approach is a Cox proportional hazards model with\ncovariate adjustment:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncox_fit <- coxph(Surv(time, event) ~ trt + age + sex, data = df)\ntidy(cox_fit, exp = TRUE, conf.int = TRUE) |>\n  knitr::kable(digits = 3,\n               caption = \"Cox PH regression coefficients (exponentiated = hazard ratios)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Cox PH regression coefficients (exponentiated = hazard ratios)\n\n|term | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:----|--------:|---------:|---------:|-------:|--------:|---------:|\n|trt  |    0.669|     0.072|    -5.608|       0|    0.582|     0.770|\n|age  |    1.035|     0.003|    10.754|       0|    1.029|     1.042|\n|sex  |    1.347|     0.064|     4.663|       0|    1.189|     1.527|\n\n\n:::\n:::\n\n\nThe estimated hazard ratio for treatment is 0.669 with a 95% interval of\n$[0.582, 0.770]$, against the true $e^{-0.4} = 0.670$. The Cox model is\ncorrectly specified here --- the DGP is proportional hazards with linear\ncovariate effects --- so this is a check that the machinery works, not evidence\nabout robustness. Age carries a hazard ratio of 1.035 per year and sex 1.347,\nagainst the true $e^{0.03} = 1.030$ and $e^{0.3} = 1.350$.\n\n### The interpretation problem with hazard ratios\n\nThe Cox hazard ratio is not a simple mean treatment effect. It compares\nhazards among those still at risk at time $t$, and that risk set is itself\naffected by treatment. I would report it, but not rely on it as the only\ncausal summary.\n\n## Restricted Mean Survival Time (RMST)\n\nThe **restricted mean survival time** is the expected survival time up\nto a cutoff $\\tau$:\n\n$$\n\\text{RMST}(\\tau) = E[\\min(T, \\tau)] = \\int_0^\\tau S(t)\\, dt.\n$$ {#eq-survival-causal-2}\n\nThe RMST difference is easier to interpret:\n\n$$\n\\Delta_{\\text{RMST}}(\\tau) = \\text{RMST}_1(\\tau) - \\text{RMST}_0(\\tau)\n= \\int_0^\\tau [S_1(t) - S_0(t)]\\, dt.\n$$ {#eq-survival-causal-3}\n\nIt also does not require proportional hazards.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use survRM2 via riskRegression / manually computing from KM\ntau <- 5  # restrict to 5 years\n\n# Manual RMST: integrate the KM curve up to tau.\n# (For production use, prefer a tested implementation such as\n#  survRM2::rmst2; the helper below is for transparency.)\n# Read the step function directly from fit$time / fit$surv, anchor\n# S(0) = 1 explicitly, and integrate as a left-endpoint rectangle sum\n# over the grid (0, event times <= tau, tau). This avoids relying on\n# how summary.survfit emits a row at time 0 and never duplicates tau in\n# a way that drops the final [last event, tau] interval.\nrmst_arm <- function(time, event, tau) {\n  fit  <- survfit(Surv(time, event) ~ 1)\n  keep <- fit$time <= tau\n  t_grid <- c(0, fit$time[keep], tau)\n  # Survival height on each interval [t_j, t_{j+1}): S(0) = 1, then the\n  # KM value just after each event; the trailing value is a placeholder\n  # dropped by head(., -1) below.\n  last_s <- if (any(keep)) fit$surv[keep][sum(keep)] else 1\n  s_grid <- c(1, fit$surv[keep], last_s)\n  sum(diff(t_grid) * head(s_grid, -1))\n}\n\nrmst_trt  <- rmst_arm(df$time[df$trt == 1], df$event[df$trt == 1], tau)\nrmst_ctrl <- rmst_arm(df$time[df$trt == 0], df$event[df$trt == 0], tau)\n\ncat(sprintf(\"RMST(τ=5) under treatment: %.3f years\\n\", rmst_trt))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRMST(τ=5) under treatment: 4.351 years\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"RMST(τ=5) under control:   %.3f years\\n\", rmst_ctrl))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRMST(τ=5) under control:   4.147 years\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Difference:                %.3f years\\n\", rmst_trt - rmst_ctrl))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDifference:                0.203 years\n```\n\n\n:::\n:::\n\n\nThe unadjusted RMST is 4.351 years under treatment and 4.147 under control, a\ndifference of 0.203 years, against a true 0.271. The RMST difference says how\nmany survival years are gained up to the cutoff $\\tau$, and this one understates\nthe gain by a quarter, because the treated are older and therefore at higher\nbaseline hazard.\n\n### Adjusted RMST via IPW\n\nTo adjust for confounding, weight the KM curve by the inverse propensity\nscore:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Propensity score\nps_fit <- glm(trt ~ age + sex, data = df, family = binomial)\ndf$ps  <- predict(ps_fit, type = \"response\")\ndf$ipw <- ifelse(df$trt == 1, 1 / df$ps, 1 / (1 - df$ps))\ndf$ipw <- pmin(df$ipw, quantile(df$ipw, 0.99))  # trim\n\nkm_ipw <- survfit(Surv(time, event) ~ trt, data = df, weights = ipw)\nprint(km_ipw, rmean = tau)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(time, event) ~ trt, data = df, weights = ipw)\n\n      records    n events rmean* se(rmean) median 0.95LCL 0.95UCL\ntrt=0    1039 1499   1061   4.12    0.0365   6.46    5.95    6.91\ntrt=1     461 1494    897   4.40    0.0317   7.73    6.94    8.85\n    * restricted mean with upper limit =  5 \n```\n\n\n:::\n:::\n\n\nThe weighted restricted means are 4.40 years under treatment and 4.12 under\ncontrol, a difference of 0.28 against the true 0.271. Weighting moved the\nestimate from 0.203 to 0.28 and closed almost the whole gap. Note that the\n`n` column now reports the weighted totals, 1,494 and 1,499, rather than the\n461 and 1,039 actual records --- that is the pseudo-population the weights\nconstruct.\n\n## Inverse Probability of Censoring Weighting (IPCW)\n\nIf censoring is informative, for example if sicker patients drop out earlier,\ntreating censoring as random is biased. IPCW weights observations by the\ninverse probability of remaining uncensored, conditional on covariates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model the censoring hazard\n# Use 1 - event as the \"censoring\" indicator\ncens_fit <- coxph(Surv(time, 1 - event) ~ trt + age + sex, data = df)\n\n# Predict survival of censoring at each event time for each unit\ndf_sub <- df |>\n  arrange(time)\ntimes_at_risk <- df_sub$time\n# G(t | X): probability of being uncensored at time t given X\n# Use survfit on cens_fit to get S_C(t | X)\nsc_fit <- survfit(cens_fit, newdata = df_sub)\n# We only need each subject's OWN survival at their OWN event time, not the\n# full cross product of all N subjects' curves at all N event times.\n# summary(sc_fit, times=df_sub$time, extend=TRUE)$surv followed by diag()\n# builds that full N x N matrix just to throw away everything off the\n# diagonal -- for N in the tens of thousands this is a multi-GB allocation\n# and can OOM. Look each subject's own time up in sc_fit's existing\n# per-subject step function instead (sc_fit$surv is already an\n# n_times x N matrix that survfit(newdata=) computes regardless; this just\n# avoids building a second, larger one on top of it). For very large N,\n# packages like `riskRegression`/`pec` avoid materializing even that\n# per-subject curve matrix and would scale further.\nsc_idx  <- findInterval(df_sub$time, sc_fit$time)\nsc_at_t <- sc_fit$surv[cbind(pmax(sc_idx, 1), seq_len(nrow(df_sub)))]\nsc_at_t[sc_idx == 0] <- 1  # before the first censoring event, S_C = 1\n\n# IPCW weight: 1 / P(C > T_i | X_i) for event times, 0 for censoring times\ndf_sub$ipcw <- ifelse(df_sub$event == 1, 1 / pmax(sc_at_t, 0.01), 0)\nsummary(df_sub$ipcw[df_sub$event == 1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.001   1.075   1.137   1.149   1.219   1.353 \n```\n\n\n:::\n:::\n\n\nIPCW upweights observations that remain uncensored despite having a high\npredicted chance of censoring. The weights here run from 1.001 to 1.353 with a\nmean of 1.149, which is mild. That is expected in this simulation: censoring is\nexponential dropout with a 40-year mean plus an administrative cutoff, and\nneither depends on the covariates in a way that would make censoring strongly\ninformative. The correction is available and small; in a study where sicker\npatients drop out, it would not be.\n\n## Doubly-robust survival estimation\n\nThe `riskRegression` package combines the outcome model, propensity score,\nand censoring model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Average treatment effect on survival probability at t = 5\n# ATE(t) = P(T(1) > t) - P(T(0) > t)\ndf$trt_f <- factor(df$trt)\ncox_for_ate <- coxph(Surv(time, event) ~ trt_f + age + sex, data = df,\n                     x = TRUE, y = TRUE)\nps_for_ate  <- glm(trt_f ~ age + sex, data = df, family = binomial, x = TRUE)\n# With right-censoring, the IPTW/AIPTW survival estimator needs a model for\n# the censoring mechanism (a Cox model for time-to-censoring).\ncens_for_ate <- coxph(Surv(time, event == 0) ~ age + sex, data = df,\n                      x = TRUE, y = TRUE)\n\nate_surv <- ate(\n  event       = cox_for_ate,\n  treatment   = ps_for_ate,\n  censor      = cens_for_ate,\n  data        = df,\n  times       = 5,\n  estimator   = c(\"Gformula\", \"IPTW\", \"AIPTW\"),\n  cause       = 1,\n  se          = TRUE,\n  B           = 0,\n  verbose     = FALSE\n)\n\nsummary(ate_surv)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Average treatment effect \n\n - Treatment            : trt_f (2 levels: \"0\" \"1\")\n - Event                : event (cause: 1, censoring: 0)\n - Time  [min;max]      : time [0.0372;12]\n - at risk/time         :   5\n   number in treatment  0 561\n   number in treatment  1 283\n\n Estimation procedure \n - Estimators : G-formula, Inverse probability of treatment weighting, Augmented and double robust estimator\n - Uncertainty: Gaussian approximation \n                where the variance is estimated via the influence function \n\n Testing procedure\n - Null hypothesis     : given two treatments (A,B) and a specific timepoint, equal risks \n - Confidence level    : 0.95\n\n Results: \n - Difference in standardized risk (B-A) between time zero and 'time' \n                reported on the scale [-1;1] (difference between two probabilities)\n (difference in average risks when treating all subjects with the experimental treatment (B),\n                                vs. treating all subjects with the reference treatment (A))\n\n time trt_f=A risk(trt_f=A) trt_f=B risk(trt_f=B) difference            ci\n    5       0         0.393       1         0.287     -0.106 [-0.14;-0.07]\n  p.value\n 5.36e-09\n\n difference      : estimated difference in standardized risks \n ci              : pointwise confidence intervals \n p.value         : (unadjusted) p-value \n```\n\n\n:::\n\n```{.r .cell-code}\n# The summary displays one estimator; put all three side by side\nate_tab <- as.data.frame(data.table::as.data.table(ate_surv, type = \"diffRisk\"))\nknitr::kable(ate_tab[, c(\"estimator\", \"estimate\", \"se\", \"lower\", \"upper\")],\n             digits = 3,\n             caption = \"Risk difference at t = 5 under each estimator.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Risk difference at t = 5 under each estimator.\n\n|estimator | estimate|    se|  lower|  upper|\n|:---------|--------:|-----:|------:|------:|\n|GFORMULA  |   -0.106| 0.018| -0.142| -0.070|\n|IPTW      |   -0.095| 0.027| -0.148| -0.041|\n|AIPTW     |   -0.099| 0.027| -0.152| -0.046|\n\n\n:::\n:::\n\n\nThe object contains three estimators, shown side-by-side in the table:\n\n- **Gformula** — parametric g-computation using the Cox model only.\n- **IPTW** — inverse probability of treatment weighting.\n- **AIPTW** — augmented IPTW (doubly robust); the recommended default.\n\nAll three agree, and all three are close to the truth: $-0.106$, $-0.095$ and\n$-0.099$ against a true risk difference of $-0.108$. Treatment cuts the\nfive-year risk of the event by about ten percentage points. The g-formula has\nthe smallest standard error, 0.018 against 0.027 for the other two, because it\nleans entirely on the Cox model, which is correctly specified here. That is an\nefficiency gain bought with an assumption, and AIPTW's wider interval is the\nprice of not needing it.\n\nAgreement across these estimates is reassuring. Disagreement is a warning\nabout model specification.\n\n## Hazard ratio vs RMST: which to report?\n\nFor causal reporting, RMST is often easier to defend than the hazard ratio:\n\n| Quantity | Pro | Con |\n|---|---|---|\n| **Hazard ratio** | Compact summary; familiar | Requires PH; no causal interpretation; conditional on survivors |\n| **RMST difference** | Directly interpretable as \"years gained\"; no PH assumption | Depends on cutoff $\\tau$; less familiar |\n| **Survival probability difference at t** | Direct probability statement | Depends on choice of $t$ |\n\nIn practice, report at least:\n\n1. The KM curves with risk tables (description).\n2. The Cox HR with adjustment (familiar comparison to literature).\n3. The RMST difference at a clinically meaningful $\\tau$ (interpretable\n   causal contrast).\n4. The DR ATE on survival probability at one or two follow-up times.\n\n## Connections\n\n- The [G-Methods chapter](g-methods.qmd) covers IPTW with time-varying\n  treatments — directly applicable when treatment evolves during\n  follow-up. The IPCW machinery here is the censoring analogue.\n- The [Heterogeneous Effects chapter](heterogeneous-effects.qmd) ML\n  methods extend to survival via causal survival forests\n  (`grf::causal_survival_forest`).\n- The [Bayesian Causal Inference chapter](bayesian-causal.qmd) extends\n  to survival via Bayesian additive regression trees for time-to-event\n  outcomes (`BART::surv.bart` for discrete-time survival, or `BART::abart`\n  for an accelerated-failure-time model with right-censoring).\n\n## Summary\n\n- Survival outcomes require methods that handle censoring.\n- Cox models are familiar, but hazard ratios are hard to interpret causally.\n- RMST differences are often the clearest causal summary.\n- IPCW handles informative censoring.\n- `riskRegression::ate` reports g-formula, IPTW, and AIPTW estimates for\n  survival probabilities.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}