{
  "hash": "2473d0e65664b525df11ad0f27927a69",
  "result": {
    "engine": "knitr",
    "markdown": "# DAGs, ADMGs, Identification, and Estimation\n\n\n\nThe potential-outcomes chapter asked when an observed data set can tell us about $E[Y(1)-Y(0)]$. Graphs give one way to state the assumptions behind the answer. A graph records which variables are allowed to cause other variables, and whether some observed variables may share unobserved common causes. Once the graph is stated, identification is a graph problem. Estimation comes after that: estimate the functional that the graph identified.\n\nI use `dagitty` for graphs and backdoor adjustment, `causaleffect` for the general Pearl-Shpitser ID algorithm, and small direct estimators for the examples. The goal is to keep the order clear: graph first, identified functional second, estimator third.\n\n## DAGs and ADMGs\n\nA directed acyclic graph, or DAG, has directed arrows such as `X -> A`. In causal work, an arrow means a direct causal relation is allowed by the model. Absence of an arrow is also a substantive assumption.\n\nAn acyclic directed mixed graph, or ADMG, adds bidirected arrows such as `A <-> Y`. A bidirected edge represents an unobserved common cause. This is useful because many econometric applications have variables we cannot measure: ability, preferences, latent health, firm quality, and so on.\n\nThe graph is not an estimator. It is a compact statement of assumptions. The workflow is:\n\n1. write down a DAG or ADMG;\n2. ask whether the target effect is identified;\n3. estimate the identified functional from data.\n\n## A DAG: Backdoor Adjustment\n\nStart with a simple observational study. `A` is treatment, `Y` is the outcome, and `X` is an observed confounder:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ng_dag <- dagitty(\"dag {\n  X -> A\n  X -> Y\n  A -> Y\n}\")\ncoordinates(g_dag) <- list(\n  x = c(X = 1, A = 0, Y = 2),\n  y = c(X = 1, A = 0, Y = 0)\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggdag(g_dag) + theme_dag_blank()\n```\n\n::: {.cell-output-display}\n![Backdoor DAG: X is an observed confounder of A → Y.](graphs-identification-estimation_files/figure-html/fig-dag-backdoor-1.png){#fig-dag-backdoor width=480}\n:::\n:::\n\n\nThe graph says `X` affects both treatment and outcome. It also says there is no unobserved common cause between `A` and `Y` after we condition on `X`. In this case the treatment effect is identifiable by **backdoor adjustment**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadj_sets <- adjustmentSets(g_dag, exposure = \"A\", outcome = \"Y\")\nadj_sets\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{ X }\n```\n\n\n:::\n:::\n\n\nThe adjustment set is $\\{X\\}$. Under this graph,\n\n$$\nE[Y(a)] = E_X\\{E(Y \\mid A=a, X)\\}.\n$$ {#eq-graphs-identification-estimation-1}\n\nSo the graph has translated a causal query into an observed-data functional.\n\n## Estimating the DAG Effect with AIPW\n\nWe simulate data that match this graph, so we can check whether an estimator\nbuilt from the identified functional recovers an effect we already know.\n\nWe draw $n = 400$ observations. The confounder is $X \\sim N(0,1)$. Treatment is\n$A \\sim \\text{Bernoulli}(\\Lambda(-0.2 + 0.8X))$, with $\\Lambda$ the logistic\nfunction, so a higher $X$ makes treatment more likely. The outcome is\n$Y = 1 + 1.5A + 0.7X + 0.3\\varepsilon$ with $\\varepsilon \\sim N(0,1)$. The\neffect is constant across units, so the ATE is 1.5.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\n\nlogistic <- function(x) 1 / (1 + exp(-x))\n\nn  <- 400\nX  <- rnorm(n)\npA <- logistic(-0.2 + 0.8 * X)\nA  <- as.numeric(runif(n) < pA)\nY  <- 1 + 1.5 * A + 0.7 * X + 0.3 * rnorm(n)\n\ndf_dag <- data.frame(X = X, A = A, Y = Y)\nhead(df_dag)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            X A          Y\n1  0.52058907 0  1.6530538\n2 -1.07969076 0  0.1907760\n3  0.13923812 0  1.0984536\n4 -0.08474878 0  1.0941604\n5 -0.66663962 1  1.8965341\n6 -2.51608903 0 -0.8245336\n```\n\n\n:::\n:::\n\n\nThe analyst sees only $X$, $A$ and $Y$. Because $X$ raises both the chance of\ntreatment and the outcome, a raw contrast of $Y$ by $A$ overstates the effect.\n\nBecause the graph is backdoor-identified, use AIPW with the adjustment set the graph chose. The function below implements the AIPW point estimate and an EIF-based standard error.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naipw_backdoor <- function(data, treatment, outcome, adjust) {\n  fmla_y <- as.formula(paste0(outcome, \" ~ \", treatment, \" * (\",\n                              paste(adjust, collapse = \" + \"), \")\"))\n  fmla_a <- as.formula(paste0(treatment, \" ~ \",\n                              paste(adjust, collapse = \" + \")))\n\n  mu_fit <- lm(fmla_y, data = data)\n  pi_fit <- glm(fmla_a, data = data, family = binomial())\n\n  d1 <- data; d1[[treatment]] <- 1\n  d0 <- data; d0[[treatment]] <- 0\n  mu1 <- predict(mu_fit, newdata = d1)\n  mu0 <- predict(mu_fit, newdata = d0)\n  pi1 <- predict(pi_fit, newdata = data, type = \"response\")\n\n  w  <- data[[treatment]]; y <- data[[outcome]]\n  if1 <- w     * (y - mu1) / pi1       + mu1\n  if0 <- (1-w) * (y - mu0) / (1 - pi1) + mu0\n  psi  <- if1 - if0\n\n  est  <- mean(psi)\n  se   <- sd(psi) / sqrt(length(psi))\n  ci   <- est + c(-1, 1) * qnorm(0.975) * se\n  data.frame(estimand = \"Backdoor ACE\",\n             estimate = round(est, 4),\n             lower_95 = round(ci[1], 4),\n             upper_95 = round(ci[2], 4),\n             se       = round(se, 4))\n}\n\naipw_backdoor(df_dag, \"A\", \"Y\", adjust = \"X\") |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|estimand     | estimate| lower_95| upper_95|     se|\n|:------------|--------:|--------:|--------:|------:|\n|Backdoor ACE |   1.4886|    1.427|   1.5502| 0.0314|\n\n\n:::\n:::\n\n\nAIPW returns 1.4886 with an influence-function standard error of 0.0314, and\nthe 95% interval $[1.427, 1.550]$ covers the true ACE of 1.5. The graph chose\nthe adjustment set and the estimator used that set.\n\n::: {.callout-note}\nThe standard error here, `sd(psi) / sqrt(n)`, is the influence-function\nstandard error of the AIPW estimator. It is asymptotically valid when\nthe nuisance functions ($\\mu$ and $\\pi$) are regular parametric fits,\nas they are here. With flexible machine-learning nuisances it is **not**\nvalid as written: you then need cross-fitting (sample splitting) so the\nnuisance estimates are independent of the fold being evaluated, and the\nvariance should still be computed from the efficient influence function\n(or by bootstrap). Treating a full-sample ML AIPW estimate with this\nplug-in SE will generally understate uncertainty.\n:::\n\n## An ADMG: Front-Door Identification\n\nNow suppose treatment and outcome share an unobserved common cause. A simple adjustment argument no longer works. The front-door ADMG has a mediator `M` that transmits the effect of `A` to `Y`, while `A` and `Y` are hidden-confounded:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ng_fd <- dagitty(\"dag {\n  A -> M\n  M -> Y\n  A <-> Y\n}\")\ncoordinates(g_fd) <- list(\n  x = c(A = 0, M = 1, Y = 2),\n  y = c(A = 0, M = 0, Y = 0)\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggdag(g_fd) + theme_dag_blank()\n```\n\n::: {.cell-output-display}\n![Front-door ADMG: A and Y share an unobserved common cause (curved bidirected edge), but the effect propagates through the mediator M.](graphs-identification-estimation_files/figure-html/fig-front-door-1.png){#fig-front-door width=480}\n:::\n:::\n\n\nThe bidirected edge `A <-> Y` means that ordinary backdoor adjustment is not available. Indeed `dagitty` reports no adjustment set:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsets_fd <- adjustmentSets(g_fd, exposure = \"A\", outcome = \"Y\")\n# An empty dagitty adjustment-set list prints nothing at all, which is easy to\n# mistake for a chunk that failed to run. Report the count explicitly.\ncat(\"Valid backdoor adjustment sets:\", length(sets_fd), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nValid backdoor adjustment sets: 0 \n```\n\n\n:::\n:::\n\n\nThere are none. No set of observed variables blocks the confounding, because\nthe confounder is not observed.\n\nBut the effect is still identified by the front-door criterion (Pearl, 1995). I call the Pearl-Shpitser ID algorithm in `causaleffect` to obtain the symbolic expression. The function wants the graph as an `igraph` object with bidirected edges encoded as two directed edges marked `description = \"U\"`. It returns the expression as a LaTeX string, so the printed line below is LaTeX source, not a typeset formula:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ng_fd_ig <- graph_from_literal(A -+ M, M -+ Y, A -+ Y, Y -+ A)\n# Mark the A<->Y bidirected edge (encoded as the two directed edges A->Y and\n# Y->A) by endpoint name rather than by hardcoded edge index -- igraph's\n# internal edge ordering after graph_from_literal() is not part of its\n# documented contract, so indices like c(2, 4) can silently point at the\n# wrong edges if igraph's internals, the vertex/edge creation order, or the\n# package version ever changes.\nedge_ends <- ends(g_fd_ig, E(g_fd_ig))\nconfounded <- (edge_ends[, 1] == \"A\" & edge_ends[, 2] == \"Y\") |\n              (edge_ends[, 1] == \"Y\" & edge_ends[, 2] == \"A\")\nE(g_fd_ig)$description[confounded] <- \"U\"\nexpr_fd <- causal.effect(y = \"Y\", x = \"A\", G = g_fd_ig, simp = TRUE)\ncat(expr_fd, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\\sum_{M}P(M|A)\\left(\\sum_{A}P(Y|A,M)P(A)\\right) \n```\n\n\n:::\n:::\n\n\nThe expression $\\sum_M P(M\\mid A)\\sum_{A'} P(Y\\mid A', M) P(A')$ is precisely the front-door formula.\n\n## Estimating the ADMG Effect with the Front-Door Formula\n\nWe simulate a front-door setting so we can compare the front-door estimate\nagainst a truth we derive below.\n\nWe draw $n = 400$ observations. The latent confounder is $U \\sim N(0,1)$.\nTreatment is $A \\sim \\text{Bernoulli}(\\Lambda(-0.1 + 0.8U))$, the mediator is\n$M \\sim \\text{Bernoulli}(\\Lambda(-0.4 + 1.2A))$, and the outcome is\n$Y \\sim \\text{Bernoulli}(\\Lambda(-1.0 + 0.9M + 0.7U))$. All three observed\nvariables are binary. $U$ is not in the observed data; it is what the\nbidirected edge `A <-> Y` stands for. Two features make the front-door\ncriterion apply: $U$ enters $A$ and $Y$ but not $M$, and $A$ reaches $Y$ only\nthrough $M$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2027)\n\nn     <- 400\nU     <- rnorm(n)\nA_fd  <- as.numeric(runif(n) < logistic(-0.1 + 0.8 * U))\nM     <- as.numeric(runif(n) < logistic(-0.4 + 1.2 * A_fd))\nY_fd  <- as.numeric(runif(n) < logistic(-1.0 + 0.9 * M + 0.7 * U))\n\ndf_fd <- data.frame(A = A_fd, M = M, Y = Y_fd)\nhead(df_fd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  A M Y\n1 0 0 0\n2 0 1 1\n3 1 1 1\n4 1 1 1\n5 0 1 1\n6 1 0 0\n```\n\n\n:::\n:::\n\n\nThe front-door point estimator is a direct evaluation of the identification expression:\n\n$$\nE[Y(a)] = \\sum_m P(M=m\\mid A=a)\\sum_{a'} P(Y=1\\mid A=a', M=m) P(A=a').\n$$ {#eq-graphs-identification-estimation-2}\n\nThe DGP has a known truth. Under $do(A=a)$ the mediator is\n$M \\sim \\text{Bern}(\\Lambda(-0.4 + 1.2a))$ while $U$ keeps its marginal $N(0,1)$\ndistribution, so\n\n$$\n\\tau = \\big[\\Lambda(0.8) - \\Lambda(-0.4)\\big]\\;\n       \\big[g(-0.1) - g(-1.0)\\big], \\qquad\ng(c) = E_U\\big[\\Lambda(c + 0.7U)\\big],\n$$ {#eq-graphs-identification-estimation-3}\n\nwhich evaluates to $0.2887 \\times 0.1894 = 0.0547$. The naive contrast\n$E[Y\\mid A=1]-E[Y\\mid A=0]$ equals $0.158$ in the population this DGP defines --- almost three times the\ncausal effect, because $U$ raises both the chance of treatment and the outcome.\nThat gap is what the front-door step removes. The table below reports the\nsample version of the naive contrast alongside the front-door estimate.\n\nFor binary $A$, $M$, $Y$ we plug sample proportions into that formula, and take\nthe standard error from 500 bootstrap resamples:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfront_door_ace <- function(data) {\n  pA <- mean(data$A)\n  p_marginal_A <- c(\"0\" = 1 - pA, \"1\" = pA)\n\n  # P(M | A): rows indexed by A, columns by M\n  pM_given_A <- prop.table(table(data$A, data$M), margin = 1)\n  # P(Y=1 | A, M)\n  pY_given_AM <- with(data, tapply(Y, list(A, M), mean))\n\n  # E[Y(a)] for a in {0, 1}\n  ey_do <- function(a) {\n    m_levels <- as.numeric(colnames(pM_given_A))\n    sum(sapply(m_levels, function(m) {\n      mar <- pM_given_A[as.character(a), as.character(m)]\n      inner <- sum(sapply(c(0, 1), function(ap)\n        pY_given_AM[as.character(ap), as.character(m)] *\n          p_marginal_A[as.character(ap)]))\n      mar * inner\n    }))\n  }\n  ey_do(1) - ey_do(0)\n}\n\n# Bootstrap for SE\nset.seed(99)\nB   <- 500\nboot_ace <- replicate(B, {\n  idx <- sample.int(nrow(df_fd), replace = TRUE)\n  front_door_ace(df_fd[idx, ])\n})\n\nest_fd <- front_door_ace(df_fd)\nse_fd  <- sd(boot_ace)\nci_fd  <- est_fd + c(-1, 1) * qnorm(0.975) * se_fd\n\nnaive_fd <- mean(df_fd$Y[df_fd$A == 1]) - mean(df_fd$Y[df_fd$A == 0])\n\ndata.frame(estimand = c(\"Naive E[Y|A=1] - E[Y|A=0]\", \"Front-door ACE\", \"Truth\"),\n           estimate = round(c(naive_fd, est_fd, 0.0547), 4),\n           lower_95 = c(NA, round(ci_fd[1], 4), NA),\n           upper_95 = c(NA, round(ci_fd[2], 4), NA),\n           se       = c(NA, round(se_fd, 4), NA)) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|estimand                            | estimate| lower_95| upper_95|     se|\n|:-----------------------------------|--------:|--------:|--------:|------:|\n|Naive E[Y&#124;A=1] - E[Y&#124;A=0] |   0.1395|       NA|       NA|     NA|\n|Front-door ACE                      |   0.0775|   0.0403|   0.1146| 0.0189|\n|Truth                               |   0.0547|       NA|       NA|     NA|\n\n\n:::\n:::\n\n\nThe naive contrast is 0.1395, more than twice the true 0.0547. The front-door\nestimate is 0.0775 with a bootstrap standard error of 0.0189, and its 95%\ninterval $[0.040, 0.115]$ covers the truth. The confounding bias is removed;\nwhat is left is sampling noise, and the interval is wide relative to an effect\nof 0.05 because the formula estimates seven proportions from 400 binary\nobservations: $P(A=1)$, the two mediator probabilities $P(M=1 \\mid A=a)$, and\nthe four outcome probabilities $P(Y=1 \\mid A=a, M=m)$.\n\n## General ID Algorithm\n\nBackdoor adjustment and the front-door formula are useful because they are easy to estimate. ADMGs can be more general. The Pearl-Shpitser ID algorithm asks the broader question:\n\n```text\nCan P(Y | do(A)) be written using only the observed joint law P(V)?\n```\n\nThe algorithm works recursively:\n\n1. remove variables that are not ancestors of the outcome;\n2. add interventions that are irrelevant after graph surgery;\n3. split the remaining graph into bidirected districts;\n4. identify each district as a factor of the observed law, if possible;\n5. return a hedge witness when no such reduction is possible.\n\nFor the front-door graph, the general ID algorithm succeeds and returns the same front-door formula we obtained above. For more complex ADMGs it may yield novel functionals that no named estimator covers — this is where the plug-in approach is essential.\n\n## When the Graph Says No\n\nThe **bow graph** has both a direct causal edge and unobserved confounding between the same two variables:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ng_bow <- dagitty(\"dag {\n  A -> Y\n  A <-> Y\n}\")\ncoordinates(g_bow) <- list(\n  x = c(A = 0, Y = 1),\n  y = c(A = 0, Y = 0)\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggdag(g_bow) + theme_dag_blank()\n```\n\n::: {.cell-output-display}\n![Bow ADMG: a direct edge A → Y plus a bidirected A ↔ Y. The effect is not identified.](graphs-identification-estimation_files/figure-html/fig-bow-1.png){#fig-bow width=384}\n:::\n:::\n\n\nThe effect of `A` on `Y` is not identified in this ADMG. The observed association mixes the direct causal effect with the latent common cause.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ng_bow_ig <- graph_from_literal(A -+ Y, Y -+ A)\ng_bow_ig <- set_edge_attr(g_bow_ig, \"description\",\n                          index = c(1, 2), value = \"U\")\ng_bow_ig <- add_edges(g_bow_ig, c(\"A\", \"Y\"))   # add the direct A -> Y\n\nresult <- tryCatch(\n  causal.effect(y = \"Y\", x = \"A\", G = g_bow_ig, simp = TRUE),\n  error = function(e) paste(\"Not identifiable:\", conditionMessage(e))\n)\nresult\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Not identifiable: Not identifiable.\"\n```\n\n\n:::\n:::\n\n\n`causaleffect` raises an error message indicating the effect is not identifiable.\n\n## Practical Workflow\n\nFor applied work, a useful workflow is:\n\n1. write the graph before looking at estimates;\n2. use bidirected edges for latent common causes;\n3. ask `dagitty::adjustmentSets(graph, exposure, outcome)` — if non-empty, you have a backdoor route;\n4. if no adjustment set exists, call `causaleffect::causal.effect(y, x, G)` — if it returns an expression, the effect is identified by a more general route; if it errors, the effect is not identified in this ADMG;\n5. estimate using AIPW for backdoor effects, the front-door formula when the algorithm returns that pattern, or a plug-in evaluation of the symbolic expression for general ID functionals;\n6. report the graph and the identification route along with the estimate.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}