{
  "hash": "feafc6fc1d7788cc55159448dff43bbe",
  "result": {
    "engine": "knitr",
    "markdown": "# Applied Graph Workflow: Smoking Cessation\n\n\n\nThe previous chapter used small graph examples. Here I apply the same graph-identification-estimation workflow to a real data set: the complete-case National Health and Nutrition Examination Survey I Epidemiologic Follow-up Study (NHEFS) data distributed through the `causaldata` package.\n\nThe question is:\n\n```text\nWhat is the effect of quitting smoking on weight change from 1971 to 1982?\n```\n\nThe treatment is `qsmk`, an indicator for quitting smoking between baseline and follow-up. The outcome is `wt82_71`, weight change over the follow-up period. This is observational data. The effect is not identified by the data alone. It is identified only after we state the adjustment assumptions in the graph.\n\n## Data\n\nWe keep the treatment `qsmk`, the outcome `wt82_71` (weight change in kg), and\nthe nine baseline covariates commonly used in NHEFS smoking-cessation examples:\n`sex`, `race`, `age`, `school` (years of schooling), `smokeintensity`\n(cigarettes per day in 1971), `smokeyrs` (years of smoking), `exercise` and\n`active` (ordinal activity codes), and `wt71` (baseline weight in kg). All are\nmeasured at baseline, before quitting.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnhefs_cols <- c(\n  \"qsmk\", \"wt82_71\",\n  \"sex\", \"race\", \"age\", \"school\",\n  \"smokeintensity\", \"smokeyrs\",\n  \"exercise\", \"active\", \"wt71\"\n)\nnhefs <- causaldata::nhefs_complete |>\n  dplyr::select(all_of(nhefs_cols)) |>\n  dplyr::mutate(across(everything(), as.numeric))\n\nc(n = nrow(nhefs), variables = ncol(nhefs))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        n variables \n     1566        11 \n```\n\n\n:::\n:::\n\n\nThe complete-case sample has 1,566 people and these 11 columns. The first five\nrows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(nhefs, 5) |>\n  dplyr::mutate(across(everything(), \\(x) signif(x, 4))) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| qsmk| wt82_71| sex| race| age| school| smokeintensity| smokeyrs| exercise| active|  wt71|\n|----:|-------:|---:|----:|---:|------:|--------------:|--------:|--------:|------:|-----:|\n|    0| -10.090|   1|    2|  42|      7|             30|       29|        3|      1| 79.04|\n|    0|   2.605|   1|    1|  36|      9|             20|       24|        1|      1| 58.63|\n|    0|   9.414|   2|    2|  56|     11|             20|       26|        3|      1| 56.81|\n|    0|   4.990|   1|    2|  68|      5|              3|       53|        3|      2| 59.42|\n|    0|   4.989|   1|    1|  40|     11|             20|       19|        2|      2| 87.09|\n\n\n:::\n:::\n\n\nWeight change is already in kilograms and can be negative, so the estimand is\nin kilograms too.\n\n## Adjustment DAG\n\nStart with the grouped graph\n\n```text\nX -> A -> Y\nX -----> Y\n```\n\nwhere `X` is the baseline covariate set, `A` is quitting smoking, and `Y` is later weight change. This graph says the baseline variables may affect both quitting and later weight change, and that there is no unmeasured common cause of quitting and later weight change after conditioning on those baseline variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconceptual_graph <- dagitty(\"dag {\n  X -> A\n  X -> Y\n  A -> Y\n}\")\ncoordinates(conceptual_graph) <- list(\n  x = c(X = 1, A = 0, Y = 2),\n  y = c(X = 1, A = 0, Y = 0)\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggdag(conceptual_graph) + theme_dag_blank()\n```\n\n::: {.cell-output-display}\n![Conceptual adjustment DAG: baseline X confounds A → Y.](smoking-cessation-graphs_files/figure-html/fig-conceptual-1.png){#fig-conceptual width=480}\n:::\n:::\n\n\nFor estimation, expand `X` into the observed NHEFS columns. The expanded graph is still an adjustment DAG: each baseline variable is allowed to point into quitting and into later weight change. We build it and count what it contains.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbaseline_vars <- setdiff(nhefs_cols, c(\"qsmk\", \"wt82_71\"))\n\nbuild_grouped_graph <- function(baseline) {\n  edges_X_to_A <- paste0(baseline, \" -> qsmk\")\n  edges_X_to_Y <- paste0(baseline, \" -> wt82_71\")\n  body <- paste(c(edges_X_to_A, edges_X_to_Y, \"qsmk -> wt82_71\"),\n                collapse = \"\\n  \")\n  dagitty(paste0(\"dag {\\n  \", body, \"\\n}\"))\n}\n\nnhefs_graph <- build_grouped_graph(baseline_vars)\nc(vertices = length(names(nhefs_graph)),\n  directed_edges = length(edges(nhefs_graph)$v))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      vertices directed_edges \n            11             19 \n```\n\n\n:::\n:::\n\n\nEleven vertices and 19 directed edges: two out of each of the nine baseline\nvariables, plus `qsmk -> wt82_71`.\n\n## Identification\n\n`dagitty::adjustmentSets` checks the graph before estimation. In this adjustment DAG, the minimal sufficient adjustment set is the full baseline:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadj_sets <- adjustmentSets(nhefs_graph, exposure = \"qsmk\",\n                           outcome = \"wt82_71\", type = \"minimal\")\nadj_sets\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{ active, age, exercise, race, school, sex, smokeintensity, smokeyrs,\n  wt71 }\n```\n\n\n:::\n:::\n\n\nThe graph therefore identifies the causal mean by the adjustment formula\n\n$$\nE[Y(a)] = E_X\\{E(Y \\mid A=a, X)\\}.\n$$ {#eq-smoking-cessation-graphs-1}\n\nThis formula is not a modeling claim by itself. It is the observed-data functional implied by the graph. Estimation still requires nuisance models for the outcome regression and treatment mechanism.\n\n## Estimation with AIPW\n\nThe book keeps identification and estimation as separate steps. The graph supplies the adjustment set; the estimator uses that set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naipw_backdoor <- function(data, treatment, outcome, adjust) {\n  fmla_y <- as.formula(paste0(outcome, \" ~ \", treatment, \" * (\",\n                              paste(adjust, collapse = \" + \"), \")\"))\n  fmla_a <- as.formula(paste0(treatment, \" ~ \",\n                              paste(adjust, collapse = \" + \")))\n\n  mu_fit <- lm(fmla_y, data = data)\n  pi_fit <- glm(fmla_a, data = data, family = binomial())\n\n  d1 <- data; d1[[treatment]] <- 1\n  d0 <- data; d0[[treatment]] <- 0\n  mu1 <- predict(mu_fit, newdata = d1)\n  mu0 <- predict(mu_fit, newdata = d0)\n  pi1 <- predict(pi_fit, newdata = data, type = \"response\")\n  # Truncate (winsorize) the propensity score away from 0/1. AIPW divides by\n  # pi1 and (1-pi1), so an estimated propensity near the boundary produces\n  # huge inverse-probability weights and blows up the estimator's variance.\n  # Bounding at [0.01, 0.99] trades a small amount of bias (we no longer use\n  # the true estimated propensity for the most extreme units) for much\n  # lower variance -- a standard and usually favorable trade-off, but worth\n  # flagging explicitly since it is a bias-variance choice, not a free lunch.\n  pi1 <- pmin(pmax(pi1, 0.01), 0.99)\n\n  w  <- data[[treatment]]; y <- data[[outcome]]\n  if1 <- w     * (y - mu1) / pi1       + mu1\n  if0 <- (1-w) * (y - mu0) / (1 - pi1) + mu0\n  psi  <- if1 - if0\n\n  est <- mean(psi); se <- sd(psi) / sqrt(length(psi))\n  ci  <- est + c(-1, 1) * qnorm(0.975) * se\n  data.frame(estimand = \"Quit smoking vs continued smoking\",\n             estimate = signif(est, 4),\n             lower_95 = signif(ci[1], 4),\n             upper_95 = signif(ci[2], 4),\n             se       = signif(se, 4))\n}\n\naipw_backdoor(nhefs, \"qsmk\", \"wt82_71\", adjust = baseline_vars) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|estimand                          | estimate| lower_95| upper_95|     se|\n|:---------------------------------|--------:|--------:|--------:|------:|\n|Quit smoking vs continued smoking |    3.293|    2.317|    4.269| 0.4981|\n\n\n:::\n:::\n\n\nQuitters gain 3.29 kg more than continuing smokers, with a standard error of\n0.50 and a 95% interval of $[2.32, 4.27]$. Under the DAG this is the average\neffect of quitting versus continuing on weight change in the complete-case\nNHEFS population. The causal interpretation depends on the graph, especially\nthe assumption that the measured baseline variables block the relevant backdoor\npaths.\n\nThe `sd(psi) / sqrt(n)` standard error is the AIPW influence-function\nSE and is valid here because the nuisances are parametric logistic/linear\nfits. If you replace them with flexible machine learners, use\ncross-fitting and an influence-function (or bootstrap) variance instead;\nthe plug-in SE on full-sample ML fits is not generally valid.\n\n## Sensitivity Graph\n\nNow encode a different assumption: quitting and later weight change share an unobserved common cause even after conditioning on the measured baseline variables. In an ADMG this is a bidirected edge, `qsmk <-> wt82_71`. We rebuild the same graph with that one edge added and count the sufficient adjustment sets it admits.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbuild_sensitivity_graph <- function(baseline) {\n  edges_X_to_A <- paste0(baseline, \" -> qsmk\")\n  edges_X_to_Y <- paste0(baseline, \" -> wt82_71\")\n  body <- paste(c(edges_X_to_A, edges_X_to_Y,\n                  \"qsmk -> wt82_71\", \"qsmk <-> wt82_71\"),\n                collapse = \"\\n  \")\n  dagitty(paste0(\"dag {\\n  \", body, \"\\n}\"))\n}\n\nsensitivity_graph <- build_sensitivity_graph(baseline_vars)\nsens_adj <- adjustmentSets(sensitivity_graph, exposure = \"qsmk\",\n                           outcome = \"wt82_71\", type = \"minimal\")\ncat(\"Number of sufficient adjustment sets:\", length(sens_adj), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of sufficient adjustment sets: 0 \n```\n\n\n:::\n:::\n\n\nThe count is zero. One edge changes the identifying conclusion: under this graph the observed NHEFS variables are not enough to identify the effect, and no adjustment set exists. The data are the same as in the previous section, and the 3.29 kg is still computable, but nothing licenses reading it as a causal effect. This is why the graph has to come before the estimator.\n\n## Structured Baseline Graph\n\nThe simple adjustment graph is often the clearest starting point. A more detailed DAG can record baseline ordering: demographics may precede education, smoking history, activity, and baseline weight; those variables may then affect quitting and later weight change. We write that graph out, ask for its minimal adjustment set, and check whether the set equals the full baseline we used before.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstructured_graph <- dagitty(\"dag {\n  age -> school\n  age -> smokeyrs\n  age -> wt71\n  age -> active\n  age -> exercise\n  age -> qsmk\n  age -> wt82_71\n\n  sex -> smokeintensity\n  sex -> smokeyrs\n  sex -> wt71\n  sex -> qsmk\n  sex -> wt82_71\n\n  race -> school\n  race -> smokeintensity\n  race -> qsmk\n  race -> wt82_71\n\n  school -> smokeintensity\n  school -> qsmk\n  school -> wt82_71\n\n  smokeyrs -> smokeintensity\n  smokeyrs -> qsmk\n  smokeyrs -> wt82_71\n\n  smokeintensity -> qsmk\n  smokeintensity -> wt82_71\n\n  exercise -> wt71\n  exercise -> qsmk\n  exercise -> wt82_71\n\n  active -> wt71\n  active -> qsmk\n  active -> wt82_71\n\n  wt71 -> qsmk\n  wt71 -> wt82_71\n\n  qsmk -> wt82_71\n}\")\n\nstruct_adj <- adjustmentSets(structured_graph, exposure = \"qsmk\",\n                             outcome = \"wt82_71\", type = \"minimal\")\nstruct_adj\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{ active, age, exercise, race, school, sex, smokeintensity, smokeyrs,\n  wt71 }\n```\n\n\n:::\n\n```{.r .cell-code}\ndata.frame(\n  matches_full_baseline = setequal(unlist(struct_adj[[1]]), baseline_vars)\n) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|matches_full_baseline |\n|:---------------------|\n|TRUE                  |\n\n\n:::\n:::\n\n\nThe check returns `TRUE`. For this treatment effect the detailed baseline DAG is adjustment-equivalent to the simpler expanded DAG: same sufficient adjustment set, same identifying functional, and therefore the same 3.29 kg estimate. The extra arrows among baseline variables may be useful for documentation, but they are also extra causal assumptions. If those assumptions are not needed for the estimand, the grouped adjustment graph is usually easier to defend.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}