{
  "hash": "c6f593c224b43c8cde96431cc39cc055",
  "result": {
    "engine": "knitr",
    "markdown": "# Heterogeneous Treatment Effects with Machine Learning\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(grf)\nlibrary(policytree)\nlibrary(ggplot2)\n```\n:::\n\n\nThe [estimands chapter](causal-estimands.qmd) defined the conditional average\ntreatment effect\n\n$$\n\\text{CATE}(x) = \\mathbb{E}[Y(1) - Y(0) \\mid X = x]\n$$ {#eq-heterogeneous-effects-1}\n\nas the effect of treatment for units with covariates $X=x$. In the\nsimulation we could compute it from known potential outcomes. In real data\nwe do not observe both $Y(0)$ and $Y(1)$, so CATE has to be estimated from\n$(X,D,Y)$.\n\nI use four kinds of tools:\n\n- **Meta-learners**: S-, T-, X-, R-, and DR-learners.\n- **Causal forests**: random forests designed for CATE estimation.\n- **BLP and CLAN**: simple summaries and tests of heterogeneity.\n- **Policy trees**: rules for deciding who should be treated.\n\n## The data-generating process\n\nWe simulate $n = 5000$ units with five covariates, each drawn independently\nfrom $U(0,1)$. Treatment is $D \\sim \\text{Bernoulli}(\\Lambda(-0.3 + 1.5X_2))$.\nThe CATE function is the one from the estimands chapter, $\\tau(x) = 1 + 2x_1$.\nThe potential outcomes are $Y(0) = 0.5X_2 + \\varepsilon$ with\n$\\varepsilon \\sim N(0,1)$ and $Y(1) = Y(0) + \\tau(X)$, and we observe\n$Y = DY(1) + (1-D)Y(0)$.\n\nTwo covariates do the work and three are irrelevant. $X_1$ modifies the effect but\nhas nothing to do with selection. $X_2$ drives both treatment and the outcome,\nso it is a backdoor confounder, and it is observed. $X_3$, $X_4$ and $X_5$ enter\nneither equation. The population ATE is $\\int_0^1 (1+2x)\\,dx = 2$.\n\nThe aim is to hand six estimators the same data and see which recover\n$\\tau(x)$, judged by the correlation between estimated and true individual\neffects.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\nn <- 5000\np <- 5      # 5 covariates: only X1 is the effect modifier; X2..X5 are noise\n\nX <- matrix(runif(n * p), n, p)\ncolnames(X) <- paste0(\"X\", 1:p)\n# Treatment depends on the OBSERVED covariate X2 (a backdoor confounder we\n# adjust for), so unconfoundedness given X holds and the estimators are\n# consistent for the true ATE/CATE.\nps  <- plogis(-0.3 + 1.5 * X[, 2])\nD   <- rbinom(n, 1, ps)\ntau <- 1 + 2 * X[, 1]          # CATE varies along X1 only\nY0  <- 0.5 * X[, 2] + rnorm(n)\nY1  <- Y0 + tau\nY   <- ifelse(D == 1, Y1, Y0)\n\ncat(sprintf(\"n = %d, true ATE = %.3f\\n\", n, mean(tau)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn = 5000, true ATE = 2.006\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"True CATE at X1 = 0.2: %.2f\\n\", 1 + 2 * 0.2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue CATE at X1 = 0.2: 1.40\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"True CATE at X1 = 0.8: %.2f\\n\", 1 + 2 * 0.8))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue CATE at X1 = 0.8: 2.60\n```\n\n\n:::\n:::\n\n\nThe realized ATE in this draw is 2.006 against a population value of 2, and the\ntrue CATE runs from 1.40 at $X_1 = 0.2$ to 2.60 at $X_1 = 0.8$. Because $X_2$ is\nobserved and every estimator below conditions on it, unconfoundedness holds and\nall of them are consistent for the true CATE and ATE. Any differences we see\nare finite-sample behaviour, not bias from a missing variable.\n\n## Meta-learners\n\nA meta-learner is a recipe that turns a regression method into a CATE\nestimator. The regression method can be a random forest, boosting, neural\nnetwork, or a simple linear model.\n\n### S-learner (\"single\")\n\nFit one regression of $Y$ on $(D, X)$, then predict the difference between\n$D=1$ and $D=0$ at each $x$:\n\n$$\n\\hat\\tau^S(x) = \\hat\\mu(1, x) - \\hat\\mu(0, x).\n$$ {#eq-heterogeneous-effects-2}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use a flexible learner — random forest from grf::regression_forest\nXD_train <- cbind(D = D, X)\nfit_S <- regression_forest(XD_train, Y, num.trees = 500)\n\n# Counterfactual predictions at D = 1 and D = 0 for every X\nmu1 <- predict(fit_S, cbind(D = rep(1, n), X))$predictions\nmu0 <- predict(fit_S, cbind(D = rep(0, n), X))$predictions\ntau_S <- mu1 - mu0\n\ncor_S <- cor(tau_S, tau)\ncat(sprintf(\"S-learner CATE correlation with truth: %.3f\\n\", cor_S))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nS-learner CATE correlation with truth: 0.970\n```\n\n\n:::\n:::\n\n\nThe S-learner's estimates correlate 0.970 with the true individual effects. It\nis simple, and its weakness is that the model may treat $D$ as a minor\npredictor of $Y$ and shrink the treatment effect toward zero.\n\n### T-learner (\"two\")\n\nFit two separate regressions: $\\hat\\mu_1$ on treated units, $\\hat\\mu_0$ on\ncontrols. Then $\\hat\\tau^T(x) = \\hat\\mu_1(x) - \\hat\\mu_0(x)$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_T1 <- regression_forest(X[D == 1, ], Y[D == 1], num.trees = 500)\nfit_T0 <- regression_forest(X[D == 0, ], Y[D == 0], num.trees = 500)\n\nmu1_T <- predict(fit_T1, X)$predictions\nmu0_T <- predict(fit_T0, X)$predictions\ntau_T <- mu1_T - mu0_T\n\ncor_T <- cor(tau_T, tau)\ncat(sprintf(\"T-learner CATE correlation with truth: %.3f\\n\", cor_T))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nT-learner CATE correlation with truth: 0.968\n```\n\n\n:::\n:::\n\n\nThe T-learner correlates 0.968, essentially the same as the S-learner. Giving\ntreatment and control separate outcome models can help with heterogeneity, but\nit can also extrapolate badly when the treated and control covariate\ndistributions do not overlap.\n\n### X-learner [@kunzel-2019-metalearners]\n\nThe X-learner starts from the T-learner. It imputes missing potential\noutcomes, creates pseudo-treatment effects, and then smooths those\npseudo-effects as functions of $X$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: T-learner fits (already done above)\n# Step 2: Pseudo-outcomes\nD1_pseudo <- Y[D == 1] - predict(fit_T0, X[D == 1, ])$predictions   # observed - imputed Y(0)\nD0_pseudo <- predict(fit_T1, X[D == 0, ])$predictions - Y[D == 0]   # imputed Y(1) - observed\n\n# Step 3: Regress pseudo-outcomes on X in each arm\nfit_X1 <- regression_forest(X[D == 1, ], D1_pseudo, num.trees = 500)\nfit_X0 <- regression_forest(X[D == 0, ], D0_pseudo, num.trees = 500)\n\ntau_X1 <- predict(fit_X1, X)$predictions\ntau_X0 <- predict(fit_X0, X)$predictions\n\n# Step 4: Weighted combination — use propensity score as the weight\nps_fit <- regression_forest(X, D, num.trees = 500)\nps_hat <- predict(ps_fit, X)$predictions\nps_hat <- pmin(pmax(ps_hat, 0.02), 0.98)   # trim\n\ntau_X <- ps_hat * tau_X0 + (1 - ps_hat) * tau_X1\n\ncor_X <- cor(tau_X, tau)\ncat(sprintf(\"X-learner CATE correlation with truth: %.3f\\n\", cor_X))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nX-learner CATE correlation with truth: 0.984\n```\n\n\n:::\n:::\n\n\nThe X-learner correlates 0.984, the best of the five meta-learners here. The\nextra smoothing step is what buys the improvement: regressing the pseudo-effects\non $X$ imposes that the effect is a function of the covariates, which is true by\nconstruction in this DGP. The X-learner is also useful when one treatment arm is\nmuch smaller than the other.\n\n### R-learner [@nie-wager-2021]\n\nThe R-learner partials out the main effects of $X$ from both $Y$ and $D$.\nIt then estimates how the residualized treatment predicts the residualized\noutcome:\n\n$$\n\\tilde Y_i = \\frac{Y_i - \\hat m(X_i)}{D_i - \\hat e(X_i)}, \\quad\n\\text{weights} = (D_i - \\hat e(X_i))^2,\n$$ {#eq-heterogeneous-effects-3}\n\nwhere $\\hat m(x) = \\mathbb{E}[Y \\mid X = x]$ and $\\hat e(x) = \\mathbb{E}[D \\mid X = x]$\nare cross-fitted nuisance estimates. Regressing $\\tilde Y$ on $X$ with these\nweights gives the CATE estimate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Cross-fitting: split sample into 2 folds, fit nuisances on one, predict on the other\nset.seed(7)\nfolds <- sample(rep(1:2, length.out = n))\n\nm_hat <- numeric(n)\ne_hat <- numeric(n)\nfor (k in 1:2) {\n  train <- folds != k\n  test  <- folds == k\n  m_fit <- regression_forest(X[train, ], Y[train], num.trees = 500)\n  e_fit <- regression_forest(X[train, ], D[train], num.trees = 500)\n  m_hat[test] <- predict(m_fit, X[test, ])$predictions\n  e_hat[test] <- predict(e_fit, X[test, ])$predictions\n}\ne_hat <- pmin(pmax(e_hat, 0.02), 0.98)\n\n# R-learner pseudo-outcome and weights\npseudo_R <- (Y - m_hat) / (D - e_hat)\nweights_R <- (D - e_hat)^2\n\n# Regress pseudo-outcomes on X with weights — use a regression forest\nfit_R <- regression_forest(X, pseudo_R, sample.weights = weights_R, num.trees = 500)\ntau_R <- predict(fit_R, X)$predictions\n\ncor_R <- cor(tau_R, tau)\ncat(sprintf(\"R-learner CATE correlation with truth: %.3f\\n\", cor_R))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR-learner CATE correlation with truth: 0.930\n```\n\n\n:::\n:::\n\n\nThe R-learner correlates 0.930, the weakest here. Errors in the nuisance models\nhave only second-order effects on the target, which is the theoretical appeal,\nbut the pseudo-outcome divides by $D_i - \\hat e(X_i)$, and that denominator is\nnear zero for any unit whose treatment is well predicted. Those units get\nenormous pseudo-outcomes. The weights $(D_i-\\hat e(X_i))^2$ are designed to\noffset exactly that, and they do so in a weighted least-squares sense, but the\nregression target is still much noisier than the T- or X-learner's.\n\n### DR-learner [@kennedy-2020-optimal-dr]\n\nThe DR-learner uses an AIPW-style pseudo-outcome and then regresses it on\n$X$:\n\n$$\n\\tilde Y_i^{DR} = \\hat\\mu_1(X_i) - \\hat\\mu_0(X_i) +\n\\frac{D_i (Y_i - \\hat\\mu_1(X_i))}{\\hat e(X_i)} -\n\\frac{(1 - D_i) (Y_i - \\hat\\mu_0(X_i))}{1 - \\hat e(X_i)}.\n$$ {#eq-heterogeneous-effects-4}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu1_cf <- numeric(n); mu0_cf <- numeric(n); e_cf <- numeric(n)\nfor (k in 1:2) {\n  train <- folds != k\n  test  <- folds == k\n  mu1_fit <- regression_forest(X[train & D == 1, , drop = FALSE], Y[train & D == 1],\n                               num.trees = 500)\n  mu0_fit <- regression_forest(X[train & D == 0, , drop = FALSE], Y[train & D == 0],\n                               num.trees = 500)\n  e_fit   <- regression_forest(X[train, ], D[train], num.trees = 500)\n  mu1_cf[test] <- predict(mu1_fit, X[test, ])$predictions\n  mu0_cf[test] <- predict(mu0_fit, X[test, ])$predictions\n  e_cf[test]   <- predict(e_fit,   X[test, ])$predictions\n}\ne_cf <- pmin(pmax(e_cf, 0.02), 0.98)\n\npseudo_DR <- (mu1_cf - mu0_cf) +\n             D * (Y - mu1_cf) / e_cf -\n             (1 - D) * (Y - mu0_cf) / (1 - e_cf)\n\nfit_DR <- regression_forest(X, pseudo_DR, num.trees = 500)\ntau_DR <- predict(fit_DR, X)$predictions\n\ncor_DR <- cor(tau_DR, tau)\ncat(sprintf(\"DR-learner CATE correlation with truth: %.3f\\n\", cor_DR))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDR-learner CATE correlation with truth: 0.931\n```\n\n\n:::\n:::\n\n\nThe DR-learner correlates 0.931. Its pseudo-outcome has no random denominator,\nbut it does carry the two inverse-probability terms, and like the R-learner it\ncross-fits on two folds, so each nuisance model is trained on 2,500 observations\nrather than 5,000. Both properties cost accuracy at this sample size. The\ndoubly-robust construction pays off when the nuisance models are wrong, and here\nthey are not.\n\n## Causal forests\n\nCausal forests are random forests built for treatment-effect heterogeneity.\nThey split the data to find treatment-effect differences, not just outcome\ndifferences. The `grf` implementation also uses honest sample splitting for\ninference.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncf <- causal_forest(X = X, Y = Y, W = D, num.trees = 2000)\n\ntau_cf <- predict(cf)$predictions\ncor_cf <- cor(tau_cf, tau)\ncat(sprintf(\"Causal forest CATE correlation with truth: %.3f\\n\", cor_cf))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCausal forest CATE correlation with truth: 0.983\n```\n\n\n:::\n\n```{.r .cell-code}\n# Doubly robust ATE estimate\nate_cf <- average_treatment_effect(cf)\ncat(sprintf(\"\\nCausal forest AIPW ATE: %.3f  (SE = %.3f, true = %.3f)\\n\",\n            ate_cf[\"estimate\"], ate_cf[\"std.err\"], mean(tau)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCausal forest AIPW ATE: 1.994  (SE = 0.031, true = 2.006)\n```\n\n\n:::\n:::\n\n\nThe causal forest correlates 0.983 with the truth, matching the X-learner, and\nits doubly-robust ATE is 1.994 with a standard error of 0.031 against a true\n2.006. Use `predict(cf, estimate.variance = TRUE)` when pointwise confidence\nintervals are needed.\n\n### Comparing all estimators\n\nThe plot puts each estimator's predicted CATE against $X_1$, one panel per\nestimator, with a loess fit through the points and the true $\\tau(x)=1+2x_1$\nas the dashed red line. What to look for is whether the blue curve tracks the\nred line and how tightly the points cluster around it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomparison <- tibble(\n  X1     = X[, 1],\n  true   = tau,\n  S      = tau_S,\n  Tlearn = tau_T,\n  X      = tau_X,\n  R      = tau_R,\n  DR     = tau_DR,\n  CF     = tau_cf\n) |>\n  pivot_longer(cols = c(S, Tlearn, X, R, DR, CF),\n               names_to = \"Estimator\", values_to = \"Predicted\")\n\nggplot(comparison, aes(x = X1, y = Predicted)) +\n  geom_point(alpha = 0.1, size = 0.4) +\n  geom_smooth(method = \"loess\", se = FALSE, colour = \"steelblue\", linewidth = 1) +\n  geom_abline(aes(intercept = 1, slope = 2), linetype = \"dashed\",\n              colour = \"firebrick\") +\n  facet_wrap(~ Estimator, ncol = 3) +\n  labs(x = expression(X[1]),\n       y = \"Estimated CATE\",\n       caption = \"Red dashed line = true τ(x) = 1 + 2*X1\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Estimated CATE vs true τ(x) = 1 + 2*X1 for each estimator. Closer to the dashed line = better.](heterogeneous-effects_files/figure-pdf/compare-plot-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nAll six recover the upward slope. Ranked by correlation with the truth, the\nX-learner (0.984) and the causal forest (0.983) come first, the S- and\nT-learners next (0.970 and 0.968), and the R- and DR-learners last (0.930 and\n0.931). All six are consistent here, so this ranking is about finite-sample\nnoise. It would change under a DGP where the nuisance models are misspecified,\nwhich is the case the doubly-robust constructions are built for.\n\n## Best linear projection (BLP)\n\nEven if CATE is nonlinear, we often want a regression-style summary: which\ncovariates are associated with larger effects? The best linear projection\nof CATE onto $X$ is\n\n$$\n\\text{BLP}(X) = \\arg\\min_{\\beta_0, \\beta} \\mathbb{E}\\left[ (\\tau(X) - \\beta_0 - X'\\beta)^2 \\right],\n$$ {#eq-heterogeneous-effects-5}\n\nwhich `grf` estimates with valid standard errors:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nblp <- best_linear_projection(cf, A = X)\nprint(blp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBest linear projection of the conditional average treatment effect.\nConfidence intervals are cluster- and heteroskedasticity-robust (HC3):\n\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  1.077587   0.119928  8.9853   <2e-16 ***\nX1           2.008322   0.104710 19.1798   <2e-16 ***\nX2          -0.051931   0.106412 -0.4880   0.6256    \nX3          -0.064522   0.102963 -0.6266   0.5309    \nX4           0.044172   0.105384  0.4192   0.6751    \nX5          -0.115495   0.104588 -1.1043   0.2695    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe coefficient on $X_1$ is 2.008 with a standard error of 0.105, against a\ntrue slope of 2. The intercept is 1.078 against a true 1. None of $X_2$ through\n$X_5$ is significant, with coefficients between $-0.115$ and 0.044 and standard\nerrors around 0.105. The projection finds the one effect modifier and correctly\nreports nothing for the other four.\n\n## Variable importance\n\n`grf` also reports variable importance. It is a rough diagnostic for which\nvariables the forest uses to find heterogeneity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvi <- variable_importance(cf)\nvi_df <- tibble(variable = paste0(\"X\", 1:p), importance = as.numeric(vi)) |>\n  arrange(desc(importance))\nprint(vi_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 x 2\n  variable importance\n  <chr>         <dbl>\n1 X1           0.725 \n2 X4           0.0953\n3 X5           0.0703\n4 X3           0.0565\n5 X2           0.0533\n```\n\n\n:::\n:::\n\n\n$X_1$ takes 0.725 of the importance. The other four sit between 0.053 and\n0.095, well below the 0.2 each would receive if the forest split at random.\nThe forest found the effect modifier without being told which one it was.\n\n## Policy trees: who should we treat?\n\nA CATE estimate is not yet a policy. If treatment has a cost, the policy\nquestion is who should be treated. A policy tree turns estimated treatment\neffects into a simple treatment rule.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# double_robust_scores() returns an n x 2 matrix of AIPW scores,\n# one column per action: Gamma_i(control), Gamma_i(treated)\nGamma <- double_robust_scores(cf)\ncost <- 2     # cost of treating one unit, in outcome units\n\n# Net value of each action: control stays as is, treating pays the cost.\n# With tau(x) = 1 + 2*x1 in [1, 3], the optimal rule is: treat iff x1 > 0.5.\nGamma[, \"treated\"] <- Gamma[, \"treated\"] - cost\n\n# Fit a depth-2 policy tree (shallow for interpretability)\ntree <- policy_tree(X, Gamma, depth = 2)\nprint(tree)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npolicy_tree object \nTree depth:  2 \nActions:  1: control 2: treated \nVariable splits: \n(1) split_variable: X1  split_value: 0.626569 \n  (2) split_variable: X1  split_value: 0.42175 \n    (4) * action: 1 \n    (5) * action: 2 \n  (3) split_variable: X1  split_value: 0.644418 \n    (6) * action: 1 \n    (7) * action: 2 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Recommended action for each unit (1 = control, 2 = treated)\nactions <- predict(tree, X)\ncat(sprintf(\"\\nTreatment rate under policy tree: %.1f%% (optimal: %.1f%%)\\n\",\n            mean(actions == 2) * 100, mean(X[, 1] > 0.5) * 100))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTreatment rate under policy tree: 56.5% (optimal: 50.5%)\n```\n\n\n:::\n\n```{.r .cell-code}\n# Value of the learned rule vs treating everyone, both evaluated with\n# the same doubly-robust scores\nwelfare_tree <- mean(ifelse(actions == 2, Gamma[, \"treated\"], Gamma[, \"control\"]))\nwelfare_all  <- mean(Gamma[, \"treated\"])\ncat(sprintf(\"Estimated welfare: policy tree %.3f vs treat-everyone %.3f (gain %.3f)\\n\",\n            welfare_tree, welfare_all, welfare_tree - welfare_all))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEstimated welfare: policy tree 0.525 vs treat-everyone 0.261 (gain 0.264)\n```\n\n\n:::\n:::\n\n\nThe tree splits on $X_1$ at every node, which is the true effect modifier, and\ntreats 56.5% of units against an optimal 50.5%. Its estimated welfare is 0.525\nagainst 0.261 for treating everyone, a gain of 0.264 per unit. The rule beats\ntreat-everyone because with a cost of 2 and $\\tau(x) = 1+2x_1$, units with\n$x_1 < 0.5$ have $\\tau(x) < 2$ and are not worth treating.\n\nThe point of the shallow tree is interpretability. It gives up some\nflexibility in exchange for a rule that can be inspected.\n\nInspect the printed tree rather than summarising it, though, because at depth 2\nboth branches split $X_1$ again: the fitted rule treats $X_1 \\in (0.422, 0.627]$\nand $X_1 > 0.644$, but not the sliver between them. Since $\\tau(x) = 1 + 2x_1$\nis monotone, the optimal rule is a *single* threshold at $x_1 = 0.5$, so that gap\nis estimation noise and not a discovery. The effective lower cut of 0.42 rather\nthan 0.50 is what produces the 56.5% treatment rate against an optimal 50.5%.\nA depth-1 tree is the better-specified model for this DGP, and the practical\nlesson is to fit the shallower tree too: a depth-2 structure should not be read\nas evidence of a genuinely non-monotone rule when a depth-1 tree does as well.\n\nFor an extended walkthrough of policy trees with IPW and AIPW losses,\nsee the [companion blog chapter on `policytree`](https://xiangao.github.io/blog_book/policytree.html).\nFor a comparison of CATE estimators across software ecosystems\n(including Stata 19's new `cate` command), see the\n[Stata CATE blog chapter](https://xiangao.github.io/blog_book/stata-cate.html).\n\n## GATES: sorted group ATEs\n\nGATES (group average treatment effects) is a simple way to report\nheterogeneity [@chernozhukov-2018-generic-ml]. Sort observations by\npredicted CATE, split them into bins, and estimate the ATE in each bin. If\nthe bin ATEs differ, the heterogeneity is not just a graph. (The same\npaper's CLAN — classification analysis — is the natural companion: compare\naverage *covariates* between the most- and least-affected bins; here that\ncomparison would show high $X_1$ in the top quintile and low $X_1$ in the\nbottom one.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sort by predicted CATE, split into 5 quintiles\nnq <- 5\nquintile <- cut(tau_cf, breaks = quantile(tau_cf, probs = seq(0, 1, 1/nq)),\n                include.lowest = TRUE, labels = FALSE)\n\n# Compute AIPW ATE within each quintile\nget_ate <- function(idx) {\n  ate <- average_treatment_effect(cf, subset = idx)\n  c(est = ate[\"estimate\"], se = ate[\"std.err\"])\n}\n\nclan <- t(sapply(1:nq, function(q) get_ate(quintile == q)))\nclan_df <- as_tibble(clan) |>\n  mutate(quintile = 1:nq,\n         lo = est.estimate - 1.96 * se.std.err,\n         hi = est.estimate + 1.96 * se.std.err)\n\nknitr::kable(clan_df[, c(\"quintile\", \"est.estimate\", \"se.std.err\", \"lo\", \"hi\")],\n             col.names = c(\"Quintile\", \"ATE\", \"SE\", \"95% LB\", \"95% UB\"),\n             digits = 3,\n             caption = \"GATES: quintile-specific ATEs sorted by predicted CATE. Heterogeneity is evident if quintile estimates differ.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: GATES: quintile-specific ATEs sorted by predicted CATE. Heterogeneity is evident if quintile estimates differ.\n\n| Quintile|   ATE|    SE| 95% LB| 95% UB|\n|--------:|-----:|-----:|------:|------:|\n|        1| 1.263| 0.070|  1.126|  1.400|\n|        2| 1.517| 0.067|  1.386|  1.649|\n|        3| 2.106| 0.065|  1.979|  2.234|\n|        4| 2.274| 0.068|  2.141|  2.408|\n|        5| 2.810| 0.068|  2.677|  2.943|\n\n\n:::\n:::\n\n\nThe quintile ATEs rise monotonically from 1.263 to 2.810, and the standard\nerrors are all about 0.068, so the top and bottom quintiles are more than\ntwenty standard errors apart. The heterogeneity is not a graphical artefact.\nThe range also sits inside the true $[1, 3]$, as it must, and the quintile\nmeans bracket the ATE of 2. One caveat: the quintiles are formed from the same forest's\n(out-of-bag) predictions used to estimate the group ATEs, which mitigates\nbut does not fully remove the bias from grouping and estimating on the same\ndata; for formal inference use a held-out fold or\n`grf::rank_average_treatment_effect()`.\n\n## Causal forests with panel data\n\nWith panel data, unit effects can be correlated with treatment and\ncovariates. A cross-sectional causal forest can then be biased. Two\npractical fixes are:\n\n1. **Demean by fixed effects** before running the causal forest.\n2. **Pass a `clusters` argument** to `causal_forest` so that observations\n   from the same unit are kept in the same training fold during honest\n   sample-splitting.\n\nTo show what each fix does and does not do, we simulate a panel of 200 firms\nobserved over 5 periods, 1,000 observations in all. Each firm draws a unit\neffect $\\alpha_i \\sim N(0, 1.5^2)$ and a firm-level covariate\n$V_{1,i} \\sim N(0,1)$, and the observed covariate adds within-firm noise,\n$V_{1,it} = V_{1,i} + N(0, 0.3^2)$. Treatment is\n$W_{it} \\sim \\text{Bernoulli}(\\Lambda(0.3 V_{1,i} + 0.5\\alpha_i))$, so the unit\neffect drives treatment. The CATE is $\\tau_{it} = 0.5 + V_{1,it}$, and the\noutcome is $Y_{it} = \\alpha_i + V_{1,it} + \\tau_{it} W_{it} + N(0,1)$.\n\nThe unit effect raises both the treatment probability and the outcome, and the\nforest never sees it. That is textbook fixed-effect confounding. The true ATE\nis 0.566 in this draw.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2024)\nn_firms <- 200\nn_t     <- 5\nn_total <- n_firms * n_t\n\n# Panel data with a unit effect that drives BOTH treatment and the outcome\n# (classic fixed-effect confounding; unit_fe is unobserved to the forest)\nfirm_id  <- rep(1:n_firms, each = n_t)\nunit_fe  <- rnorm(n_firms, sd = 1.5)[firm_id]\nV1_firm  <- rnorm(n_firms, sd = 1.0)[firm_id]   # firm-level covariate\nV1       <- V1_firm + rnorm(n_total, sd = 0.3)  # within-firm variation\nW        <- rbinom(n_total, 1, plogis(0.3 * V1_firm + 0.5 * unit_fe))\n# True CATE varies linearly with V1\ntau_panel <- 0.5 + 1.0 * V1\nY_panel  <- unit_fe + V1 + tau_panel * W + rnorm(n_total)\n\ndf_panel <- tibble(firm = firm_id, V1 = V1, W = W, Y = Y_panel)\nglimpse(df_panel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,000\nColumns: 4\n$ firm <int> 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,~\n$ V1   <dbl> 0.60231981, 0.23871074, 0.05916058, -0.24663844, 0.28957601, -0.1~\n$ W    <int> 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,~\n$ Y    <dbl> 3.99219997, 3.99833174, 1.50594149, 2.51156617, 2.37409880, 0.254~\n```\n\n\n:::\n:::\n\n\nA naive causal forest ignores the firm effects. Because `unit_fe` raises\nboth the treatment probability and the outcome, and is not in $X$, the\nnaive estimate is badly biased upward:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nX_panel <- as.matrix(df_panel[, \"V1\", drop = FALSE])\n\ncf_naive <- causal_forest(X = X_panel, Y = df_panel$Y, W = df_panel$W,\n                          num.trees = 1000)\nate_naive <- average_treatment_effect(cf_naive)\n\ncat(sprintf(\"Naive panel CF ATE: %.3f  (SE = %.3f)\\n\",\n            ate_naive[\"estimate\"], ate_naive[\"std.err\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNaive panel CF ATE: 1.706  (SE = 0.127)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"True ATE: %.3f\\n\", mean(tau_panel)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue ATE: 0.566\n```\n\n\n:::\n:::\n\n\nThe naive forest returns 1.706 with a standard error of 0.127 against a true\n0.566. It is off by three times the truth, and about nine standard errors away.\n\nAdding `clusters = firm` keeps a firm's observations together when `grf`\ndoes the honest sample split. Note what this does and does not do: it makes\nthe honest splitting and the standard errors respect the panel structure,\nbut it does *not* remove the unobserved-unit-effect confounding — the\nestimate stays close to the naive one:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncf_clust <- causal_forest(X = X_panel, Y = df_panel$Y, W = df_panel$W,\n                          clusters = df_panel$firm,\n                          num.trees = 1000)\nate_clust <- average_treatment_effect(cf_clust)\n\ncat(sprintf(\"Clustered panel CF ATE: %.3f  (SE = %.3f)\\n\",\n            ate_clust[\"estimate\"], ate_clust[\"std.err\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nClustered panel CF ATE: 1.741  (SE = 0.163)\n```\n\n\n:::\n:::\n\n\nClustering gives 1.741 with a standard error of 0.163. The estimate moved\nslightly further from the truth, not closer, and the standard error grew. This\nis the point: `clusters=` is about honesty and inference, never about\nconfounding.\n\nWhat removes the confounding is the fixed-effect style adjustment: demean\n$Y$, $W$, and $V_1$ by firm before fitting, which sweeps out `unit_fe`.\nA caveat on interpretation: with a demeaned binary treatment $W_{dm}$,\nthe GRF target is *not* generally $\\text{mean}(\\tau_{panel})$. It is a\nwithin-unit, partialled-out contrast whose implicit weighting depends\non the distribution of demeaned treatment values. Read the number\nbelow as a within-firm residualized treatment effect, not as a drop-in\nfixed-effect estimate of the same CATE/ATE target as the cross-sectional\nforest:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_dm <- df_panel |>\n  group_by(firm) |>\n  mutate(Y_dm = Y - mean(Y),\n         W_dm = W - mean(W),\n         V1_dm = V1 - mean(V1)) |>\n  ungroup()\n\ncf_fe <- causal_forest(X = as.matrix(df_dm[, \"V1_dm\"]),\n                       Y = df_dm$Y_dm,\n                       W = df_dm$W_dm,\n                       clusters = df_dm$firm,\n                       num.trees = 1000)\nate_fe <- average_treatment_effect(cf_fe)\ncat(sprintf(\"Within-transform CF ATE: %.3f  (SE = %.3f)\\n\",\n            ate_fe[\"estimate\"], ate_fe[\"std.err\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWithin-transform CF ATE: 0.577  (SE = 0.103)\n```\n\n\n:::\n:::\n\n\nThe within transform gives 0.577 with a standard error of 0.103, against a true\n0.566. Sweeping out the firm means removed the confounding that clustering did\nnot touch.\n\nThe clustered, within-transformed causal forest is a heuristic analogue to a\nfixed-effect regression with heterogeneous effects, but it does not target\nthe same estimand as a textbook within estimator: properly identified\nheterogeneous panel effects need stronger assumptions or a dedicated panel/DML\nconstruction with an orthogonal score.\nSee the [companion blog chapter on causal forests in panel data](https://xiangao.github.io/blog_book/causal-forest-panel.html)\nfor an extended simulation study comparing the panel CF to fixed-effect\nregression and random-effect regression under linear and nonlinear DGPs.\n\n## Summary\n\n- Meta-learners turn outcome-regression tools into CATE estimators.\n- Causal forests are the main `grf` estimator for heterogeneous effects.\n- BLP and GATES are useful because they summarize heterogeneity in a way\n  that looks like familiar regression output.\n- Policy trees translate CATE estimates into treatment rules.\n- In applied work, compare at least two CATE estimators and always report\n  simple heterogeneity summaries, not only a CATE scatterplot.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}