{
  "hash": "befb7e44c4dcad7cfb11736e90332561",
  "result": {
    "engine": "knitr",
    "markdown": "# Five Estimands on One DGP\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\n```\n:::\n\n\nBefore choosing an estimator, we need to know the estimand. ATE, ATT,\nLATE, CATE and QTE are not five ways to estimate the same object. They are\nfive different objects.\n\nHere I use one simulated data set so we can calculate all of them. The\nsimulation is useful because we observe both potential outcomes. In real\ndata we do not, which is exactly why identification assumptions matter.\n\n## The data-generating process\n\nWe draw $n = 20{,}000$ people. Each has an observed covariate\n$X_i \\sim U(0,1)$, an unobserved type $U_i \\sim N(0,1)$, and a randomly\nassigned offer $Z_i \\sim \\text{Bernoulli}(0.5)$. The offer is the instrument.\nIt raises the probability of treatment but does not enter the outcome. The\ntreatment probabilities are $P(D=1 \\mid Z=0, U) = 0.10 + 0.20U$ and\n$P(D=1 \\mid Z=1, U) = 0.10 + 0.20U + 0.50$, both clipped to $[0,1]$. One\nuniform draw $V_i$ is compared against both thresholds, so $D_i(1) \\ge D_i(0)$\nfor every unit and there are no defiers. The potential outcomes are\n$Y_i(0) = 0.5X_i + 0.3U_i + \\varepsilon_i$ with $\\varepsilon_i \\sim N(0,1)$,\nand $Y_i(1) = Y_i(0) + \\tau(X_i)$ with $\\tau(x) = 1 + 2x$. We observe\n$D_i = Z_i D_i(1) + (1-Z_i) D_i(0)$ and $Y_i = D_i Y_i(1) + (1-D_i) Y_i(0)$.\n\nTwo features of this design drive everything below. Selection into treatment\nruns through $U$ and $V$, never through $X$. The treatment effect runs through\n$X$ alone. And $X$ is drawn independently of $U$, $V$ and $Z$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\nn <- 20000\n\nX <- runif(n, 0, 1)        # observed covariate, in [0,1]\nU <- rnorm(n)              # latent type, unobserved\nZ <- rbinom(n, 1, 0.5)    # random instrument\n\n# Treatment assignment: depends on Z (the instrument) and U (selection on type)\n# Higher U → more likely to take treatment regardless of Z (always-takers)\n# Lower  U → less likely to take treatment regardless of Z (never-takers)\n# Middle U → responsive to Z (compliers)\npD0 <- pmin(pmax(0.10 + 0.20 * U,        0), 1)  # P(D=1 | Z=0, U)\npD1 <- pmin(pmax(0.10 + 0.20 * U + 0.50, 0), 1)  # P(D=1 | Z=1, U) — adds 0.50\n\n# One latent draw V per person, thresholded against both probabilities.\n# Since pD1 >= pD0, V < pD0 implies V < pD1, so D1 >= D0 for every unit:\n# monotonicity (no defiers) holds by construction, as the LATE theorem requires.\nV  <- runif(n)\nD0 <- as.integer(V < pD0)   # potential treatment if not offered slot\nD1 <- as.integer(V < pD1)   # potential treatment if offered slot\nD  <- ifelse(Z == 1, D1, D0)\n\n# Heterogeneous treatment effect: depends on X\n# Y(d) = baseline + d * tau(X) + 0.3 * U + noise\ntau_fn <- function(x) 1.0 + 2.0 * x   # the true individual treatment effect\n\nY0 <- 0.5 * X + 0.3 * U + rnorm(n)\nY1 <- Y0 + tau_fn(X)\nY  <- ifelse(D == 1, Y1, Y0)\n\ndf <- data.frame(X = X, Z = Z, D = D, Y = Y)\nhead(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          X Z D          Y\n1 0.9148060 1 1  4.1619422\n2 0.9370754 0 0 -0.8962833\n3 0.2861395 1 1  1.7657727\n4 0.8304476 1 1  3.0306957\n5 0.6417455 0 0  0.1362524\n6 0.5190959 0 0 -0.2396664\n```\n\n\n:::\n:::\n\n\nThe printed rows are the data an analyst would receive: $X$, $Z$, $D$ and $Y$.\nWe keep `Y0` and `Y1` aside, and every \"true\" number in this chapter is\ncomputed from them. With real data each observation reveals only one of the\ntwo.\n\n## The five estimands\n\n### ATE — average treatment effect\n\n$$\n\\text{ATE} = \\mathbb{E}[Y(1) - Y(0)]\n$$ {#eq-causal-estimands-1}\n\nATE is the mean effect in the whole population. It compares the mean outcome\nif everyone were treated with the mean outcome if nobody were treated. Here it\nis the average of $\\tau(x) = 1+2x$ over $X \\sim U(0,1)$, which is exactly 2.\nWe average the individual effects in the sample and compare.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nate_true <- mean(Y1 - Y0)\ncat(sprintf(\"ATE (population mean of Y1 - Y0) = %.3f\\n\", ate_true))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nATE (population mean of Y1 - Y0) = 1.996\n```\n\n\n:::\n\n```{.r .cell-code}\n# Theoretical ATE: integral of (1 + 2x) over Uniform[0,1] = 1 + 1 = 2\ncat(\"Theoretical ATE = integral(1 + 2x)dx on [0,1] = 2.000\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTheoretical ATE = integral(1 + 2x)dx on [0,1] = 2.000\n```\n\n\n:::\n:::\n\n\nThe sample average is 1.996 against a population value of 2. The 0.004 gap is\nsimulation noise at $n = 20{,}000$.\n\n### ATT — average treatment effect on the treated\n\n$$\n\\text{ATT} = \\mathbb{E}[Y(1) - Y(0) \\mid D = 1]\n$$ {#eq-causal-estimands-2}\n\nATT is the mean effect for the units that actually took treatment. It differs\nfrom ATE when treatment selection is related to treatment-effect\nheterogeneity. We average the individual effects over the treated units only.\n\n\n::: {.cell}\n\n```{.r .cell-code}\natt_true <- mean(Y1[D == 1] - Y0[D == 1])\ncat(sprintf(\"ATT (mean of Y1-Y0 conditional on D=1) = %.3f\\n\", att_true))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nATT (mean of Y1-Y0 conditional on D=1) = 1.995\n```\n\n\n:::\n:::\n\n\nATT is 1.995 against an ATE of 1.996. The two are analytically identical in\nthis DGP, exactly $2.0$ in the population, so the small difference is\nsimulation noise and not a true gap between the estimands.\nThe reason is mechanical: the individual treatment effect $\\tau_i = 1+2X_i$\ndepends only on $X_i$, while selection into treatment depends on $U_i$ (and\nthe instrument $Z_i$ below), and $X_i$ is generated independently of $U_i$\nand $Z_i$. Since treatment-effect heterogeneity is unrelated to who selects\ninto treatment or who complies with the instrument, averaging $\\tau_i$ over\nthe treated subpopulation or over compliers gives the same population\naverage as over everyone -- hence ATE = ATT = LATE = $2.0$ exactly here.\nIf selection (or compliance) also depended on $X$, these estimands would\ndiverge, since ATE, ATT, and LATE are different averages of $\\tau_i$\nacross different, non-identical subpopulations.\n\n### LATE — local average treatment effect (Imbens-Angrist)\n\n$$\n\\text{LATE} = \\mathbb{E}[Y(1) - Y(0) \\mid D(1) > D(0)]\n$$ {#eq-causal-estimands-3}\n\nLATE is the mean effect for compliers, the units whose treatment status is\nchanged by the instrument. Under the usual IV assumptions, the Wald estimator\nidentifies this effect, not the ATE. Identifying LATE by the Wald ratio\nadditionally requires monotonicity (no defiers): $D(1) \\ge D(0)$ for all $i$.\nThis DGP imposes it by generating both potential treatments from one shared\nlatent draw $V_i$ with ordered thresholds ($D(z) = \\mathbb{1}\\{V_i < p_{Dz}\\}$\nwith $p_{D1} \\ge p_{D0}$), so no unit is pushed *out* of treatment by the offer.\nRaising the *probability* alone would not be enough: with independent draws for\n$D(0)$ and $D(1)$, roughly 3% of units would be defiers and the Wald ratio would\nno longer equal the complier mean.\n\nWe know $D_i(0)$ and $D_i(1)$ for every unit, so we can label the compliers and\naverage their individual effects directly. We then compute the Wald ratio from\n$Y$, $D$ and $Z$ alone, which is all an analyst would have, and compare.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompliers <- (D1 == 1) & (D0 == 0)\nlate_true <- mean(Y1[compliers] - Y0[compliers])\ncat(sprintf(\"LATE (mean of Y1-Y0 conditional on complier status) = %.3f\\n\", late_true))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLATE (mean of Y1-Y0 conditional on complier status) = 1.999\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Share of compliers: %.3f\\n\", mean(compliers)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nShare of compliers: 0.456\n```\n\n\n:::\n\n```{.r .cell-code}\n# Wald estimator from the data alone\nwald <- (mean(Y[Z == 1]) - mean(Y[Z == 0])) /\n        (mean(D[Z == 1]) - mean(D[Z == 0]))\ncat(sprintf(\"Wald IV estimate (should match LATE): %.3f\\n\", wald))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWald IV estimate (should match LATE): 1.949\n```\n\n\n:::\n:::\n\n\nCompliers are 45.6% of the sample and their mean effect is 1.999, again the\npopulation value of 2. The Wald ratio gives 1.949. The two agree up to\nsampling noise: the ratio divides a difference in mean outcomes by a treatment\nrate difference of 0.456, which magnifies the noise in the numerator, and the\n0.05 gap is about one standard error of the ratio. With heterogeneous effects\nIV averages over the people moved by the instrument, and here that group has\nthe same distribution of $X$ as everyone else.\n\n### CATE — conditional average treatment effect\n\n$$\n\\text{CATE}(x) = \\mathbb{E}[Y(1) - Y(0) \\mid X = x]\n$$ {#eq-causal-estimands-4}\n\nCATE keeps $X$ in the estimand. In this DGP, CATE($x$) is simply\n$\\tau(x)=1+2x$. We cannot condition on a single point of a continuous $X$ in a\nfinite sample, so we cut $[0,1]$ into 20 equal-width bins, average the\nindividual effects within each bin, and print two of them next to the true\n$\\tau$ at the bin centre.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnbins <- 20\nbreaks <- seq(0, 1, length.out = nbins + 1)\ncenters <- (breaks[-1] + breaks[-(nbins + 1)]) / 2\nbin_idx <- cut(X, breaks = breaks, include.lowest = TRUE, labels = FALSE)\n\ncate_est <- tapply(Y1 - Y0, bin_idx, mean)\n\ncat(sprintf(\"CATE at x=%.3f: estimated %.2f, true %.2f\\n\",\n            centers[4], cate_est[4], tau_fn(centers[4])))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCATE at x=0.175: estimated 1.35, true 1.35\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"CATE at x=%.3f: estimated %.2f, true %.2f\\n\",\n            centers[16], cate_est[16], tau_fn(centers[16])))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCATE at x=0.775: estimated 2.55, true 2.55\n```\n\n\n:::\n:::\n\n\nThe binned averages are 1.35 at $x = 0.175$ and 2.55 at $x = 0.775$, matching\n$\\tau$ at both bin centres to two decimals. The effect at $x=0.775$ is nearly\ntwice the effect at $x=0.175$, and no single scalar reports that.\n\n### QTE — quantile treatment effect\n\n$$\n\\text{QTE}(q) = F^{-1}_{Y(1)}(q) - F^{-1}_{Y(0)}(q)\n$$ {#eq-causal-estimands-5}\n\nQTE compares the two marginal outcome distributions. It is the difference\nbetween a quantile under treatment and the same quantile under control. It\ndoes not follow the same person across the two potential outcomes. We take the\nquantiles of $Y(1)$ and of $Y(0)$ on a grid from 0.05 to 0.95 and difference\nthem, printing the 10th, 50th and 90th percentiles.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqte_grid <- seq(0.05, 0.95, by = 0.05)\nqte_est  <- quantile(Y1, qte_grid) - quantile(Y0, qte_grid)\n\ncat(sprintf(\"QTE(0.10) = %.3f\\n\", quantile(Y1, 0.10) - quantile(Y0, 0.10)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nQTE(0.10) = 1.709\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"QTE(0.50) = %.3f\\n\", quantile(Y1, 0.50) - quantile(Y0, 0.50)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nQTE(0.50) = 2.009\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"QTE(0.90) = %.3f\\n\", quantile(Y1, 0.90) - quantile(Y0, 0.90)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nQTE(0.90) = 2.283\n```\n\n\n:::\n:::\n\n\nQTE rises from 1.709 at the 10th percentile to 2.009 at the median and 2.283\nat the 90th. The reason is that $\\tau(X) = 1+2X$ is largest where $X$ is\nlarge, and $Y(0) = 0.5X + 0.3U + \\varepsilon$ is also increasing in $X$, so\ntreatment adds most to the units that were already high in the control\ndistribution. Treatment stretches the distribution rather than shifting it.\nThe median QTE happens to sit near the ATE here, and there is no general\nreason for that.\n\n## When the estimands differ\n\nThe three scalar estimands coincided because selection had nothing to do with\nthe effect modifier. We now break that, and see how far apart they move.\n\nThe second DGP is the first one with a single change: $X$ enters the treatment\nprobability, $P(D=1 \\mid Z=0, U, X) = 0.10 + 0.20U + 0.6X$, clipped to $[0,1]$,\nwith the offer adding 0.50 as before. Everything else is unchanged --- a fresh\nsample of $n = 20{,}000$, $X \\sim U(0,1)$, $U \\sim N(0,1)$,\n$Z \\sim \\text{Bernoulli}(0.5)$, one shared uniform draw for the two potential\ntreatments, $Y(0) = 0.5X + 0.3U + \\varepsilon$ and $\\tau(x) = 1 + 2x$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7)\nn2 <- 20000\nX2 <- runif(n2, 0, 1)\nU2 <- rnorm(n2)\nZ2 <- rbinom(n2, 1, 0.5)\n\n# High X → much more likely to take treatment (selection on X, the modifier)\npD0_2 <- pmin(pmax(0.10 + 0.20 * U2 + 0.6 * X2, 0), 1)\npD1_2 <- pmin(pmax(pD0_2 + 0.50,                 0), 1)\nV2    <- runif(n2)                  # shared draw → D1_2 >= D0_2, no defiers\nD0_2  <- as.integer(V2 < pD0_2)\nD1_2  <- as.integer(V2 < pD1_2)\nD2    <- ifelse(Z2 == 1, D1_2, D0_2)\nY0_2  <- 0.5 * X2 + 0.3 * U2 + rnorm(n2)\nY1_2  <- Y0_2 + tau_fn(X2)\nY2    <- ifelse(D2 == 1, Y1_2, Y0_2)\n\nate2  <- mean(Y1_2 - Y0_2)\natt2  <- mean(Y1_2[D2 == 1] - Y0_2[D2 == 1])\ncompliers2 <- (D1_2 == 1) & (D0_2 == 0)\nlate2 <- mean(Y1_2[compliers2] - Y0_2[compliers2])\n\ncat(\"Selection-on-X DGP:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSelection-on-X DGP:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"  ATE  = %.3f\\n\", ate2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ATE  = 2.001\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"  ATT  = %.3f  (now higher: treated have higher X → larger τ)\\n\", att2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ATT  = 2.124  (now higher: treated have higher X → larger τ)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"  LATE = %.3f  (compliers' mean X drives this)\\n\", late2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  LATE = 1.926  (compliers' mean X drives this)\n```\n\n\n:::\n:::\n\n\nATE is still 2.001, because the distribution of $X$ has not moved. ATT rises\nto 2.124 and LATE falls to 1.926. Since $\\tau = 1 + 2X$, every subgroup\naverage is $1 + 2\\,\\mathbb{E}[X \\mid \\text{subgroup}]$, so the numbers report\nthe subgroups directly: the treated have mean $X$ of 0.562 and the compliers\nhave mean $X$ of 0.463, against 0.5 in the population.\n\nThe treated are high-$X$ because high $X$ raises the treatment probability.\nThe compliers are low-$X$ for a less obvious reason. The offer adds 0.50 to a\nprobability capped at 1, so a unit with $p_{D0}$ above 0.5 has a complier\nwindow of width $1 - p_{D0}$, narrower than 0.5. High-$X$ units are the ones\nthe cap bites on: mean window width falls from 0.49 in the bottom quartile of\n$X$ to 0.34 in the top, and the complier rate falls with it, from 0.48 to\n0.34. So the instrument moves mostly low-$X$ units, and LATE lands below ATE.\n\nHere the choice between ATE, ATT and LATE changes the substantive answer.\n\n## Which estimand should you choose?\n\nThe estimand should come from the research question:\n\n| Policy question | Right estimand |\n|---|---|\n| \"What if we treated everyone?\" | ATE |\n| \"What did treating the currently-treated achieve?\" | ATT |\n| \"What can the instrument tell us?\" | LATE |\n| \"Who benefits most?\" | CATE($x$) |\n| \"Does the effect vary across the outcome distribution?\" | QTE($q$) |\n| \"What is the distribution of individual effects?\" | Often unidentifiable; bounds required |\n\nIt is fine for one paper to report more than one estimand, as long as each is\nnamed correctly. What is not fine is to report the coefficient that is easiest\nto estimate and call it \"the causal effect.\"\n\n## Summary\n\n- ATE, ATT and LATE are different averages of the individual treatment\n  effect.\n- CATE($x$) keeps heterogeneity by covariates. QTE($q$) describes changes\n  in the outcome distribution.\n- With heterogeneous effects, IV estimates LATE. It should not be described\n  as ATE unless extra assumptions justify that interpretation. This is the\n  clean case with no covariates. Once we add covariates linearly to 2SLS,\n  even LATE needs a *rich covariates* condition that is rarely defended.\n  See @blandhol-et-al-2025 and the IV chapter section \"When 2SLS with\n  Covariates Is *Actually* LATE\".\n- Estimator choice comes after the estimand is fixed.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}