{
  "hash": "115d679d5f81624b7b2a13215b03c5b0",
  "result": {
    "engine": "knitr",
    "markdown": "# Nonparametric Causal Methods\n\n\n\n> **Related reading**: For a hands-on TMLE simulation comparing\n> super-learner libraries and assessing model misspecification, see the\n> [companion blog chapter on TMLE](https://xiangao.github.io/blog_book/tmle.html)\n> in *Topics on Econometrics and Causal Inference*.\n\n## Why Do We Need Nonparametric Methods?\n\n-   Parametric models are often mis-specified\n-   Nonparametric models are more flexible; less assumptions\n-   What kind of nonparametrics are good?\n\nConsiderations:\n\n-   Plug-in (g-computation) estimators are easy.\n-   The problem is not the decomposition into $E[Y(0)]$ and $E[Y(1)]$ itself: with correctly specified models and regularity, a plug-in estimator can be efficient. The problem appears once the nuisance models are flexible and regularised. Then the error in the nuisance estimate enters the plug-in target *linearly*, and the plug-in has no term that cancels it. An influence-function estimator adds exactly such a term, and the error that survives is a product of two nuisance errors rather than one. @sec-plug-in-bias does the algebra.\n-   So they can be consistent, but the convergence rate inherits the (often slow) nuisance rate, which is especially bad in high dimensions.\n-   Ideally we remove that first-order sensitivity using an orthogonal influence function, and get $\\sqrt{n}$ efficiency.\n-   Influence-function-based (one-step/AIPW/TMLE) estimators are shown to be efficient and orthogonal to first-order nuisance error.\n\n## Influence Function Based Estimators\n\nThe semiparametric efficiency theory behind this section is set out in Bickel, Klaassen, Ritov and Wellner [-@bickel-klaassen-ritov-wellner-1993]; Kennedy [-@kennedy-2022-overview] gives a modern review aimed at exactly these estimators. Estimators based on efficient influence function are often $\\sqrt n$ consistent, meaning they converge to the truth at the $1/\\sqrt n$ rate. This means the estimation error not only goes to 0 as $n$ goes to infinity, but does so as fast as $1/ \\sqrt n$ goes to 0. Why does this matter? Because we have limited sample size, when we are based on asymptotics, the faster the bias goes to 0 the smaller sample size we need.\n\nIf we have an estimator such that $$ \\sqrt n (\\hat \\psi - \\psi) = \\sqrt n P_n(\\phi) + o_P(1) \\rightarrow N(0, var(\\phi))$$ {#eq-nonparametric-1}\n\nThen this estimator is $\\sqrt n$ consistent and asymptotically normal; and $\\phi$ is the influence function. The efficient influence function is the one with variance at the lower bound (similar to parametric case for Cramer-Rao lower bound).\n\nUnfortunately there is no universal formula for efficient influence function for every problem. We need to derive it for each problem. For example, ATE has an IF based estimator, but ATT needs a different formula; and LATE has a different formula too, etc. Deriving them is hard!\n\nTake the mean potential outcome under treatment, $\\psi_1 = E \\{ E(Y | X, A=1) \\} = E[Y(1)]$ (the ATE is the difference $\\psi_1 - \\psi_0$ of the two arm means, and its EIF is the difference of the two arm-specific EIFs below). The efficient influence function for $\\psi_1$ is $$\\phi (Z; P) = \\frac{A}{\\pi (X)} \\{ Y - \\mu (X) \\} + \\mu(X) - \\psi_1$$ {#eq-nonparametric-2} where $\\pi (X) = P(A=1 | X)$ the propensity score model, $\\mu (X) = E(Y |X, A=1)$, the outcome model.\n\nFor example, an IF-based bias-corrected estimator $$\\hat \\psi = P_n [ \\frac{A}{\\hat \\pi (X)} \\{ Y - \\hat \\mu (X) \\} + \\hat \\mu(X) ]$$ {#eq-nonparametric-3} where $P_n$ means sample mean. This is the familiar AIPW estimator. It is known to be doubly robust.\n\nSince we know the influence function, we can estimate the asymptotic variance. The uncentered summand $\\frac{A}{\\hat\\pi(X)}\\{Y-\\hat\\mu(X)\\}+\\hat\\mu(X)$ differs from $\\phi$ only by the constant $\\psi_1$, so the two have the same variance. We can use any estimators for the nuisance parameters; the sample mean of the summand is then $\\hat\\psi_1$, its sample variance estimates $var(\\phi)$, and the standard error of $\\hat\\psi_1$ is $sd(\\hat\\phi)/\\sqrt{n}$ (differencing the two arms gives the ATE).\n\nIn this estimator, both $\\hat \\mu$ and $\\hat \\pi$ can be done using any estimator, such as machine learning. One caveat: $\\sqrt n$ inference with flexible ML nuisances requires either Donsker-type complexity restrictions or sample splitting (cross-fitting), where the nuisance models are fit on one fold and evaluated on another. The manual estimators below use in-sample predictions for simplicity; the `npcausal` calls cross-fit with `nsplits=2`, and the DoubleML section below returns to sample splitting as a key ingredient.\n\n### Why the Plug-In Is Off {#sec-plug-in-bias}\n\nThe bullets above claimed that the plug-in inherits the nuisance error at first\norder and that the augmentation term removes it. That is algebra, not a\nsimulation finding, so it is worth doing before we run anything.\n\nTake $\\psi_1 = E[\\mu(X)]$ with $\\mu(x) = E(Y \\mid X = x, A = 1)$. The plug-in\nestimator is $\\hat\\psi_1^{\\,\\text{pi}} = P_n[\\hat\\mu(X)]$. Split its error into\na sampling part and a nuisance part:\n\n$$\n\\hat\\psi_1^{\\,\\text{pi}} - \\psi_1\n= \\underbrace{(P_n - P)[\\mu]}_{O_P(n^{-1/2})}\n\\; + \\; \\underbrace{P[\\hat\\mu - \\mu]}_{\\text{nuisance error, linear}}\n\\; + \\; \\underbrace{(P_n - P)[\\hat\\mu - \\mu]}_{\\text{smaller still}} .\n$$ {#eq-nonparametric-plugin}\n\nThe middle term is $E[\\hat\\mu(X) - \\mu(X)]$, and it is linear in the nuisance\nerror. If $\\hat\\mu$ converges at rate $n^{-\\alpha}$, that term is of order\n$n^{-\\alpha}$, and a regularised learner in even a moderate number of\ndimensions gives $\\alpha < 1/2$. The nuisance error then dominates the sampling\nerror, the estimator is not $\\sqrt n$ consistent, and nothing in the plug-in\ncancels it. That is what it means to say the regularisation bias passes straight\ninto the average.\n\nNow do the same for the AIPW estimator of @eq-nonparametric-3. Evaluate it under\nthe population distribution, holding the estimated nuisances fixed. Because\n$E[A\\{Y - \\hat\\mu(X)\\} \\mid X] = \\pi(X)\\{\\mu(X) - \\hat\\mu(X)\\}$,\n\n$$\nP\\Bigl[\\frac{A}{\\hat\\pi(X)}\\bigl\\{Y - \\hat\\mu(X)\\bigr\\} + \\hat\\mu(X)\\Bigr]\n= \\psi_1 + E\\Bigl[\\frac{\\pi(X) - \\hat\\pi(X)}{\\hat\\pi(X)}\\,\n                  \\bigl\\{\\mu(X) - \\hat\\mu(X)\\bigr\\}\\Bigr].\n$$ {#eq-nonparametric-drift}\n\nThe bias is a *product* of the two nuisance errors, and that is the entire\ndifference between the two estimators. The term linear in $\\hat\\mu - \\mu$ has\ncancelled: the $\\hat\\mu$ that the outcome model carries in is subtracted back\nout by the $\\hat\\mu$ sitting inside the augmentation, and what survives is\nmultiplied by the propensity-score error. By Cauchy-Schwarz the bias is bounded\nby $\\lVert \\pi - \\hat\\pi \\rVert \\, \\lVert \\mu - \\hat\\mu \\rVert$ up to the\noverlap constant, so rates of $o(n^{-1/4})$ on each nuisance suffice to make it\n$o(n^{-1/2})$ --- slower than $\\sqrt n$ on each piece, fast enough for $\\sqrt n$\non the target.\n\nTwo familiar facts fall out of @eq-nonparametric-drift directly. Double\nrobustness is immediate: if either factor is zero the whole bias is zero, which\nis why one correct model is enough. And the $n^{-1/4}$ requirement is the reason\ncross-fitting matters, since reusing the same observations to fit and to\nevaluate $\\hat\\mu$ makes the product term behave worse than the rate\ncalculation assumes.\n\n### Simulation Setup\n\nThe aim is to run one estimand through five estimators on a single data set ---\na plug-in outcome regression, AIPW computed by hand, AIPW from `npcausal`,\nTMLE, and DoubleML --- and compare them against a truth we can compute exactly.\n\nWe simulate $n = 1000$ people with four covariates: $w_1, w_2 \\sim\n\\text{Bernoulli}(0.5)$, $w_3 \\sim U(0,4)$ and $w_4 \\sim U(0,5)$, the last two\nrounded to three decimals. Treatment is\n$A \\sim \\text{Bernoulli}(\\Lambda(-0.4 + 0.2w_2 + 0.15w_3 + 0.2w_4 + 0.15w_2w_4))$.\nBoth potential outcomes are Bernoulli with the same logit index,\n$Y(d) \\sim \\text{Bernoulli}(\\Lambda(-1 + d - 0.1w_1 + 0.3w_2 + 0.25w_3 + 0.2w_4 + 0.15w_2w_4))$,\nand we observe $Y = AY(1) + (1-A)Y(0)$.\n\nTreatment shifts the logit index by exactly 1, so the individual effect\n$\\Lambda(\\text{lin} + 1) - \\Lambda(\\text{lin})$ varies across people even though\nthe shift is constant. Note also that $w_1$ enters the outcome but not the\ntreatment, and that both the propensity and the outcome carry a $w_2 w_4$\ninteraction. Neither nuisance function is linear in the covariates, which is\nwhy flexible estimators are worth using here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nn=1000\nw1 <- rbinom(n, size=1, prob=0.5)\nw2 <- rbinom(n, size=1, prob=0.5)\nw3 <- round(runif(n, min=0, max=4), digits=3)\nw4 <- round(runif(n, min=0, max=5), digits=3)\nA  <- rbinom(n, size=1, prob= plogis(-0.4 + 0.2*w2 + 0.15*w3 + 0.2*w4 + 0.15*w2*w4))\nY.1 <- rbinom(n, size=1, prob= plogis(-1 + 1 -0.1*w1 + 0.3*w2 + 0.25*w3 + 0.2*w4 + 0.15*w2*w4))\nY.0 <- rbinom(n, size=1, prob= plogis(-1 + 0 -0.1*w1 + 0.3*w2 + 0.25*w3 + 0.2*w4 + 0.15*w2*w4))\nY <- Y.1*A + Y.0*(1 - A)\nW<-data.frame(cbind(w1,w2,w3,w4))\ndata <-  data.frame(w1, w2, w3, w4, A, Y, Y.1, Y.0)\nTrue_Psi <- mean(data$Y.1-data$Y.0);\ncat(\" True_Psi:\", True_Psi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n True_Psi: 0.21\n```\n\n\n:::\n:::\n\n\nThe line above reports `mean(Y.1 - Y.0)` for this particular draw. That is a\nlegitimate quantity --- the *sample* average treatment effect --- but it is not a\nfixed benchmark, and it is easy to mistake for one. The potential outcomes are\nbinary, so at $n = 1000$ this realized average has a sampling standard deviation\nof about 0.020: two runs of the same DGP under different seeds can differ by 0.04\nwithout anything being wrong. (The R and Julia editions of this chapter print\n0.21 and 0.184 for exactly this reason.) Estimator standard errors in this\nchapter are around 0.03, so a noisy target of that size would swamp the\ncomparison we are trying to make.\n\nThe *population* ATE is a definite number, and since the DGP is fully specified\nwe can integrate it out rather than simulate it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# w1, w2 ~ Bernoulli(0.5); w3 ~ U(0,4); w4 ~ U(0,5). Average the true individual\n# effect plogis(lin0 + 1) - plogis(lin0) over that covariate distribution.\npop_ate <- mean(sapply(list(c(0,0), c(0,1), c(1,0), c(1,1)), function(w)\n  integrate(function(w4) sapply(w4, function(u4)\n    integrate(function(w3) {\n      lin0 <- -1 - 0.1*w[1] + 0.3*w[2] + 0.25*w3 + 0.2*u4 + 0.15*w[2]*u4\n      plogis(lin0 + 1) - plogis(lin0)\n    }, 0, 4)$value / 4), 0, 5)$value / 5))\n\ncat(sprintf(\"Realized-sample ATE (this draw): %.4f\\n\", True_Psi))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRealized-sample ATE (this draw): 0.2100\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Exact population ATE:           %.4f\\n\", pop_ate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nExact population ATE:           0.2028\n```\n\n\n:::\n:::\n\n\nThe realized draw is 0.2100 and the population value is 0.2028. Compare the\nestimators below against 0.2028.\n\nAll of them need estimates of the outcome regression $\\mu$ and the propensity\nscore $\\pi$. We estimate both with the same super-learner library: MARS\n(`SL.earth`), a generalised additive model, the lasso, logistic regression with\npairwise interactions, the sample mean, a random forest, and gradient boosting.\nThe super learner takes a cross-validated convex combination of these, so no\nsingle functional form has to be right.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSL.library <- c(\"SL.earth\",\"SL.gam\",\"SL.glmnet\",\"SL.glm.interaction\", \"SL.mean\",\"SL.ranger\", \"SL.xgboost\")\n```\n:::\n\n\n### Plug-in Estimator from Outcome Regression\n\n**For illustration only -- do not use in-sample ML nuisance predictions in applied work.** The manual `mu1hat`/`mu0hat`/`pi1hat` estimators below reuse the same data to fit and evaluate the outcome-regression and propensity models (no cross-fitting). With flexible machine-learning nuisance estimators this causes overfitting bias that invalidates the estimator's asymptotic normality and the validity of standard-error calculations based on it (Chernozhukov et al., 2018). Always use sample splitting / cross-fitting with ML nuisances -- as the `npcausal` calls below do (`nsplits=2`), and as DoubleML does later in this chapter.\n\nWe fit the outcome regression on all four covariates and treatment, then\npredict each unit's outcome twice, once with $A$ set to 1 and once with $A$ set\nto 0, and average the difference. This is the plug-in, or g-computation,\nestimator: no propensity score anywhere.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nmufit <- SuperLearner(Y=data$Y, X=data %>% dplyr::select(w1,w2,w3,w4,A),\n                                     SL.library=SL.library, family=\"binomial\")\n# predict the PO Y^1\nmu1hat<- predict(mufit, newdata=data %>% dplyr::select(w1,w2,w3,w4,A) %>% mutate(A=1))$pred\nmu0hat<- predict(mufit, newdata=data %>% dplyr::select(w1,w2,w3,w4,A) %>% mutate(A=0))$pred\nmean(mu1hat-mu0hat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1824593\n```\n\n\n:::\n:::\n\n\nThe plug-in gives 0.1825 against the true 0.2028, and comes with no standard\nerror. The gap is the linear nuisance term $E[\\hat\\mu - \\mu]$ of\n@eq-nonparametric-plugin showing up in one sample: the super learner's\nregularisation bias passes into the average with nothing to cancel it. The\nnumber illustrates the algebra; it is not the evidence for it.\n\n### AIPW ATE\n\nWe now add the augmentation term. We fit the propensity score with the same\nlibrary, form the two arm summands\n$\\frac{A}{\\hat\\pi}(Y - \\hat\\mu_1) + \\hat\\mu_1$ and\n$\\frac{1-A}{1-\\hat\\pi}(Y - \\hat\\mu_0) + \\hat\\mu_0$, and average their\ndifference. The standard error is the sample standard deviation of that\ndifference divided by $\\sqrt{n}$, the influence-function standard error. The\nprinted vector is the estimate followed by the lower and upper 95% bounds.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\npifit <- SuperLearner(Y=data$A, X=data %>% dplyr::select(w1,w2,w3,w4),\n                    SL.library=SL.library, family=\"binomial\")\npi1hat <- pifit$SL.predict\npi0hat <- 1- pi1hat\nIF.1<-((data$A/pi1hat)*(data$Y-mu1hat)+mu1hat)\nIF.0<-(((1-data$A)/pi0hat)*(data$Y-mu0hat)+mu0hat)\nIF<-IF.1-IF.0\naipw.1<-mean(IF.1);aipw.0<-mean(IF.0)\naipw.manual<-aipw.1-aipw.0\nci.lb<-mean(IF)-qnorm(.975)*sd(IF)/sqrt(length(IF))\nci.ub<-mean(IF)+qnorm(.975)*sd(IF)/sqrt(length(IF))\nres.manual.aipw<-c(aipw.manual,ci.lb, ci.ub)\nres.manual.aipw\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1893510 0.1291976 0.2495044\n```\n\n\n:::\n:::\n\n\nAIPW gives 0.1894 with a 95% interval of $[0.1292, 0.2495]$, which covers the\ntrue 0.2028. The augmentation term moved the estimate from 0.1825 to 0.1894 and\nsupplied an interval the plug-in could not.\n\n### AIPW ATE Using npcausal\n\nThe `npcausal` implementation follows Kennedy [-@kennedy-2022-overview]; the estimator itself is that of Robins, Rotnitzky and Zhao [-@robins-rotnitzky-zhao-1994].\n\nThe same estimator from a package, with one change that matters: `nsplits=2`\ncross-fits the nuisances, so each unit's $\\hat\\mu$ and $\\hat\\pi$ come from a\nmodel fitted without it. The output reports both arm means and their difference.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(npcausal)\nset.seed(1)\naipw<- ate(y=Y, a=A, x=W, nsplits=2, sl.lib=SL.library)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |=========                                                             |  12%\n  |                                                                            \n  |==================                                                    |  25%\n  |                                                                            \n  |==========================                                            |  38%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |============================================                          |  62%\n  |                                                                            \n  |====================================================                  |  75%\n  |                                                                            \n  |=============================================================         |  88%\n  |                                                                            \n  |======================================================================| 100%\n     parameter       est         se     ci.ll     ci.ul pval\n1      E{Y(0)} 0.5624540 0.02695873 0.5096149 0.6152931    0\n2      E{Y(1)} 0.7567899 0.01739370 0.7226983 0.7908815    0\n3 E{Y(1)-Y(0)} 0.1943359 0.03160068 0.1323985 0.2562732    0\n```\n\n\n:::\n:::\n\n\nCross-fitting gives $E[Y(0)] = 0.5625$, $E[Y(1)] = 0.7568$, and a difference of\n0.1943 with a standard error of 0.0316 and an interval of $[0.1324, 0.2563]$.\nThat is closer to the true 0.2028 than the in-sample version, and the standard\nerror is the one to trust.\n\n### AIPW ATT\n\nThe ATT has its own efficient influence function. With\n$p = P(A=1)$ and $\\mu_0(X)=E[Y|X,A=0]$,\n\n$$\\phi_{ATT}(Z) = \\frac{1}{p}\\left\\{ A(Y-\\mu_0(X)) - (1-A)\\frac{\\pi(X)}{1-\\pi(X)}(Y-\\mu_0(X)) \\right\\} - \\frac{A}{p}\\,\\psi_{ATT}.$$ {#eq-nonparametric-4}\n\nTreated units contribute their outcome-model residual; control units\nenter with the odds weight $\\pi(X)/(1-\\pi(X))$, which reweights them to\nthe covariate distribution of the treated. Note the correction term\nuses the CONTROL units — an estimator computed on the treated\nsubsample alone would silently reduce to regression adjustment.\n\nSo we fit $\\mu_0$ on the controls only, predict it for everyone, and build the\nsummand above from the propensity score already estimated. The printed vector\nis again the estimate and the two 95% bounds.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# npcausal (attached above) exports its own SL.ranger, whose fit object is\n# incompatible with SuperLearner's predict method; pin SuperLearner's wrapper\nSL.ranger <- SuperLearner::SL.ranger\ndata2 <- data %>%\n  dplyr::mutate(pi0hat=as.numeric(pi0hat), pi1hat=as.numeric(pi1hat))\nset.seed(1)\ndata0 <- data2 %>% dplyr::filter(A==0)\nmufit <- SuperLearner(Y=data0$Y, X=data0 %>% dplyr::select(w1,w2,w3,w4),\n                                     SL.library=SL.library, family=\"binomial\")\n# predict mu0 for ALL units, treated and control\nmu0hat_all <- as.numeric(predict(mufit, newdata=data2 %>% dplyr::select(w1,w2,w3,w4))$pred)\np1 <- mean(data2$A)\nresid0 <- data2$Y - mu0hat_all\n# uncentered IF-based ATT estimator\nphi <- (data2$A*resid0 -\n        (1-data2$A)*(data2$pi1hat/data2$pi0hat)*resid0)/p1\naipw.manual.att <- mean(phi)\n# centered EIF for the variance\nphi_c <- phi - (data2$A/p1)*aipw.manual.att\nci.lb<-aipw.manual.att-qnorm(.975)*sd(phi_c)/sqrt(length(phi_c))\nci.ub<-aipw.manual.att+qnorm(.975)*sd(phi_c)/sqrt(length(phi_c))\nres.manual.aipw.att<-c(aipw.manual.att,ci.lb, ci.ub)\nres.manual.aipw.att\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1817775 0.1204417 0.2431132\n```\n\n\n:::\n:::\n\n\nThe ATT comes out at 0.1818 with an interval of $[0.1204, 0.2431]$.\n\n### AIPW ATT Using npcausal\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(npcausal)\nset.seed(1)\naipw<- att(y=Y, a=A, x=W, nsplits=2, sl.lib=SL.library)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |==================                                                    |  25%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |====================================================                  |  75%\n  |                                                                            \n  |======================================================================| 100%\n      parameter       est         se      ci.ll     ci.ul  pval\n1      E(Y|A=1) 0.7668232 0.01686602 0.73376577 0.7998806 0.000\n2   E{Y(0)|A=1} 0.5938218 0.05052032 0.49480194 0.6928416 0.000\n3 E{Y-Y(0)|A=1} 0.1730014 0.05289367 0.06932981 0.2766730 0.001\n```\n\n\n:::\n:::\n\n\nCross-fitted, the ATT is 0.1730 with a standard error of 0.0529 and an interval\nof $[0.0693, 0.2767]$.\n\nThe ATT is a different estimand from the ATE, and here they genuinely differ:\nthe treatment probability rises with $w_2$, $w_3$ and $w_4$, and the individual\neffect varies with those same covariates, so averaging over the treated is not\nthe same as averaging over everyone. The two estimates are 0.1730 and 0.1943,\nand with standard errors of 0.0529 and 0.0316 the data cannot separate them.\nNote that the ATT standard error is two-thirds larger, because only the\ntreated units contribute to the average.\n\n## TMLE\n\nTargeted maximum likelihood estimation is due to van der Laan and Rubin [-@vanderlaan-rubin-2006]; van der Laan and Rose [-@vanderlaan-rose-2011] is the book-length treatment, and the source of the Super Learner used for the nuisance fits.\n\nTMLE is a variant of IF based estimator. It is also a doubly robust estimator. See Mark van der Laan and his coauthors for the recent development of TMLE.\n\nTMLE targets the same ATE with the same nuisance library, so we should expect\nit to agree with `npcausal`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tmle)\nTMLE<- tmle(Y=data$Y,A=data$A,W=W, family=\"binomial\", Q.SL.library=SL.library, g.SL.library=SL.library)\n\nTMLE$estimates$ATE\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$psi\n[1] 0.1894847\n\n$var.psi\n[1] 0.0009250159\n\n$CI\n[1] 0.1298742 0.2490951\n\n$pvalue\n[1] 4.659488e-10\n\n$bs.var\n[1] NA\n\n$bs.CI.twosided\n[1] NA NA\n\n$bs.CI.onesided.lower\n[1] -Inf   NA\n\n$bs.CI.onesided.upper\n[1]  NA Inf\n```\n\n\n:::\n:::\n\n\nTMLE gives 0.1893 with an interval of $[0.1288, 0.2498]$, against AIPW's 0.1894\nand `npcausal`'s 0.1943. The three agree to well within a standard error, which\nis what the theory predicts: they share an efficient influence function and\ndiffer only in how they solve its estimating equation.\n\n## DoubleML\n\nDouble/debiased machine learning is Chernozhukov et al. [-@chernozhukov-2018-dml]. The cross-fitting it relies on is what keeps the nuisance error from contaminating the influence function.\n\nThe R package DoubleML implements the double/debiased machine learning framework of Chernozhukov et al. (2018). It provides functionalities to estimate parameters in causal models based on machine learning methods. The double machine learning framework consists of three key ingredients: Neyman orthogonality, High-quality machine learning estimation and Sample splitting.\n\nThey consider a partially linear model:\n\n$$ y_i = \\theta d_i + g_0(x_i) + \\eta_i $$ {#eq-nonparametric-5}\n\n$$ d_i = m_0(x_i) + v_i $$ {#eq-nonparametric-6}\n\nThis model is quite general, except it does not allow interaction of $d$ and $x$; therefore no heterogeneous treatment effect across $x$. But \"DoubleML\" implements more than partially linear model, it actually allows for heterogeneous treatment effects, in models such as interactive regression model.\n\nThe basic idea of doubleML is to use any machine learning algorithm to estimate outcome equation ($l_0(X) = E(Y | X)$) and treatment equation ($m_0(X) = E(D | X)$). Then get the residuals, namely $\\tilde Y=Y-\\hat l_0(X)$ and $\\tilde D = D - \\hat m_0(X)$.\n\nThen regress $\\tilde Y$ on $\\tilde D$. Based on FWL theorem, you get $\\hat \\theta$.\n\nAn important component here is to specify a Neyman-orthogonal score function. In the case of PLR, the \"partialling-out\" score (the DoubleML default, matching the residual-on-residual regression above) is\n\n$$\\psi (Z; \\theta, \\eta) = \\big(Y- l(X) - \\theta (D-m(X))\\big)\\big(D-m(X)\\big) $$ {#eq-nonparametric-7}\n\nThe estimator $\\hat \\theta$ solves the equation that the sample mean of this score function is 0.\n\nThe estimator's variance comes from the usual sandwich formula built on the score, $\\hat\\sigma^2 = \\hat J^{-1}\\, \\widehat{E[\\psi^2]}\\, \\hat J^{-1}$ with $\\hat J = -\\frac{1}{n}\\sum_i (D_i-\\hat m(X_i))^2$.\n\nWe set up the data object first, naming the outcome, the treatment and the four\ncovariates:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(DoubleML)\ndml_data = DoubleMLData$new(data,\n                             y_col = \"Y\",\n                             d_cols = \"A\",\n                             x_cols = c(\"w1\",\"w2\",\"w3\",\"w4\"))\nprint(dml_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n================= DoubleMLData Object ==================\n\n\n------------------ Data summary      ------------------\nOutcome variable: Y\nTreatment variable(s): A\nCovariates: w1, w2, w3, w4\nInstrument(s): \nSelection variable: \nNo. Observations: 1000\n```\n\n\n:::\n:::\n\n\nBoth nuisance functions are estimated by a random forest with 500 trees, depth\nat most 5, and a minimum node size of 2. DoubleML cross-fits them and solves\nthe partialling-out score.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(mlr3)\nlibrary(mlr3learners)\n# suppress messages from mlr3 package during fitting\nlgr::get_logger(\"mlr3\")$set_threshold(\"warn\")\nlearner = lrn(\"regr.ranger\", num.trees=500,  max.depth=5, min.node.size=2)\nml_l = learner$clone()\nml_m = learner$clone()\nlearner = lrn(\"regr.glmnet\")\nml_g_sim = learner$clone()\nml_m_sim = learner$clone()\nset.seed(123)\nobj_dml_plr = DoubleMLPLR$new(dml_data, ml_l=ml_l, ml_m=ml_m)\nobj_dml_plr$fit()\nobj_dml_plr$summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEstimates and significance testing of the effect of target variables\n  Estimate. Std. Error t value Pr(>|t|)    \nA   0.19257    0.03136    6.14 8.24e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nDoubleML returns 0.19257 with a standard error of 0.03136, in line with AIPW's\n0.1894 and TMLE's 0.1893.\n\nOne caveat on what this number is. The partially linear model has no\ntreatment-covariate interaction, so its $\\theta$ is not the ATE when effects are\nheterogeneous, and in this DGP they are: the individual effect\n$\\Lambda(\\text{lin}+1) - \\Lambda(\\text{lin})$ depends on the covariates. By the\nFrisch-Waugh-Lovell argument behind the partialling-out score, $\\theta$ is the\naverage of the conditional effects weighted by the conditional variance of\ntreatment, $\\text{Var}(A \\mid X)$, so people whose treatment is hardest to\npredict count most. It equals the ATE only when the effect is constant. Here\nthe two are close, 0.193 against 0.203, but that is a property of this DGP and\nnot a general result.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}