{
  "hash": "35c4ee1d380dca98f0ad4c90d36c9ca4",
  "result": {
    "engine": "knitr",
    "markdown": "# DiD with Continuous Treatment\n\n\n\nThe DiD chapter treats the treatment as on or off. Many treatments come in amounts. A county gets one Walmart or five. A state raises the minimum wage by fifty cents or by three dollars. A hospital receives a small grant or a large one. With a dose we want more than the effect of being treated. We want to know how the effect changes with the dose.\n\nWe first look at two periods, where @callaway-goodman-bacon-santanna-2024 show what parallel trends identifies with a dose and what it leaves out. A simulation with known truth shows the difference. We then move to staggered adoption, using the heterogeneous-slopes extension of extended two-way fixed effects (ETWFE) in @wooldridge-2026-nonbinary, and replicate his study of Walmart and county retail employment.\n\n## Two periods\n\nWe observe units $i = 1, \\dots, n$ in two periods, $t = 1, 2$. Nobody is treated in period 1. Before period 2, each unit receives a dose $D_i \\ge 0$, and units with $D_i = 0$ stay untreated. For each dose $d$, unit $i$ has a potential outcome $Y_{it}(d)$, and we observe $Y_{it} = Y_{it}(D_i)$. No anticipation means $Y_{i1}(d) = Y_{i1}(0)$ for every $d$. Let $\\Delta Y_i = Y_{i2} - Y_{i1}$.\n\nThere are two natural estimands. Take two doses $d$ and $d'$. The first estimand, $ATT(d \\mid d')$, is the average effect of dose $d$, relative to no treatment, among the units that actually received dose $d'$:\n\n$$ATT(d \\mid d') = E[Y_{i2}(d) - Y_{i2}(0) \\mid D_i = d'].$$ {#eq-dc-att}\n\nThe leading case is $ATT(d \\mid d)$, the effect of each group's own dose. The second estimand, $ATE(d)$, is the effect of dose $d$ averaged over all treated units, whatever dose they received:\n\n$$ATE(d) = E[Y_{i2}(d) - Y_{i2}(0) \\mid D_i > 0].$$ {#eq-dc-ate}\n\nIts derivative $ATE'(d)$ is the average causal response at $d$: the average effect of a small increase in the dose.\n\nParallel trends with a dose says that, without treatment, every dose group would have followed the trend of the untreated:\n\n$$E[Y_{i2}(0) - Y_{i1}(0) \\mid D_i = d] = E[Y_{i2}(0) - Y_{i1}(0) \\mid D_i = 0] \\quad \\text{for all } d.$$ {#eq-dc-pt}\n\nUnder @eq-dc-pt and no anticipation,\n\n$$E[\\Delta Y_i \\mid D_i = d] - E[\\Delta Y_i \\mid D_i = 0] = ATT(d \\mid d).$$ {#eq-dc-id}\n\nThis is the binary DiD done separately at each dose. It identifies the whole curve $ATT(d \\mid d)$.\n\nThe difficulty starts when we compare doses. For the two doses $d$ and $d'$,\n\n$$ATT(d \\mid d) - ATT(d' \\mid d') = \\underbrace{ATT(d \\mid d) - ATT(d' \\mid d)}_{\\text{causal response}} + \\underbrace{ATT(d' \\mid d) - ATT(d' \\mid d')}_{\\text{selection on gains}}.$$ {#eq-dc-decomp}\n\nThe first term is causal. It is what moving the dose from $d'$ to $d$ does for the units that chose $d$. The second term compares two groups at the same dose $d'$. It is non-zero when the units that chose $d$ would gain differently from dose $d'$ than the units that chose $d'$. Parallel trends says nothing about this term. So the slope of the curve in @eq-dc-id mixes the causal response with selection on gains.\n\n@callaway-goodman-bacon-santanna-2024 remove the second term with strong parallel trends:\n\n$$E[Y_{i2}(d) - Y_{i1}(0) \\mid D_i = d] = E[Y_{i2}(d) - Y_{i1}(0) \\mid D_i > 0] \\quad \\text{for all } d > 0.$$ {#eq-dc-spt}\n\nIn words, the average path from untreated in period 1 to dose $d$ in period 2 is the same for the units that chose $d$ as for all treated units. Together with @eq-dc-pt it gives $ATT(d \\mid d) = ATE(d)$ for every $d$. Comparisons across doses are then causal, and the slope of the identified curve is the average causal response.\n\n@wooldridge-2026-nonbinary reaches the same point from a regression. Let $B_i$ be the gain of unit $i$ from one unit of dose, so that the effect is linear in the dose with a slope that varies across units: $Y_{i2}(d) = Y_{i2}(0) + d B_i$. Let $\\gamma = E[Y_{i2}(0) - Y_{i1}(0)]$ be the untreated trend, and let $\\delta = E(B_i \\mid D_i > 0)$ be the average slope among the treated. Under @eq-dc-pt,\n\n$$E(\\Delta Y_i \\mid D_i) = \\gamma + \\delta D_i$$ {#eq-dc-linear}\n\nholds when $E(B_i \\mid D_i = d) = \\delta$ for every $d > 0$. That condition is strong parallel trends for the linear model. Adding powers of $D_i$ to the regression relaxes the linearity.\n\n## A simulation with known truth\n\nWe now check these claims on data where we know the truth. The aim is to see which curve the DiD estimator in @eq-dc-id recovers when gains are, and are not, related to the dose.\n\nEach scenario has 3,000 units observed in two periods. 1,000 units are untreated. The other 2,000 receive a dose drawn uniformly on $[0.5, 2.5]$. The untreated outcome is the sum of a unit effect $\\alpha_i$, a period effect $\\lambda_t$ and an error $\\varepsilon_{it}$:\n\n$$Y_{it}(0) = \\alpha_i + \\lambda_t + \\varepsilon_{it}.$$\n\nThe common trend is $\\lambda_2 - \\lambda_1 = 1$, so parallel trends holds. The unit effect is $\\alpha_i = 2 + 0.5 D_i + v_i$, where $v_i$ is a normal error with variance 1. It rises with the dose, so treated and untreated units differ in levels. The error $\\varepsilon_{it}$ is normal with standard deviation 0.5. The effect of dose $d$ on unit $i$ is a common dose response $m(d)$ scaled by a unit-specific factor $b_i$:\n\n$$Y_{i2}(d) - Y_{i2}(0) = b_i\\, m(d), \\qquad m(d) = 1.5 d - 0.3 d^2.$$ {#eq-dc-sim}\n\nThe dose response $m(d)$ is concave. The two scenarios differ only in $b_i$. Let $u_i$ be a normal error with standard deviation 0.2. In scenario A, $b_i = 1 + u_i$, independent of the dose. In scenario B, $b_i = 1 + 0.5(D_i - 1.5) + u_i$ for treated units, so units with larger gains take larger doses.\n\nThe truth follows from @eq-dc-sim. In both scenarios $E(b_i \\mid D_i > 0) = 1$, so $ATE(d) = m(d)$. In scenario A, $ATT(d \\mid d) = m(d)$ as well. In scenario B, $ATT(d \\mid d) = [1 + 0.5(d - 1.5)]\\, m(d)$. It lies below $m(d)$ for doses under 1.5 and above it for doses over 1.5.\n\nWe estimate the curve in @eq-dc-id by regressing $\\Delta Y_i$ on a cubic polynomial in $D_i$ among the treated, and subtracting the mean of $\\Delta Y_i$ among the untreated. In scenario B the true $ATT(d \\mid d)$ is a cubic, so the polynomial can fit it exactly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# simulated from the DGP above by data/gen_did_dose_sim.R\nsim <- fread(\"data/did_dose_sim.csv\")\nm  <- function(d) 1.5 * d - 0.3 * d^2\nmp <- function(d) 1.5 - 0.6 * d          # derivative of m\n\ndose_curve <- function(dt) {\n  w <- dcast(dt, id + d ~ t, value.var = \"y\")\n  w[, dy := `2` - `1`]\n  fit <- lm(dy ~ d + I(d^2) + I(d^3), data = w[d > 0])\n  list(fit = fit, base = w[d == 0, mean(dy)], dose = w[d > 0, d],\n       att = mean(w[d > 0, dy]) - w[d == 0, mean(dy)])\n}\nfits <- list(A = dose_curve(sim[scenario == \"A\"]),\n             B = dose_curve(sim[scenario == \"B\"]))\n\ngrid <- seq(0.5, 2.5, by = 0.05)\nkappa <- c(A = 0, B = 0.5)\ncurves <- rbindlist(lapply(c(\"A\", \"B\"), function(sc) {\n  est <- predict(fits[[sc]]$fit, data.frame(d = grid)) - fits[[sc]]$base\n  data.table(scenario = paste(\"Scenario\", sc), d = grid,\n             `Estimate` = est,\n             `ATT(d|d)` = (1 + kappa[sc] * (grid - 1.5)) * m(grid),\n             `ATE(d)` = m(grid))\n}))\ncurves[d %in% c(0.75, 1.5, 2.25)]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     scenario     d  Estimate  ATT(d|d)  ATE(d)\n       <char> <num>     <num>     <num>   <num>\n1: Scenario A  0.75 0.9401995 0.9562500 0.95625\n2: Scenario A  1.50 1.5863984 1.5750000 1.57500\n3: Scenario A  2.25 1.8422626 1.8562500 1.85625\n4: Scenario B  0.75 0.5816057 0.5976562 0.95625\n5: Scenario B  1.50 1.5863984 1.5750000 1.57500\n6: Scenario B  2.25 2.5383564 2.5523437 1.85625\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlong <- melt(curves, id.vars = c(\"scenario\", \"d\"), variable.name = \"curve\")\nggplot(long, aes(d, value, colour = curve, linetype = curve)) +\n  geom_line(linewidth = 0.8) +\n  facet_wrap(~scenario) +\n  scale_linetype_manual(values = c(\"solid\", \"dashed\", \"dotted\")) +\n  labs(x = \"Dose d\", y = \"Effect\", colour = NULL, linetype = NULL) +\n  theme_bw() + theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Estimated dose-response curve against the true ATT(d|d) and ATE(d). In scenario A the two truths coincide.](did-continuous_files/figure-pdf/dc-sim-plot-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nIn scenario A the estimate lies on the common truth. At doses 0.75, 1.5 and 2.25 it is 0.94, 1.59 and 1.84, against true values 0.96, 1.58 and 1.86. In scenario B the estimate follows $ATT(d \\mid d)$: 0.58, 1.59 and 2.54, against 0.60, 1.58 and 2.55. It misses $ATE(d)$, which is 0.96, 1.58 and 1.86. The estimator does what @eq-dc-id says. It identifies $ATT(d \\mid d)$, and that equals $ATE(d)$ only when gains are unrelated to the dose.\n\nThe slopes show the same thing. We average the derivative of each curve over the treated doses in the sample.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nslopes <- rbindlist(lapply(c(\"A\", \"B\"), function(sc) {\n  cf <- coef(fits[[sc]]$fit); d <- fits[[sc]]$dose; k <- kappa[sc]\n  data.table(scenario = sc,\n             estimated_slope = mean(cf[2] + 2 * cf[3] * d + 3 * cf[4] * d^2),\n             true_slope_att  = mean(k * m(d) + (1 + k * (d - 1.5)) * mp(d)),\n             acrt            = mean((1 + k * (d - 1.5)) * mp(d)),\n             selection       = mean(k * m(d)),\n             acr             = mean(mp(d)))\n}))\nslopes[, lapply(.SD, round, 3), by = scenario]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   scenario estimated_slope true_slope_att  acrt selection   acr\n     <char>           <num>          <num> <num>     <num> <num>\n1:        A           0.536          0.593 0.593     0.000 0.593\n2:        B           1.184          1.241 0.498     0.742 0.593\n```\n\n\n:::\n:::\n\n\nThe average causal response is 0.59 in both scenarios. In scenario A the slope of the estimated curve is 0.54, close to it. In scenario B the slope is 1.18, twice the causal response. The decomposition in @eq-dc-decomp accounts for the gap. The true slope of $ATT(d \\mid d)$ is 1.24. Of this, 0.50 is the causal response of the units at each dose, and 0.74 is selection on gains.\n\nThe `contdid` package of Callaway implements this estimator in R. Its overall ATT and overall average causal response match ours exactly. In version 0.1.1, its dose-specific curve is computed on a spline basis rebuilt from the evaluation grid, and this shifts the curve when the grid does not span the sample doses. For that reason we plot our own fit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncd_check <- rbindlist(lapply(c(\"A\", \"B\"), function(sc) {\n  dt <- sim[scenario == sc][, g := fifelse(d > 0, 2, 0)]\n  cd <- suppressMessages(cont_did(\n    yname = \"y\", dname = \"d\", gname = \"g\", tname = \"t\", idname = \"id\",\n    data = as.data.frame(dt), target_parameter = \"level\",\n    aggregation = \"dose\", treatment_type = \"continuous\",\n    dose_est_method = \"parametric\", degree = 3, num_knots = 0,\n    control_group = \"nevertreated\", bstrap = FALSE))\n  data.table(scenario = sc,\n             att_ours = fits[[sc]]$att, att_contdid = cd$overall_att,\n             acr_ours = slopes[scenario == sc, estimated_slope],\n             acr_contdid = cd$overall_acrt)\n}))\ncd_check[, lapply(.SD, round, 4), by = scenario]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   scenario att_ours att_contdid acr_ours acr_contdid\n     <char>    <num>       <num>    <num>       <num>\n1:        A   1.4792      1.4792   0.5363      0.5363\n2:        B   1.5843      1.5843   1.1839      1.1839\n```\n\n\n:::\n:::\n\n\n## Staggered adoption\n\nNow units enter treatment at different times, as in the ETWFE section of the DiD chapter. Periods run $t = 1, \\dots, T$, and the first period in which any unit is treated is $q$. A cohort $g \\in \\{q, \\dots, T\\}$ is the set of units first treated in period $g$. Let $D_{ig} = 1$ if unit $i$ is in cohort $g$, and $D_{ig} = 0$ otherwise. Never-treated units have $D_{ig} = 0$ for every $g$. The vector $\\mathbf D_i = (D_{iq}, \\dots, D_{iT})$ collects unit $i$'s cohort dummies. For each period $s$, the time dummy $fs_t$ equals 1 if $t = s$ and 0 otherwise.\n\nThe treatment $\\mathbf W_{it}$ is a $1 \\times J$ row vector, where $J$ is the number of treatment variables. A single dose has $J = 1$. A dose and its square has $J = 2$. A set of mutually exclusive treatment levels has $J$ equal to the number of levels. Every unit has $\\mathbf W_{it} = \\mathbf 0$ before its entry period, and $\\mathbf W_i$ stacks unit $i$'s rows over all $T$ periods. We write $\\mathbf w$ for a possible value of $\\mathbf W_{it}$. The dose may change after entry. In the Walmart data it is the number of stores open.\n\n@wooldridge-2026-nonbinary writes potential outcomes as linear in the treatment, with slopes that vary by unit and period. Let $\\mathbf B_{it}$ be a $J \\times 1$ vector of random slopes, whose $j$-th element is unit $i$'s gain in period $t$ from one unit of treatment variable $j$. Let $\\gamma_t$ be a time effect, $C_i$ an unobserved unit effect, and $U_{it}$ an idiosyncratic error. The potential outcome at treatment value $\\mathbf w$ is\n\n$$Y_{it}(\\mathbf w) = \\mathbf w\\, \\mathbf B_{it} + \\gamma_t + C_i + U_{it}.$$ {#eq-dc-po}\n\nThe additive $\\gamma_t + C_i$ is parallel trends. Nothing restricts $\\mathbf B_{it}$. The estimand is its mean for each cohort and period:\n\n$$\\boldsymbol\\delta_{gs} = E(\\mathbf B_{is} \\mid D_{ig} = 1), \\qquad s \\ge g.$$ {#eq-dc-delta}\n\nIn words, $\\boldsymbol\\delta_{gs}$ is the average effect of one more unit of each treatment variable for cohort $g$ in period $s$. With a binary treatment it is the cohort-period ATT of ETWFE.\n\nWooldridge assumes no anticipation and strict exogeneity. Strict exogeneity says the error $U_{it}$ has mean zero given the whole treatment path $\\mathbf W_i$, the unit effect $C_i$ and the slopes $\\mathbf B_{it}$. He needs one more assumption, which has no counterpart in the binary case. He calls it limited selection:\n\n$$E(\\mathbf B_{it} \\mid \\mathbf W_i) = E(\\mathbf B_{it} \\mid \\mathbf D_i).$$ {#eq-dc-ls}\n\nOnce we know when a unit entered, its dose path carries no information about its average gain. With a binary treatment the entry date fixes the whole treatment path, so @eq-dc-ls holds automatically. With two periods and a scalar dose it is the strong parallel trends of @eq-dc-spt in its linear form.\n\nLet $A_i = E(C_i \\mid \\mathbf W_i)$ be the mean of the unit effect given the treatment path. Under these assumptions,\n\n$$E(Y_{it} \\mid \\mathbf W_i) = \\sum_{g=q}^{T} \\sum_{s=g}^{T} (D_{ig}\\, fs_t\\, \\mathbf W_{it})\\, \\boldsymbol\\delta_{gs} + \\gamma_t + A_i.$$ {#eq-dc-reg}\n\n$A_i$ is a unit effect. So a two-way fixed effects (TWFE) regression of $Y_{it}$ on the interactions $D_{ig}\\, fs_t\\, \\mathbf W_{it}$, with unit and time effects, estimates every $\\boldsymbol\\delta_{gs}$. This is ETWFE with the treatment indicator replaced by the dose. Standard errors are clustered by unit.\n\nThere are many cohort-period slopes, so we aggregate them. Let $e$ be the exposure time, the number of periods since entry, and let $N_g$ be the number of units in cohort $g$. Let $\\hat{\\boldsymbol\\delta}_{gs}$ be the TWFE estimate of $\\boldsymbol\\delta_{gs}$. The estimated effect at exposure $e$, written $\\hat{\\boldsymbol\\tau}_{e}$, averages over the cohorts observed that long, with weights proportional to cohort size:\n\n$$\\hat{\\boldsymbol\\tau}_{e} = \\sum_{g=q}^{T-e} \\frac{N_g}{N_q + \\dots + N_{T-e}}\\, \\hat{\\boldsymbol\\delta}_{g,g+e}.$$ {#eq-dc-agg}\n\nThe overall effect weights every cohort-period slope by $N_g$. In a balanced panel it is the average slope over all treated unit-periods.\n\nPre-trends can be tested in two ways. A lead is a dummy $D_{ig}\\, fs_t$ for a period $s$ before cohort $g$ enters. The first test fits TWFE on the untreated observations only, the unit-periods with $\\mathbf W_{it} = \\mathbf 0$, with leads for $s \\le g - 2$, so that the period just before entry is the base. It then tests whether the leads are zero. The second test adds the same leads to @eq-dc-reg. With a binary treatment the two give identical estimates. With a dose they differ. When the leads show a trend, Wooldridge adds cohort-specific linear trends to @eq-dc-reg. For each cohort $g$, the regressor $D_{ig} \\cdot t$ is a linear time trend for that cohort only. The assumption then becomes that each cohort's gap from the never-treated units would have kept growing along the same line after entry.\n\n## Wooldridge's regression and the CGBS estimator\n\nThe two approaches target the same objects. Under parallel trends and strong parallel trends, each identifies the average effect of the dose for every cohort and period. They differ in how they estimate it and in what they can handle.\n\nThe first difference is the comparison group. Wooldridge runs one TWFE regression in levels on all periods, @eq-dc-reg. Every untreated observation serves as a control: the never-treated units, the not-yet-treated units, and the pre-entry periods of every cohort. In the binary case this regression is the imputation estimator of @borusyak-jaravel-spiess-2024. @callaway-goodman-bacon-santanna-2024 build on @callaway-santanna-2021 instead. For each cohort and period they compare the cohort with the never-treated or the not-yet-treated units, using the long difference from the period just before entry, and fit the dose response in that comparison. The regression uses more data, and it is more efficient when the errors are homoskedastic and serially uncorrelated. In exchange it needs parallel trends in every pre-entry period. The differencing approach needs it only from the base period on.\n\nThe second difference is the shape of the dose response. In Wooldridge's regression, the shape comes from the functions of the dose placed in $\\mathbf W_{it}$: the dose itself, its powers, or dummies for dose levels. The estimand is the average slope $\\boldsymbol\\delta_{gs}$. CGBS fit a B-spline in the dose within each cohort and period, or a nonparametric curve whose complexity is chosen from the data. They report the curve $ATT(d \\mid d)$ and its derivative. The two also treat a dose near zero differently. With two periods, Wooldridge's regression has no separate intercept for the treated units, so its fitted effect goes to zero as the dose goes to zero. The CGBS fit gives the treated units their own intercept, so the effect can jump at any positive dose. The two coincide once a dummy for a positive dose is added to $\\mathbf W_{it}$. The estimator in our simulation follows CGBS.\n\nThe third difference is scope. The table compares Wooldridge's regression with the R package `contdid`, version 0.1.1, which implements CGBS.\n\n| | Wooldridge (2026) | `contdid` 0.1.1 |\n|---|---|---|\n| Dose changes after entry | Yes | No |\n| Covariates | Yes, in the trends and in the slopes | No |\n| Cohort-specific trends | Yes | No |\n| Unbalanced panel | Yes | No |\n| Multi-level or vector treatment | Yes, through $\\mathbf W_{it}$ | No |\n| Exit from treatment | Yes | No |\n| Standard errors | Analytic, clustered by unit | Multiplier bootstrap |\n| Reported effects | Average slopes by cohort and period, aggregated by exposure | $ATT(d \\mid d)$ and its derivative, aggregated by dose or by exposure |\n\nThe first row decides the Walmart application. The number of stores changes after entry, so the CGBS estimator, as implemented, does not apply. The other rows show what the single regression buys: covariates, trends, exit and missing years enter as extra terms. In the other direction, CGBS trace out the whole dose-response curve within each cohort and period. Wooldridge reports average slopes and needs powers of the dose to show curvature.\n\n## Walmart and county retail employment\n\n@wooldridge-2026-nonbinary applies the method to the county panel of @brown-butts-2025. It covers 1,288 counties from 1977 to 1999. No county had a Walmart before 1986. Stores then opened in 14 cohorts, from 1986 to 1999, and 395 counties never got one. The treatment is a single dose, so $J = 1$ and we write it without bold: $W_{it}$ is the number of Walmarts open in county $i$ in year $t$. The outcome is log retail employment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# extract of walmart_lw.dta from Wooldridge's replication files (data/gen_walmart_lw.R)\nwm <- fread(\"data/walmart_lw.csv\")\nwm[year == 1999, .N, by = .(cohort)][order(cohort)]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    cohort     N\n     <int> <int>\n 1:      0   395\n 2:   1986    69\n 3:   1987    74\n 4:   1988    60\n 5:   1989    77\n 6:   1990   118\n 7:   1991   113\n 8:   1992    88\n 9:   1993    98\n10:   1994    48\n11:   1995    53\n12:   1996    25\n13:   1997    26\n14:   1998    23\n15:   1999    21\n```\n\n\n:::\n\n```{.r .cell-code}\nwm[n_open > 0, .N, by = n_open][order(n_open)][, share := round(N / sum(N), 3)][]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    n_open     N share\n     <int> <int> <num>\n 1:      1  6278 0.797\n 2:      2  1042 0.132\n 3:      3   300 0.038\n 4:      4   128 0.016\n 5:      5    54 0.007\n 6:      6    17 0.002\n 7:      7    20 0.003\n 8:      8    11 0.001\n 9:      9     7 0.001\n10:     10     5 0.001\n11:     11    12 0.002\n12:     12     5 0.001\n13:     13     1 0.000\n```\n\n\n:::\n:::\n\n\nMost treated counties have a single store. One store accounts for 80% of treated county-years, two for 13%, and the largest count is 13. Within a cohort and year, the slope is fit from the change relative to untreated counties and from the differences in store counts. With so many single-store counties, it mostly measures the effect of the first store.\n\nA single-coefficient TWFE regression is the natural starting point.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoeftable(feols(log_retail_emp ~ n_open | fips + year, wm, cluster = ~fips))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Estimate  Std. Error  t value     Pr(>|t|)\nn_open 0.03441203 0.005651171 6.089363 1.494081e-09\nattr(,\"vcov_type\")\n[1] \"Clustered (fips)\"\n```\n\n\n:::\n:::\n\n\nOne more Walmart raises retail employment by 3.4%, with a standard error of 0.57 percentage points. In the binary case this regression makes forbidden comparisons, which use already-treated units as controls, when effects vary by cohort and time. The same holds with a dose. So we build the regressors of @eq-dc-reg, one for each cohort and year from entry on: $W_{it}$ times the cohort dummy times the year dummy.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncohorts <- 1986:1999\ncells <- CJ(g = cohorts, s = cohorts)[s >= g]\nwcols <- sprintf(\"w_%d_%d\", cells$g, cells$s)\nfor (k in seq_len(nrow(cells)))\n  set(wm, j = wcols[k],\n      value = (wm$cohort == cells$g[k]) * (wm$year == cells$s[k]) * wm$n_open)\ntrcols <- sprintf(\"tr_%d\", cohorts)\nfor (k in seq_along(cohorts))\n  set(wm, j = trcols[k], value = (wm$cohort == cohorts[k]) * wm$year)\n\nfit_het <- feols(log_retail_emp ~ ..(\"^w_\") | fips + year, wm, cluster = ~fips)\nlength(coef(fit_het))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 105\n```\n\n\n:::\n:::\n\n\nThat gives 105 slopes. We aggregate them with @eq-dc-agg. Each aggregate is a linear combination of the slopes with fixed weights, so its standard error comes from the clustered covariance matrix. This matches Stata's `margins` in Wooldridge's code.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNg <- wm[year == 1999 & cohort > 0, .N, by = cohort]\nsetkey(Ng, cohort)\n\naggregate_slopes <- function(fit) {\n  b <- coef(fit)[wcols]; V <- vcov(fit)[wcols, wcols]\n  lincomb <- function(a) c(estimate = sum(a * b), se = sqrt(drop(t(a) %*% V %*% a)))\n  by_e <- t(sapply(0:13, function(e) {\n    gs <- cohorts[cohorts + e <= 1999]\n    a <- setNames(numeric(length(wcols)), wcols)\n    a[sprintf(\"w_%d_%d\", gs, gs + e)] <- Ng[J(gs)]$N / sum(Ng[J(gs)]$N)\n    lincomb(a)\n  }))\n  a_all <- Ng[J(cells$g)]$N\n  rbind(by_e, overall = lincomb(a_all / sum(a_all)))\n}\nagg_het <- aggregate_slopes(fit_het)\n```\n:::\n\n\nBefore reading the effects, we check pre-trends. Following the first test above, we fit TWFE on the untreated county-years with a lead for each cohort and each year at least two years before entry. We then average the leads by years until entry, with the cohort weights of @eq-dc-agg.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nun <- wm[n_open == 0, .(fips, year, cohort, log_retail_emp)]\nleads <- CJ(g = cohorts, s = 1977:1999)[s <= g - 2]\nlcols <- sprintf(\"l_%d_%d\", leads$g, leads$s)\nfor (k in seq_len(nrow(leads)))\n  set(un, j = lcols[k], value = (un$cohort == leads$g[k]) * (un$year == leads$s[k]))\nfit_pre <- feols(log_retail_emp ~ ..(\"^l_\") | fips + year, un, cluster = ~fips)\nb <- coef(fit_pre); V <- vcov(fit_pre)\npre <- rbindlist(lapply(2:22, function(k) {\n  gs <- cohorts[cohorts - k >= 1977]\n  a <- setNames(numeric(length(b)), names(b))\n  a[sprintf(\"l_%d_%d\", gs, gs - k)] <- Ng[J(gs)]$N / sum(Ng[J(gs)]$N)\n  data.table(time = -k, estimate = sum(a * b), se = sqrt(drop(t(a) %*% V %*% a)))\n}))\nggplot(pre, aes(time, estimate)) +\n  geom_hline(yintercept = 0) +\n  geom_pointrange(aes(ymin = estimate - 1.96 * se, ymax = estimate + 1.96 * se),\n                  colour = \"darkcyan\") +\n  labs(x = \"Years until first Walmart\", y = \"Log retail employment\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Weighted pre-treatment estimates from the untreated observations, with 95% intervals. The year before entry is the base.](did-continuous_files/figure-pdf/dc-wm-pre-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nThe leads fall almost linearly as we go back in time. Twenty years before entry, counties that later got a Walmart had retail employment about 19 log points lower, relative to the year before entry, than the never-treated counties. Retail employment was growing faster in these counties long before any store opened. Parallel trends fails, so Wooldridge also reports estimates with the cohort-specific linear trends.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_trend <- feols(log_retail_emp ~ ..(\"^w_\") + ..(\"^tr_\") | fips + year,\n                   wm, cluster = ~fips)\nagg_trend <- aggregate_slopes(fit_trend)\n\ntab <- data.table(exposure = c(0:13, \"overall\"),\n                  no_trends = sprintf(\"%.4f (%.4f)\", agg_het[, 1], agg_het[, 2]),\n                  cohort_trends = sprintf(\"%.4f (%.4f)\", agg_trend[, 1], agg_trend[, 2]))\nknitr::kable(tab, col.names = c(\"Exposure\", \"No trends\", \"Cohort trends\"),\n             align = \"lrr\")\n```\n\n::: {.cell-output-display}\n\n\n|Exposure |       No trends|   Cohort trends|\n|:--------|---------------:|---------------:|\n|0        | 0.0291 (0.0041)| 0.0049 (0.0033)|\n|1        | 0.0439 (0.0042)| 0.0196 (0.0034)|\n|2        | 0.0357 (0.0044)| 0.0113 (0.0035)|\n|3        | 0.0301 (0.0046)| 0.0070 (0.0036)|\n|4        | 0.0286 (0.0048)| 0.0060 (0.0039)|\n|5        | 0.0316 (0.0051)| 0.0073 (0.0041)|\n|6        | 0.0344 (0.0055)| 0.0106 (0.0046)|\n|7        | 0.0412 (0.0063)| 0.0200 (0.0054)|\n|8        | 0.0459 (0.0072)| 0.0236 (0.0064)|\n|9        | 0.0480 (0.0082)| 0.0274 (0.0083)|\n|10       | 0.0624 (0.0104)| 0.0373 (0.0111)|\n|11       | 0.0671 (0.0121)| 0.0422 (0.0146)|\n|12       | 0.0706 (0.0160)| 0.0587 (0.0200)|\n|13       | 0.0895 (0.0210)| 0.0925 (0.0302)|\n|overall  | 0.0386 (0.0051)| 0.0156 (0.0046)|\n\n\n:::\n:::\n\n\nThe table reproduces Table 7.1 of @wooldridge-2026-nonbinary, estimates and standard errors, to all four decimals.\n\nWithout trends, one more store raises retail employment by about 3% to 4% in the first years. The effect climbs to 9% by year 13. The overall effect is 0.0386 (0.0051). It is close to the single-coefficient TWFE estimate of 0.0344, and a little more precise.\n\nThe cohort trends change the estimates a lot. The effect in the entry year is 0.0049 (0.0033), indistinguishable from zero. From the entry year to year 6, the effects are between a sixth and a half of their values without trends. They then rise steadily, and by year 13 the two columns agree at about 0.09. The overall effect falls to 0.0156 (0.0046), less than half the estimate without trends. The trends also make the estimates more precise up to about year 8. The long exposures rest on the earliest cohorts only, so their standard errors grow. Year 13 comes from the 1986 cohort alone.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoeftable(feols(log_retail_emp ~ n_open + ..(\"^tr_\") | fips + year,\n                wm, cluster = ~fips))[\"n_open\", ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Estimate  Std. Error     t value    Pr(>|t|) \n0.009987276 0.004501562 2.218624830 0.026686196 \n```\n\n\n:::\n:::\n\n\nWith the same trends, the single-coefficient regression gives 0.0100 (0.0045). The flexible model costs almost nothing in precision.\n\n## Where it can go wrong\n\nEverything above rests on limited selection. In the Walmart data the dose changes after entry, so @eq-dc-ls requires that the number of stores a county ends up with says nothing about its gain from them. A county where the first store did well is a likely site for a second and a third. If so, high-count counties have larger slopes, and the estimates mix the causal response with selection on gains, as in scenario B of the simulation. Store openings that respond to past retail growth also violate strict exogeneity. The model is also linear in the count, so the second store has the same effect as the first. Adding $W_{it}^2$, or the indicator $1[W_{it} \\ge 2]$ that equals 1 when the county has two or more stores, to $\\mathbf W_{it}$ checks this.\n\nThe trend-adjusted estimates extrapolate a straight line for up to 13 years after entry. The pre-period leads support a straight line before entry. Nothing in the data can check whether it continues after entry. There is a second issue. @eq-dc-reg has no separate intercept for each cohort and year after entry, and every treated county has at least one store. So the trend $D_{ig} \\cdot t$ is fit from post-entry years as well as from the years before. If the effect grows with exposure, part of that growth can load onto the trend. @wolfers-2006 showed this with unit-specific trends for divorce laws. It is one reason the trend estimates are so much smaller in the middle years.\n\nA sensitivity analysis in the style of @rambachan-roth-2023 suits this case. It bounds how far the post-entry path may depart from the extrapolated trend, and reports the effect as a function of that bound.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}