{
  "hash": "6c3c2e4f6d81122bb0d89450e095d97a",
  "result": {
    "engine": "knitr",
    "markdown": "# Shift-Share Instrumental Variables\n\n\n\nShift-share, or Bartik, instruments answer one specific problem, so it is\nclearest to write the regression down first.\n\nWe want the effect of a local economic shock on a local outcome. For region\n$\\ell$,\n\n$$\nY_\\ell \\;=\\; \\beta X_\\ell + Z_\\ell'\\gamma + u_\\ell ,\n$$ {#eq-shift-share-iv-structural}\n\nwhere $X_\\ell$ is the shock the region actually experienced --- local import\ncompetition per worker, in the China-shock literature --- and $Y_\\ell$ is the\noutcome, say the change in the local manufacturing employment share. The\nparameter we want is $\\beta$.\n\nThe endogenous regressor is $X_\\ell$. Regions do not receive their shocks at\nrandom. A region whose import competition rises sharply may be a region whose\nindustries were already losing ground, and whatever caused that decline sits in\n$u_\\ell$ and moves $Y_\\ell$ on its own. Then $\\text{Cov}(X_\\ell, u_\\ell) \\ne 0$,\nand OLS mixes the effect of the shock with the local conditions that produced\nit. We cannot sign that bias in advance; it depends on whether those local\nconditions push the outcome up or down.\n\nThe shift-share instrument replaces the realised local shock with a predicted\none, assembled from two pieces that are meant to have nothing to do with\n$u_\\ell$: each region's *baseline* industry shares, fixed before the outcome\nperiod, and *national* or foreign industry-level shocks, common across regions.\nA region with a large baseline share in an industry is mechanically more exposed\nto a shock hitting that industry, and that exposure is predicted rather than\nrealised.\n\nBuilding the instrument is the easy part. The difficult part is saying which of\nthe two pieces carries the exogeneity assumption --- the shares, the shocks, or\nboth --- because the two answers lead to different identification arguments,\ndifferent diagnostics, and different standard errors. That is what the rest of\nthe chapter is about.\n\n## The construction\n\nFor each location $\\ell$ and industry $k$, let $s_{\\ell k}$ be the share of\nlocal employment in industry $k$ at baseline, and let $g_k$ be a national\ngrowth rate (or trade shock) for that industry. The shift-share instrument is\n\n$$\nB_\\ell \\;=\\; \\sum_{k=1}^{K} s_{\\ell k}\\, g_k.\n$$ {#eq-shift-share-iv-1}\n\nThis is \"shift-share\" because it combines a local share with an\nindustry-level shift. @bartik-1991 used local industry mix to predict local\nemployment growth. @autor-dorn-hanson-2013 used local industry shares\ninteracted with industry-level Chinese import growth in other high-income\ncountries.\n\nThe first-stage regression is then\n\n$$\n\\Delta L_\\ell \\;=\\; \\pi_0 + \\pi_1 B_\\ell + X_\\ell'\\gamma + \\epsilon_\\ell,\n$$ {#eq-shift-share-iv-2}\n\nwith $B_\\ell$ instrumenting for the observed local shock in a 2SLS for the\noutcome of interest.\n\n## Two identification views\n\nThere are two ways to justify a shift-share instrument. They put the\nexogeneity assumption on different objects.\n\n### Share view (GPSS 2020)\n\nTreat the shares $s_{\\ell k}$ as the source of identifying variation, with the\nshocks $g_k$ acting as weights. The instrument is valid if shares are\nexogenous to the outcome (conditional on controls).\n@goldsmith-pinkham-sorkin-swift-2020 (henceforth GPSS) prove that the\nshift-share IV is numerically equivalent to a GMM combination of $K$\njust-identified IVs, one per industry share:\n\n$$\n\\hat\\beta^{SS} \\;=\\; \\sum_{k=1}^{K} \\hat\\alpha_k\\, \\hat\\beta_k,\n$$ {#eq-shift-share-iv-3}\n\nwhere $\\hat\\beta_k$ is the just-identified IV using share $s_{\\cdot k}$ alone\nand $\\hat\\alpha_k$ is the **Rotemberg weight**. This gives an important\ndiagnostic: which industry shares are driving the estimate?\n\n### Shock view (BHJ 2022)\n\nTreat the shocks $g_k$ as the source of identifying variation. Shares are\nexposure weights. Under this view, shocks should be uncorrelated with the\nsecond-stage unobservables, conditional on industry-level controls.\n@borusyak-hull-jaravel-2022 (henceforth BHJ) show how to rewrite the\nregression at the shock level.\n\nThe two views are not mutually exclusive. In an application, we should be\nclear which one is being defended and report diagnostics for both.\n\n## Inference\n\nStandard OLS or cluster-robust standard errors on the regional regression\n**underestimate uncertainty** because the same industry shocks appear in many\nregions, inducing cross-region correlation that region-level clustering does\nnot capture. Two corrections are now standard:\n\n- **Cluster on shocks (BHJ)**: equivalent to running the regression at the\n  industry-shock level. Implemented via shock-level reweighting.\n- **AKM SE** [@adao-kolesar-morales-2019]: explicit formula for SE accounting\n  for shock-level correlation. Available in the `ShiftShareSE` R package.\n\n## Simulation: build intuition\n\nThe aim is to see the shift-share IV recover a known effect that OLS misses,\nand then to break the identifying assumption on purpose and see which\ndiagnostic catches it.\n\nWe use 500 regions and 20 industries. Each region has a vector of industry\nshares $s_{\\ell k}$ summing to one, concentrated so that a few industries\ndominate any given region. Each industry draws a shock $g_k \\sim N(0,1)$,\nindependently of the shares and of everything at the region level. The\ninstrument is $B_\\ell = \\sum_k s_{\\ell k} g_k$.\n\nThere is one region-level confounder $u_\\ell \\sim N(0,1)$. The observed local\nshock and the outcome are\n\n$$\nX_\\ell = B_\\ell + 0.3u_\\ell + \\varepsilon_\\ell, \\qquad\nY_\\ell = 0.5 X_\\ell + u_\\ell + \\eta_\\ell,\n$$ {#eq-shift-share-iv-5}\n\nwith $\\varepsilon$ and $\\eta$ independent noise of standard deviation about 0.3\nand 0.5. The true effect is $\\beta = 0.5$.\n\nBecause $u$ enters both $X$ and $Y$, OLS is biased, and we can say by how much:\n$\\text{Cov}(X,u)/\\text{Var}(X) = 0.3/0.315 = 0.95$, so OLS should return about\n$0.5 + 0.95 = 1.45$.\n\nThe data are generated once and stored as CSVs so that this book and its Julia\ncompanion produce identical numbers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_region   <- 500\nn_industry <- 20\nbeta_true  <- 0.5\n\ndf     <- read_csv(\"data/shift_share_sim.csv\", show_col_types = FALSE)\nshares <- as.matrix(read_csv(\"data/shift_share_shares.csv\", show_col_types = FALSE))\n# This simulation is constructed to satisfy the Borusyak et al. (2022)\n# shock-exogeneity assumption: the industry-level shocks are drawn\n# independently of the region-level confounder `u` and of the shares\n# themselves. The shares are allowed to be endogenous (correlated with\n# region characteristics) -- it is specifically the shocks that must be\n# \"as good as randomly assigned\" for this identification argument, which is\n# a different (and in this simulation, the maintained) assumption from the\n# Goldsmith-Pinkham et al. (2020) shares-exogeneity view discussed above.\nshocks <- read_csv(\"data/shift_share_shocks.csv\", show_col_types = FALSE)$shock\nu      <- df$u\nhead(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 x 5\n  region      X      Y       B      u\n   <dbl>  <dbl>  <dbl>   <dbl>  <dbl>\n1      1 -0.518  0.117 -0.138  -0.308\n2      2  0.213 -1.07   0.547  -0.539\n3      3  0.652  0.892  0.351   1.37 \n4      4  0.286  0.861  0.0385  1.10 \n5      5 -0.334 -0.330  0.421  -0.112\n6      6  0.376 -1.73   1.17   -1.75 \n```\n\n\n:::\n:::\n\n\nA naive OLS suffers from the confounder `u`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols  <- feols(Y ~ X, data = df)\nivss <- feols(Y ~ 1 | X ~ B, data = df)\netable(ols, ivss, headers = c(\"OLS\", \"Shift-share IV\"),\n       digits = 3, digits.stats = 3, fitstat = ~ . + ivf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                   ols             ivss\n                                   OLS   Shift-share IV\nDependent Var.:                      Y                Y\n                                                       \nConstant              -0.154** (0.047)    0.077 (0.059)\nX                      1.45*** (0.075) 0.531*** (0.131)\n_____________________ ________________ ________________\nS.E. type                          IID              IID\nObservations                       500              500\nR2                               0.428            0.025\nAdj. R2                          0.427            0.022\nF-test (1st stage), X               --            370.5\n---\nSignif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nOLS gives 1.45 with a standard error of 0.075, matching the 1.45 predicted\nabove and nearly three times the true effect of 0.5. The shift-share\nIV gives 0.531 with a standard error of 0.131, within a quarter of a standard\nerror of the truth. The first-stage $F$ is 370.5, so the instrument is strong.\n\nNote the price again: the IV standard error is 0.131 against 0.075 for OLS, and\nthe second-stage $R^2$ is 0.025 against 0.428. A biased estimator can fit well.\n\n### Rotemberg weights\n\nThe GPSS decomposition says the shift-share IV is a weighted average of\n$K$ just-identified IVs (one per industry share). Compute the weights:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Rotemberg weight for industry k (using centered moments to match the\n# demeaned 2SLS regression):\n#   alpha_k = g_k * Cov(s_{.k}, X) / sum_j g_j * Cov(s_{.j}, X)\n# Each industry's just-identified IV estimate uses s_{.k} as instrument:\n#   beta_k = Cov(s_{.k}, Y) / Cov(s_{.k}, X)\n# GPSS prove the shift-share IV estimate equals sum_k alpha_k * beta_k.\n\ncov_sk_X <- sapply(1:n_industry, function(k) cov(shares[, k], df$X))\ncov_sk_Y <- sapply(1:n_industry, function(k) cov(shares[, k], df$Y))\ndenom    <- sum(shocks * cov_sk_X)\n\nalpha  <- shocks * cov_sk_X / denom\nbeta_k <- cov_sk_Y / cov_sk_X\n\nrotemberg <- tibble(industry = 1:n_industry,\n                    shock    = shocks,\n                    weight   = alpha,\n                    beta_k   = beta_k)\n\nkable(rotemberg, digits = 3,\n      caption = paste0(\"Rotemberg decomposition. Sum of alpha*beta_k = \",\n                       round(sum(alpha * beta_k), 3),\n                       \" (= shift-share IV estimate of \",\n                       round(coef(ivss)[\"fit_X\"], 3), \").\"))\n```\n\n::: {.cell-output-display}\n\n\nTable: Rotemberg decomposition. Sum of alpha*beta_k = 0.531 (= shift-share IV estimate of 0.531).\n\n| industry|  shock| weight|  beta_k|\n|--------:|------:|------:|-------:|\n|        1|  1.250|  0.054|   0.604|\n|        2| -0.959|  0.048|   0.244|\n|        3| -0.212|  0.005|   2.576|\n|        4|  0.745|  0.002| -10.225|\n|        5|  2.663|  0.387|   0.469|\n|        6| -1.068|  0.082|   1.025|\n|        7|  0.100| -0.001|  -1.627|\n|        8| -0.718|  0.025|  -0.689|\n|        9|  1.181|  0.058|   0.853|\n|       10| -0.197|  0.004|   1.188|\n|       11|  0.741|  0.023|  -0.112|\n|       12|  0.051| -0.001|  -0.055|\n|       13| -0.442|  0.014|   0.611|\n|       14|  0.270|  0.003|  -0.013|\n|       15|  0.631|  0.003|  -3.240|\n|       16|  2.271|  0.204|   0.746|\n|       17| -0.212|  0.001|   0.174|\n|       18| -0.115|  0.000| -39.532|\n|       19|  0.020|  0.000|   1.234|\n|       20| -1.183|  0.089|   0.554|\n\n\n:::\n:::\n\n\nThe weighted sum reproduces the 2SLS estimate exactly: $\\sum_k \\alpha_k\n\\hat\\beta_k = 0.531$, which is the shift-share IV coefficient. That is the GPSS\nequivalence, and it holds numerically, not approximately.\n\nThe weights are concentrated. Industry 5 carries 0.387 and industry 16 carries\n0.204, so those two supply nearly 60% of the identifying variation, and the\nnext three (industries 20, 6 and 9) bring the total past 80%. Under the share\nview, the exogeneity of those few industries' shares is the assumption the\nestimate rests on. Notice that the two dominant industries are also the two\nwith the largest shocks, 2.66 and 2.27: $\\alpha_k$ is proportional to $g_k\n\\text{Cov}(s_{\\cdot k}, X)$, so a big shock buys influence.\n\nThe $\\hat\\beta_k$ column is more surprising and worth reading carefully.\nIndustry 18 gives $-39.5$, industry 4 gives $-10.2$, industry 15 gives $-3.2$.\nThese are not near the true 0.5, and it would be easy to read them as evidence\nof severe treatment-effect heterogeneity. They are not. Each $\\hat\\beta_k =\n\\text{Cov}(s_{\\cdot k}, Y)/\\text{Cov}(s_{\\cdot k}, X)$ is a just-identified IV\nusing one share as the instrument, and when $\\text{Cov}(s_{\\cdot k}, X)$ is\nnear zero that ratio explodes. It is a weak-instrument artefact, one industry\nat a time.\n\nThe decomposition is immune to it by construction. Since\n\n$$\n\\alpha_k \\hat\\beta_k\n= \\frac{g_k \\text{Cov}(s_{\\cdot k}, X)}{\\sum_j g_j \\text{Cov}(s_{\\cdot j}, X)}\n  \\cdot \\frac{\\text{Cov}(s_{\\cdot k}, Y)}{\\text{Cov}(s_{\\cdot k}, X)}\n= \\frac{g_k \\text{Cov}(s_{\\cdot k}, Y)}{\\sum_j g_j \\text{Cov}(s_{\\cdot j}, X)},\n$$ {#eq-shift-share-iv-6}\n\nthe troublesome $\\text{Cov}(s_{\\cdot k}, X)$ cancels. Every industry with an\nexploding $\\hat\\beta_k$ has a weight near zero for exactly the same reason its\n$\\hat\\beta_k$ blew up. Industry 18 carries a weight of 0.000 and industry 4 a\nweight of 0.002.\n\nRead the two columns together, then. Among the industries that carry real\nweight, the estimates are 0.469, 0.746, 0.554, 1.025, 0.853 and 0.604 --- close\nenough to 0.5 to be sampling noise, which is what we should see in a simulation\nwith a homogeneous effect. In real data, if industries with *large* weights\ngive very different estimates, the shift-share IV is averaging over genuine\nheterogeneity and that should be reported.\n\nThe plot below makes the pairing visible: each industry's just-identified IV\nestimate on the vertical axis, with point size proportional to its Rotemberg\nweight. The outlying estimates are the smallest points.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(rotemberg, aes(x = factor(industry), y = beta_k, size = abs(weight))) +\n  geom_hline(yintercept = beta_true, linetype = \"dashed\", color = \"red\") +\n  geom_point(alpha = 0.7) +\n  scale_size_continuous(name = \"|Rotemberg weight|\") +\n  labs(x = \"Industry\", y = \"Just-identified IV estimate\",\n       title = \"Industry-level IV estimates and weights\",\n       subtitle = paste(\"Red line = true effect =\", beta_true)) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](shift-share-iv_files/figure-pdf/rotemberg-plot-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n### What goes wrong when shares are endogenous\n\nNow break the share-exogeneity assumption on purpose. We introduce a second\nregion-level confounder $v_\\ell$, add $0.15 v_\\ell$ to industry 1's share\n(renormalising the rows to sum to one), and let $v$ enter the outcome with\ncoefficient 0.6:\n\n$$\nY_\\ell = 0.5 X_\\ell + u_\\ell + 0.6 v_\\ell + \\eta_\\ell .\n$$ {#eq-shift-share-iv-7}\n\nEverything else is unchanged. Industry 1's share is now correlated with the\nsecond-stage error, so the instrument built from it is invalid, and we ask\nwhich diagnostic notices.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Re-do shares so industry 1's share covaries with a new confounder v\nv <- read_csv(\"data/shift_share_bad_v.csv\", show_col_types = FALSE)$v\nshares_bad <- shares\nshares_bad[, 1] <- pmax(0.01, shares[, 1] + 0.15 * v)\nshares_bad <- shares_bad / rowSums(shares_bad)   # renormalise to sum to 1\n\nbad_noise <- read_csv(\"data/shift_share_bad_noise.csv\", show_col_types = FALSE)\nB_bad <- as.numeric(shares_bad %*% shocks)\nX_bad <- B_bad + 0.3 * u + bad_noise$noise_x\nY_bad <- beta_true * X_bad + u + 0.6 * v + bad_noise$noise_y\n\ndf_bad <- tibble(X = X_bad, Y = Y_bad, B = B_bad)\nivss_bad <- feols(Y ~ 1 | X ~ B, data = df_bad)\ncat(\"True beta:\", beta_true, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue beta: 0.5 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Shift-share IV with bad share 1:\", round(coef(ivss_bad)[\"fit_X\"], 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nShift-share IV with bad share 1: 0.798 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Rotemberg weights recomputed under the bad shares\ncov_sk_X_bad <- sapply(1:n_industry, function(k) cov(shares_bad[, k], X_bad))\nalpha_bad    <- shocks * cov_sk_X_bad / sum(shocks * cov_sk_X_bad)\ncat(\"Rotemberg weight of industry 1:\", round(alpha_bad[1], 3),\n    \"-- rank\", rank(-abs(alpha_bad))[1], \"of\", n_industry, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRotemberg weight of industry 1: 0.11 -- rank 3 of 20 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Leave-one-industry-out: rebuild the instrument without industry 1\nB_loo    <- as.numeric(shares_bad[, -1] %*% shocks[-1])\nivss_loo <- feols(Y ~ 1 | X ~ B, data = tibble(X = X_bad, Y = Y_bad, B = B_loo))\ncat(\"Shift-share IV without industry 1:\", round(coef(ivss_loo)[\"fit_X\"], 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nShift-share IV without industry 1: 0.48 \n```\n\n\n:::\n:::\n\n\nThe estimate moves from 0.531 to 0.798 against a true 0.5, so one endogenous\nshare out of twenty is enough to inflate the estimate by 60%. Note which\ndiagnostic catches it. Rotemberg weights\nmeasure *influence* --- whose exogeneity the estimate leans on --- not\nendogeneity: the offending industry carries a weight of only 0.11, third\nlargest of twenty, yet it alone moves the estimate from 0.5 to 0.8. The\nleave-one-industry-out check is what isolates it: rebuilding the instrument\nwithout industry 1 restores the estimate to 0.48.\n\n## Empirical: the China shock (Autor, Dorn, Hanson 2013)\n\nThe standard shift-share application is the China-shock study of\n@autor-dorn-hanson-2013 (henceforth ADH). Commuting zones are exposed\ndifferently to Chinese import competition because their baseline industry\nmixes differ. The instrument is\n\n$$\n\\text{IV}_\\ell \\;=\\; \\sum_k \\frac{L_{\\ell k,\\,1990}}{L_{\\ell,\\,1990}}\\,\n                   \\frac{\\Delta M^{other}_{k}}{L_{k,\\,1990}},\n$$ {#eq-shift-share-iv-4}\n\nwhere the shocks $\\Delta M^{other}_k$ are growth in Chinese imports into\nother high-income countries. This leave-one-out construction removes\nUS-specific demand from the shock. In the actual ADH design the employment\nshares are lagged one census behind the outcome period (e.g. 1980 employment\nfor the 1990--2000 stack), precisely to mitigate share endogeneity; we date\neverything to 1990 here to keep the notation light.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# David Dorn distributes the replication data at\n# https://www.ddorn.net/data.htm — files needed:\n#   workfile_china.dta  (commuting zone data, 1990-2007)\n#   industry_shares.csv (czone-industry shares)\n#   industry_imports.csv (industry-level imports)\n\nlibrary(haven)\nlibrary(fixest)\n\ncz   <- read_dta(\"workfile_china.dta\")\nfit  <- feols(d_sh_empl_mfg ~ 1 | d_tradeusch_pw ~ d_tradeotch_pw_lag,\n              data = cz,\n              cluster = ~ statefip)\nsummary(fit)\n```\n:::\n\n\nModern best-practice extensions of the basic ADH regression. These blocks are\nschematic --- they do not run here, so check argument names against the\ncurrent package documentation before adapting them:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Rotemberg weights via the bartik.weight package (Goldsmith-Pinkham)\n# devtools::install_github(\"paulgp/bartik-weight\")\nlibrary(bartik.weight)\nrw <- bw(cz, master = master_spec, y = \"d_sh_empl_mfg\",\n         x = \"d_tradeusch_pw\", weight = \"timepwt48\",\n         G = G_growth, Z = Z_shares)\n\n# Plot the Rotemberg weights to see which industries drive the estimate\nplot(rw)\n\n# 2. Adão-Kolesár-Morales standard errors\n# devtools::install_github(\"kolesarm/ShiftShareSE\")\nlibrary(ShiftShareSE)\nivreg_ss(d_sh_empl_mfg ~ d_tradeusch_pw + controls,\n         X = \"d_tradeotch_pw_lag\",\n         data = cz, W = shock_weights, region_cvar = \"czone\",\n         method = \"akm0\")\n\n# 3. BHJ shock-level inference: collapse to shock (industry-period) level\n# devtools::install_github(\"borusyak/shift-share\")\nlibrary(ssaggregate)\nshocks_data <- ssaggregate(data = cz, vars = c(\"d_sh_empl_mfg\",\n                                                \"d_tradeusch_pw\"),\n                            shock = \"d_tradeotch_pw_lag\", weights = \"timepwt48\",\n                            l = \"czone\", n = \"industry\", t = \"year\",\n                            s = \"share\")\n# Now regress at shock level — interpretation: shock-level IV\nfeols(d_sh_empl_mfg ~ 1 | d_tradeusch_pw ~ shock, data = shocks_data)\n```\n:::\n\n\nFor a new shift-share paper, I would expect Rotemberg weights, AKM standard\nerrors, and a BHJ shock-level version or an explanation for why it is not\nappropriate.\n\n## Summary\n\n- Shift-share IV combines local shares and industry shocks.\n- The GPSS view puts exogeneity on shares; the BHJ view puts it on shocks.\n- Rotemberg weights show which industry shares drive the 2SLS estimate.\n- Region-level clustering is usually too optimistic. Use AKM standard errors\n  or shock-level inference when possible.\n- In R, `fixest`, `bartik.weight`, `ShiftShareSE`, and `ssaggregate` cover\n  most of the workflow.\n\nFor a longer treatment --- more on the GPSS decomposition, the Rotemberg weights,\nand the inference options --- see\n[The Bartik instrument](https://xiangao.github.io/blog_book/bartik-instrument.html)\nin *Topics on Econometrics and Causal Inference*.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}