{
  "hash": "c48e6efd17a999eb9f51996839d039e9",
  "result": {
    "engine": "knitr",
    "markdown": "# Difference-in-Differences\n\n\n\nWhen unconfoundedness fails, we need weaker assumptions. The parallel trends assumption leads to the difference-in-differences estimator.\n\n> **Related reading**: For a side-by-side comparison of DiD, synthetic\n> control, synthetic DiD, and multivariate SC on a *single* panel — and\n> how the choice of estimator changes the answer — see the\n> [Same data, different estimators](https://xiangao.github.io/blog_book/same-data-different-estimators.html)\n> chapter in *Topics on Econometrics and Causal Inference*.\n\n## $T=2$ Panel Data\n\nSuppose we have two periods, $t = (1,2)$. Some units are treated just prior to period 2. For each individual $i$, there are four potential outcomes:\n\n$$ [Y_{i1}(0), Y_{i1}(1), Y_{i2}(0), Y_{i2}(1)] $$ {#eq-did-1}\n\nLet $D$ denote the treated group. The ATT in period 2 is\n\n$$ \\tau_{2,att} = E(Y_2(1) - Y_2(0) | D=1) $$ {#eq-did-2}\n\nThe first term is observed. The second is the counterfactual.\n\n## Parallel Trends Assumption\n\n$$ E[Y_2(0) -Y_1(0) | D=1] = E[Y_2(0) - Y_1(0) | D =0] $$ {#eq-did-3}\n\nor\n\n$$ E[\\Delta Y(0) | D=1] = E[\\Delta Y(0) | D =0] $$ {#eq-did-4}\n\nIn words, the change in untreated potential outcomes between periods 1 and 2 is the same for treated and control groups.\n\n## No Anticipation Assumption\n\n$$ E[Y_1(1) - Y_1(0) | D=1] = 0 $$ {#eq-did-5}\n\nThis is to say, in period 1, there is no treatment effect for the treated group.\n\n## DiD is Identified with PT and NA\n\nWith Parallel Trends, we notice $$\\small  E[Y_2(0) | D=1 ]= E[Y_1(0) | D=1] + E[Y_2(0) - Y_1(0) | D=0] $$ {#eq-did-6}\n\nThen, with No Anticipation, $$\n\\begin{aligned}\nE[Y_2(0) | D=1 ] &= E[Y_1(1) | D=1] + E[Y_2(0) - Y_1(0) | D=0]\\\\\n&= E[Y_1 | D=1] + E[Y_2-Y_1 | D=0]\n\\end{aligned}\n$$ {#eq-did-7} \n\n$$\\small  \\tau_{2,att} = E[Y_2 - Y_1 | D=1] - E[Y_2-Y_1 | D=0] $$ {#eq-did-8}\n\n## Advantages and Disadvantages of DiD\n\nAdvantages:\n\n-   No need to assume unconfoundedness. We \"only\" need PT and NA. Or say we don't need treatment itself to be independent of potential outcomes, but we do need it to be independent to the change in potential outcome at least for untreated state. This is importantly weaker in a lot of situations. There can be selection bias. If the selection bias does not change over time, then DiD can handle it.\n\nDisadvantages:\n\n-   PT and NA might be violated.\n-   PT is not scale free, in the sense that even if outcome can have PT, but then non-linear transformation of outcome won't have PT (for example log of Y).\n\n## Traditional DiD\n\nIn practice, DiD in many period setting is usually done with\n\n$$ Y_{it} = \\alpha_i + \\phi_t + W_{it} \\beta + \\epsilon_{it} $$ {#eq-did-9}\n\nhere $W_{it} =(1[t=2] \\cdot D_i)$, which is the interaction of post-treatment indicator and treatment group indicator.\n\nThis is usually called Two Way Fixed Effect (TWFE). There are multiple ways to implement the same model in practice.\n\nTWFE can be done by \"Pooled OLS\". That is, using OLS on time dummies and firm (individual) dummies. Wooldridge (2021) shows it's equivalent to use treatment dummies, instead of individual dummies. He also shows that this model can be equivalently implemented with fixed effect model and random effect model.\n\n## TWFE with Staggered Treatment Timing\n\nThe problem comes in when there is different timing of treatment. People used to still use\n\n$$ Y_{it} = \\alpha_i + \\phi_t + W_{it} \\beta + \\epsilon_{it} $$ {#eq-did-10}\n\nwhere $W_{it}$ now is a dummy when an individual $i$ gets treated at time $t$.\n\nHowever, what is $\\beta$ here?\n\n## Goodman-Bacon Decomposition\n\nGoodman-Bacon (2021) showed that $\\beta$ in the TWFE is a weighted average of many different treatment effects, between treated cohorts, and control units, both can be different at different time points. The weights are a function of the size of the subsample, relative size of treatment and control units, and the timing of treatment in the sub sample. The decomposition weights themselves are non-negative and sum to one; the problem is that the units treated earlier are used as controls later. When those \"forbidden\" 2x2 comparisons are expressed in terms of the underlying cohort-time ATTs, some ATTs receive negative weight (de Chaisemartin and D'Haultfœuille 2020). Therefore there is no meaningful interpretation of $\\beta$: it does not need to be a convex combination of treatment effects.\n\n![Bacon decomposition](images/bacon1.png)\n\n![Bacon decomposition](images/bacon2.png)\n\n## Wooldridge's ETWFE\n\nThere are a lot of ways to deal with staggered DiD situation. Wooldridge (2021) is basically saying: This is not a problem of TWFE, it's a mis-use of TWFE. The reason we get non-sensible result of $\\beta$ is that we know there is heterogeneous treatment effect, in the sense the treatment effect differs across cohort, but we force them to be the same. If we relax it, it can work. As he shows, this works when we specify cohort effects accordingly.\n\n$$ y_{it} = \\alpha_i + \\phi_t + \\sum_{g=g_0}^G \\sum_{t=g}^T \\lambda_{g,t} \\times 1(g,t) + \\epsilon_{i,t} $$ {#eq-did-11}\n\nHere $g$ is a cohort indicator, a cohort is determined by the time of getting treatment. ETWFE is allowing each cohort to have different effect at each different time point after being treated. The baseline group is the never treated group. If there is no never treated group, it can easily be changed to comparing to the last treated group.\n\n## Example 1: US Teen Employment\n\nWe'll use the mpdta dataset on US teen employment from the did package. \"Treatment\" in this dataset refers to an increase in the minimum wage rate. Our goal is to estimate the effect of this minimum wage treatment (treat) on the log of teen employment (lemp). Notice that the panel ID is at the county level (countyreal), but treatment was staggered across cohorts (first.treat) so that a group of counties were treated at the same time. In addition to these staggered treatment effects, we also observe log population (lpop) as a potential control variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"mpdta\", package = \"did\")\nhead(mpdta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    year countyreal     lpop     lemp first.treat treat\n866 2003       8001 5.896761 8.461469        2007     1\n841 2004       8001 5.896761 8.336870        2007     1\n842 2005       8001 5.896761 8.340217        2007     1\n819 2006       8001 5.896761 8.378161        2007     1\n827 2007       8001 5.896761 8.487352        2007     1\n937 2003       8019 2.232377 4.997212        2007     1\n```\n\n\n:::\n:::\n\n\nThe three tables below give the panel shape: observations per year, the\never-treated indicator, and the treatment cohorts.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(mpdta$year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n2003 2004 2005 2006 2007 \n 500  500  500  500  500 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(mpdta$treat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   0    1 \n1545  955 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(mpdta$first.treat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   0 2004 2006 2007 \n1545  100  200  655 \n```\n\n\n:::\n:::\n\n\nThe panel is balanced: 500 counties observed in each of 2003 through 2007,\n2,500 observations. 955 observations belong to ever-treated counties and 1,545\nto never-treated ones. The cohorts are 2004 (100 observations, so 20 counties),\n2006 (200, or 40 counties) and 2007 (655, or 131 counties), with 309 counties\nnever treated. Treatment timing is staggered, which is exactly the case where\nplain TWFE misbehaves.\n\nWe fit ETWFE with log population as a control, clustering on county.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(etwfe)\n\nmod =\n  etwfe(\n    fml  = lemp ~ lpop, # outcome ~ controls\n    tvar = year,        # time variable\n    gvar = first.treat, # group variable\n    data = mpdta,       # dataset\n    vcov = ~countyreal  # vcov adjustment (here: clustered)\n    )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS estimation, Dep. Var.: lemp\nObservations: 2,500\nFixed-effects: first.treat: 4,  year: 5\nStandard-errors: Clustered (countyreal) \n                        Estimate Std. Error   t value  Pr(>|t|)    \nlpop                    1.065461   0.021824 48.821102 < 2.2e-16 ***\nfirst.treat::2004:lpop  0.050982   0.037756  1.350320  0.177525    \nfirst.treat::2006:lpop -0.041095   0.047390 -0.867183  0.386259    \nfirst.treat::2007:lpop  0.055518   0.039212  1.415838  0.157447    \nyear::2004:lpop         0.011014   0.007554  1.458043  0.145458    \nyear::2005:lpop         0.020733   0.008104  2.558268  0.010814 *  \nyear::2006:lpop         0.010535   0.010816  0.974084  0.330487    \nyear::2007:lpop         0.020921   0.011808  1.771708  0.077053 .  \n... 14 coefficients remaining (display them with summary() or use\nargument n)\n... 10 variables were removed because of collinearity\n(.Dtreat:first.treat::2006:year::2004,\n.Dtreat:first.treat::2006:year::2005 and 8 others [full set in\n$collin.var])\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 0.537131     Adj. R2: 0.871722\n                 Within R2: 0.869464\n```\n\n\n:::\n:::\n\n\nThe raw model has one coefficient per cohort-year cell plus the control\ninteractions, 22 in all, and ten more were dropped for collinearity. That is not\nsomething to read directly. `emfx()` aggregates the cells into the ATT.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemfx(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n .Dtreat Estimate Std. Error     z Pr(>|z|)    S   2.5 %  97.5 %\n    TRUE  -0.0506     0.0125 -4.05   <0.001 14.3 -0.0751 -0.0261\n\nTerm: .Dtreat\nType: response\nComparison: TRUE - FALSE\n```\n\n\n:::\n:::\n\n\nThe ATT is $-0.0506$ with a standard error of 0.0125 and a 95% interval of\n$[-0.0751, -0.0261]$. Raising the minimum wage lowered teen employment by about\n5% on average across treated county-years.\n\nThe same cells can be aggregated by time since treatment instead.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_es = emfx(mod, type = \"event\")\nmod_es\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n event Estimate Std. Error     z Pr(>|z|)    S   2.5 %   97.5 %\n     0  -0.0332     0.0134 -2.48    0.013  6.3 -0.0594 -0.00702\n     1  -0.0573     0.0171 -3.34   <0.001 10.2 -0.0910 -0.02373\n     2  -0.1379     0.0308 -4.48   <0.001 17.0 -0.1982 -0.07753\n     3  -0.1095     0.0323 -3.39   <0.001 10.5 -0.1729 -0.04620\n\nTerm: .Dtreat\nType: response\nComparison: TRUE - FALSE\n```\n\n\n:::\n:::\n\n\nThe effect grows with exposure: $-0.033$ in the treatment year, $-0.057$ after\none year, $-0.138$ after two, $-0.110$ after three. All four are significant.\nThe standard errors widen with event time, from 0.013 to 0.032, because the\nlater horizons rest on fewer cohorts: event time 0 uses all three cohorts (191\ncounties), event time 1 uses the 2004 and 2006 cohorts (60 counties), and event\ntimes 2 and 3 rest on the 2004 cohort alone (20 counties).\n\nAdding `post_only = FALSE` keeps the pre-treatment periods in the plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_es2 = emfx(mod, type = \"event\", post_only = FALSE)\n\nggplot(mod_es2, aes(x = event, y = estimate, ymin = conf.low, ymax = conf.high)) +\n  geom_hline(yintercept = 0) +\n  geom_vline(xintercept = -1, lty = 2) +\n  geom_pointrange(col = \"darkcyan\") +\n  labs(\n    x = \"Years post treatment\", y = \"Effect on log teen employment\",\n    caption = \"Note: Zero pre-treatment effects for illustrative purposes only.\"\n  )\n```\n\n::: {.cell-output-display}\n![](did_files/figure-pdf/did7-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nRead the pre-treatment points with care, and note the caption on the figure.\nWith `etwfe`'s default comparison group the pre-treatment estimates are forced\nto zero by construction, so their sitting on the line is arithmetic, not\nevidence for parallel trends. The Poisson example below uses\n`cgroup = \"never\"`, which frees them and makes the pre-period a real check.\n\n## Example 2: Staggered DiD\n\nTo see whether ETWFE recovers what it should, we switch to simulated data where\nthe answer is recorded in the file.\n\n`data/did_staggered_6.dta` is Wooldridge's simulated staggered panel: 500 units\nobserved annually from 2001 to 2006, 3,000 observations. Units are treated in\n2004 (119 units), 2005 (83) or 2006 (36), and 262 are never treated. The\noutcome is `y`, `x` is a covariate, `d4`, `d5` and `d6` are cohort dummies, and\n`f04`, `f05`, `f06` are year dummies. What makes the file useful is `te4`,\n`te5` and `te6`: the true unit-level treatment effect each unit would\nexperience under each cohort's treatment date. The effects are heterogeneous\nacross units and grow with time since treatment, which is precisely the\nconfiguration that breaks plain TWFE.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# now we do staggered did.\nlibrary(haven)\ndid_data <- read_dta('data/did_staggered_6.dta') %>%\n  mutate(first_treat = case_when(d4==1 ~ 2004,\n                                  d5==1 ~ 2005,\n                                  d6==1 ~ 2006,\n                                  .default = 0))\n\nhead(did_data %>% select(id, year, y, x,d4, d5, d6, te4, te5, te6, first_treat ))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 x 11\n     id  year     y     x    d4    d5    d6   te4   te5   te6 first_treat\n  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>       <dbl>\n1     1  2001  18.4 0.900     0     0     0  0     0    0               0\n2     1  2002  18.1 0.900     0     0     0  0     0    0               0\n3     1  2003  18.6 0.900     0     0     0  0     0    0               0\n4     1  2004  16.5 0.900     0     0     0  1.43  0    0               0\n5     1  2005  20.0 0.900     0     0     0  2.57  2.25 0               0\n6     1  2006  19.9 0.900     0     0     0  5.07  4.23 0.786           0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(did_data$first_treat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   0 2004 2005 2006 \n1572  714  498  216 \n```\n\n\n:::\n:::\n\n\nThe counts are observations, six per unit: 1,572 never-treated, 714 in the 2004\ncohort, 498 in 2005, 216 in 2006.\n\nBecause the true effects are in the data, we can compute the target before\nestimating it. Grouping the true effects by cohort and year gives the true ATT\nin each cohort-year cell.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndid_data <- did_data %>%\n  mutate(treated_cohort1 =    case_when(d4 & f04 ~ \"d4f04\",\n                              d4 & f05 ~ \"d4f05\",\n                              d4 & f06 ~ \"d4f06\"),\n         treated_cohort2 = case_when (\n                              d5 & f05 ~ \"d5f05\",\n                              d5 & f06 ~ \"d5f06\"),\n         treated_cohort3= case_when(\n                              d6 & f06 ~ \"d6f06\"))\n\n  did_data %>%\n    group_by(treated_cohort1) %>%\n    summarise(mean4=mean(te4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 x 2\n  treated_cohort1 mean4\n  <chr>           <dbl>\n1 d4f04            3.76\n2 d4f05            4.02\n3 d4f06            4.58\n4 <NA>             1.83\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  did_data %>%\n    group_by(treated_cohort2) %>%\n    summarise(mean5=mean(te5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 x 2\n  treated_cohort2 mean5\n  <chr>           <dbl>\n1 d5f05           2.74 \n2 d5f06           3.52 \n3 <NA>            0.978\n```\n\n\n:::\n\n```{.r .cell-code}\n  did_data %>%\n    group_by(treated_cohort3) %>%\n    summarise(mean6=mean(te6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 x 2\n  treated_cohort3 mean6\n  <chr>           <dbl>\n1 d6f06           1.85 \n2 <NA>            0.329\n```\n\n\n:::\n:::\n\n\nSo the true cohort-year ATTs are: the 2004 cohort gains 3.76, 4.02 and 4.58 in\n2004, 2005 and 2006; the 2005 cohort gains 2.74 and 3.52 in 2005 and 2006; the\n2006 cohort gains 1.85 in 2006. (The `NA` rows are the units outside that\ncohort, which are not part of its ATT.) Effects grow with time since treatment\nand shrink across later cohorts --- heterogeneity in both directions.\n\nAveraging those cells over the 559 treated observations gives a true overall\nATT of **3.677**. That is the number ETWFE has to reproduce.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(etwfe)\n\n# this replicates Jeff's results with pooled ols or xtreg, with covariate x.\nmod =\n  etwfe(\n    fml  = y ~ x, # outcome ~ controls\n    tvar = year,        # time variable\n    gvar = first_treat, # group variable\n    data = did_data,       # dataset\n    vcov = ~id\n        )\n\nmod\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS estimation, Dep. Var.: y\nObservations: 3,000\nFixed-effects: first_treat: 4,  year: 6\nStandard-errors: Clustered (id) \n                     Estimate Std. Error   t value  Pr(>|t|)    \nx                    0.240952   0.452664  0.532298 0.5947564    \nfirst_treat::2004:x -1.191253   0.934130 -1.275254 0.2028127    \nfirst_treat::2005:x  0.551133   0.606947  0.908042 0.3642944    \nfirst_treat::2006:x  0.994478   0.827570  1.201685 0.2300556    \nyear::2002:x         0.395894   0.327576  1.208558 0.2274050    \nyear::2003:x         0.975554   0.319476  3.053604 0.0023818 ** \nyear::2004:x         0.330593   0.350924  0.942064 0.3466155    \nyear::2005:x         0.238847   0.398165  0.599869 0.5488659    \n... 13 coefficients remaining (display them with summary() or use\nargument n)\n... 18 variables were removed because of collinearity\n(.Dtreat:first_treat::2004:year::2002,\n.Dtreat:first_treat::2004:year::2003 and 16 others [full set in\n$collin.var])\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 2.92391     Adj. R2: 0.194759\n                Within R2: 0.110397\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemfx(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n .Dtreat Estimate Std. Error    z Pr(>|z|)     S 2.5 % 97.5 %\n    TRUE     3.67      0.172 21.3   <0.001 333.2  3.33   4.01\n\nTerm: .Dtreat\nType: response\nComparison: TRUE - FALSE\n```\n\n\n:::\n:::\n\n\nETWFE gives 3.67 with a standard error of 0.172 and a 95% interval of\n$[3.33, 4.01]$, against a true 3.677. It recovers the ATT to three decimals.\n\nThe same holds for the disaggregations. By time since treatment:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_es = emfx(mod, type = \"event\")\nmod_es\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n event Estimate Std. Error    z Pr(>|z|)     S 2.5 % 97.5 %\n     0     3.11      0.213 14.6   <0.001 158.5  2.69   3.53\n     1     4.02      0.248 16.2   <0.001 193.4  3.53   4.51\n     2     4.21      0.331 12.7   <0.001 120.9  3.56   4.86\n\nTerm: .Dtreat\nType: response\nComparison: TRUE - FALSE\n```\n\n\n:::\n:::\n\n\nEstimated 3.11, 4.02 and 4.21 at event times 0, 1 and 2, against true values of\n3.11, 3.81 and 4.58. Every interval covers its truth, and the estimates\nreproduce the growth in the effect with exposure.\n\nAnd by calendar year:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_es2 = emfx(mod, type = \"calendar\")\nmod_es2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n year Estimate Std. Error    z Pr(>|z|)     S 2.5 % 97.5 %\n 2004     3.51      0.303 11.6   <0.001 100.6  2.92   4.10\n 2005     3.73      0.253 14.7   <0.001 160.9  3.24   4.23\n 2006     3.70      0.249 14.8   <0.001 163.0  3.21   4.19\n\nTerm: .Dtreat\nType: response\nComparison: TRUE - FALSE\n```\n\n\n:::\n:::\n\n\nEstimated 3.51, 3.73 and 3.70 in 2004, 2005 and 2006, against true values of\n3.76, 3.49 and 3.80. Again all three intervals cover.\n\nNote that the calendar profile is nearly flat while the event-time profile\nrises. There is no contradiction: later calendar years mix an older cohort with\nlarge accumulated effects and a newly treated cohort with small ones, and the\ntwo movements offset. This is why the aggregation has to be chosen to match the\nquestion being asked.\n\n## Nonlinear ETWFE: Count and Binary Outcomes\n\n> **Related reading**: The theory behind nonlinear ETWFE --- Wooldridge's\n> conditional parallel-trends assumption on the linear index, the incidental\n> parameters argument for cohort rather than unit intercepts, and the average\n> partial effects that follow --- is developed at length in\n> [Extended two-way fixed effects](https://xiangao.github.io/blog_book/extended-twfe.html)\n> in *Topics on Econometrics and Causal Inference*, with\n> [count data](https://xiangao.github.io/blog_book/count-data.html) and\n> [Poisson with exposure](https://xiangao.github.io/blog_book/poisson-exposure.html)\n> covering the count case in more detail.\n\nETWFE is not limited to linear (continuous) outcomes. When the dependent variable is a count or a binary indicator, linear TWFE can give nonsensical results — negative predicted probabilities, additive effects that ignore the bounded or non-negative nature of $Y$. The `etwfe` package supports nonlinear families via the `family` argument, which passes to `fixest::feglm()`.\n\nThe key identifying assumption shifts slightly. Instead of parallel trends on $E[Y_{it}(\\infty)]$, we assume parallel trends on the **linear index** — that is, on $\\log E[Y_{it}(\\infty)]$ for Poisson, or on $\\text{logit}\\, E[Y_{it}(\\infty)]$ for logit. This is Wooldridge's (2023) Conditional Parallel Trends assumption stated on $G^{-1}(E[Y])$. When the true treatment effect is multiplicative (e.g., a policy raises counts by 50% regardless of baseline), this assumption is more natural than additive PT on $Y$ itself.\n\nOne implementation detail matters: the nonlinear ETWFE specification uses **cohort fixed effects** (one intercept per treatment cohort) plus year fixed effects — not individual unit fixed effects. The `etwfe` package handles this automatically. In the linear case the two are numerically equivalent (Wooldridge 2021), but in nonlinear models unit fixed effects raise the incidental-parameters problem and make average partial effects uncomputable — the unit intercepts cannot be averaged out of the nonlinear link. Wooldridge (2023) instead uses cohort intercepts (a Mundlak device), which is what `etwfe` implements.\n\n### Simulated example: staggered count data\n\nWe simulate $N = 400$ units over $T = 6$ periods, 2,400 observations. Units are\nsplit into four groups of 100 by id: the first is treated from period 3, the\nsecond from period 4, the third from period 5, and the fourth never. Each unit\ndraws a fixed effect $\\alpha_i \\sim N(0, 0.3^2)$. The log mean is\n$\\log \\mu_{it} = 1 + 0.2t + \\alpha_i + 0.4 D_{it}$, and the outcome is\n$Y_{it} \\sim \\text{Poisson}(\\mu_{it})$.\n\nThe treatment effect is multiplicative and homogeneous on the log scale: every\ntreated unit's expected count rises by a factor of $\\exp(0.4)$, that is by\n$\\exp(0.4) - 1 = 0.492$, or 49%. Parallel trends holds on the log scale by\nconstruction, and fails on the level scale, since a constant proportional\neffect is a larger absolute effect for units with higher baselines.\n\nOn the count scale the ATT is not 0.492. It is\n$E[\\mu_{it}(0) \\mid \\text{treated}] \\times (\\exp(0.4)-1)$, and the mean\nuntreated count among treated observations is 7.649, so the true ATT is\n$7.649 \\times 0.4918 = 3.762$ counts.\n\nThe table below reports mean counts by cohort and treatment status.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(etwfe)\n\nset.seed(42)\nN <- 400; Tmax <- 6\n\nunit_fe_vals <- rnorm(N) * 0.3\n\ndf_count <- expand.grid(id = 1:N, year = 1:Tmax) %>%\n  as_tibble() %>%\n  arrange(id, year) %>%\n  mutate(\n    cohort_grp  = ((id - 1) %/% 100) + 1,\n    first_treat = c(3, 4, 5, 0)[cohort_grp],   # 0 = never treated\n    treated     = (first_treat > 0) & (year >= first_treat),\n    unit_fe     = unit_fe_vals[id],\n    log_mu      = 1 + 0.2 * year + unit_fe + 0.4 * treated,\n    count       = rpois(n(), exp(log_mu))\n  )\n\ndf_count %>%\n  group_by(first_treat, treated) %>%\n  summarise(mean_count = mean(count), .groups = \"drop\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 x 3\n  first_treat treated mean_count\n        <dbl> <lgl>        <dbl>\n1           0 FALSE         6.15\n2           3 FALSE         3.72\n3           3 TRUE         10.7 \n4           4 FALSE         4.29\n5           4 TRUE         11.5 \n6           5 FALSE         4.80\n7           5 TRUE         13.2 \n```\n\n\n:::\n:::\n\n\nThe never-treated group averages 6.15 counts. Treated cohorts average 3.72,\n4.29 and 4.80 before treatment and 10.7, 11.5 and 13.2 after. The pre-treatment\nmeans look low only because they are drawn from earlier periods, and the time\ntrend adds 0.2 to the log mean each period. This is exactly the comparison that\na raw before-after difference would get wrong.\n\n### Poisson ETWFE\n\nPass `family = \"poisson\"` to `etwfe()`. Everything else — cohort dummies, `emfx()`, event study — works identically to the linear case. We use `cgroup = \"never\"` so that pre-treatment estimates are not mechanistically forced to zero.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_pois <- etwfe(\n  fml         = count ~ 1,\n  tvar        = year,\n  gvar        = first_treat,\n  data        = df_count,\n  family      = \"poisson\",\n  cgroup      = \"never\",\n  vcov        = ~id\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemfx(mod_pois)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n .Dtreat Estimate Std. Error    z Pr(>|z|)     S 2.5 % 97.5 %\n    TRUE     3.99       0.33 12.1   <0.001 109.6  3.34   4.64\n\nTerm: .Dtreat\nType: response\nComparison: TRUE - FALSE\n```\n\n\n:::\n:::\n\n\nThe estimate is 3.99 counts with a standard error of 0.33 and a 95% interval of\n$[3.34, 4.64]$, against the true 3.762 derived above. The interval covers it.\n\n`emfx()` returns average marginal effects — the average difference $E[Y(1)] - E[Y(0)]$ in **count units** across treated observations. This is the ATT on the count scale. The underlying model imposes PT on the log scale, so each cohort-time treatment coefficient in the raw model can be exponentiated to get the incidence rate ratio for that cell (here they share a common value because the simulated effect is homogeneous).\n\n### Event study\n\nBecause we passed `cgroup = \"never\"`, the pre-treatment estimates are free\nparameters rather than zeros by construction, so the pre-period is an actual\ntest here. On the count scale the post-treatment effect should also grow with\nevent time even though the log-scale effect is constant, because the baseline\ncount grows with the time trend: the true values are 3.13, 3.82, 4.17 and 4.69\nat event times 0 through 3.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_pois_es <- emfx(mod_pois, type = \"event\", post_only = FALSE)\n\nggplot(mod_pois_es, aes(x = event, y = estimate, ymin = conf.low, ymax = conf.high)) +\n  geom_hline(yintercept = 0) +\n  geom_vline(xintercept = -1, lty = 2) +\n  geom_pointrange(col = \"darkcyan\") +\n  labs(\n    x = \"Years post treatment\",\n    y = \"ATT (count units)\",\n    title = \"Nonlinear ETWFE event study (Poisson)\"\n  )\n```\n\n::: {.cell-output-display}\n![](did_files/figure-pdf/did_pois4-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nPre-treatment estimates are close to zero, confirming parallel trends on the log scale holds in the simulation. The post-treatment points rise with event time, which is the count-scale consequence of a constant log-scale effect applied to a growing baseline, not evidence of a growing treatment effect.\n\n### Comparison: linear ETWFE on log(count + 1)\n\nA common alternative is to log-transform the count and run linear ETWFE. This is biased when zeros are present (the $+1$ shift distorts the linear index) and misinterprets the scale of the effect. For comparison:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_count <- df_count %>% mutate(log_count = log(count + 1))\n\nmod_lin <- etwfe(\n  fml  = log_count ~ 1,\n  tvar = year,\n  gvar = first_treat,\n  data = df_count,\n  vcov = ~id\n)\nemfx(mod_lin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n .Dtreat Estimate Std. Error    z Pr(>|z|)     S 2.5 % 97.5 %\n    TRUE     0.38     0.0319 11.9   <0.001 106.8 0.318  0.443\n\nTerm: .Dtreat\nType: response\nComparison: TRUE - FALSE\n```\n\n\n:::\n:::\n\n\nThe linear model returns 0.38 with a 95% interval of $[0.318, 0.443]$. That\nnumber is neither the count-scale ATT of 3.99 nor the log-scale parameter 0.4,\nthough it happens to sit near the latter because the counts here are large\nenough that $\\log(Y+1) \\approx \\log Y$. With many zeros the approximation\nbreaks and the estimate drifts.\n\nThe linear model estimates the ATT on the $\\log(Y+1)$ scale — not the same quantity as the Poisson ATT and harder to interpret. When treatment effects are multiplicative, Poisson ETWFE is the more appropriate model.\n\n## Spatial Interference\n\nEverything in this chapter so far assumes SUTVA: one unit's outcome does not depend on another unit's treatment. That is not always plausible. A treated municipality may affect deforestation in nearby untreated municipalities. A vaccinated household may reduce transmission to nearby households. A labor-market policy in one commuting zone may change flows to its neighbors. With this kind of spatial spillover, the usual DiD estimand no longer has the interpretation we want. Xu [-@xu2023] shows that ignoring interference can produce an estimand that is neither a direct effect nor a spillover effect.\n\nXu [-@xu2023; -@xu2026] develops a doubly robust DiD that keeps the identifying logic of conditional parallel trends but adds an exposure mapping $G_{it} = G(i, W_{-it})$ for unit $i$'s neighborhood treatment status. The estimand is the direct ATT at exposure level $g$,\n\n$$ \\tau_g(t, c) = \\frac{1}{|S_M|} \\sum_{i \\in S_M} \\mathbb{E}[y_{it}(c, g) - y_{it}(\\infty, g) \\mid z_i, C_i = c, G_{it} = g], $$ {#eq-did-12}\n\nwhere $C_i$ is unit $i$'s first treatment period (so $\\{C_i > t\\}$ is the not-yet-directly-treated comparison group), $S_M = \\{C_i = c\\} \\cup \\{C_i > t\\}$, and $g$ is a chosen exposure level. The DR plug-in averages three pieces over $S_M$: an IPW term from the treated cohort, an IPW term from the not-yet-treated, and a regression-imputation term, with three propensity models ($\\eta_{tc}$ for cohort, $\\eta_{tcg}$ and $\\eta_{t\\infty g}$ for exposure) and two outcome-change regressions. It is consistent if either all three propensities or both outcome models are correctly specified.\n\nThe companion package [`didint`](https://github.com/xiangao/didint) implements this. The 2x2 base case (Xu 2023):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(didint)\n\n# Wide-format two-period data with a binary exposure G.\nres <- did_int_2x2(\n  data       = panel,\n  yname      = \"Y_post\",\n  yname_pre  = \"Y_pre\",\n  treat      = \"W\",\n  exposure   = \"G\",\n  g          = 1,\n  covariates = c(\"z1\", \"z2\"),\n  trim       = 0.01     # Xu (2026) uses 0.01 in the Brazil application\n)\nprint(res)\n```\n:::\n\n\nFor staggered adoption (Xu 2026), `did_int_staggered()` loops over `(cohort, time)` cells with $t \\geq c$, restricts to $S_M$ in each cell, fits the DR estimator, and aggregates across cells using joint-IF stacking (per-cell IFs share the never-treated comparison group, so independence-style SEs underestimate uncertainty noticeably). The `vignettes/brazil_amazon.Rmd` vignette of `didint` replicates Section III of Xu (2026), the *Lista de Municípios Prioritários* policy on Amazon deforestation, using the public Assunção-McMillan-Murphy-Souza-Rodrigues replication archive on Zenodo.\n\nA Julia port with identical estimators is available as [`DidInterference.jl`](https://github.com/xiangao/DidInterference.jl).\n\n## Persistent Outcomes and Heterogeneous Dynamics\n\nStandard event-study TWFE regressions like\n\n$$ Y_{it} = \\alpha_i + \\gamma_t + \\sum_{j} D_{it}^j \\delta_j + X_{it}'\\beta + U_{it} $$ {#eq-did-13}\n\nimplicitly assume the residual has no serial dependence once unit and\ntime fixed effects are absorbed. When outcomes are genuinely\npersistent — earnings, employment, consumption, anything with habits\nor adjustment costs — that assumption fails. The event-time dummies\npick up the persistence on top of the true causal effect, producing\nspurious pre-trends and biased post-treatment estimates. With a true\nAR(1) DGP and persistence $\\rho_Y$, the omitted-variable bias on the\nevent-time coefficients grows geometrically with the event-time\nhorizon (Botosaru and Liu, 2025, Figure 1).\n\nBotosaru and Liu [-@botosaru-liu-2025] introduce a **dynamic panel\nwith correlated random coefficients** that handles both persistence\nand unit-level heterogeneity in dynamic responses:\n\n$$ Y_{it} = \\rho_Y Y_{i,t-1} + \\alpha_i + \\sum_j D_{it}^j \\delta_{ij} + X_{it}'\\beta + U_{it}, $$ {#eq-did-14}\n\nwith a parsimonious AR(1) structure on the event-time effects to keep\ndimensionality manageable:\n\n$$ \\delta_{ij} = \\rho_\\delta \\delta_{i,j-1} + \\varepsilon_{ij}, \\quad j \\geq 1. $$ {#eq-did-15}\n\nThe latent $\\lambda_i = (\\alpha_i, \\delta_{i0})$ is a unit-specific\ncorrelated random coefficient. A two-step semiparametric estimator: step 1\nis **quasi-maximum likelihood** for the common parameters\n$(\\rho_Y, \\rho_\\delta, \\sigma_U^2, \\sigma_\\varepsilon^2, \\beta)$ under\na Gaussian working assumption on $\\lambda_i$ (consistent under\nmisspecification of that working assumption); step 2 is\n**Tweedie / Gaussian-conjugate empirical Bayes** for the unit-level\nposterior trajectories $\\{\\delta_{i,j}\\}_{j=0}^J$, achieving asymptotic\nratio optimality.\n\nA companion paper [@botosaru-liu-2026] adds a **homogeneous-feedback\nextension**: covariates $X_{it}$ are allowed to adjust endogenously to\npast $Y$ and treatment (the canonical example: minimum-wage policy\naffects wages directly and also indirectly through firms re-optimising\ninput demand). Under the assumption that the covariate adjustment rule\ndoes not depend on $\\lambda_i$ given the observable history, the\nlikelihood factors into a structural piece (for $Y \\mid X$, history)\nand a feedback piece (for $X$ given history), each separately\nidentified. The factorisation yields a clean decomposition of dynamic\ntreatment effects into **direct** (through $\\delta_{i,j}$) and\n**indirect** (through covariate feedback) components.\n\nThe package [`tvhte`](https://github.com/xiangao/tvhte) implements\nboth papers:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tvhte)\n\n# Fit on a panel with staggered cohorts and a covariate\nfit <- tvhte(Y = panel_Y, Y0 = baseline_Y, t0 = cohort,\n             J = max_event_time, X = panel_X)\nprint(fit)\n\n# Feedback model + direct/indirect counterfactual decomposition\nfb <- fit_feedback(panel_Y, baseline_Y, panel_X, baseline_X)\ncf <- simulate_counterfactual(fit, fb, t0_star = alt_cohort)\n```\n:::\n\n\nA Julia port with the same API is at\n[`TVHTE.jl`](https://github.com/xiangao/TVHTE.jl); both packages have\ndeployed docs at <https://xiangao.github.io/tvhte/> and\n<https://xiangao.github.io/TVHTE.jl/>.\n\n## Synthetic Control\n\nThe biggest problem with DiD is the PT assumption. There is not really a test for it, just like the unconfoundedness assumption. It is less demanding than unconfoundedness assumption, but nevertheless hard to justify sometimes.\n\nAbadie (2010)'s idea is to construct a control unit, out of many control units (donor pool), which is a weighted average of all donor units, that then hopefully is very close to the treated unit in terms of outcome, in the pre-treatment periods. This works pretty well in practice, when you have a somewhat large donor pool. Of course there is still no test for post-treatment period, but for pre-treatment periods, usually it can get almost identical trend as the treated unit. This was designed for single treated unit at the beginning, but got extended to multiple treated units later on.\n\n## Synthetic DiD\n\nArkhangelsky et al (2021) tries to combine the idea of DiD and SC. SC assigns different weights to different control units. The standard DiD is a TWFE, assigning equal weights to all time periods and units.\n\nTo see that, DiD objective function:\n\n$$ \\small (\\hat \\tau^{did}, \\hat \\mu, \\hat \\alpha, \\hat \\beta) = \\underset{\\tau, \\mu, \\alpha, \\beta}{argmin} { \\Sigma_{i=1}^N \\Sigma_{t=1}^T (Y_{it} - \\mu - \\alpha_i - \\beta_t - W_{it} \\tau)^2}$$ {#eq-did-16}\n\nSC objective function: $$ (\\hat \\tau^{sc}, \\hat \\mu, \\hat \\beta) = \\underset{\\tau, \\mu, \\beta}{argmin} { \\Sigma_{i=1}^N \\Sigma_{t=1}^T \\hat \\omega_i^{sc} (Y_{it} - \\mu - \\beta_t - W_{it} \\tau)^2}$$ {#eq-did-17}\n\nIt's a unit-weighted regression with time effects. The weights are set to optimally match donor units to treated unit so that they are as close as possible, in each time point. Note there is no $\\alpha_i$, since it's forced to be 0 — so SC is not simply DiD with weights: it also drops the unit fixed effects. The clean nesting is through SDiD below: DiD is SDiD with all unit and time weights set to 1, and SC is SDiD with the $\\alpha_i$ removed and time weights set to 1.\n\nSDiD:\n\n$$ \\small (\\hat \\tau^{sdid}, \\hat \\mu, \\hat \\alpha, \\hat \\beta) = \\underset{\\tau, \\mu, \\alpha, \\beta}{argmin} { \\Sigma_{i=1}^N \\Sigma_{t=1}^T \\hat \\omega_i^{sdid} \\hat \\lambda_t^{sdid} (Y_{it} - \\mu - \\alpha_i - \\beta_t - W_{it} \\tau)^2}$$ {#eq-did-18}\n\nSDiD sets another weight in addition to SC weights, which changes over time. The SC weights are trying to construct a control unit that is close to the treated unit; the SDiD weights are trying to put more weights on pre-treatment periods that are more similar to post-treatment periods.\n\n### Example: California Proposition 99\n\nThe `california_prop99` panel is annual per-capita cigarette sales in packs for\n39 US states from 1970 to 2000. California raised its cigarette tax in 1989, so\nthere is one treated unit, 38 controls, 19 pre-treatment years and 12\npost-treatment years. The estimand is the effect of Proposition 99 on\nCalifornia's cigarette consumption.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(synthdid)\ndata('california_prop99')\nsetup = panel.matrices(california_prop99)\ntau.hat = synthdid_estimate(setup$Y, setup$N0, setup$T0)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(tau.hat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$estimate\n[1] -15.60383\n\n$se\n     [,1]\n[1,]   NA\n\n$controls\n               estimate 1\nNevada              0.124\nNew Hampshire       0.105\nConnecticut         0.078\nDelaware            0.070\nColorado            0.058\nIllinois            0.053\nNebraska            0.048\nMontana             0.045\nUtah                0.042\nNew Mexico          0.041\nMinnesota           0.039\nWisconsin           0.037\nWest Virginia       0.034\nNorth Carolina      0.033\nIdaho               0.031\nOhio                0.031\nMaine               0.028\nIowa                0.026\n\n$periods\n     estimate 1\n1988      0.427\n1986      0.366\n1987      0.206\n\n$dimensions\n          N1           N0 N0.effective           T1           T0 T0.effective \n       1.000       38.000       16.388       12.000       19.000        2.783 \n```\n\n\n:::\n:::\n\n\nThe point estimate, $-15.6$, is the headline number from Arkhangelsky et al.\n(2021). Note that the `se` entry comes back `NA`, and that is not a glitch to\nskim past: `summary()` defaults to a **jackknife** standard error, which deletes\none treated unit at a time. California is the *only* treated unit here, so\ndeleting it leaves nothing to estimate and the jackknife is undefined. The\nbootstrap SE fails for the same reason. With a single treated unit the usable\noption is the placebo method, which builds the reference distribution by\npretending each control state was treated:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(12345)\ncat(sprintf(\"N0 = %d control states, T0 = %d pre-periods, N1 = %d treated unit\\n\",\n            setup$N0, setup$T0, nrow(setup$Y) - setup$N0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nN0 = 38 control states, T0 = 19 pre-periods, N1 = 1 treated unit\n```\n\n\n:::\n\n```{.r .cell-code}\nse_placebo <- as.numeric(synthdid_se(tau.hat, method = \"placebo\"))\ncat(sprintf(\"SDiD estimate %.2f, placebo SE %.2f, 95%% CI [%.2f, %.2f]\\n\",\n            as.numeric(tau.hat), se_placebo,\n            as.numeric(tau.hat) - 1.96 * se_placebo,\n            as.numeric(tau.hat) + 1.96 * se_placebo))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSDiD estimate -15.60, placebo SE 8.37, 95% CI [-32.01, 0.80]\n```\n\n\n:::\n:::\n\n\nTwo cautions on that interval. The placebo standard error is a permutation\nquantity, so it moves with the seed --- report the seed, or average over several.\nAnd it is justified under the assumption that the treated unit is exchangeable\nwith the controls, which is a real assumption about California, not a technicality.\nThe interval here comfortably includes zero, which is worth stating plainly: the\nmuch-cited $-15.6$ is not statistically distinguishable from no effect with 38\ncontrol states and one treated unit. Note also that `summary(tau.hat,\nse.method = \"placebo\")` does *not* fix the `NA` --- the `se` field stays empty;\n`synthdid_se()` has to be called directly.\n\nThe summary output is also worth reading past the point estimate. The unit\nweights are concentrated: Nevada takes 0.124, New Hampshire 0.105, Connecticut\n0.078, and the effective number of controls is 16.4 out of 38. The time weights\nput 0.427 on 1988, 0.366 on 1986 and 0.206 on 1987, giving an effective 2.8\npre-periods out of 19. Both are the point of the method --- weight the donors\nand the pre-periods that resemble the target --- and both are the reason the\ninference is hard.\n\nRunning the same panel through all three estimators shows what the weighting\ndoes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntau.sc   = sc_estimate(setup$Y, setup$N0, setup$T0)\ntau.did  = did_estimate(setup$Y, setup$N0, setup$T0)\nestimates = list(tau.did, tau.sc, tau.hat)\nnames(estimates) = c('Diff-in-Diff', 'Synthetic Control', 'Synthetic Diff-in-Diff')\nprint(unlist(estimates))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Diff-in-Diff      Synthetic Control Synthetic Diff-in-Diff \n             -27.34911              -19.61966              -15.60383 \n```\n\n\n:::\n:::\n\n\nPlain DiD gives $-27.35$, synthetic control $-19.62$, and synthetic DiD\n$-15.60$. The three differ by more than the placebo standard error of 8.37, so\nthe choice of estimator matters more here than the sampling uncertainty within\nany one of them. DiD weights every control state and every pre-period equally,\nwhich is why it moves furthest: states unlike California, and pre-periods unlike\nthe late 1980s, all count in full.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot <- synthdid_plot(estimates, facet.vertical=FALSE,\n              control.name='control', treated.name='california',\n              lambda.comparable=TRUE, se.method = 'none',\n              trajectory.linetype = 1, line.width=.75, effect.curvature=-.4,\n              trajectory.alpha=.7, effect.alpha=.7,\n              diagram.alpha=1, onset.alpha=.7) +\n    theme(legend.position=c(.26,.07), legend.direction='horizontal',\n          legend.key=element_blank(), legend.background=element_blank(),\n          strip.background=element_blank(), strip.text.x = element_blank())\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot\n```\n\n::: {.cell-output-display}\n![](did_files/figure-pdf/did17-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nEach panel shows California's trajectory against the weighted control\ntrajectory, with the estimated effect drawn as the gap after 1989. The time\nweights $\\lambda_t$ are plotted along the bottom, so the pre-periods that\nactually enter the comparison are visible: for synthetic DiD they concentrate on\n1986 to 1988, the years just before the tax change. The synthetic control and\nsynthetic DiD panels track California closely before 1989; the DiD panel does\nnot, which is the visual counterpart to its larger estimate.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}