{
  "hash": "70869bb661b9fa2b02acb63eac7d9920",
  "result": {
    "engine": "knitr",
    "markdown": "# Recentered Formula Instruments\n\n\n\nMany treatments are computed from a formula that combines a random shock with\nnon-random exposure. Medicaid eligibility is a state's rules applied to a\nperson's income. Import exposure is national industry shocks applied to a\nregion's industry mix. The Bartik instrument of the previous chapter is one\nsuch formula. This chapter covers the general version of Borusyak and Hull\n[@borusyak-hull-2023], their result on which formula is best\n[@borusyak-hull-2026], and what both mean for shift-share.\n\n## Formula instruments\n\nUnit $i$ has outcome $y_i$ and treatment $x_i$, with a constant effect $\\beta$:\n\n$$\ny_i = \\beta x_i + \\varepsilon_i .\n$$ {#eq-ri-model}\n\nThe treatment is $x_i = h_i(g, w, u)$, where $h_i$ is a known function, $g$\ncollects the random shocks, $w$ collects predetermined variables such as\nincome or industry shares, and $u$ collects anything else. The identifying\nassumption puts all the randomness on the shocks [@borusyak-hull-2026,\nAssumption 1]:\n\n$$\nE[\\varepsilon_i \\mid g, w] = E[\\varepsilon_i \\mid w] .\n$$ {#eq-ri-exog}\n\nThe error may depend on $w$ in any way. Poorer people may have worse\noutcomes, and regions with more manufacturing may have been declining anyway.\n\nA formula instrument is $z_i = f_i(g, w)$ for a fixed function $f_i$. Its\nexpected value over the shock draws, holding $w$ fixed, is the expected\ninstrument $\\mu_i = E[z_i \\mid w]$. The recentered instrument\n$\\tilde z_i = z_i - \\mu_i$ is valid, because by iterated expectations and\n@eq-ri-exog,\n\n$$\nE[\\tilde z_i \\varepsilon_i]\n= E\\big[\\tilde z_i\\, E[\\varepsilon_i \\mid w]\\big]\n= E\\big[E[\\tilde z_i \\mid w]\\, E[\\varepsilon_i \\mid w]\\big] = 0 .\n$$\n\nWithout recentering the same steps give $E[z_i \\varepsilon_i] = E[\\mu_i\nE[\\varepsilon_i \\mid w]]$, which is not zero when the expected instrument is\ncorrelated with the predictable part of the error. Subtracting $\\mu_i$ and\ncontrolling for $\\mu_i$ are equivalent by Frisch–Waugh–Lovell. Computing\n$\\mu_i$ requires the design: how the shocks could have been drawn. We redraw\nthem from that design, or permute them if they are exchangeable, and average\nthe formula over the draws.\n\nAny recentered formula is valid, so we can pick the most precise.\n@borusyak-hull-2026 [Theorem 1] show it starts from the best prediction of the\ntreatment, recentered:\n\n$$\n\\tilde z = E[x \\mid g, w] - E[x \\mid w] .\n$$ {#eq-ri-optimal}\n\nThe full optimal instrument adds two refinements, partly controlling for the\npredictable part of the error and GLS weighting, which need a model of the\nerror. The authors drop them. Their algorithm predicts the treatment from its\nformula, recenters the prediction by redrawing the shocks, and uses the result\nas the instrument. When $x_i$ depends only on $(g, w)$, the prediction is\n$x_i$ itself.\n\n## Shift-share as a formula instrument\n\nThe Bartik instrument $B_\\ell = \\sum_k s_{\\ell k} g_k$ of @eq-shift-share-iv-1\nis the linear formula, shares times shocks. It differs from\n@eq-ri-optimal in two ways.\n\nThe first is recentering. Suppose the industry shocks are exchangeable within\nperiod $t$, with mean $\\bar g_t$, and let $S_\\ell = \\sum_k s_{\\ell k}$ be\nregion $\\ell$'s sum of shares. Then\n\n$$\n\\mu_\\ell = S_\\ell\\, \\bar g_t .\n$$ {#eq-ri-ss-mu}\n\nIf the shares sum to one, $\\mu_\\ell = \\bar g_t$ is common to all regions and\nperiod effects absorb it, so Bartik is already recentered. If they are\nincomplete, as with manufacturing shares, heavily manufacturing regions get a\nlarge instrument in every draw, and Bartik is biased unless we control for\n$S_\\ell$ interacted with period [@borusyak-hull-jaravel-2022].\n\nThe second is the formula. Take two regions with half their employment in\nelectronics, and an import shock to electronics. Region A's plants compete\nwith Chinese imports. Region B's make military components and do not. Bartik\ngives both half the shock, but only A's import competition rises, so the\ninstrument varies where the treatment does not. The best predictor gives A\nhalf the shock and B nothing, then recenters each by its own expected value.\nBoth instruments are valid, and the second has the stronger first stage. When\nthe treatment really is shares times shocks, the best predictor is Bartik\nitself and the two differ only by recentering. The formula matters when the\ntreatment has more structure than Bartik uses: eligibility rules, export\nexposure, transport networks, nonlinear indices.\n\n|                     | Shift-share (Bartik)      | Recentered formula instrument          |\n|---------------------|---------------------------|----------------------------------------|\n| Formula             | Shares times shocks       | Best prediction of the treatment       |\n| Expected instrument | Usually not subtracted    | Subtracted, or controlled for          |\n| Shock design        | Implicit                  | Written down to compute $\\mu_\\ell$     |\n| Inputs              | Shares and shocks         | Treatment formula and shock design     |\n\n: Shift-share and recentered formula instruments. {#tbl-ri-compare}\n\nThe formula instrument asks for more: the treatment's formula and an explicit\nshock design. With heterogeneous effects, different instruments weight units\ndifferently, so a gain in precision is a gain for a different weighted\naverage [@borusyak-hull-2026, Proposition D1].\n\n## Simulation\n\nThe aim is to compare a shock-only instrument with the recentered treatment.\nThere are 50 states and 10,000 people. Income $\\text{inc}_i$, in multiples of\nthe poverty line, is log-normal with median 1.4. Each state draws an\neligibility threshold $T_k$ from $\\{0.5, 1, 1.38, 2\\}$ with equal\nprobabilities, and\n\n$$\nx_i = 1[\\text{inc}_i < T_{s(i)}], \\qquad\ny_i = 0.3\\, x_i + \\varepsilon_i, \\qquad\n\\varepsilon_i = -0.5 \\log \\text{inc}_i + \\alpha_{s(i)} + \\nu_i ,\n$$ {#eq-ri-dgp}\n\nwhere $s(i)$ is $i$'s state, $\\alpha_k \\sim N(0, 0.3^2)$ is a state effect\nand $\\nu_i \\sim N(0, 1)$. Poorer people are more often eligible and have\nhigher errors, so OLS is biased. Expected eligibility $\\mu_i$ is the share of\nthe four thresholds above $\\text{inc}_i$.\n\nWe compare OLS (the same as instrumenting $x_i$ with itself); the simulated\ninstrument of @currie-gruber-1996, the share of all 10,000 people eligible\nunder their state's threshold; the recentered treatment $x_i - \\mu_i$; and\nOLS of $y$ on $x$ and $\\mu$, which is the controlled form of the recentered\ntreatment [@borusyak-hull-2026, footnote 8]. Holding the people fixed, we\nredraw the 50 thresholds 1,000 times, so only the shocks change. The people\nand draws are stored as CSVs so the Julia companion computes the same numbers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npeople <- read_csv(\"data/recenter_people.csv\", show_col_types = FALSE)\ndraws  <- as.matrix(read_csv(\"data/recenter_policy_draws.csv\",\n                             show_col_types = FALSE)[, -1])\npool <- c(0.5, 1.0, 1.38, 2.0)\nbeta_true <- 0.3\nmu    <- sapply(people$income, function(v) mean(v < pool))  # expected eligibility\ngener <- sapply(pool, function(t) mean(people$income < t))  # state generosity\n\ncoef_x <- function(f) {\n  nm <- intersect(c(\"fit_x\", \"x\"), names(coef(f)))[1]\n  c(est = unname(coef(f)[nm]), se = unname(se(f)[nm]))\n}\n\none_draw <- function(r) {\n  thr <- draws[r, people$state]\n  d <- mutate(people, x = as.numeric(income < thr), y = beta_true * x + eps,\n              z_sim = gener[match(thr, pool)], z_rc = x - mu, mu = mu)\n  fits <- list(feols(y ~ x, d, cluster = ~state),\n               feols(y ~ 1 | x ~ z_sim, d, cluster = ~state),\n               feols(y ~ 1 | x ~ z_rc, d, cluster = ~state),\n               feols(y ~ x + mu, d, cluster = ~state))\n  rbind(sapply(fits, coef_x),\n        r2 = c(NA, cor(d$x, d$z_sim)^2, cor(d$x, d$z_rc)^2, NA))\n}\n\nmc <- simplify2array(mclapply(seq_len(nrow(draws)), one_draw, mc.cores = 6))\n\ntibble(estimator = c(\"OLS\", \"Simulated instrument\", \"Recentered treatment\",\n                     \"OLS controlling for mu\"),\n       mean     = apply(mc[\"est\", , ], 1, mean),\n       sd       = apply(mc[\"est\", , ], 1, sd),\n       coverage = apply(abs(mc[\"est\", , ] - beta_true) <= 1.96 * mc[\"se\", , ], 1, mean),\n       first_stage_R2 = apply(mc[\"r2\", , ], 1, mean)) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|estimator              |  mean|    sd| coverage| first_stage_R2|\n|:----------------------|-----:|-----:|--------:|--------------:|\n|OLS                    | 0.637| 0.049|    0.000|             NA|\n|Simulated instrument   | 0.302| 0.167|    0.937|          0.263|\n|Recentered treatment   | 0.300| 0.086|    0.927|          0.589|\n|OLS controlling for mu | 0.300| 0.080|    0.935|             NA|\n\n\n:::\n:::\n\n\nOLS averages 0.637 against a true 0.3. The three other estimators are centred\non 0.3, with coverage of 92.7% to 93.7% for clustered 95% intervals with 50\nclusters. The simulated instrument has a standard deviation of 0.167 across\ndraws, the recentered treatment 0.086, and its controlled form 0.080. The\nsimulated instrument varies only across states, so its first-stage $R^2$ is\n0.26. The recentered treatment varies within states, among people whose\nincome lies between the lowest and highest thresholds, and its $R^2$ is 0.59.\n\n## The China shock\n\nThe ADH regression has incomplete shares: lagged employment shares of 397\nmanufacturing industries in each of 722 commuting zones, over two periods.\nADH control for the start-of-period manufacturing share with one coefficient\nfor both periods. Under exchangeable shocks within period, @eq-ri-ss-mu says\nthe right control is $S_\\ell$ times the period's mean shock, which is 4.8 in\nthe first period and 17.3 in the second. A stricter design treats shocks as\nexchangeable only within the 20 two-digit SIC sectors in each period, giving\n$\\mu_\\ell = \\sum_m S_{\\ell m} \\bar g_{mt}$, where $S_{\\ell m}$ is the zone's\nshare in sector $m$ and $\\bar g_{mt}$ the sector's mean shock. All fits use\nADH's controls, census-division effects, population weights and standard\nerrors clustered by state, with the GPSS replication files.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadh <- read_csv(\"data/adh_master.csv\", show_col_types = FALSE)\ntr  <- read_csv(\"data/adh_shares_triplets.csv\", show_col_types = FALSE)\nshk <- read_csv(\"data/adh_shocks.csv\", show_col_types = FALSE)\n\nby_row <- function(v) {                        # sum over industries, by zone\n  out <- numeric(nrow(adh)); s <- rowsum(v, tr$row)\n  out[as.integer(rownames(s))] <- s[, 1]; out\n}\nsector  <- paste(shk$sic87dd %/% 100, shk$year)\ng_bar_m <- tapply(shk$g, sector, mean)\n\nadh <- mutate(adh, B = by_row(tr$share * shk$g[tr$col]), S = by_row(tr$share),\n              mu2 = by_row(tr$share * g_bar_m[sector[tr$col]]))\n\ncontrols <- \"l_sh_popedu_c + l_sh_popfborn + l_sh_empl_f + l_sh_routine33 +\n             l_task_outsource + t2 | division\"\niv <- function(extra) {\n  feols(as.formula(paste(\"d_sh_empl_mfg ~\", extra, controls, \"| shock ~ B\")),\n        adh, weights = ~weights, cluster = ~statefip)\n}\nfits <- list(\"ADH controls\"                     = iv(\"l_shind_manuf_cbp +\"),\n             \"Without the manufacturing share\"  = iv(\"\"),\n             \"Design 1: S x period\"             = iv(\"S + S:t2 +\"),\n             \"Design 2: sector expected instrument\" = iv(\"mu2 +\"))\ntibble(specification = names(fits),\n       estimate = sapply(fits, \\(f) coef(f)[\"fit_shock\"]),\n       se       = sapply(fits, \\(f) se(f)[\"fit_shock\"])) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|specification                        | estimate|    se|\n|:------------------------------------|--------:|-----:|\n|ADH controls                         |   -0.596| 0.100|\n|Without the manufacturing share      |   -0.712| 0.083|\n|Design 1: S x period                 |   -0.267| 0.087|\n|Design 2: sector expected instrument |   -0.144| 0.117|\n\n\n:::\n:::\n\n\nThe first row reproduces ADH's −0.596: an increase in import exposure of\n$1,000 per worker over a decade lowers the manufacturing employment share by\nabout 0.6 percentage points. Controlling for the expected instrument period by\nperiod gives −0.267 (0.087). ADH's control is close to $S_\\ell$, with a\ncorrelation of 0.92, but one coefficient cannot absorb a term whose slope more\nthan triples between periods. The sector design gives −0.144 (0.117), because\nit no longer uses the fact that electronics and toys received larger shocks\nthan food or paper.\n\nEach row is right under its own design, and the data cannot tell us which\ndesign holds. Recentering forces the design to be stated, and here it matters\na great deal.\n\n## The Medicaid application\n\n@borusyak-hull-2026 instrument Medicaid eligibility in the 2014 ACA expansion\nwith actual minus expected eligibility, treating expansion as random within\nthe governor's party. The first-stage partial $R^2$ rises from 0.01 to 0.80\nover the simulated instrument and the standard error on crowd-out falls by\n44%. Most of the gain comes from the 18% of the sample whose eligibility the\nexpansion could change; outside it, the recentered instrument is zero, and in\nthe full sample without an exposure control it is less precise than the\nsimulated one [@borusyak-hull-2026, Table A4]. Their 2012–2013 placebo on\nprivate insurance is −0.011, half the main estimate of −0.023 (Table A2).\n\n## Summary\n\nShift-share is one formula instrument, with the formula and the design fixed\nby convention. Any formula of shocks and exposure is valid once its expected\nvalue over the shock design is subtracted, and the most efficient formula is\nthe recentered best prediction of the treatment. For Bartik this gives two\nchecks: whether incomplete shares require controlling for the sum of shares\ntimes the mean shock, and whether the treatment depends on the shocks through\nmore than shares times shocks. In the ADH data the first check alone moves the\nestimate from −0.60 to −0.27.\n\nFor the shift-share construction, the share and shock views, and inference,\nsee the previous chapter, [Shift-Share Instrumental Variables](shift-share-iv.qmd).\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}