{
  "hash": "4c8665982c101990cc14d2e7c33a7225",
  "result": {
    "engine": "knitr",
    "markdown": "# Continuous and Multivalued Treatments\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(WeightIt)\nlibrary(causaldrf)\nlibrary(lmtp)\nlibrary(SuperLearner)\n```\n:::\n\n\nSo far most examples use a binary treatment. Many treatments are not binary:\ndose of a drug, hours in a program, dollars spent, or a treatment with\nseveral levels. In those cases \"the treatment effect\" is not one number. We\nusually want a dose-response curve,\n\n$$\n\\mu(d) = \\mathbb{E}[Y(d)], \\quad d \\in \\mathcal{D}.\n$$ {#eq-continuous-treatments-1}\n\nI use three approaches:\n\n1. **Generalized propensity score** (GPS; Hirano-Imbens 2004), which models\n   the conditional density of treatment given covariates.\n2. **Doubly-robust dose-response estimation** [in the spirit of\n   @kennedy-2017-continuous], which combines a GPS with an outcome model.\n3. **Longitudinal modified treatment policies** [LMTP; @diaz-2023-lmtp],\n   which are useful when treatments are time-varying or when fixed treatment\n   levels create positivity problems.\n\n> **Related reading**: The LMTP material below is condensed from the\n> longer treatment in [Longitudinal modified treatment policy (LMTP)](https://xiangao.github.io/blog_book/lmtp.html)\n> in *Topics on Econometrics and Causal Inference*, which follows\n> Nicholas Williams's tutorials at\n> [beyondtheate.com](https://beyondtheate.com/).\n\n## The continuous-treatment setup\n\nThe aim is to recover a known dose-response curve from data in which the dose\nis chosen partly on covariates that also move the outcome.\n\nWe simulate $n = 2000$ units with two covariates, $X_1, X_2 \\sim N(0,1)$,\nindependent of each other. The dose is $D = 2 + 0.5X_1 + 0.5X_2 + \\nu$ with\n$\\nu \\sim N(0,1)$. The dose-response curve is $\\mu(d) = 1 + 2d - 0.15d^2$, and\nthe outcome is $Y = \\mu(D) + 0.3X_1 - 0.3X_2 + \\varepsilon$ with\n$\\varepsilon \\sim N(0,1)$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\nn  <- 2000\nX1 <- rnorm(n)\nX2 <- rnorm(n)\n# Continuous treatment, depends on X1, X2\nD  <- 2 + 0.5 * X1 + 0.5 * X2 + rnorm(n, sd = 1.0)\n# Dose-response: nonlinear in D\ntrue_mu <- function(d) 1.0 + 2.0 * d - 0.15 * d^2\nY  <- true_mu(D) + 0.3 * X1 - 0.3 * X2 + rnorm(n)\n\ndf <- tibble(Y = Y, D = D, X1 = X1, X2 = X2)\ncat(sprintf(\"Treatment range: [%.2f, %.2f]\\n\", min(D), max(D)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTreatment range: [-1.82, 6.39]\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"True μ(d=2) = %.2f, μ(d=4) = %.2f, μ(d=6) = %.2f\\n\",\n            true_mu(2), true_mu(4), true_mu(6)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue μ(d=2) = 4.40, μ(d=4) = 6.60, μ(d=6) = 7.60\n```\n\n\n:::\n:::\n\n\nThe observed doses run from $-1.82$ to 6.39, and the true curve gives\n$\\mu(2) = 4.40$, $\\mu(4) = 6.60$ and $\\mu(6) = 7.60$.\n\nThe dose-response curve is concave, with clearly diminishing returns. It is worth being precise about the shape rather\nthan calling it hump-shaped, because the vertex sits at $d = 2/0.3 \\approx 6.67$,\njust *beyond* the largest dose in the sample. Over the observed range the curve is\ntherefore increasing throughout --- its slope $2 - 0.3d$ is still positive\n(about 0.08) at the maximum observed dose --- so the downturn is extrapolation, not\nsomething these data identify. The estimation problem is to recover the curvature\nthat is in range when the observed dose is confounded by $X$.\n\n## Naive regression vs adjusted regression\n\nWe fit three models and compare their implied dose-response curves against the\ntruth: $Y$ on $D$ alone, $Y$ on $D$ and the covariates, and $Y$ on a quadratic\nin $D$ and the covariates. All three are evaluated at $X_1 = X_2 = 0$ over\n$d \\in [0,10]$.\n\nOne feature of this DGP is worth stating before reading the plot. $X_1$ and\n$X_2$ are confounders in the graph, since each raises the dose and each moves\nthe outcome. But their linear bias cancels: each raises $D$ by 0.5, while they\nenter $Y$ with $+0.3$ and $-0.3$, so the omitted-variable term\n$\\text{Cov}(D,\\, 0.3X_1 - 0.3X_2)/\\text{Var}(D)$ is\n$0.3(0.5) - 0.3(0.5) = 0$ exactly. The naive slope is 1.421 and the adjusted\nslope 1.409. Adjusting for $X$ changes almost nothing here, and the one problem\nleft for the linear models is functional form.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Linear fit, ignoring covariates\nlinear_naive <- lm(Y ~ D, data = df)\n# Linear fit with covariate adjustment\nlinear_adj   <- lm(Y ~ D + X1 + X2, data = df)\n# Nonlinear fit with covariate adjustment\npoly_adj     <- lm(Y ~ poly(D, 2) + X1 + X2, data = df)\n\nds <- seq(0, 10, by = 0.5)\n\npredict_mu <- function(fit, ds) {\n  data.frame(d = ds, X1 = 0, X2 = 0) |>\n    rename(D = d) -> nd\n  predict(fit, newdata = nd)\n}\n\n# True dose-response\ndf_true <- tibble(d = ds, mu = true_mu(ds))\n\ndf_fits <- bind_rows(\n  tibble(d = ds, mu = predict_mu(linear_naive, ds), method = \"Linear (naive)\"),\n  tibble(d = ds, mu = predict_mu(linear_adj,   ds), method = \"Linear (adj X)\"),\n  tibble(d = ds, mu = predict_mu(poly_adj,     ds), method = \"Quadratic (adj X)\")\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_line(data = df_fits, aes(d, mu, colour = method), linewidth = 1.0) +\n  geom_line(data = df_true, aes(d, mu), colour = \"black\",\n            linetype = \"dashed\", linewidth = 1.0) +\n  labs(x = \"Dose D\", y = \"Expected outcome E[Y(d)]\",\n       colour = \"Method\",\n       caption = \"Black dashed line = true μ(d) = 1 + 2d - 0.15 d²\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Fitted vs true dose-response. Linear fits miss the curvature; the quadratic-adjusted fit comes closer.](continuous-treatments_files/figure-html/naive-plot-1.png){width=672}\n:::\n:::\n\n\nThe two linear fits lie almost on top of each other, because the\nomitted-variable term cancels exactly in this DGP, and both run straight\nthrough the curvature. At $d = 2$ they give 4.13\nagainst a true 4.40; at $d = 6$ they give 9.82 and 9.77 against a true 7.60.\nTheir common slope of about 1.41 is close to the average of the true slope\n$2 - 0.3d$ over the observed doses, which is 1.403 --- a straight line through\na concave curve recovers the average derivative, not the curve.\n\nThe quadratic adjusted fit gives 4.34, 6.61 and 7.83 at $d = 2, 4, 6$ against\nthe true 4.40, 6.60 and 7.60. It is better here because the true curve is\nquadratic and we fitted a quadratic. In real applications the functional form\nis not known, which is what motivates the next two sections.\n\n## Generalized propensity score (GPS)\n\nThe **generalized propensity score** is the conditional density of the\ntreatment given covariates:\n\n$$\nr(d, x) = f_{D \\mid X}(d \\mid x).\n$$ {#eq-continuous-treatments-2}\n\nTwo results from @hirano-imbens-2004-gps are what make this object useful, and both\nare worth stating before we compute anything.\n\nThe first is the assumption they need, which is weaker than it looks. *Weak\nunconfoundedness* requires $Y(d) \\perp D \\mid X$ separately for each dose $d$.\nIt does not require the whole path $\\{Y(d) : d\\}$ to be jointly independent of\n$D$ given $X$, which would be a much stronger demand at a continuous treatment.\n\nThe second is the balancing property. Conditional on the scalar $r(d, X)$, the\ncovariates carry no further information about whether a unit received dose $d$:\n\n$$\nf_D\\bigl(d \\mid r(d, X)\\bigr) = f_D\\bigl(d \\mid r(d, X),\\, X\\bigr).\n$$ {#eq-continuous-treatments-balance}\n\nSo a one-dimensional score does the job of the full covariate vector, exactly as\nin the binary case. Put the two together and the dose-response function is\n\n$$\n\\mu(d) = E[Y(d)] = E\\Bigl[\\, E\\bigl(Y \\mid D = d,\\; r(d, X)\\bigr) \\Bigr],\n$$ {#eq-continuous-treatments-doseresp}\n\nwhere the outer expectation runs over the distribution of $r(d, X)$ in the whole\nsample. Read the argument of $r$ carefully, because it is where this estimator\nis usually got wrong: at each counterfactual dose $d$ we must recompute every\nunit's score *at that* $d$, not reuse the score at the dose the unit happened to\nreceive. The code below does this in `estimate_dose()`, and it is the reason the\nGPS has to be recomputed inside the loop over doses.\n\nOne more point of theory explains why the GPS enters as a regressor rather than\nas a weight. The GPS is a conditional *density*, not a probability, so it\ncarries the units of $1/D$; weights of the form $1/\\hat r$ are therefore not\nscale-free and change if the dose is rescaled. Multiplying by the marginal\ndensity $f_D(D)$ restores scale invariance, which is what the stabilised weights\nbelow do, and it is why they are reported here only as an overlap diagnostic.\nThe Hirano-Imbens estimator sidesteps the issue by putting the score in the\noutcome model instead.\n\nIn practice we start with a normal model for $D \\mid X$:\n$D \\mid X \\sim \\mathcal{N}(\\beta_0+\\beta'X,\\sigma^2)$. Fitting $D$ on\n$X_1$ and $X_2$ by OLS gives $\\hat\\beta$ and $\\hat\\sigma$, and the score at any\ndose $d$ for unit $i$ is the normal density evaluated there,\n\n$$\n\\hat r(d, x_i) = \\frac{1}{\\hat\\sigma\\sqrt{2\\pi}}\n  \\exp\\!\\left\\{-\\frac{\\bigl(d - x_i'\\hat\\beta\\bigr)^2}{2\\hat\\sigma^2}\\right\\}.\n$$ {#eq-continuous-treatments-gpshat}\n\nThat is the whole calculation: one linear regression, then one density\nevaluation per unit per dose. Nothing here needs a package. `lm` fits the dose\nmodel, `dnorm` evaluates @eq-continuous-treatments-gpshat, and `density` and\n`approx` from `stats` supply the marginal density $f_D$ used in the diagnostic\nweights, which are trimmed at the 99th percentile.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit GPS model: D ~ X with Normal residuals\ngps_model <- lm(D ~ X1 + X2, data = df)\nd_pred    <- predict(gps_model)\nsigma_e   <- sigma(gps_model)\n\n# GPS for each unit's observed treatment\ngps <- dnorm(df$D, mean = d_pred, sd = sigma_e)\ndf$gps <- gps\n\n# IPW-style weights for continuous treatment: 1 / GPS\n# Stabilise by multiplying by the marginal density f_D(D)\n# NOTE: sw_cont is computed only as an overlap/positivity diagnostic.\n# The Hirano-Imbens estimator below does NOT weight by it: the GPS\n# enters as a regressor in the outcome model.\nmarginal_D <- density(df$D)\nfD <- approx(marginal_D$x, marginal_D$y, xout = df$D)$y\ndf$sw_cont <- pmin(fD / gps, quantile(fD / gps, 0.99))\n\ncat(sprintf(\"Weight summary: min=%.3f, mean=%.3f, max=%.3f\\n\",\n            min(df$sw_cont), mean(df$sw_cont), max(df$sw_cont)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWeight summary: min=0.039, mean=0.947, max=4.390\n```\n\n\n:::\n:::\n\n\nThe weights run from 0.039 to 4.390 with a mean of 0.947. No unit carries an\nextreme weight, so overlap along the dose is good and the estimators below are\nnot resting on a handful of observations.\n\nThe Hirano-Imbens estimator has two steps. First regress $Y$ on flexible\nfunctions of $D$ and the estimated GPS. Then, for each dose $d$, average the\npredicted outcome over the sample. The plot compares the resulting curve\nagainst the truth.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Stage 2: regress Y on flexible function of (D, GPS)\nhi_fit <- lm(Y ~ poly(D, 2) + poly(gps, 2) + I(D * gps), data = df)\n\n# Dose-response at each d: average over the empirical distribution of GPS\n# at that d.\nestimate_dose <- function(d) {\n  # Predict GPS at this d for each unit\n  gps_at_d <- dnorm(d, mean = d_pred, sd = sigma_e)\n  nd <- data.frame(D = d, gps = gps_at_d)\n  mean(predict(hi_fit, newdata = nd))\n}\n\nds <- seq(0, 10, by = 0.5)\nhi_dose <- sapply(ds, estimate_dose)\n\ndf_hi <- tibble(d = ds, mu = hi_dose, method = \"Hirano-Imbens GPS\")\n\nggplot() +\n  geom_line(data = df_hi, aes(d, mu, colour = method), linewidth = 1.2) +\n  geom_line(data = df_true, aes(d, mu), colour = \"black\",\n            linetype = \"dashed\", linewidth = 1.0) +\n  labs(x = \"Dose D\", y = \"E[Y(d)]\",\n       caption = \"Dashed black = truth; coloured = Hirano-Imbens GPS estimator\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](continuous-treatments_files/figure-html/hi-est-1.png){width=672}\n:::\n:::\n\n\nThe GPS curve tracks the concavity that the linear fits missed. It is fitted\nwith a quadratic in $D$ and in the GPS, so it is not assumption-free either,\nbut the assumption is now about how the outcome depends on the dose and the\nscore rather than about a straight line.\n\n## Doubly-robust dose-response estimation\n\nA kernel-localized AIPW estimator — in the spirit of\n@kennedy-2017-continuous, who develop a more elaborate pseudo-outcome\nversion with formal guarantees — is the continuous-treatment analogue of\nAIPW. It combines:\n\n- An outcome model $\\hat\\mu(d, x) = \\mathbb{E}[Y \\mid D = d, X = x]$\n- A generalised propensity score $\\hat r(d \\mid x)$\n\nThen the dose-response at $d$ is estimated by\n\n$$\n\\hat\\mu_{DR}(d) = \\frac{1}{n} \\sum_i \\left[ \\hat\\mu(d, X_i) + K_h(D_i - d) \\cdot \\frac{Y_i - \\hat\\mu(D_i, X_i)}{\\hat r(D_i \\mid X_i)} \\right],\n$$ {#eq-continuous-treatments-3}\n\nwhere $K_h$ is a kernel around dose $d$. The bandwidth $h$ controls how much\nnearby observed doses contribute to the estimate. (The code below uses the\nweight-normalized — Hájek — version of the correction term, dividing the\nweights by their mean; the population limit is unchanged.)\n\nTwo features of this estimator are worth understanding, because they are what\nthe comparison table at the end of the chapter is really about.\n\nThe first is why it is doubly robust, and the algebra is the same as in the\nbinary case worked through in @sec-plug-in-bias. The first term is a plug-in\nbuilt from the outcome model. The second subtracts that model's own residual,\nreweighted by the score. A first-order error in $\\hat\\mu$ therefore enters twice\nwith opposite signs and cancels, and what survives involves the product of the\nerror in $\\hat\\mu$ and the error in $\\hat r$. If either nuisance is right, the\nproduct is zero.\n\nThe second is why a bandwidth appears here when none appeared for the ATE. The\nATE is a single number, and it is estimable at the $\\sqrt n$ rate. But $\\mu(d)$\nat a *point* $d$ is a regression function, and no $\\sqrt n$ estimator of it\nexists without smoothness assumptions, because the data hold only finitely many\nobservations near any given dose. The kernel is how we borrow from neighbouring\ndoses, and $h$ sets the exchange rate: a wide bandwidth pulls in doses where the\ntruth is different, a narrow one leaves too few observations to average over.\nUnder the usual second-order smoothness the best trade is $h \\propto n^{-1/5}$\nand the rate is $n^{-2/5}$, slower than $\\sqrt n$ by construction. That is why\nbandwidth sensitivity is listed below as a cost of the method rather than as a\ntuning detail.\n\n@kennedy-2017-continuous handle the localisation more carefully. Instead of\nsmoothing the correction term, they construct a pseudo-outcome whose conditional\nmean given $D = d$ is exactly $\\mu(d)$, and then run a single nonparametric\nregression of that pseudo-outcome on $D$. All the smoothing sits in one place,\nwhich is what lets them state formal guarantees. The version used here keeps the\ndoubly-robust structure and is easier to read, with weaker theory behind it.\n\nUsing the GPS already estimated above, the implementation is short. The outcome\nmodel is a quadratic in $D$ with both covariates and their interactions with\n$D$; the kernel is Gaussian with bandwidth $h = 0.5$. The plot puts this curve\nnext to the GPS curve and the truth.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Outcome model μ̂(D, X): flexible polynomial\nmu_fit <- lm(Y ~ D + I(D^2) + X1 + X2 + I(D * X1) + I(D * X2), data = df)\ndf$mu_at_obs <- predict(mu_fit)\n\n# DR estimator at dose d with bandwidth h\ndr_estimate <- function(d, h = 0.5) {\n  # Counterfactual prediction at D = d for each unit\n  mu_at_d <- predict(mu_fit, newdata = transform(df, D = d))\n  # Kernel weight on observed treatment near d\n  kernel <- dnorm(df$D - d, sd = h)\n  weight <- kernel / df$gps\n  weight <- weight / mean(weight)  # normalise\n  # DR correction\n  correction <- weight * (df$Y - df$mu_at_obs)\n  mean(mu_at_d) + mean(correction)\n}\n\nds <- seq(0, 10, by = 0.5)\ndr_dose <- sapply(ds, dr_estimate)\n\ndf_drf <- tibble(d = ds, mu = dr_dose, method = \"DR (kernel AIPW)\")\n\nggplot() +\n  geom_line(data = df_hi,  aes(d, mu, colour = method), linewidth = 1.0) +\n  geom_line(data = df_drf, aes(d, mu, colour = method), linewidth = 1.0) +\n  geom_line(data = df_true, aes(d, mu), colour = \"black\",\n            linetype = \"dashed\", linewidth = 1.0) +\n  labs(x = \"Dose D\", y = \"E[Y(d)]\",\n       caption = \"Black dashed = truth\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](continuous-treatments_files/figure-html/drf-1.png){width=672}\n:::\n:::\n\n\nRead this as an illustrative kernel-AIPW construction rather than a\nturnkey doubly robust theorem. For continuous treatments, a formal\ndoubly robust dose-response result -- consistency if either the\noutcome model or the GPS is correct -- requires additional bandwidth,\nnuisance-convergence-rate, smoothness, and orthogonalization conditions\n(see Kennedy et al. on continuous-treatment DR estimators). The\nself-normalized kernel correction shown here conveys the intuition but\ndoes not by itself establish those guarantees. As usual, the bandwidth\ntrades bias against variance.\n\nThe `causaldrf` package provides ready-made versions of these estimators,\nincluding `hi_est`, `iptw_est`, `aipwee_est`, `gam_est`, `nw_est`, and\n`bart_est`.\n\n## Longitudinal Modified Treatment Policies (LMTP)\n\nFixed-dose interventions can be unrealistic. For example, there may be\nalmost no observations near $D=10$, so estimating $Y(10)$ requires\nextrapolation. LMTP avoids this by defining interventions as changes to the\nobserved treatment, such as \"shift everyone's dose down by one unit.\" This\nkeeps the counterfactual treatment closer to the observed support.\n\n### What LMTP identifies\n\nWrite the policy as a function $d$ that takes a unit's history $H_t$ up to time\n$t$ and returns a treatment value: $d(H_t) = A_t - 1$ for a one-unit downward\nshift, or $d(H_t) = 0$ for the static \"treat nobody\" policy. The estimand is\n$E[Y(\\bar d)]$, the mean outcome if every period's treatment were replaced by\nthe value the policy assigns.\n\nThree assumptions identify it. Sequential exchangeability: at each period the\npotential outcome is independent of the current treatment given the observed\nhistory, $Y(\\bar d) \\perp A_t \\mid H_t$. Consistency, in the usual sense. And\npositivity, which is the assumption that motivates the whole approach: the\n*shifted* value must have positive density given the history. A shift of one unit\nstays inside the observed support, while a fixed dose of $D = 10$ may sit where\nno comparable unit exists.\n\nGiven those three, the estimand has a sequential-regression form. Start at the\nlast period and work backwards:\n\n$$\nm_T(H_T) = E\\bigl[Y \\mid H_T,\\, A_T = d(H_T)\\bigr], \\qquad\nm_t(H_t) = E\\bigl[m_{t+1} \\mid H_t,\\, A_t = d(H_t)\\bigr],\n$$ {#eq-continuous-treatments-lmtp}\n\nwith $E[Y(\\bar d)] = E[m_1]$. In plain terms: predict the outcome as if the last\ntreatment had followed the policy, treat that prediction as the outcome for the\nprevious period and predict it the same way, and repeat back to the first\nperiod. This is the g-formula written as a sequence of regressions rather than as\nan integral, which is what makes it estimable at all. `lmtp` fits each\nregression, optionally with machine learning, and adds a targeting or weighting\nstep at each stage so that the recursion is doubly robust rather than a plug-in.\n\n### A two-period example\n\nWe simulate $N = 1500$ units over two periods. The first covariate is\n$L_1 \\sim U(0,1)$ and the first treatment is a coin flip,\n$A_1 \\sim \\text{Bernoulli}(0.5)$. The second covariate is\n$L_2 \\sim N(0.25L_1,\\, 0.5^2)$, and the second treatment depends on both the\nfirst treatment and the current covariate,\n$A_2 \\sim \\text{Bernoulli}(\\Lambda(0.5 - 0.2A_1 + 0.1L_2))$. The outcome is\n$Y \\sim N(A_2 + L_2,\\, 0.3^2)$.\n\nThe truths follow from the DGP without simulation. $L_2$ does not depend on\n$A_1$, so setting both treatments to 0 leaves\n$E[Y] = E[L_2] = 0.25 \\cdot E[L_1] = 0.125$. Setting both to 1 gives\n$1 + 0.125 = 1.125$. And $A_1$ affects $Y$ only through $A_2$, which the policy\nfixes, so the contrast between the two policies is exactly 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nN    <- 1500\nL_1  <- runif(N, 0, 1)\nA_1  <- rbinom(N, 1, 0.5)\nL_2  <- rnorm(N, 0.25 * L_1, 0.5)\nA_2  <- rbinom(N, 1, plogis(0.5 - 0.2 * A_1 + 0.1 * L_2))\nY    <- rnorm(N, A_2 + L_2, 0.3)\n\nlmtp_data <- data.frame(L_1, A_1, L_2, A_2, Y)\nhead(lmtp_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        L_1 A_1        L_2 A_2           Y\n1 0.2655087   0  0.4913989   0 -0.42997401\n2 0.3721239   1 -0.3696255   0 -0.76396535\n3 0.5728534   0  0.5900039   0  0.79312079\n4 0.9082078   1 -0.2434529   1  1.23628221\n5 0.2016819   0  0.3198965   0  0.02620015\n6 0.8983897   0  0.1336102   1  1.00441306\n```\n\n\n:::\n:::\n\n\nFor simplicity the worked example uses *static* policies (set every\ntreatment to 0, then to 1) on a binary treatment — `lmtp` handles these in\nthe same framework. A genuinely *modified* policy on a continuous dose\nwould instead return a shift of the observed value, e.g.\n`function(data, trt) data[[trt]] - 1`, which is what keeps the\ncounterfactual on the observed support. Here is the set-to-zero policy:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshift_zero <- function(data, trt) {\n  # Set treatment to 0 everywhere — for comparison to \"never treat\"\n  a <- data[[trt]]\n  rep(0, length(a))\n}\n```\n:::\n\n\nThen fit the LMTP estimator with `lmtp::lmtp_tmle`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# TMLE-based LMTP estimator with super-learners for nuisance functions\n# (using SL.glm to keep it fast; in practice use richer SL libraries)\nlmtp_fit <- lmtp_tmle(\n  data       = lmtp_data,\n  trt        = c(\"A_1\", \"A_2\"),\n  outcome    = \"Y\",\n  baseline   = NULL,\n  time_vary  = list(c(\"L_1\"), c(\"L_2\")),\n  shift      = shift_zero,\n  outcome_type = \"continuous\",\n  learners_outcome = c(\"SL.glm\"),\n  learners_trt     = c(\"SL.glm\"),\n  folds = 2\n)\n\n# tidy() gives the estimate, SE, and CI as a data frame\n# (the styled console print does not render cleanly in the book)\ntidy(lmtp_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  estimate std.error conf.low conf.high\n     <dbl>     <dbl>    <dbl>     <dbl>\n1    0.118    0.0252   0.0681     0.167\n```\n\n\n:::\n:::\n\n\nThe set-to-zero policy gives 0.118 with a standard error of 0.0252 and a 95%\ninterval of $[0.068, 0.167]$, which covers the true 0.125.\n\nThe useful part of `lmtp` is that it handles the time-ordering of\ncovariates, treatments, and outcomes: $L_2$ is a post-treatment covariate for\n$A_1$ and a pre-treatment covariate for $A_2$, and the estimator has to respect\nthat ordering rather than conditioning on $L_2$ throughout.\n\n### Contrasts between policies\n\nWe can also compare two policies, such as \"set to 0\" versus \"set to 1\":\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshift_one <- function(data, trt) {\n  a <- data[[trt]]\n  rep(1, length(a))\n}\n\nlmtp_one <- lmtp_tmle(\n  data       = lmtp_data,\n  trt        = c(\"A_1\", \"A_2\"),\n  outcome    = \"Y\",\n  baseline   = NULL,\n  time_vary  = list(c(\"L_1\"), c(\"L_2\")),\n  shift      = shift_one,\n  outcome_type = \"continuous\",\n  learners_outcome = c(\"SL.glm\"),\n  learners_trt     = c(\"SL.glm\"),\n  folds = 2\n)\n\ncontrast <- lmtp_contrast(lmtp_one, ref = lmtp_fit)\nas.data.frame(contrast$estimates)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     shift       ref  estimate  std.error  conf.low conf.high       p.value\n1 1.103091 0.1176079 0.9854826 0.03489166 0.9170962  1.053869 1.683133e-175\n```\n\n\n:::\n:::\n\n\nThe contrast is the difference between the two policy-specific mean outcomes.\nTreat-always gives 1.103 against a true 1.125, treat-never gives 0.118 against\na true 0.125, and their difference is 0.9855 with a standard error of 0.0349\nand a 95% interval of $[0.917, 1.054]$. The true contrast is exactly 1, and the\ninterval covers it.\n\n## Choosing among the three\n\n| Method | Strengths | Weaknesses |\n|---|---|---|\n| **GPS (Hirano-Imbens)** | Conceptually transparent; widely understood | Parametric assumptions on the GPS and the outcome-GPS regression; sensitive to their misspecification |\n| **Doubly-robust** (kernel AIPW) | Consistent if either nuisance is correct, and can attain nonparametric oracle rates, under the bandwidth, smoothness, and nuisance-rate conditions the formal estimator requires | More complex; the construction shown above conveys the intuition rather than establishing those guarantees; nuisance models need careful tuning; sensitive to bandwidth |\n| **LMTP** | Handles continuous + multivalued + time-varying uniformly; respects positivity | More setup; requires defining a shift function |\n\nIn practice:\n\n- For a simple cross-sectional continuous treatment with good overlap, GPS\n  or the Kennedy DR estimator is a natural start.\n- For time-varying treatments or policy shifts, use LMTP.\n- For multivalued treatments, use a multinomial propensity model and the\n  same adjustment logic.\n\n## When to use these methods\n\nThese methods are useful when:\n\n1. Treatment has more than two values.\n2. The research question is about the shape of the dose-response curve.\n3. The intervention is better described as shifting treatment than setting\n   treatment to a fixed value.\n\nFor strictly binary, single-time-period problems, the standard\n[Estimation](estimation.qmd) and [Heterogeneous Effects](heterogeneous-effects.qmd)\nmethods are sufficient.\n\n## Summary\n\n- Continuous and multivalued treatments usually require a dose-response\n  curve, not a single coefficient.\n- GPS extends propensity-score logic to continuous treatments by modeling\n  the density of treatment given covariates.\n- Kennedy's DR estimator adds an outcome model to the GPS.\n- LMTP is useful when the intervention is a policy shift or when treatment is\n  time-varying.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}