{
  "hash": "9d7165dbb86311edd4b468a878a82bb7",
  "result": {
    "engine": "knitr",
    "markdown": "# From Graph to Estimate\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dagitty)\nlibrary(igraph)\nlibrary(causaleffect)\nlibrary(ggplot2)\n```\n:::\n\n\nThe previous chapters covered discovery: algorithms that learn a graph from\ndata. But a graph is not an estimate. After we have a graph, we still need\nto ask two questions:\n\n1. **Identification**: is the target effect a function of the observed-data\n   distribution?\n2. **Estimation**: once the identifying formula is known, estimate it from\n   the data.\n\nIn R, `dagitty` handles identification via the backdoor and front-door\ncriteria; `causaleffect` implements the full Pearl–Shpitser ID algorithm for\nacyclic directed mixed graphs (ADMGs) with hidden confounders. Estimation\nis done directly from the identifying formula — a step that is explicit in\nR, making the connection between the formula and the estimator transparent.\n\n## Backdoor: standard adjustment\n\nStart with the simple case. $X$ is a common cause of treatment $A$ and\noutcome $Y$, and $X$ is observed. Backdoor adjustment applies.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# X is a common cause of A and Y\ng_bd <- dagitty(\"dag { X -> A; X -> Y; A -> Y }\")\nexposures(g_bd) <- \"A\"\noutcomes(g_bd)  <- \"Y\"\n\nsets <- adjustmentSets(g_bd, exposure = \"A\", outcome = \"Y\")\ncat(\"Adjustment sets:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAdjustment sets:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(sets)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{ X }\n```\n\n\n:::\n:::\n\n\n`dagitty` finds `{X}` as the minimal adjustment set. Adjusting on $X$\nblocks the only open backdoor path $A \\leftarrow X \\rightarrow Y$.\n\nWe simulate data matching that graph. We draw $n = 2000$ observations with\n$X \\sim N(0,1)$, treatment $A \\sim \\text{Bernoulli}(\\Lambda(X))$, and outcome\n$Y = 2A + X + 0.5\\varepsilon$ with $\\varepsilon \\sim N(0,1)$. The effect is\nconstant, so the true ACE is 2. We then estimate it with AIPW using the\nadjustment set the graph chose, and take a 95% interval from 500 bootstrap\nresamples.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nn     <- 2000\nX     <- rnorm(n)\nA     <- as.numeric(runif(n) < 1 / (1 + exp(-X)))  # logistic: A depends on X\nY     <- 2 * A + X + 0.5 * rnorm(n)                 # true ACE = 2\ndata_bd <- data.frame(X = X, A = A, Y = Y)\n\n# AIPW (doubly-robust) estimator for the backdoor-adjusted ACE\n# Outcome model: E[Y | A, X]\nmu1 <- predict(lm(Y ~ A + X, data = data_bd), newdata = transform(data_bd, A = 1))\nmu0 <- predict(lm(Y ~ A + X, data = data_bd), newdata = transform(data_bd, A = 0))\n\n# Propensity score: P(A = 1 | X)\nps  <- predict(glm(A ~ X, data = data_bd, family = binomial), type = \"response\")\n\n# AIPW influence function\naipw <- mean(\n  (data_bd$A / ps) * (Y - mu1) - ((1 - data_bd$A) / (1 - ps)) * (Y - mu0) +\n  mu1 - mu0\n)\n\ncat(sprintf(\"Backdoor AIPW ACE (true = 2.0): %.3f\\n\", aipw))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBackdoor AIPW ACE (true = 2.0): 1.990\n```\n\n\n:::\n\n```{.r .cell-code}\n# Bootstrap 95% CI\nset.seed(99)\nboot_bd <- replicate(500, {\n  idx  <- sample.int(n, replace = TRUE)\n  bd   <- data_bd[idx, ]\n  m1   <- predict(lm(Y ~ A + X, data = bd), newdata = transform(bd, A = 1))\n  m0   <- predict(lm(Y ~ A + X, data = bd), newdata = transform(bd, A = 0))\n  p    <- predict(glm(A ~ X, data = bd, family = binomial), type = \"response\")\n  mean((bd$A / p) * (bd$Y - m1) - ((1 - bd$A) / (1 - p)) * (bd$Y - m0) + m1 - m0)\n})\nci_bd <- quantile(boot_bd, c(0.025, 0.975))\ncat(sprintf(\"95%% CI: [%.3f, %.3f]\\n\", ci_bd[1], ci_bd[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: [1.942, 2.043]\n```\n\n\n:::\n:::\n\n\nAIPW returns 1.990 with a 95% bootstrap interval of $[1.942, 2.043]$, covering\nthe true 2. The AIPW estimator is consistent if either the outcome model or the\npropensity score is correctly specified; here both are, since the DGP is linear\nin the outcome and logistic in the treatment.\n\n## Front-door: p-fixable effects\n\nNow suppose $A$ and $Y$ have an unmeasured common cause $U$, but there is a\nmeasured mediator $M$ on the path $A \\rightarrow M \\rightarrow Y$. Backdoor\nadjustment fails because $U$ is unobserved. The front-door formula can still\nidentify the effect.\n\nIn `dagitty`, the bidirected edge $A \\leftrightarrow Y$ (representing the\nlatent $U$) appears as `A <-> Y`. For `causaleffect`, the same edge is\nencoded as two directed edges `A -> Y` and `Y -> A` both marked with\n`description = \"U\"` in the igraph object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# dagitty for display and adjustment-set check\ng_fd <- dagitty(\"dag { A -> M; M -> Y; A <-> Y }\")\nexposures(g_fd) <- \"A\"\noutcomes(g_fd)  <- \"Y\"\n\n# An empty dagitty adjustment-set list prints nothing at all, so report the\n# count rather than calling print() on it and appearing to produce no output.\nsets_fd <- adjustmentSets(g_fd, exposure = \"A\", outcome = \"Y\")\ncat(\"Valid backdoor adjustment sets:\", length(sets_fd), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nValid backdoor adjustment sets: 0 \n```\n\n\n:::\n\n```{.r .cell-code}\n# causaleffect for ID algorithm: bidirected A <-> Y = two directed edges + description \"U\"\ng_fd_ig <- graph_from_literal(A -+ M, M -+ Y, A -+ Y, Y -+ A)\n# Mark the A<->Y bidirected edge by endpoint name rather than a hardcoded\n# edge index: igraph happens to sort edges by source vertex today (giving\n# order A->M(1), A->Y(2), M->Y(3), Y->A(4)), but that ordering isn't part of\n# igraph's documented contract, so indices like c(2,4) can silently break if\n# igraph's internals or this graph's construction ever changes.\nedge_ends <- ends(g_fd_ig, E(g_fd_ig))\nconfounded <- (edge_ends[, 1] == \"A\" & edge_ends[, 2] == \"Y\") |\n              (edge_ends[, 1] == \"Y\" & edge_ends[, 2] == \"A\")\ng_fd_ig <- set_edge_attr(g_fd_ig, \"description\", index = which(confounded), value = \"U\")\n\nexpr_fd <- causal.effect(y = \"Y\", x = \"A\", G = g_fd_ig, simp = TRUE)\ncat(\"\\nIdentifying expression:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nIdentifying expression:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(expr_fd, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\\sum_{M}P(M|A)\\left(\\sum_{A}P(Y|A,M)P(A)\\right) \n```\n\n\n:::\n:::\n\n\nThere are no valid backdoor adjustment sets, as expected: $U$ is unobserved, so\nno set of measured variables blocks the path it opens. And the expression\n`causal.effect` returns is the front-door formula,\n$\\sum_M P(M \\mid A) \\sum_{A'} P(Y \\mid A', M)\\, P(A')$.\n\nWe now simulate data for it. We draw $n = 3000$ observations with an unmeasured\nconfounder $U \\sim N(0,1)$, treatment $A \\sim \\text{Bernoulli}(\\Lambda(U))$,\nmediator $M \\sim \\text{Bernoulli}(\\Lambda(0.5 + 2A))$, and outcome\n$Y = 1.5M + 2U + 0.5\\varepsilon$ with $\\varepsilon \\sim N(0,1)$. The mediator\ndepends on $A$ alone and the outcome depends on $M$ and $U$ but not directly on\n$A$, which is what the front-door criterion requires.\n\nThe truth follows from the DGP. Intervening on $A$ changes $Y$ only through\n$M$, so the ACE is $1.5 \\times [P(M=1 \\mid A=1) - P(M=1 \\mid A=0)]\n= 1.5 \\times [\\Lambda(2.5) - \\Lambda(0.5)] = 1.5 \\times 0.302 = 0.453$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2)\nn     <- 3000\nU     <- rnorm(n)                                     # unmeasured confounder\nA_fd  <- as.numeric(runif(n) < 1 / (1 + exp(-U)))     # A depends on U\nM_fd  <- as.numeric(runif(n) < 1 / (1 + exp(-(0.5 + 2 * A_fd))))  # M depends on A only\nY_fd  <- 1.5 * M_fd + 2 * U + 0.5 * rnorm(n)          # Y depends on M and U\n\n# True ACE: E[Y | do(A=1)] - E[Y | do(A=0)]\n# = 1.5 * (E[M | A=1] - E[M | A=0])\ntrue_EMA1  <- 1 / (1 + exp(-(0.5 + 2)))   # scalar P(M=1 | A=1)\ntrue_EMA0  <- 1 / (1 + exp(-0.5))         # scalar P(M=1 | A=0)\ntrue_ace_fd <- 1.5 * (true_EMA1 - true_EMA0)\ncat(sprintf(\"True front-door ACE = %.3f\\n\", true_ace_fd))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue front-door ACE = 0.453\n```\n\n\n:::\n\n```{.r .cell-code}\ndata_fd <- data.frame(A = A_fd, M = M_fd, Y = Y_fd)\n```\n:::\n\n\nEstimate the front-door functional using the plug-in formula:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfront_door_ace <- function(data) {\n  pA <- mean(data$A)\n  pM_given_A <- prop.table(table(data$A, data$M), margin = 1)\n  pY_given_AM <- with(data, tapply(Y, list(A, M), mean))\n\n  ey_do <- function(a) {\n    sum(sapply(c(0, 1), function(m) {\n      p_m_given_a <- pM_given_A[as.character(a), as.character(m)]\n      inner <- sum(sapply(c(0, 1), function(ap)\n        pY_given_AM[as.character(ap), as.character(m)] *\n          ifelse(ap == 1, pA, 1 - pA)))\n      p_m_given_a * inner\n    }))\n  }\n  ey_do(1) - ey_do(0)\n}\n\nest_fd <- front_door_ace(data_fd)\n\nset.seed(77)\nboot_fd <- replicate(500, {\n  idx <- sample.int(nrow(data_fd), replace = TRUE)\n  front_door_ace(data_fd[idx, ])\n})\nci_fd  <- quantile(boot_fd, c(0.025, 0.975))\n\ncat(sprintf(\"Front-door ACE: %.3f  [95%% CI: %.3f, %.3f]\\n\",\n            est_fd, ci_fd[1], ci_fd[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFront-door ACE: 0.499  [95% CI: 0.432, 0.577]\n```\n\n\n:::\n\n```{.r .cell-code}\n# Naïve mean difference for comparison\nnaive_ace <- mean(Y_fd[A_fd == 1]) - mean(Y_fd[A_fd == 0])\ncat(sprintf(\"Naïve mean difference (biased!): %.3f\\n\", naive_ace))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNaïve mean difference (biased!): 2.083\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"True ACE:                        %.3f\\n\", true_ace_fd))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue ACE:                        0.453\n```\n\n\n:::\n:::\n\n\nThe front-door estimate is 0.499 with a 95% bootstrap interval of\n$[0.432, 0.577]$, which covers the true 0.453. The naive mean difference is\n2.083 --- more than four times the truth, and outside the front-door interval\nby a factor of four. The formula recovers the effect even though $U$ is never\nmeasured; the naive comparison is picking up the path through $U$, which enters\nthe outcome with coefficient 2 and the treatment through the logit.\n\nThe bias here is far larger than in the front-door example of the\n[graphs chapter](graphs-identification-estimation.qmd), where the naive\ncontrast was 0.14 against a truth of 0.055. The difference is the strength of\nthe confounding: $U$ enters $Y$ with coefficient 2 here against 0.7 there.\nNothing about the front-door formula changes; what changes is how much work it\nis doing.\n\n## When identification fails\n\nNot every graph identifies the effect. If $A$ and $Y$ have a hidden common\ncause and there is no front-door variable, the effect is not identified. The\ngraph below is the **bow**: a directed edge $A \\to Y$ plus a bidirected\n$A \\leftrightarrow Y$, and nothing else. Remove the mediator $M$ from the\nfront-door graph and this is what is left.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# A → Y with unmeasured confounding (A <-> Y) and no mediator: the \"bow\"\n# graph needs THREE igraph edges — the directed A → Y plus the\n# bidirected pair (encoded as two opposite edges marked \"U\").\n# graph_from_literal() silently collapses a duplicated A -+ Y, so we\n# build the multigraph with make_graph().\ng_unident_ig <- make_graph(c(\"A\",\"Y\",  \"A\",\"Y\",  \"Y\",\"A\"), directed = TRUE)\n# make_graph() preserves the literal edge order given above (unlike\n# graph_from_literal(), which re-sorts), so index 2:3 is reliable as long as\n# the c(...) vector above isn't reordered -- mark by endpoint pair anyway so\n# a future edit to that vector can't silently mismark the real A->Y edge.\nedge_ends <- ends(g_unident_ig, E(g_unident_ig))\n# The first A->Y edge is the real causal edge; the second (a duplicate,\n# per `duplicated()`) together with Y->A forms the bidirected U pair.\nu_edges <- which(((edge_ends[,1]==\"A\" & edge_ends[,2]==\"Y\") & duplicated(edge_ends)) |\n                  (edge_ends[,1]==\"Y\" & edge_ends[,2]==\"A\"))\ng_unident_ig <- set_edge_attr(g_unident_ig, \"description\",\n                               index = u_edges, value = \"U\")\n\nresult <- tryCatch(\n  causal.effect(y = \"Y\", x = \"A\", G = g_unident_ig, simp = TRUE),\n  error = function(e) conditionMessage(e)\n)\ncat(\"Result from causal.effect:\\n\", result, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nResult from causal.effect:\n Not identifiable. \n```\n\n\n:::\n:::\n\n\n`causaleffect` raises an error, printed above as \"Not identifiable.\", which the\n`tryCatch` captures. This is a useful failure. The algorithm did not return a\nformula that would quietly estimate the wrong thing; it reported that no\nfunction of the observed distribution equals the causal effect under this\ngraph. No amount of data helps, because the obstacle is the graph and not the\nsample size.\n\nThe honest response in applied work is to report the\nnon-identifiability, then either:\n\n1. Find additional variables that close the unmeasured-confounding paths\n2. Apply sensitivity analysis to bound the effect under maintained assumptions\n3. Find an instrumental variable for a LATE-style identification (IV chapter)\n\nSaying that the hidden confounding is probably small is sensitivity analysis,\nnot identification.\n\n## End-to-end: discover, identify, estimate\n\nDiscovery algorithms return graphs that can be passed to the identification\nstep:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(pcalg)\n\n# Step 1: discover the graph (chapters on causal discovery)\nsuffStat <- list(C = cor(data_obs), n = nrow(data_obs))\npc_fit   <- pc(suffStat, indepTest = gaussCItest,\n               alpha = 0.05, p = ncol(data_obs))\n\n# Step 2: check for backdoor adjustment set using dagitty\n# (convert pcalg CPDAG → dagitty for convenience).\n# NOTE the t(): as(graphNEL, \"matrix\") is from→to, but pcalg2dagitty\n# expects the amat.cpdag coding, which is its transpose — without it\n# every directed edge is silently reversed.\ng_dag <- pcalg2dagitty(t(as(pc_fit@graph, \"matrix\")),\n                        colnames(data_obs), type = \"cpdag\")\nsets  <- adjustmentSets(g_dag, exposure = \"A\", outcome = \"Y\")\n\n# Step 3: if an adjustment set is valid for every DAG in the class, estimate\n#         it with AIPW\n# Step 4: if the CPDAG is still unresolved, do NOT hand it to\n#         causaleffect::causal.effect() -- that function expects a specified\n#         DAG/ADMG, and different orientations in the class can imply\n#         different effects, different valid adjustment sets, or a different\n#         identification status. Instead either\n#           (a) orient the remaining edges with background knowledge and then\n#               run ordinary identification, or\n#           (b) report what the whole class permits: pcalg::ida() for\n#               linear-Gaussian total effects, otherwise enumerate the\n#               compatible DAGs and keep only conclusions that hold across\n#               all of them.\n# Step 5: estimate the returned functional by plug-in or regression\n```\n:::\n\n\nStep 4 is where this workflow most often goes wrong, so it is worth stating\nplainly: a CPDAG is an equivalence class, not a graph. An empty adjustment-set\nresult for a CPDAG is not permission to pass one arbitrary orientation to the ID\nalgorithm. The [causal discovery chapter](causal-discovery.qmd) sets out what to\ndo instead.\n\nIn applied work, I would not trust the discovered graph blindly. A more\nreasonable workflow is:\n\n1. **Hypothesise** a graph based on subject-matter knowledge\n2. **Discover** a data-driven graph using PC/GES/FCI\n3. **Compare** the two — disagreement points to substantive questions\n4. **Identify** under both graphs separately\n5. **Estimate** under both, and report the range as part of the result\n\nIf the estimate changes a lot across plausible graphs, the data alone is not\nsettling the question.\n\n## Why this matters\n\nThe graph-identification-estimation sequence matters because:\n\n- **Backdoor adjustment is not always available.** Many real DAGs have\n  hidden confounders. Front-door, nested, and general ID algorithms are\n  the recourse, but they are too complex to derive by hand for non-trivial\n  graphs.\n- **The right estimator depends on the identification strategy.**\n  AIPW-for-backdoor uses a different formula than the front-door plug-in.\n  Matching the estimator to the identification result avoids the common\n  mistake of plugging a graph into the wrong estimator.\n- **Reporting becomes more disciplined.** Once the workflow forces you to\n  specify a graph, it becomes harder to wave hands about \"unconfoundedness\"\n  — you have to say exactly which variables are doing the unconfounding\n  work.\n\n## Summary\n\n- A graph is not an estimate. Identification is the bridge.\n- `dagitty` handles backdoor and front-door checks; `causaleffect` handles\n  general ADMG identification.\n- Backdoor effects can be estimated with AIPW.\n- Front-door effects require estimating the front-door functional.\n- If the effect is not identified, report that instead of forcing a biased\n  regression estimate.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}