{
  "hash": "649e2982445bcf5177e505d8bf2cbce7",
  "result": {
    "engine": "knitr",
    "markdown": "# IV in Poisson with Fixed Effects\n\n\n\nPoisson regression specifies the conditional mean as an exponential function.\nAs a quasi-MLE, it needs the mean to be correct, not the full count\ndistribution. If a regressor is endogenous, the IV strategy has to respect\nthat nonlinear mean. I consider two cases: a continuous endogenous variable\nand a binary endogenous variable.\n\n## The Control Function Framework\n\n### Linear second stage — CF equals 2SLS\n\nIn the previous chapter we saw that adding the first-stage residual $\\hat{v}_2$ to an OLS second stage recovers the same coefficient as 2SLS. The algebra is:\n\n1. **First stage**: $y_2 = \\mathbf{z}\\boldsymbol{\\pi} + v_2$, estimated by OLS. Residual $\\hat{v}_2 = y_2 - \\hat{y}_2$ satisfies $E(\\mathbf{z}'\\hat{v}_2) = 0$.\n\n2. **Structural error decomposition**: write $\\varepsilon_1 = \\rho v_2 + \\eta_1$, where $E(\\mathbf{z}'\\eta_1) = 0$ and $E(v_2\\,\\eta_1) = 0$ by construction.\n\n3. **Augmented second stage**: substitute to get $y_1 = \\mathbf{z}_1\\boldsymbol{\\delta}_1 + \\alpha_1 y_2 + \\rho\\,\\hat{v}_2 + \\eta_1.$\n\nOLS on this equation is the **control function estimator**. The Frisch–Waugh–Lovell (FWL) theorem guarantees it is numerically identical to 2SLS — no extra assumption beyond $E(\\mathbf{z}'\\varepsilon_1) = 0$ is required.\n\n### Nonlinear second stage — CF diverges from 2SLS\n\nWhen the conditional mean is $\\exp(\\mathbf{x}\\boldsymbol{\\beta})$ (Poisson), a direct IV/GMM approach solves moment conditions in the instruments without modifying the exponential mean. The form of the moments matters. The additive moments $E[\\mathbf{z}'(y_1 - \\exp(\\mathbf{x}\\boldsymbol{\\beta}))] = 0$ require an additive structural error; when unobserved heterogeneity sits *inside* $\\exp(\\cdot)$ — the natural case for counts — the valid moments are the multiplicative ones of @mullahy-1997, $E[\\mathbf{z}'(y_1 e^{-\\mathbf{x}\\boldsymbol{\\beta}} - 1)] = 0$. The **control function approach** instead imposes the stronger *conditional mean assumption* [@wooldridge-2010-crosssection, sec. 18.5; @wooldridge-2014-qmle]:\n\n$$E[y_1 \\mid \\mathbf{z}_1,\\, y_2,\\, v_2] = \\exp\\!\\bigl(\\mathbf{z}_1\\boldsymbol{\\delta}_1 + \\alpha_1 y_2 + \\rho v_2\\bigr).$$ {#eq-poisson-iv-1}\n\nThis says the unobservable enters the conditional mean **linearly inside** $\\exp(\\cdot)$. Under this assumption, substituting $\\hat{v}_2$ for $v_2$ and running Poisson QMLE gives a consistent estimate of $\\alpha_1$.\n\nThree practical consequences:\n\n| Property | Linear (OLS/2SLS) | Nonlinear (Poisson CF) |\n|:---|:---|:---|\n| Extra assumption beyond IV exogeneity | None — FWL applies | CF mean assumption required |\n| CF vs. 2SLS/GMM numerically | **Identical** | **Different** — FWL fails |\n| SE from second stage alone | Valid only under $\\rho = 0$ — use 2SLS SEs | **Invalid** — bootstrap needed |\n| Test of endogeneity | $t$-stat on $\\hat{v}_2$ (DWH) | Same — $t$-stat on $\\hat{v}_2$ |\n\n::: {.callout-note}\n**Intuition for the CF assumption.** The decomposition $\\varepsilon_1 = \\rho v_2 + \\eta_1$ is exactly the same as in the linear case. What changes is where the decomposition gets applied: in the linear model it enters additively outside any transformation; in Poisson it must enter inside $\\exp(\\cdot)$ to be absorbed by the quasi-MLE score. If the true $\\rho \\neq 0$, omitting $\\hat{v}_2$ from the exponential mean leaves a multiplicative endogeneity term $e^{\\rho v_2}$ correlated with $y_2$, biasing $\\hat\\alpha_1$ upward or downward depending on the sign of $\\rho$.\n:::\n\n---\n\n## Part 1 — Continuous endogenous variable\n\n### Data generating process\n\nWe simulate a panel where `time` (continuous, e.g. minutes on site) is endogenous: it is correlated with an unobserved factor `e` that also affects `visits`. The excluded instrument is `phone` (binary, e.g. phone-access indicator). Fixed effects are `ad` (20 groups) and `female`.\n\nThere are 20 ad groups of 250 observations each, $n = 5000$. Each group draws a\nfixed effect $\\alpha_g \\sim N(0, 0.5^2)$. At the individual level,\n$\\text{female} \\sim \\text{Bernoulli}(0.5)$,\n$\\text{phone} \\sim \\text{Bernoulli}(0.4)$, $\\text{frfam} \\sim U(0,1)$, and the\nunobservable is $e \\sim N(0,1)$. The endogenous regressor is\n\n$$\n\\text{time} = 1.5\\,\\text{phone} + 0.5\\,\\text{frfam} + \\alpha_g + e,\n$$ {#eq-poisson-iv-7}\n\nand the count is $\\text{visits} \\sim \\text{Poisson}(\\lambda)$ with\n\n$$\n\\lambda = \\exp(0.5 + 0.8\\,\\text{time} + 0.4\\,\\text{frfam} + \\alpha_g\n          + 0.3\\,\\text{female} + 0.5\\,e).\n$$ {#eq-poisson-iv-8}\n\nThe true $\\alpha_1$ is 0.8. The same $e$ appears in `time` and in the log mean,\nwhich is the endogeneity, and `phone` appears only in `time`, which is the\nexclusion restriction. Note that $e$ enters the log mean *linearly inside*\n$\\exp(\\cdot)$: the control-function assumption holds here by construction, so\nthis simulation tests the estimator rather than the assumption.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\nn_ad <- 20; obs_per <- 250; n <- n_ad * obs_per\n\nfe_ad  <- rnorm(n_ad) * 0.5\nfe_grp <- rep(1:n_ad, each = obs_per)\nfemale <- as.integer(runif(n) < 0.5)\nphone  <- as.integer(runif(n) < 0.4)\nfrfam  <- runif(n)\ne      <- rnorm(n)\n\ntime <- 1.5 * phone + 0.5 * frfam + fe_ad[fe_grp] + e\n\ntrue_alpha <- 0.8\nlambda <- exp(0.5 + true_alpha * time + 0.4 * frfam +\n              fe_ad[fe_grp] + 0.3 * female + 0.5 * e)\nvisits <- rpois(n, lambda)\n\ndf1 <- data.frame(\n  visits = visits, time = time, phone = phone,\n  frfam = frfam, female = female, ad = fe_grp\n)\n\ncat(sprintf(\"n = %d   groups = %d   visits mean = %.2f\\n\", n, n_ad, mean(visits)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn = 5000   groups = 20   visits mean = 26.43\n```\n\n\n:::\n:::\n\n\n### Naive Poisson — endogeneity bias\n\nIgnoring the endogeneity of `time` gives a biased estimate of $\\alpha_1$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnaive1 <- fepois(visits ~ time + frfam | ad + female, data = df1)\netable(naive1, title = \"Naive Poisson — time is endogenous\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                            naive1\nDependent Var.:             visits\n                                  \ntime             1.139*** (0.0025)\nfrfam           0.2202*** (0.0092)\nFixed-Effects:  ------------------\nad                             Yes\nfemale                         Yes\n_______________ __________________\nS.E. type                      IID\nObservations                 5,000\nSquared Cor.               0.95297\nPseudo R2                  0.91842\nBIC                       32,823.9\n---\nSignif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe naive estimate is 1.139 against a true 0.8, an upward bias of 0.34. The\nsign follows the callout above: $\\rho = 0.5 > 0$, so omitting the control\nfunction leaves a multiplicative $e^{0.5e}$ term positively correlated with\n`time`. The magnitude is roughly predictable too. Conditioning on `frfam`, `ad`\nand `female` but not `phone`, the surviving variation in `time` is\n$1.5\\,\\text{phone} + e$ with variance $1.5^2(0.4)(0.6) + 1 = 1.54$, so a linear\napproximation puts the bias near $0.5 \\times 1/1.54 = 0.32$, close to the 0.34\nobserved.\n\n### Control function approach\n\nThe two-step CF procedure:\n\n1. **First stage** — project `time` on `phone`, `frfam`, and fixed effects via `feols`. The residual $\\hat{v}_2 = \\text{time} - \\hat{\\text{time}}$ satisfies $E(\\mathbf{z}'\\hat{v}_2)=0$ by construction. A linear first stage is appropriate here because `time` is continuous. **This does not carry over when $y_2$ is binary** — see the derivation in Part 2, where Wooldridge is explicit that the linear reduced-form/independent-error setup cannot be assumed once $y_2$ is discrete [@wooldridge-2010-crosssection, sec. 18.5; @imbens-wooldridge-2007-cf].\n\n2. **Second stage** — Poisson QMLE with $\\hat{v}_2$ added as a regressor inside the exponential mean. The CF assumption $E[y_1 \\mid \\mathbf{z}_1, y_2, v_2] = \\exp(\\mathbf{z}_1\\boldsymbol{\\delta}_1 + \\alpha_1 y_2 + \\rho v_2)$ holds exactly here because the DGP specifies $0.5\\,e$ linearly inside $\\exp(\\cdot)$.\n\nNote that unlike 2SLS in a linear model, $\\hat{v}_2$ does *not* replace $y_2$ — both enter together.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: linear projection\nfs1       <- feols(time ~ phone + frfam | ad + female, data = df1)\ndf1$v2hat <- residuals(fs1)\n\n# Step 2: Poisson CF\nm1_cf <- fepois(visits ~ time + v2hat + frfam | ad + female, data = df1)\netable(m1_cf, title = \"CF: linear projection first stage\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                             m1_cf\nDependent Var.:             visits\n                                  \ntime            0.7801*** (0.0041)\nv2hat           0.5150*** (0.0050)\nfrfam           0.3775*** (0.0093)\nFixed-Effects:  ------------------\nad                             Yes\nfemale                         Yes\n_______________ __________________\nS.E. type                      IID\nObservations                 5,000\nSquared Cor.               0.99614\nPseudo R2                  0.94394\nBIC                       22,627.7\n---\nSignif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"time coefficient: %.4f  (true %.1f)\\n\", coef(m1_cf)[\"time\"], true_alpha))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntime coefficient: 0.7801  (true 0.8)\n```\n\n\n:::\n:::\n\n\nThe coefficient on `time` is 0.7801, within 2.5 percent of the true\n$\\alpha_1 = 0.8$, against the naive 1.139. The coefficient on `v2hat` is 0.5150,\nwhich is $\\rho$, and the DGP sets $\\rho = 0.5$ --- the control function\nrecovers the endogeneity parameter as well as the structural one. Its\n$t$-statistic of 103 is the Hausman-type test, and it rejects exogeneity\ndecisively.\n\n### Bootstrap standard errors\n\nThe second-stage standard errors are incorrect because first-stage estimation error propagates. A cluster bootstrap (by `ad` group) corrects this. `parLapply` with a PSOCK cluster parallelises the 500 replications safely inside Quarto's rendering environment:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbootstrap_cf_continuous <- function(df, B = 500) {\n  clusters <- unique(df$ad)\n  K        <- length(clusters)\n\n  boot_one <- function(b) {\n    library(fixest)\n    set.seed(b)\n    drawn <- sample(clusters, K, replace = TRUE)\n    df_b  <- do.call(rbind, lapply(seq_along(drawn), function(i) {\n      sub         <- df[df$ad == drawn[i], ]\n      sub$ad_boot <- i\n      sub\n    }))\n    fs         <- feols(time ~ phone + frfam | ad_boot + female, data = df_b)\n    df_b$v2hat <- residuals(fs)\n    ss         <- fepois(visits ~ time + v2hat + frfam | ad_boot + female, data = df_b)\n    coef(ss)[\"time\"]\n  }\n\n  n_cores <- max(1L, detectCores() - 1L)\n  cl      <- makePSOCKcluster(n_cores)\n  clusterExport(cl, c(\"df\", \"clusters\", \"K\"), envir = environment())\n  results <- parLapply(cl, seq_len(B), boot_one)\n  stopCluster(cl)\n  unlist(results)\n}\n\nboot1    <- bootstrap_cf_continuous(df1, 500)\ncoef1    <- coef(m1_cf)[\"time\"]\nnaive_se <- se(m1_cf)[\"time\"]\n\ncat(sprintf(\"time coefficient:   %.4f  (true %.1f)\\n\", coef1, true_alpha))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntime coefficient:   0.7801  (true 0.8)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Naive 2nd-stage SE: %.4f\\n\", naive_se))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNaive 2nd-stage SE: 0.0041\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Bootstrap SE:       %.4f\\n\", sd(boot1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBootstrap SE:       0.0079\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Bootstrap 95%% CI: [%.4f, %.4f]\\n\",\n            quantile(boot1, 0.025), quantile(boot1, 0.975)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBootstrap 95% CI: [0.7637, 0.7930]\n```\n\n\n:::\n:::\n\n\nThe bootstrap standard error is 0.0079 against the naive second-stage 0.0041,\nalmost twice as large, confirming that ignoring first-stage uncertainty\nunderstates uncertainty by about half here. Note that the 95% interval here happens to just exclude the true 0.8: a Monte Carlo over fresh seeds of this design centers the CF estimator on 0.80 (mean 0.802, sd 0.009), so this draw is simply an unlucky one — and with only 20 clusters the bootstrap interval is itself noisy.\n\n---\n\n## Part 2 — Binary endogenous variable\n\nWhen $y_2 \\in \\{0,1\\}$, the linear-projection first stage from Part 1 loses its\njustification, and two probit-based alternatives become the theoretically\ngrounded routes instead.\n\n### Data generating process\n\nWe use a clean probit DGP for the binary endogenous variable with a fresh structural error `e2` independent of Part 1. The endogeneity coefficient `ρ = 0.2` is kept small so the CF assumption holds approximately well and estimates are close to the true value.\n\nThe covariates `phone`, `frfam`, `female` and the group effects $\\alpha_g$ are\ncarried over from Part 1, and we draw a new $e_2 \\sim N(0,1)$. The binary\nendogenous variable is a probit threshold,\n\n$$\n\\text{time\\_hi} = \\mathbb{1}\\{1.5\\,\\text{phone} + 0.4\\,\\text{frfam} + e_2 \\ge 0\\},\n$$ {#eq-poisson-iv-9}\n\nand the count is $\\text{visits} \\sim \\text{Poisson}(\\lambda_2)$ with\n\n$$\n\\lambda_2 = \\exp(0.5 + 0.8\\,\\text{time\\_hi} + 0.4\\,\\text{frfam} + \\alpha_g\n            + 0.3\\,\\text{female} + 0.2\\,e_2).\n$$ {#eq-poisson-iv-10}\n\nThe true $\\alpha_1$ is again 0.8, and $\\rho = 0.2$. Because the latent index is\nexactly a probit, the first stage in Approach B is correctly specified by\nconstruction, which isolates the approximation error from any misspecification.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\ne2      <- rnorm(n)\n\n# Binary endogenous variable: clean probit latent index\ntime_hi <- as.integer(1.5 * phone + 0.4 * frfam + e2 >= 0)\n\n# Poisson outcome — true coefficient 0.8, endogeneity via ρ*e2 (ρ=0.2)\nrho2    <- 0.2\nlambda2 <- exp(0.5 + true_alpha * time_hi + 0.4 * frfam +\n               fe_ad[fe_grp] + 0.3 * female + rho2 * e2)\nvisits2 <- rpois(n, lambda2)\n\ndf2 <- data.frame(\n  visits = visits2, time_hi = time_hi, phone = phone,\n  frfam = frfam, female = female, ad = fe_grp, e2 = e2\n)\n\ncat(sprintf(\"time_hi mean:      %.3f\\n\", mean(time_hi)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntime_hi mean:      0.729\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Cor(time_hi, e2):  %.3f  (endogeneity)\\n\", cor(time_hi, e2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCor(time_hi, e2):  0.622  (endogeneity)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"visits mean:       %.2f\\n\", mean(visits2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nvisits mean:       6.18\n```\n\n\n:::\n:::\n\n\n73% of observations have `time_hi = 1`, the correlation between `time_hi` and\n$e_2$ is 0.622, and mean visits are 6.18, well below Part 1's 26.4 --- a binary\nregressor cannot generate the exponential variation that a continuous,\nunbounded `time` does.\n\n### Why Approach A's assumption breaks down for binary $y_2$\n\nPart 1's control function rests on writing $y_2 = \\mathbf{z}\\boldsymbol{\\pi} + v_2$\nwith $v_2$ *independent* of $\\mathbf{z}$ (Assumption (3.25) in\n@imbens-wooldridge-2007-cf; eq. 18.39 in @wooldridge-2010-crosssection, sec. 18.5).\nThat is an assumption about the reduced form, not a consequence of OLS: the\npopulation linear projection always exists and its residual is always\n*uncorrelated* with $\\mathbf{z}$, but independence is much stronger, and\nindependence is what the Poisson control-function argument needs.\n\nFor a binary $y_2$ it fails by construction. Conditional on $\\mathbf{z}$,\n$v_2 = y_2 - \\mathbf{z}\\boldsymbol{\\pi}$ takes only the two values\n$1-\\mathbf{z}\\boldsymbol{\\pi}$ and $-\\mathbf{z}\\boldsymbol{\\pi}$, and\n$\\mathrm{Var}(v_2\\mid\\mathbf{z}) = p(\\mathbf{z})[1-p(\\mathbf{z})]$ is itself a\nfunction of $\\mathbf{z}$. Wooldridge says as much for exactly this case: \"it\nwould be very unusual for a discrete variable to be expressible as a linear\nequation with additive error independent of $\\mathbf{z}$\"\n[@wooldridge-2010-crosssection, sec. 18.5]. For a Poisson outcome with a binary\nendogenous variable he replaces the linear reduced form with the threshold model\n$y_2 = 1[\\mathbf{z}\\boldsymbol{\\pi}_2 + v_2 \\ge 0]$ and *keeps* the independence\nassumption, now about the latent $v_2$ [@imbens-wooldridge-2007-cf, sec. 3.3].\n\nThat is the distinction to hold on to, because Approach B's generalized residual\nis two-valued given $\\mathbf{z}$ as well. Discreteness of the derived residual is\nnot the issue; which object independence is asserted about is. Approach A asserts\nit of the observed $v_2$, where both the two values and the probabilities of\nlanding on them move with $\\mathbf{z}$. Terza's setup asserts it of the\ncontinuous latent probit error, $v_2 \\mid \\mathbf{z} \\sim N(0,1)$ --- the\nassumption every probit already makes.\n\nSo for a binary $y_2$, Approach A is not a weaker-but-valid alternative to\nApproach B; its own first-stage assumption cannot hold. What survives is the\nlocal approximation derived next, plus its validity as a Hausman-type exogeneity\ntest, since under $H_0:\\rho=0$ there is no endogeneity left to approximate.\n\n### The exact correction (Terza 1998) and Approach B as its local approximation\n\n@terza-1998, exposited in @wooldridge-2010-crosssection (sec. 18.5) and\n@imbens-wooldridge-2007-cf (sec. 3.3, eqs. 3.32–3.36), derives the *exact*\ncontrol function when $y_2$ follows a probit, $y_2 = 1[\\mathbf{z}\\boldsymbol{\\pi}_2 + v_2 \\geq 0]$,\nand $(c_1, v_2)$ — the Poisson heterogeneity and the probit error — are\njointly normal. Here $\\rho$ is the *coefficient* in the linear projection of\n$c_1$ on $v_2$, i.e. $E(\\exp(c_1) \\mid v_2) = \\exp(\\rho v_2)$ — **not** the\ncorrelation between them. With $v_2$ standard normal the two differ by a factor\nof $\\sigma_{c_1}$, since $\\rho = \\mathrm{Corr}(c_1,v_2)\\,\\sigma_{c_1}$, and the\ndistinction is not cosmetic: this chapter's DGP sets $c_1 = 0.2\\,e_2$ with\n$v_2 = e_2$, so the *correlation* is exactly $1$ while the $\\rho$ that governs\nthe approximation below is $0.2$. Reading $\\rho$ as a correlation is also what\n$h(\\cdot)$ forbids — it is $\\rho$ in the coefficient sense that makes\n$\\exp(\\rho^2/2)$ the lognormal correction and puts $\\rho$ on the same scale as\nthe probit index. It is **not** \"add the\ngeneralized residual linearly inside $\\exp(\\cdot)$\" (that is Approach B as\ncoded below). The exact result is multiplicative:\n\n$$E(y_1 \\mid \\mathbf{z}, y_2) = \\exp(\\mathbf{z}_1\\boldsymbol{\\delta}_1 + \\alpha_1 y_2)\\cdot h(y_2, \\mathbf{z}\\boldsymbol{\\pi}_2, \\rho)$$ {#eq-poisson-iv-2}\n$$h(y_2, \\mathbf{z}\\boldsymbol{\\pi}_2, \\rho) = \\exp(\\rho^2/2)\\left\\{y_2\\,\\frac{\\Phi(\\rho + \\mathbf{z}\\boldsymbol{\\pi}_2)}{\\Phi(\\mathbf{z}\\boldsymbol{\\pi}_2)} + (1-y_2)\\,\\frac{1-\\Phi(\\rho + \\mathbf{z}\\boldsymbol{\\pi}_2)}{1-\\Phi(\\mathbf{z}\\boldsymbol{\\pi}_2)}\\right\\}$$ {#eq-poisson-iv-3}\n\nestimated by plugging in the first-stage probit's $\\hat{\\boldsymbol{\\pi}}_2$\nand then jointly QMLE-fitting $(\\boldsymbol\\delta_1,\\alpha_1,\\rho)$ against this\nmean function — a genuinely nonlinear second stage, not a linear regressor\naddition.\n\n**Why Approach B (linear addition of the generalized residual) is a good\napproximation, and exactly how good.** Taylor-expand $h$ in $\\rho$ around\n$\\rho=0$. Since $\\tfrac{d}{d\\rho}\\exp(\\rho^2/2)\\big|_{\\rho=0}=0$, only the\n$\\Phi$-ratio terms contribute to first order:\n$$\\left.\\frac{\\partial}{\\partial\\rho}\\frac{\\Phi(\\rho+\\mathbf{z}\\boldsymbol\\pi_2)}{\\Phi(\\mathbf{z}\\boldsymbol\\pi_2)}\\right|_{\\rho=0} = \\frac{\\phi(\\mathbf{z}\\boldsymbol\\pi_2)}{\\Phi(\\mathbf{z}\\boldsymbol\\pi_2)} = \\lambda(\\mathbf{z}\\boldsymbol\\pi_2), \\qquad\n\\left.\\frac{\\partial}{\\partial\\rho}\\frac{1-\\Phi(\\rho+\\mathbf{z}\\boldsymbol\\pi_2)}{1-\\Phi(\\mathbf{z}\\boldsymbol\\pi_2)}\\right|_{\\rho=0} = -\\lambda(-\\mathbf{z}\\boldsymbol\\pi_2)$$ {#eq-poisson-iv-4}\nwhere $\\lambda(\\cdot)=\\phi(\\cdot)/\\Phi(\\cdot)$ is the inverse Mills ratio. Since\n$h(y_2,\\mathbf{z}\\boldsymbol\\pi_2,0)=1$,\n$$h(y_2,\\mathbf{z}\\boldsymbol\\pi_2,\\rho) \\approx 1 + \\rho\\cdot\\underbrace{\\bigl[y_2\\lambda(\\mathbf{z}\\boldsymbol\\pi_2) - (1-y_2)\\lambda(-\\mathbf{z}\\boldsymbol\\pi_2)\\bigr]}_{=\\ \\hat r_2,\\ \\text{the generalized residual}}$$ {#eq-poisson-iv-5}\nand $\\exp(x_1\\beta_1)\\cdot h(\\cdot) \\approx \\exp(x_1\\beta_1)\\cdot(1+\\rho\\, \\hat r_2) \\approx \\exp(x_1\\beta_1 + \\rho\\,\\hat r_2)$\nfor small $\\rho\\,\\hat r_2$ — recovering exactly Approach B's construction\n(adding $\\hat r_2$ linearly inside $\\exp(\\cdot)$). So **Approach B is the\nfirst-order-in-$\\rho$ local approximation to Terza's exact correction**, not\nthe exact correction itself; the approximation error is $O(\\rho^2)$. This is\nconsistent with the DGP above (small $\\rho=0.2$, kept deliberately\nsmall so this approximation stays tight) and with a direct large-$n$ check\nof both A and B run against this chapter's own DGP: the probability limits\nare $\\hat\\alpha_1^A \\to 0.839$ and $\\hat\\alpha_1^B \\to 0.822$ against the true\n$0.8$ — both biased, B roughly half of A's bias, matching the theoretical\nranking (B is a valid local approximation to the exact correction; A has no\nsuch derivation behind it at all for binary $y_2$) but neither exact.\n\n### Why use Approach B instead of the exact correction?\n\nIf Terza's $h(\\cdot)$ is exact and Approach B only approximates it, why does\nanyone use the approximation? Because $h(\\cdot)$ does not reduce to\n$\\exp(\\text{linear index})$: the $\\Phi$-ratios and the $\\exp(\\rho^2/2)$ term\nmake the second stage genuinely nonlinear in $\\rho$, so it needs custom\noptimisation code, and combining that with the within-group demeaning that makes\nFE-Poisson tractable is not straightforward. The cost scales badly exactly where\nFE-Poisson is most needed, with many high-dimensional fixed effects. Approach B's\nsecond stage instead has the same functional form as ordinary Poisson with one\nextra regressor in the index, so it runs in `fepois`, `ppmlhdfe` or `xtpoisson`\nunmodified. Joint nonlinear estimation would be more efficient, but Wooldridge\nnotes for the closely analogous binary-$y_1$ case that the iterations can be hard\nto converge, with $\\hat\\rho_1$ drifting toward $\\pm 1$\n[@wooldridge-2010-crosssection, sec. 15.7.3]. At $\\rho = 0.2$ the approximation\nerror is small next to sampling noise anyway, and the coefficient on $\\hat r_2$\ndoubles as a Hausman-type $t$-test for exogeneity sitting next to the coefficient\nof interest. This is the usual control-function tradeoff: give up some efficiency\nfor a second stage that is numerically simple, compatible with existing FE\nsoftware, and easy to read.\n\n### Three approaches: practical recap\n\n| | First stage | What enters 2nd stage | Status for binary $y_2$ |\n|---|---|---|---|\n| **A** | `feols` (OLS) | Residuals $\\hat{v}_2$ | **No valid first-stage assumption** — $v_2$ independent of $\\mathbf{z}$ fails by construction; usable only as an approximation, and as a Hausman-type exogeneity test |\n| **B** | `feglm` (probit) | Gen. residuals $\\hat{r}_2$ | First-order-in-$\\rho$ local approximation to Terza's exact correction; requires probit correctly specified |\n| **C** | Any model | Fitted values $\\hat{p}_2$ | Distribution-free (@mullahy-1997) — robust to misspecification of the model for $\\Pr(y_2=1\\mid\\mathbf{z})$ |\n\nA and B additionally require the second-stage Poisson conditional mean to be\ncorrectly specified. C's validity does not depend on how well the first-stage\nmodel for $y_2$ fits.\n\n### Approach A — Linear projection CF\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfs_a      <- feols(time_hi ~ phone + frfam | ad + female, data = df2)\ndf2$v2hat <- residuals(fs_a)\n\nm_a <- fepois(visits ~ time_hi + v2hat + frfam | ad + female, data = df2)\netable(m_a, title = \"Approach A: OLS residual as control function\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                               m_a\nDependent Var.:             visits\n                                  \ntime_hi         0.8613*** (0.0321)\nv2hat           0.2674*** (0.0318)\nfrfam           0.4168*** (0.0199)\nFixed-Effects:  ------------------\nad                             Yes\nfemale                         Yes\n_______________ __________________\nS.E. type                      IID\nObservations                 5,000\nSquared Cor.               0.73423\nPseudo R2                  0.41908\nBIC                       22,269.3\n---\nSignif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nApproach A gives 0.8613 with a coefficient of 0.2674 on `v2hat`.\n\n### Approach B — Probit generalized residuals\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfs_b <- feglm(time_hi ~ phone + frfam | ad + female,\n              data = df2, family = binomial(probit))\n\n# Generalized residual: r̂ = y·φ(η)/Φ(η) − (1−y)·φ(η)/(1−Φ(η))\neta      <- predict(fs_b, type = \"link\")\ndf2$gr2  <- ifelse(df2$time_hi == 1,\n                   dnorm(eta) / pnorm(eta),\n                   -dnorm(eta) / (1 - pnorm(eta)))\n\nm_b <- fepois(visits ~ time_hi + gr2 + frfam | ad + female, data = df2)\netable(m_b, title = \"Approach B: probit generalized residual\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                               m_b\nDependent Var.:             visits\n                                  \ntime_hi         0.8544*** (0.0329)\ngr2             0.1664*** (0.0200)\nfrfam           0.4162*** (0.0199)\nFixed-Effects:  ------------------\nad                             Yes\nfemale                         Yes\n_______________ __________________\nS.E. type                      IID\nObservations                 5,000\nSquared Cor.               0.73424\nPseudo R2                  0.41905\nBIC                       22,270.4\n---\nSignif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nApproach B gives 0.8544, slightly closer to the truth than A's 0.8613, with a\ncoefficient of 0.1664 on the generalized residual. That coefficient is an\nestimate of $\\rho$, whose true value is 0.2; it is not exact because Approach B\nis itself only a first-order approximation.\n\n### Does the first stage have to be probit? Logit works too — with a caveat\n\nNothing about the local-approximation argument above is specific to the\nnormal distribution. The generalized residual is defined for *any*\ncorrectly-specified binary-response GLM [@gourieroux-monfort-renault-trognon-1987], and for a **logit** first stage it collapses to something\nparticularly simple. With $\\Lambda(\\cdot)$ the logistic CDF and\n$\\lambda(\\eta)=\\Lambda(\\eta)[1-\\Lambda(\\eta)]$ its density,\n\n$$\\hat r_2 = y_2\\cdot\\frac{\\lambda(\\hat\\eta)}{\\Lambda(\\hat\\eta)} - (1-y_2)\\cdot\\frac{\\lambda(\\hat\\eta)}{1-\\Lambda(\\hat\\eta)}\n= y_2\\bigl[1-\\Lambda(\\hat\\eta)\\bigr] - (1-y_2)\\Lambda(\\hat\\eta) = y_2 - \\Lambda(\\hat\\eta) = y_2 - \\hat p_2,$$ {#eq-poisson-iv-6}\n\ni.e. **the logit generalized residual is just the plain response residual**\n$y_2-\\hat p_2$ — no Mills-ratio machinery needed: `logit` first stage, then\n`y2 - predict(fit, type=\"response\")`, is the right generalized residual,\nnot a shortcut.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfs_b_logit <- feglm(time_hi ~ phone + frfam | ad + female,\n                     data = df2, family = binomial(logit))\ndf2$phat_logit <- predict(fs_b_logit, type = \"response\")\ndf2$gr2_logit  <- df2$time_hi - df2$phat_logit   # algebraically = generalized residual\n\nm_b_logit <- fepois(visits ~ time_hi + gr2_logit + frfam | ad + female, data = df2)\netable(m_b_logit, title = \"Approach B with a logit first stage\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         m_b_logit\nDependent Var.:             visits\n                                  \ntime_hi         0.8625*** (0.0320)\ngr2_logit       0.2668*** (0.0317)\nfrfam           0.4157*** (0.0199)\nFixed-Effects:  ------------------\nad                             Yes\nfemale                         Yes\n_______________ __________________\nS.E. type                      IID\nObservations                 5,000\nSquared Cor.               0.73428\nPseudo R2                  0.41908\nBIC                       22,269.2\n---\nSignif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Probit-based Approach B: alpha1 = %.4f\\n\", coef(m_b)[\"time_hi\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProbit-based Approach B: alpha1 = 0.8544\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Logit-based  Approach B: alpha1 = %.4f\\n\", coef(m_b_logit)[\"time_hi\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLogit-based  Approach B: alpha1 = 0.8625\n```\n\n\n:::\n:::\n\n\nThe logit first stage gives 0.8625 against the probit's 0.8544, a difference of\n0.008 on estimates whose standard errors are 0.032. The choice of link is not\nwhat matters here.\n\nTwo limits are worth noting. Terza's *exact* correction is probit-specific: the\nclosed form $h(\\cdot)$ comes from the truncated moments of the bivariate normal,\nand no analogue for a logistic $v_2$ appears in @terza-1998,\n@wooldridge-2010-crosssection or @imbens-wooldridge-2007-cf. Logit gives Approach\nB with the same $O(\\rho^2)$ error as probit, but no logit version of the exact\ncorrection. Second, the link-robustness that Approach C enjoys --- the fitted\nprobability is a valid instrument even if the link is wrong, since any function\nof $\\mathbf z$ is a valid instrument [@imbens-wooldridge-2007-cf] --- belongs to\nusing the fitted value as an *instrument*, not as a *residual*. It does not carry\nover to A or B, where the second-stage conditional mean still has to be right.\n\n### Approach C — Fitted values as instrument (IV/GMM Poisson)\n\nAny function of the exogenous $\\mathbf{z}$ is a valid instrument. Probit fitted probabilities are used here as the instrument for `time_hi`. We implement IV/GMM Poisson via `gmm::gmm()` with the multiplicative moment conditions $E[\\mathbf{z}'(y_1 e^{-\\mathbf{x}\\boldsymbol{\\beta}} - 1)] = 0$ [@mullahy-1997]. The additive moments $E[\\mathbf{z}'(y_1 - \\exp(\\mathbf{x}\\boldsymbol{\\beta}))] = 0$ would be inconsistent here: the DGP puts its unobservables (the `ad` effects, `female`, and $\\rho_2 e_2$) inside $\\exp(\\cdot)$, so the structural error is multiplicative — running the additive version on these data gives $\\hat\\alpha_1 \\approx 0.63$, a bias no intercept shift can absorb:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Probit without FE for fitted probabilities (instrument)\nfs_c     <- glm(time_hi ~ phone + frfam, family = binomial(probit), data = df2)\ndf2$phat <- fitted(fs_c)\n\n# Multiplicative moment conditions (Mullahy 1997): Z'(y*exp(-X*beta) - 1) = 0\n# X = [time_hi, frfam, 1],  Z = [phat, frfam, 1]\ngmm_moments <- function(beta, x) {\n  y      <- x[, \"visits\"]\n  th     <- x[, \"time_hi\"]\n  fr     <- x[, \"frfam\"]\n  ph     <- x[, \"phat\"]\n  eta    <- pmin(pmax(beta[1] * th + beta[2] * fr + beta[3], -30), 30)\n  resid  <- y * exp(-eta) - 1\n  cbind(ph * resid, fr * resid, resid)\n}\n\ngmm_data <- as.matrix(df2[, c(\"visits\", \"time_hi\", \"frfam\", \"phat\")])\nm_c      <- gmm(gmm_moments, x = gmm_data,\n                t0 = c(0, 0, log(mean(df2$visits))))\ncoef_c   <- coef(m_c)\nse_c     <- sqrt(diag(vcov(m_c)))\n\ncat(sprintf(\"\\nApproach C — IV/GMM Poisson (no FE, for illustration)\\n\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nApproach C — IV/GMM Poisson (no FE, for illustration)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"  time_hi:  coef = %7.4f   SE = %7.4f   z = %6.3f\\n\",\n            coef_c[1], se_c[1], coef_c[1] / se_c[1]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  time_hi:  coef =  0.7844   SE =  0.0656   z = 11.950\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"  frfam:    coef = %7.4f   SE = %7.4f   z = %6.3f\\n\",\n            coef_c[2], se_c[2], coef_c[2] / se_c[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  frfam:    coef =  0.4576   SE =  0.0370   z = 12.369\n```\n\n\n:::\n:::\n\n\nGMM gives 0.7844 with a standard error of 0.0656 on `time_hi`, and 0.4576 on\n`frfam` against a true 0.4. The point estimate is the closest of the three to\n0.8, and the standard error is twice A's and B's --- the trade-off the\ncomparison section below takes apart.\n\n::: {.callout-note}\n**Approach C with FE** requires demeaning the regressor and instrument matrices via within-group centering before solving the Poisson moment conditions. Because Poisson is nonlinear this is not straightforward. Approaches A and B both run unmodified in `feols`/`feglm` + `fepois`, so either is practical when many fixed effects are present; of the two, prefer B (see the takeaway below).\n:::\n\n### A vs C — not equivalent in Poisson\n\nIn a linear model, using $\\hat{y}_2$ as an instrument (2SLS) is numerically identical to adding $\\hat{v}_2 = y_2 - \\hat{y}_2$ as a regressor — the Frisch-Waugh-Lovell theorem. **In Poisson this equivalence breaks**, because Approach A puts $\\hat{v}_2$ inside $\\exp(\\cdot)$ while Approach C uses $\\hat{y}_2$ in the moment conditions without modifying the exponential mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef_a <- coef(m_a)[\"time_hi\"]\ncoef_b <- coef(m_b)[\"time_hi\"]\n\ncat(sprintf(\"Approach A  (CF, OLS residual, with FE):   α̂₁ = %.4f\\n\", coef_a))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nApproach A  (CF, OLS residual, with FE):   α̂₁ = 0.8613\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Approach B  (CF, probit GR, with FE):      α̂₁ = %.4f\\n\", coef_b))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nApproach B  (CF, probit GR, with FE):      α̂₁ = 0.8544\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Approach C  (IV/GMM Poisson, no FE):       α̂₁ = %.4f\\n\", coef_c[1]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nApproach C  (IV/GMM Poisson, no FE):       α̂₁ = 0.7844\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"True α₁ = %.1f\\n\", true_alpha))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue α₁ = 0.8\n```\n\n\n:::\n:::\n\n\nThe three land at 0.8613, 0.8544 and 0.7844 against a true 0.8. They differ\ndespite using the same exclusion restriction, which is the point: in a linear\nmodel FWL would force A and C to agree exactly, and here they are 0.077 apart.\n2SLS $\\ne$ CF for Poisson.\n\n### Bootstrap for Approach A (binary EEV)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbootstrap_cf_binary <- function(df, B = 500) {\n  clusters <- unique(df$ad)\n  K        <- length(clusters)\n\n  boot_one <- function(b) {\n    library(fixest)\n    set.seed(b)\n    drawn <- sample(clusters, K, replace = TRUE)\n    df_b  <- do.call(rbind, lapply(seq_along(drawn), function(i) {\n      sub         <- df[df$ad == drawn[i], ]\n      sub$ad_boot <- i\n      sub\n    }))\n    fs         <- feols(time_hi ~ phone + frfam | ad_boot + female, data = df_b)\n    df_b$v2hat <- residuals(fs)\n    ss         <- fepois(visits ~ time_hi + v2hat + frfam | ad_boot + female, data = df_b)\n    coef(ss)[\"time_hi\"]\n  }\n\n  n_cores <- max(1L, detectCores() - 1L)\n  cl      <- makePSOCKcluster(n_cores)\n  clusterExport(cl, c(\"df\", \"clusters\", \"K\"), envir = environment())\n  results <- parLapply(cl, seq_len(B), boot_one)\n  stopCluster(cl)\n  unlist(results)\n}\n\nboot2     <- bootstrap_cf_binary(df2, 500)\nnaive_se2 <- se(m_a)[\"time_hi\"]\n\ncat(sprintf(\"Approach A bootstrap (binary EEV, 500 reps, cluster by ad)\\n\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nApproach A bootstrap (binary EEV, 500 reps, cluster by ad)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"  Point estimate:     %.4f  (true %.1f)\\n\", coef_a, true_alpha))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Point estimate:     0.8613  (true 0.8)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"  Naive 2nd-stage SE: %.4f\\n\", naive_se2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Naive 2nd-stage SE: 0.0321\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"  Bootstrap SE:       %.4f\\n\", sd(boot2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Bootstrap SE:       0.0331\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"  Bootstrap 95%% CI:  [%.4f, %.4f]\\n\",\n            quantile(boot2, 0.025), quantile(boot2, 0.975)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Bootstrap 95% CI:  [0.8025, 0.9308]\n```\n\n\n:::\n:::\n\n\nThe bootstrap standard error is 0.0331 against the naive 0.0321 --- almost\nidentical here, unlike Part 1 where the bootstrap was twice the naive figure.\nThe reason is that the binary first stage carries much less estimation\nuncertainty into the second stage than the continuous one did. The 95% interval\n$[0.803, 0.931]$ excludes the true 0.8, which is the approximation bias\ndiscussed above showing up in inference, not a coverage failure of the\nbootstrap.\n\n### Comparison across all methods\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnaive_p2    <- fepois(visits ~ time_hi + frfam | ad + female, data = df2)\ncoef_naive2 <- coef(naive_p2)[\"time_hi\"]\n\nmethods <- c(\n  \"True value\",\n  \"Naive Poisson (binary y₂)\",\n  \"A: Linear CF (with FE)\",\n  \"B: Probit GR CF (with FE)\",\n  \"C: IV/GMM Poisson (no FE)\"\n)\nests <- c(true_alpha, coef_naive2, coef_a, coef_b, coef_c[1])\n\ncat(\"\\n── Binary EEV: coefficient on time_hi ─────────────────────\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n── Binary EEV: coefficient on time_hi ─────────────────────\n```\n\n\n:::\n\n```{.r .cell-code}\nfor (i in seq_along(methods)) {\n  cat(sprintf(\"  %-38s  α̂₁ = %6.4f\\n\", methods[i], ests[i]))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  True value                              α̂₁ = 0.8000\n  Naive Poisson (binary y₂)             α̂₁ = 1.0832\n  A: Linear CF (with FE)                  α̂₁ = 0.8613\n  B: Probit GR CF (with FE)               α̂₁ = 0.8544\n  C: IV/GMM Poisson (no FE)               α̂₁ = 0.7844\n```\n\n\n:::\n:::\n\n\nThe naive Poisson gives 1.0832 against a true 0.8, so ignoring the endogeneity\noverstates the effect by 35%. Approaches A and B (with FE) recover the true\nvalue closely, at 0.8613 and 0.8544; a small upward\nbias from $\\rho=0.2$ and the binary EEV is expected — see the derivation\nabove (A has no valid first-stage assumption for binary $y_2$; B is correct\nonly to first order in $\\rho$). Approach C happens to land closest in this\ndraw, and its near-centring is not luck: the omitted `ad` and `female` effects\nare independent multiplicative heterogeneity, absorbed by the intercept under\nthe multiplicative moments ($\\beta_0 \\to \\beta_0 + \\log E[e^{c}]$), so omitting\nthe fixed effects costs no slope *bias* at all. Mullahy's moments are\n*consistent* for this DGP, where A and B are only approximately unbiased: over\n10 seeds at this $n$, C averages $0.7985$ against A's $0.8323$ and B's $0.8185$,\nand at $n=10^6$ it sits at $0.8015$ (sd $0.0013$) against plims of $0.839$ and\n$0.822$. The catch is variance rather than bias. Without the fixed effects C is\nabout three times as noisy (sd $0.068$ at $n=5000$, against $0.024$ and\n$0.026$), so at this sample size its RMSE is the *worst* of the three — $0.065$,\nagainst A's $0.039$ and B's $0.031$ — and a single draw can easily leave it\nfurther from $0.8$ than either CF estimator. With many groups, Approach B\nremains the practical choice, understood as a first-order approximation whose\nsmall bias buys real precision rather than as a theoretically exact method.\n\n### Takeaway for the binary case\n\n- **Use Approach B when you need fixed effects.** Among the estimators that\n  drop into FE-Poisson unmodified it is the theoretically motivated choice, and\n  its error is *derived*, not assumed: $O(\\rho^2)$, shrinking as the endogeneity\n  shrinks.\n- **Approach C trades bias for variance — decide which one binds.** Mullahy's\n  multiplicative moments are *consistent* here, not merely accurate to first\n  order, whenever the multiplicative heterogeneity is independent of\n  $\\mathbf z$. But consistency is not accuracy at a given sample size. Over 10\n  seeds at this chapter's $n=5000$, C is nearly unbiased (mean $0.7985$) and yet\n  almost three times as noisy as B (sd $0.068$ against $0.026$), so its RMSE is\n  the *worst* of the three: $0.065$, against A's $0.039$ and B's $0.031$. B's\n  small derived bias buys a great deal of precision. Prefer C once $n$ is large\n  enough that its variance is not the binding constraint — and note that it does\n  not accommodate high-dimensional fixed effects either way.\n- **Approach A is a fallback, not a first choice.** It lands close to the truth\n  at $\\rho=0.2$ here, but it has no theoretical justification for binary $y_2$.\n  Do not lean on it when $\\rho$ is not known to be small.\n- **Probit or logit both work for Approach B.** Only Terza's exact correction\n  needs normality.\n",
    "supporting": [
      "poisson-iv_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}